/**
 * @file include/halo/networking/api.hpp
 * Functions of the networking module that other modules and the data tables call (namespace halo::networking). The record types are
 * forward-declared, so the header is light enough for every caller and for the data tables.
 */
#pragma once

#include <stdint.h>



struct ban_list_entry;
struct bit_stream;
struct cache;
struct client_position_packet;
struct client_update_record;
struct flag;
struct hash_table;
struct local_player_vehicle_update_ack;
struct message_delta_decode_state;
struct message_delta_encode_context;
struct message_delta_definition;
struct message_delta_field_type;
struct message_delta_sample_ring_buffer;
struct message_delta_static_fields;
struct network_bandwidth_graph;
struct network_channel;
struct network_channel_list;
struct network_channel_stream;
struct network_client_globals;
struct network_game_search_entry;
struct network_game_session;
struct network_machine;
struct network_message_record;
struct network_mutex_record;
struct network_player_entry;
struct message_delta_context;
struct network_receive_queue;
struct network_resolved_address;
struct network_server_globals;
struct network_thread_record;
struct network_timer_pair;
struct network_ui_widget;
typedef struct network_ui_widget network_ui_widget;
struct object;
struct player;
struct player_action;
struct player_update_history;
struct player_update_history_node;
struct real_vector3d;
struct remote_player_action_state;
struct remote_player_update_header;
struct s_network_address;
struct server_browser_custom_options;
struct server_browser_gametype1_decoded;
struct server_browser_gametype1_options;
struct server_browser_gametype3_options;
struct server_list_globals;
struct ticker_text_buffer;
struct vector3d_lerp_table;
struct vehicle_update_body;
struct widget;
typedef float real;
typedef int32_t (*server_browser_sort_comparator)(const void *, const void *);
typedef uint32_t datum_index;

namespace halo::networking {

/**
 * The engine globals the networking module owns (their storage is defined by standalone/data under the original link names);
 * other modules reach them through globals().
 */
struct Globals {
    network_server_globals *&server;
    network_client_globals *&client;
    int16_t &game_mode;
    uint8_t &host_handoff_requested;
    uint8_t &server_host_valid;
    int16_t &join_error_code;
    uint8_t &join_error_reason;
    uint8_t &disconnect_timeout_flag;
    uint8_t &client_vehicle_ack_enabled;
    uint32_t &game_socket_port;
};

Globals &globals();

void autopatch_current_version_string_get(char *out);
uint32_t autopatch_download_complete_callback(int32_t request_id, int32_t error, uint8_t *data, uint32_t size);
uint8_t autopatch_download_get_result(void **out_data, int32_t *out_size, int32_t slot_index);
uint8_t autopatch_download_pool_initialize(void);
uint32_t autopatch_download_pool_shutdown(void);
int32_t autopatch_download_pool_tick(void);
void autopatch_download_progress_callback(int32_t request, int32_t state, const char *buffer, int32_t buffer_length, int32_t bytes_received, int32_t total_size, void *param);
int32_t autopatch_download_start(void *path, int32_t local_file);
uint32_t autopatch_download_worker_thread(void);
char * autopatch_get_proxy_settings(void);
uint32_t __stdcall autopatch_proxy_initialize(void *parameter);
char * autopatch_temp_name_generate(void);
uint32_t autopatch_version_string_is_outdated(char *version);
uint8_t ban_list_check_and_reject_player(char *key);
ban_list_entry * ban_list_find_by_name(char *key);
ban_list_entry * ban_list_get_or_add_entry(char *name, char *cd_key_hash);
int32_t build_local_player_position_update(uint8_t *out_changed, player *plr);
int32_t build_local_player_vehicle_update(uint8_t *out_changed, player *plr);
void build_player_full_resync_update(uint32_t player_index);
void build_remote_player_action_update(uint32_t player_index, uint32_t network_key, uint8_t update_id_byte, player_action control);
void build_remote_player_transform_update(uint32_t player_index, uint32_t network_key, uint8_t update_id_byte, player_action control);
int32_t build_remote_player_vehicle_attachment_update(uint8_t *cache, uint8_t update_id, uint8_t flags, char is_full, player_action *control, int32_t network_key);
int32_t build_remote_player_vehicle_update(uint8_t *cache, uint8_t update_id, uint8_t flags, char is_full, player_action *control, int32_t network_key);
int8_t chimera__on_connect(const uint32_t *target_address, network_client_globals *client, const uint32_t *session_info);
void chimera__rcon_out(char *text, int32_t unused_machine_id);
void console_command_bool_get_set(uint32_t argument_count, uint8_t *value, char **arguments, const char *name);
void digital_throttle_decode_vector(real *out, uint32_t code);
int32_t digital_throttle_encode_vector(real_vector3d vector);
int32_t dynamic_pointer_array_add_unique(void *value, server_list_globals *array);
int32_t dynamic_pointer_array_find_index(server_list_globals *array, void *value);
void dynamic_pointer_array_remove_at(int32_t index, server_list_globals *array);
void format_local_time_and_date(char *date_dest, int32_t max_len, int32_t time_value, char *time_dest);
void format_time_and_date_strings(char *date_dest, struct tm *time_value, int32_t max_len, char *time_dest);
void game_variant_list_matching_substring(uint32_t argument_count, char **arguments);
int32_t gamespy_array_length(void *array);
void * gamespy_array_nth(void *array, int32_t index);
void gamespy_think_all(void);
void handle_remote_player_action_update(remote_player_action_state *control_source, remote_player_update_header *header, uint8_t is_baseline);
uint8_t is_local_player_update_in_order(int32_t current_update_id, int32_t new_update_id);
uint8_t is_remote_player_update_in_order(player *plr, uint8_t new_update_id, int32_t update_id);
int32_t join_game_server_browser_tick(network_ui_widget *browser_widget);
void join_game_ticker_string_copy(uint16_t *buffer, int32_t capacity, int32_t string_index);
void map_list_matching_substring(uint32_t argument_count, char **arguments);
int32_t master_server_connection_start(void);
void master_server_connection_wait_thread(void);
void master_server_ensure_list_connection(void);
void master_server_list_refresh_request(void);
void master_server_process_pending_requests(void);
int32_t message_delta_array_field_decode(message_delta_field_type *field_type, uint8_t *previous, uint8_t *destination, bit_stream *stream);
int32_t message_delta_array_field_encode(message_delta_field_type *field_type, uint8_t *previous, uint8_t *destination, bit_stream *stream);
int32_t message_delta_blob_compute_size(message_delta_field_type *field_type);
int32_t message_delta_boolean_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_boolean_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_byte_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_byte_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_compound_compute_size(message_delta_field_type *field_type);
int32_t message_delta_compound_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
uint8_t message_delta_compound_initialize(message_delta_field_type *field_type);
int32_t message_delta_compute_size_1(message_delta_field_type *field_type);
int32_t message_delta_compute_size_16(message_delta_field_type *field_type);
int32_t message_delta_compute_size_2(message_delta_field_type *field_type);
int32_t message_delta_compute_size_3(message_delta_field_type *field_type);
int32_t message_delta_compute_size_32(message_delta_field_type *field_type);
int32_t message_delta_compute_size_4(message_delta_field_type *field_type);
int32_t message_delta_compute_size_6(message_delta_field_type *field_type);
int32_t message_delta_compute_size_8(message_delta_field_type *field_type);
uint8_t message_delta_count_initialize(message_delta_field_type *field_type);
int32_t message_delta_decode_array_field(void **context);
int32_t message_delta_decode_begin(message_delta_decode_state *state, bit_stream *stream);
uint8_t message_delta_decode_compound_field(void **context, void *destination);
uint8_t message_delta_decode_compound_field_forced(void **context, void *destination, int32_t changed_offset, uint8_t force);
uint8_t message_delta_decode_compound_field_staged(void **context);
int32_t message_delta_decode_field_changed_flags(void **context);
int32_t message_delta_decode_message_header(bit_stream *stream, message_delta_decode_state *state);
int32_t message_delta_decode_static_fields(int32_t message_type, bit_stream *stream, int32_t offset);
int32_t message_delta_decode_vector3d_indexed(int32_t param_1, int32_t mode, real *destination, bit_stream *stream);
void message_delta_definitions_invoke_field_bindings(void);
void message_delta_definitions_teardown_field_bindings(void);
int32_t message_delta_dword_array_decode(message_delta_field_type *field_type, uint32_t *previous, uint32_t *destination, bit_stream *stream);
uint8_t message_delta_encode_all_fields(message_delta_encode_context *ctx, int32_t static_base, int32_t item, int32_t type_base);
uint8_t message_delta_encode_field(int32_t changed_offset, message_delta_encode_context *ctx, int32_t field_index, int32_t type_offset);
int32_t message_delta_encode_message(int32_t extra_eax, int32_t extra_edx, int32_t flag, int32_t message_type, int32_t changed_offset, void **items, int32_t type_offset, int32_t count, char force_changed);
uint8_t message_delta_encode_message_header(message_delta_encode_context *ctx);
uint8_t message_delta_encode_prepare_item(message_delta_encode_context *ctx);
int32_t message_delta_encode_single_value(int32_t message_type, void *changed_value, void *item, void *type_value, int32_t buffer, int32_t bit_budget, char force_changed);
int32_t message_delta_encode_vector3d(int32_t unused, real *previous, real *values, bit_stream *stream);
int32_t message_delta_enum_width_compute_size(message_delta_field_type *field_type);
void message_delta_field_bindings_invoke(message_delta_static_fields *list);
uint8_t message_delta_field_bindings_lazy_init(message_delta_static_fields *list);
void message_delta_field_bindings_teardown(message_delta_static_fields *list);
void message_delta_field_layout_compute_size(message_delta_definition *definition);
int32_t message_delta_first_dword_compute_size(message_delta_field_type *field_type);
int32_t message_delta_flags_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_flags_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
uint8_t message_delta_flags_initialize(message_delta_field_type *field_type);
int32_t message_delta_float_array_encode(message_delta_field_type *field_type, float *previous, float *values, bit_stream *stream);
int32_t message_delta_grenade_counts_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_grenade_counts_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_grenade_index_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_grenade_index_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_index_compute_size(message_delta_field_type *field_type);
int32_t message_delta_index_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_index_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
uint8_t message_delta_index_initialize(message_delta_field_type *field_type);
void message_delta_index_teardown(message_delta_field_type *field_type);
int32_t message_delta_integer_compute_size(message_delta_field_type *field_type);
int32_t message_delta_integer_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_integer_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
uint8_t message_delta_integer_initialize(message_delta_field_type *field_type);
int32_t message_delta_item_placement_compute_size(message_delta_field_type *field_type);
int32_t message_delta_item_placement_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_item_placement_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
uint8_t message_delta_item_placement_initialize(message_delta_field_type *field_type);
int32_t message_delta_locality_compute_size(message_delta_field_type *field_type);
int32_t message_delta_locality_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
uint8_t message_delta_locality_initialize(message_delta_field_type *field_type);
int32_t message_delta_long_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_long_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
void message_delta_metrics_dump(char *suffix);
int32_t message_delta_normal_compute_size(message_delta_field_type *field_type);
int32_t message_delta_normal_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_normal_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
uint8_t message_delta_normal_initialize(message_delta_field_type *field_type);
void message_delta_parameters_protocol_dump_to_config_file(void);
uint8_t message_delta_parameters_protocol_find_registered(char *name, void **out_value);
void message_delta_parameters_protocol_format_received_values(int32_t *values);
void message_delta_parameters_protocol_format_registered_values(void);
void message_delta_parameters_protocol_free_registered(void);
void message_delta_parameters_protocol_pack_values(int32_t *out_values);
int32_t message_delta_parameters_protocol_parse_value_from_config(char *name, char *format, void *out_value);
void message_delta_parameters_protocol_receive_update(void **context);
void message_delta_parameters_protocol_register(char *scope, char *name, int32_t type, void *value);
void message_delta_parameters_protocol_reload_from_config_file(void);
void message_delta_parameters_protocol_send_update(void);
int32_t message_delta_pointer_compute_size(message_delta_field_type *field_type);
int32_t message_delta_pointer_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_pointer_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
uint8_t message_delta_pointer_initialize(message_delta_field_type *field_type);
void message_delta_protocol_initialize(void);
uint32_t message_delta_quantize_float_to_int(uint32_t max_level, real value, real minimum, real maximum);
int32_t message_delta_quantized_real_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_quantized_real_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
uint8_t message_delta_quantized_real_initialize(message_delta_field_type *field_type);
int32_t message_delta_range_compute_size(message_delta_field_type *field_type);
uint8_t message_delta_range_initialize(message_delta_field_type *field_type);
int32_t message_delta_read_changed_subfields(message_delta_decode_state *state, uint8_t *changed_flags, int32_t changed_offset, int32_t destination_offset);
int32_t message_delta_real_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
void message_delta_sample_record_and_append(int32_t a, int32_t c, int32_t b, message_delta_sample_ring_buffer *ring);
void message_delta_sample_ring_buffer_append(message_delta_sample_ring_buffer *ring, const int32_t *entry);
int32_t message_delta_sample_ring_buffer_average(message_delta_sample_ring_buffer *ring);
int32_t message_delta_scalar_array_compute_size(message_delta_field_type *field_type);
int32_t message_delta_string_compute_size(message_delta_field_type *field_type);
int32_t message_delta_string_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_string_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_structure_array_compute_size(message_delta_field_type *field_type);
int32_t message_delta_structure_array_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
uint8_t message_delta_structure_array_initialize(message_delta_field_type *field_type);
int32_t message_delta_throttle_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_throttle_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_vector_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_vector_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_velocity_compute_size(message_delta_field_type *field_type);
int32_t message_delta_velocity_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_weapon_index_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_weapon_index_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_wide_string_compute_size(message_delta_field_type *field_type);
int32_t message_delta_wide_string_decode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t message_delta_wide_string_encode(message_delta_field_type *field_type, void *previous, void *current, bit_stream *stream);
int32_t mutex_create(network_mutex_record **out_handle);
char network_address_parse_port(char *address_string, int32_t *port_out);
char network_address_string_is_valid(char *address_string);
char network_address_string_normalize(char *address_string, char *out_buffer, uint8_t *out_is_any);
char * network_address_to_string(s_network_address *addr);
int32_t network_bandwidth_direction_name_to_index(const char *name);
void network_bandwidth_graph_accumulate_received(int32_t byte_count, int32_t packet_count);
void network_bandwidth_graph_accumulate_sent(int32_t byte_count, int32_t packet_count);
int32_t network_bandwidth_graph_find_peak_sample(int32_t *out_peak_countdown, network_bandwidth_graph *graph);
void network_bandwidth_graph_instance_history_reset(network_bandwidth_graph *graph);
void network_bandwidth_graph_instance_init(network_bandwidth_graph *graph, int32_t units_index, int32_t direction_index);
void network_bandwidth_graph_instance_update_layout(network_bandwidth_graph *graph, uint8_t force_refresh);
void network_bandwidth_graph_new_sample(network_bandwidth_graph *graph);
uint32_t network_bandwidth_graph_reset(void);
uint32_t network_bandwidth_graph_set_units_command(const char *units_name, const char *direction_name);
void network_bandwidth_graph_tick(network_bandwidth_graph *graph);
void network_bandwidth_graph_update(void);
void network_bandwidth_graph_update_columns(int32_t new_sample, network_bandwidth_graph *graph);
void network_bandwidth_rate_compute(network_bandwidth_graph *graph);
int32_t network_bandwidth_unit_name_to_index(const char *name);
uint8_t network_banlist_add_ban(int32_t identity_lookup_key, int32_t duration_override_seconds, network_player_entry *target_player);
void network_banlist_load(void);
void network_banlist_print(void);
void network_banlist_save(void);
void network_buffer_pair_pool_clear(void);
int16_t network_channel_attempt_connect(s_network_address *address, network_receive_queue *queue, int32_t unused_param_1, uint8_t use_query_socket);
void network_channel_connected_callback(void *connection, int32_t result, const uint8_t *message, int32_t length);
void network_channel_delete(network_channel *channel);
char network_channel_dispatch_bitstream_unit(network_server_globals *server, uint32_t unit, bit_stream *stream, network_machine *machine);
char network_channel_drain_bitstream(network_server_globals *server, network_machine *machine);
void network_channel_gap_441020(void *socket, void *connection, uint32_t ip, uint16_t port, int32_t reset, const void *message, int32_t length, int32_t reliable, int32_t resend);
void network_channel_gap_441040(void *socket, void *connection, uint32_t ip, uint16_t port, int32_t reset, const void *message, int32_t length);
void network_channel_gap_441060(void *socket);
int32_t network_channel_gap_4410b0(void *socket, uint32_t ip, uint16_t port, const uint8_t *message, uint32_t length);
int32_t network_channel_gap_441200(void *socket, uint32_t ip, uint16_t port, const uint8_t *message, uint32_t length);
void network_channel_gap_441f30(void *connection);
void network_channel_gap_4ba660(void *sb, uint32_t reason, void *server, void *instance);
int16_t network_channel_get_remote_address(s_network_address *address, network_receive_queue *queue);
int32_t network_channel_incoming_read_item(network_channel *channel, uint8_t *destination, int32_t *out_bit_offset, int32_t *out_remaining_bits, s_network_address *out_address, int32_t max_item_bits);
int32_t network_channel_key_close(network_player_entry *entry, datum_index requested_handle);
int32_t network_channel_key_open(network_player_entry *entry);
uint8_t network_channel_key_resolve_target(network_player_entry *entry);
int32_t network_channel_key_send_state(network_client_globals *client, message_delta_context *context);
int32_t network_channel_list_add(network_receive_queue *entry, network_channel_list *list);
int32_t network_channel_list_mark_readable(network_channel_list *list);
network_channel_list * network_channel_list_new(int16_t requested_capacity);
int32_t network_channel_list_remove(network_receive_queue *entry, network_channel_list *list);
char network_channel_listen_service(network_channel *channel, network_channel **out_new_child);
network_channel * network_channel_new(uint32_t flags);
network_channel * network_channel_new_child(network_receive_queue *endpoint);
char network_channel_queue_message(network_channel *channel, uint32_t header_value, uint32_t body_value, int32_t header_bit_count, char immediate, char flush_after, int32_t body_bit_count);
void network_channel_receive_callback(void *handle, uint8_t *data, int32_t length);
void network_channel_record_timestamp(network_channel *channel);
int32_t network_channel_reliable_pool_ensure_capacity(network_channel *channel, int32_t body_capacity_needed, int32_t header_capacity_needed);
void network_channel_reliable_pool_store(network_channel *channel, uint8_t *body_data, uint8_t *header_data, int32_t priority, uint32_t header_bits, uint32_t body_bits);
void network_channel_remote_address_or_default(network_channel *channel, network_resolved_address *out_address);
int32_t network_channel_remove_child(network_channel *parent, network_channel *child);
void network_channel_scan_retransmit_timeouts(network_channel *channel);
char network_channel_service(network_channel *channel, int32_t timeout_ms, network_channel **out_new_child);
int32_t network_channel_service_close_if_disconnected(network_channel *channel);
char network_channel_service_light(network_channel *channel, int32_t timeout_ms, network_channel **out_new_child);
int32_t network_channel_service_retransmit_only(network_channel *channel);
int32_t network_channel_short_disconnect_timeout(void);
char network_channel_stream_flush(network_channel_stream *stream, network_channel *channel, char mode);
void network_channel_stream_init(network_channel_stream *stream);
char network_channel_transmit(network_channel *channel);
void network_channels_close(void);
void network_channels_open(void);
uint32_t network_client_begin_connect(wchar_t *player_name, s_network_address *target_address);
uint32_t network_client_check_connection_quality(int16_t machine_id, client_update_record update);
int16_t network_client_connect_progress_percent(network_client_globals *client, int16_t *out_percent);
void network_client_connection_handshake_tick(int16_t state, network_server_globals *owner);
char network_client_drain_queued_updates(network_server_globals *server, network_machine *machine, bit_stream *stream);
int32_t network_client_globals_create(void);
void network_client_globals_dispose(void);
void network_client_handle_server_text_message(void *message);
int32_t network_client_identity_tick(network_client_globals *client);
void network_client_rejoin_check(int8_t machine_player_index);
void network_client_send_local_player_updates(void);
int8_t network_client_state_dispatch(network_client_globals *client);
void network_client_timer_default_or_disconnect(network_client_globals *client);
void network_client_timer_schedule(int32_t delay_ms, int32_t context, network_client_globals *client);
char network_client_update_dispatch(void);
int32_t network_connection_endpoint_set(const uint32_t *source, network_client_globals *connection);
int32_t network_connection_finalize_join(network_client_globals *client);
uint8_t network_connection_initiate(network_client_globals *connection, const uint32_t *target, const uint32_t *session_info, const uint32_t *connect_address);
void network_connection_retransmit_if_overdue(const uint32_t *sender_address, network_client_globals *client, uint32_t deadline_ms, int32_t remote_time);
void network_connection_send_keepalive(network_client_globals *client);
void network_connection_stats_end(int32_t connection_id, uint16_t connection_key);
void network_connection_stats_log_tick(void);
int32_t network_connection_stats_lookup_or_add(int32_t connection_id, uint16_t connection_key);
void network_connection_stats_record_packet(void *gamespy_connection, int32_t payload_length, uint8_t is_sent, uint8_t is_reliable, uint8_t is_resend);
void network_debug_fill_canary_buffer(uint32_t *buffer);
void network_disconnect_notify_dropped_machines(network_client_globals *client);
void network_dispatch_initialize(void);
void network_event_feed_flush(int32_t *queue);
void network_event_feed_queue_append(uint8_t *queue, uint32_t *key, uint32_t *payload);
void network_game_action_apply(void **context, network_client_globals *client);
char network_game_action_queue_drain(network_client_globals *client, bit_stream *stream, const uint32_t *sender);
uint32_t network_game_all_machines_have_player(network_server_globals *server);
uint32_t network_game_any_team_empty(network_server_globals *server);
uint32_t network_game_broadcast_player_set_changed(uint8_t *param_1);
uint32_t network_game_broadcast_state_snapshot(const uint32_t *record, network_server_globals *server);
void network_game_broadcast_team_object_updates(int32_t *object_count, uint32_t object_type_mask, int32_t machine_id, int32_t *bytes_sent);
void network_game_client_apply_position_update(network_machine *machine, const client_position_packet *packet, int32_t tick_count, uint32_t history_byte);
void network_game_client_apply_received_update(network_machine *machine, uint32_t server, void **message);
uint32_t network_game_client_connect_to_address(wchar_t *player_name, char *address_string);
int32_t network_game_client_decode_and_discard_ingame_message(network_client_globals *client, const uint8_t *buffer, int32_t length, const uint32_t *sender_address);
int32_t network_game_client_decode_and_discard_join_message(network_client_globals *client, const uint8_t *buffer, int32_t length, const uint32_t *sender_address);
int32_t network_game_client_decode_beacon_reply(network_client_globals *client, const uint8_t *buffer, int32_t length);
int32_t network_game_client_decode_connect_rejected(network_client_globals *client, const uint8_t *buffer, int32_t length, const uint32_t *expected_sequence);
int32_t network_game_client_decode_join_accepted(network_client_globals *client, const uint8_t *buffer, int32_t length, const uint32_t *sender_address);
int32_t network_game_client_decode_join_complete(network_client_globals *client, const uint8_t *buffer, int32_t length, const uint32_t *sender_address);
int32_t network_game_client_decode_join_finalize_ack(network_client_globals *client, const uint8_t *buffer, int32_t length, const uint32_t *sender_address);
int32_t network_game_client_decode_join_finalize_message(network_client_globals *client, const uint8_t *buffer, int32_t length, const uint32_t *sender_address);
int32_t network_game_client_decode_player_config_value(network_client_globals *client, const uint8_t *buffer, int32_t length, const uint32_t *sender_address);
char network_game_client_decode_player_join_chunk(network_client_globals *client, uint8_t *message, int32_t message_length, int32_t *expected_sender);
char network_game_client_decode_player_slot_chunk(network_client_globals *client, uint8_t *message, int32_t message_length, int32_t *expected_sender);
int32_t network_game_client_decode_pong_reply(network_client_globals *client, const uint8_t *buffer, int32_t length, const uint32_t *sender_address);
int32_t network_game_client_decode_settings_or_ack(network_client_globals *client, const uint8_t *buffer, int32_t length, const int32_t *expected_sequence);
char network_game_client_decode_state_update_chunk(network_client_globals *client, uint8_t *message, int32_t message_length, int32_t *expected_sender);
int32_t network_game_client_decode_sync_complete(network_client_globals *client, const uint8_t *buffer, int32_t length, const uint32_t *sender_address);
uint32_t network_game_client_game_settings_updated(network_server_globals *host);
uint32_t network_game_client_handle_map_data(network_server_globals *server, network_message_record *record, int32_t length);
uint32_t network_game_client_handle_retry_schedule(network_server_globals *server, network_machine *machine, network_message_record *record, int32_t length);
uint32_t network_game_client_handle_settings_relay(network_server_globals *server, network_message_record *record, int32_t length);
int8_t network_game_client_update(network_client_globals *client);
int32_t network_game_decode_settings_request(network_client_globals *client, const uint8_t *buffer, int32_t length, const int32_t *expected_sequence);
void network_game_generate_unique_random_name(network_game_session *session, wchar_t *out_name);
wchar_t * network_game_get_random_player_name(void);
int32_t network_game_is_active(void);
char network_game_message_decode_dispatch(network_client_globals *client, uint16_t *record, int32_t record_length, const uint32_t *sender);
int32_t network_game_message_decode_ingame_notification(network_client_globals *client, const uint8_t *buffer, int32_t length, const uint32_t *sender_address);
int32_t network_game_message_decode_replicated_command(network_client_globals *client, uint8_t *message, int32_t message_length, int32_t *expected_sender);
uint32_t network_game_message_handle_build_version(network_server_globals *server, network_machine *machine, network_message_record *record, int32_t length);
uint32_t network_game_message_handle_handshake_forward(network_server_globals *server, network_message_record *record, int32_t length);
uint32_t network_game_message_handle_join_finalize_ack_role2(network_server_globals *server, network_machine *machine, network_message_record *record, int32_t length);
uint32_t network_game_message_handle_keepalive(network_channel **channel, int32_t *record);
uint32_t network_game_message_handle_ping_timestamp(int32_t **message, network_server_globals *server);
uint32_t network_game_message_handle_player_count_broadcast(network_server_globals *server, network_message_record *record, int32_t length);
uint32_t network_game_message_handle_player_entry_update(network_server_globals *server, network_message_record *record, int32_t length);
uint32_t network_game_message_handle_retry_schedule(network_server_globals *server, network_machine *machine, network_message_record *record, int32_t length);
uint32_t network_game_message_handle_settings_relay(network_server_globals *server, network_message_record *record, int32_t length);
uint32_t network_game_message_handle_settings_relay_role2(network_server_globals *server, network_message_record *record, int32_t length);
uint32_t network_game_process_incoming_message(int32_t length, network_machine *machine, uint16_t *record, network_server_globals *server);
int32_t network_game_process_incoming_messages(network_client_globals *client);
int32_t network_game_record_message_send(network_client_globals *client, const uint32_t *source);
char network_game_scenario_load_request(network_game_session *session);
uint8_t network_game_search_entry_is_fresh(network_game_search_entry *entry);
int32_t network_game_search_results_add_or_update(network_game_search_entry *results, const uint8_t *announcement);
void network_game_server_handle_client_join(int32_t *object_count_passthrough, network_server_globals *server, network_machine *machine, uint8_t bl_passthrough);
uint32_t network_game_server_handle_info_request(network_server_globals *server, network_machine *machine, network_message_record *record, int32_t length);
char network_game_server_handle_join_confirm(network_machine *machine, network_server_globals *server, network_message_record *buffer, int32_t length);
char network_game_server_handle_join_password(network_machine *machine, network_server_globals *server, network_message_record *buffer, int32_t length);
void network_game_server_handoff_object_ownership(int32_t *object_count_passthrough, network_server_globals *server, network_machine *machine);
int32_t network_game_server_host_create(void);
void network_game_server_host_dispose(network_server_globals *host);
void * network_game_server_host_new(void);
char network_game_server_load_scenario(void);
void network_game_server_per_frame_tick(int16_t update_count, network_server_globals *server);
void network_game_server_send_message_to_all_machines_ingame(uint8_t *context);
uint32_t network_game_session_finalize_and_add_player(network_player_entry *entry, network_server_globals *server, network_machine *machine);
void network_game_session_reset(network_game_session *session);
int32_t network_game_session_reset_defaults(network_server_globals *server);
char network_game_settings_ack_send(network_client_globals *client, int16_t template_row);
uint32_t network_game_settings_broadcast_send(network_server_globals *server, const network_player_entry *entry);
int32_t network_game_settings_packet_receive(network_client_globals *client, const uint32_t *request);
void network_game_settings_packet_send(network_client_globals *client, const uint8_t *request);
uint8_t network_game_start_new_server_from_profile(uint32_t unused);
uint8_t network_game_start_new_server_with_name_and_password(uint32_t unused, uint16_t *name, uint16_t *password);
int32_t network_game_state_update_receive(network_client_globals *client, uint8_t *record);
void network_handle_registry_close_all(void);
char network_host_channel_service_tick(network_client_globals *client);
void network_host_full_state_broadcast(network_server_globals *host);
char network_host_lobby_tick(network_client_globals *client);
void network_host_presence_broadcast_tick(network_client_globals *client);
void network_host_round_reset(network_server_globals *host);
int32_t network_host_send_scenario_announcement(network_server_globals *host);
int32_t network_host_shutdown_or_defer(void);
char network_host_update_tick(network_server_globals *host);
void network_hostname_thread_proc(char *hostname_buffer);
char network_incoming_item_dispatch(network_client_globals *client, uint32_t item_flag, bit_stream *stream, const uint32_t *sender);
int32_t network_index_cache_find_or_allocate_slot(uint8_t *container, int32_t key);
int32_t network_index_cache_get(hash_table *table, int32_t key);
uint8_t network_index_cache_insert_if_free(uint8_t *container, int32_t slot, int32_t key);
uint8_t network_index_cache_remove(uint8_t *container, int32_t key);
int16_t network_initialize(void);
int32_t network_join_connect_retry_tick(network_client_globals *client);
uint32_t network_join_handshake_tick(network_client_globals *client);
void network_join_hostname_resolved_callback(int32_t resolve_failed, uint32_t unused, uint8_t *hostent);
uint8_t network_join_request_reset_state(network_machine *machine, const char *response);
uint32_t network_join_request_resolve_host(void);
void network_join_status_text_update(int32_t mode, network_client_globals *client);
network_receive_queue * network_listen_accept_pending_connection(void);
void network_listen_connection_request_handler(int32_t listen_handle, int32_t reply_socket, uint32_t remote_address, uint32_t remote_port_raw, int32_t transport_handle, uint32_t *payload, uint32_t payload_length);
uint32_t network_listen_reject_pending_connection(int32_t reject_code);
uint32_t network_listen_start(network_receive_queue *queue);
int network_local_hostent_get(void **out_hostent);
char * network_log_path_resolve(char *requested_path);
void network_machine_check_build_version(const char *remote_version, network_machine *machine);
uint32_t network_machine_clear_flag_by_id(network_server_globals *server, int32_t machine_id);
network_machine * network_machine_find_by_id(network_server_globals *server, int32_t machine_id);
int32_t network_machine_reset(network_machine *machine);
void network_machine_timer_start(network_machine *machine, int32_t duration_ms);
void network_map_cycle_list_broadcast(void);
uint16_t * network_message_block_build(uint16_t *buffer, uint32_t *source, uint8_t flags, uint32_t length);
uint16_t * network_message_read_sized_buffer(uint16_t *buffer, int32_t capacity, bit_stream *stream);
network_mutex_record * network_mutex_slot_allocate(void);
uint8_t network_name_string_is_valid_for_mode(char *name, void *character, int32_t mode);
int32_t network_object_owner_team_index_desired(object *obj);
uint32_t network_object_record_last_sender(int32_t player_index, int32_t quit_tick, network_server_globals *server);
void network_object_release_ownership_claim(uint8_t slot_index);
void network_password_field_set(network_server_globals *object, wchar_t *source);
void network_player_assign_random_color(network_game_session *session, network_player_entry *entry);
uint32_t network_player_entry_add(network_game_session *session, network_player_entry *incoming);
char network_player_entry_find(network_game_session *session, network_player_entry *key);
uint32_t network_player_entry_remove(network_player_entry *key, network_game_session *session);
uint8_t network_player_entry_update(network_player_entry *incoming, network_game_session *session);
char network_player_entry_validate(network_player_entry *entry);
char network_player_join_finalize(network_client_globals *client, network_player_entry *entry);
uint8_t network_player_name_collision_check(network_game_session *session, uint16_t *candidate_name);
void network_player_ping_field_update_and_report(void *decode_context);
void network_player_update_history_log_write(const char *format, ...);
uint16_t * network_prepare_challenge_packet(int32_t message_type, void *payload);
int32_t network_random_offset(int32_t base);
void network_receive_queue_close_socket(network_receive_queue *queue);
void network_receive_queue_free(network_receive_queue *queue);
network_receive_queue * network_receive_queue_new(void);
int32_t network_send_join_request_packet(network_client_globals *connection);
void network_server_advance_connect_state(network_server_globals *server);
uint8_t network_server_any_machine_awaiting_flag(network_server_globals *server);
char network_server_build_full_game_info_packet(network_machine *machine);
char network_server_build_game_info_packet(network_server_globals *server, network_machine *machine);
int32_t network_server_check_machine_timeout(network_server_globals *server, network_machine *machine);
int32_t network_server_count_connected_machines(network_server_globals *server);
uint8_t network_server_count_machines_and_resolve_address(network_server_globals *server, network_channel *channel);
void network_server_handle_rcon_request(network_player_entry *client, void *message);
uint8_t network_server_heartbeat_tick(network_server_globals *server);
uint8_t network_server_notify_or_resend_challenge(int16_t reason, network_machine *machine, network_server_globals *server);
void network_server_password_get(network_server_globals *server, wchar_t *dest);
int32_t network_server_password_is_set(network_server_globals *server);
void network_server_password_set(const wchar_t *source, network_server_globals *server);
uint32_t network_server_resend_challenge_periodic(network_server_globals *server);
char network_server_service_machines_tick(network_server_globals *server);
uint32_t network_server_status_periodic_print(network_server_globals *server);
int32_t network_server_validate_join_request(network_server_globals *server);
uint8_t network_session_autoban_player(datum_index player_handle);
char network_session_broadcast_to_all(network_server_globals *server, int32_t bit_count, int32_t status_bit, void *data, int32_t immediate, int32_t flush_after, char force, int32_t priority);

/** The length in bits of a prepared challenge packet: its 16 bit header carries the byte count in the high 12 bits. */
inline int32_t network_packet_bit_count(const void *packet)
{
    return static_cast<int32_t>(*static_cast<const uint16_t *>(packet) >> 4) << 3;
}
char network_session_broadcast_to_flagged(int32_t body_bit_count, network_server_globals *server, int32_t status_bit, void *data, int32_t immediate, int32_t flush_after, char force, int32_t unused);
network_client_globals * network_session_create(void);
void network_session_destroy(network_client_globals *client);
void network_session_disconnect_with_error(int16_t error_code);
void network_session_host_cd_key_callback(int32_t game_id, int32_t local_id, int32_t authenticated, const char *message, void *instance);
void network_session_host_dispatch_message(int32_t key_id, int32_t index, void *buffer, void *user_data);
void network_session_host_dispose(void);
void network_session_host_natneg_callback(int32_t cookie);
void network_session_host_natneg_completed(int32_t result, uint32_t socket, const uint8_t *remote_address, void *user_data);
void network_session_host_qr2_add_error(int32_t error, char *message, void *user_data);
int32_t network_session_host_qr2_count(int32_t key_type, void *user_data);
void network_session_host_qr2_key_list(int32_t key_type, void *keybuffer, void *user_data);
void network_session_host_qr2_server_key(int32_t key_id, void *buffer, void *user_data);
void network_session_host_qr2_team_key(int32_t key_id, int32_t index, void *buffer, void *user_data);
uint8_t network_session_host_reject_or_cleanup_client(const char *response, const char *challenge, uint32_t ip, int32_t local_id);
int32_t network_session_host_start(void *user_data);
void network_session_host_start_info_set(const char *host_name, char *map_name, char *variant_name, int32_t game_type);
void network_session_host_update(void);
char network_session_info_packet_send(const uint32_t *source, network_client_globals *client);
void network_session_player_join_notify(network_client_globals *client, const uint32_t *source);
uint8_t network_session_player_table_index_apply(network_client_globals *client, int32_t table_index, const uint8_t *candidate);
int32_t network_session_reject_pending_connection_callback(void *unused, int32_t reject_code);
uint8_t network_session_send_to_machine(int32_t machine_id, network_server_globals *server, uint32_t status_bit, void *data, uint32_t body_bit_count, uint32_t reliable, uint32_t unknown_a, char force, uint32_t priority);
int32_t network_shutdown(void);
uint8_t network_signal_quality_glyph(uint32_t code);
int32_t network_staged_message_commit(network_client_globals *client, uint16_t message_value);
void network_stats_overlay_draw(network_bandwidth_graph *graph);
void network_stats_summary_log_open(void);
void network_stats_summary_log_write(void);
int32_t network_thread_create(uint8_t flags, void *start_address, void *parameter, network_thread_record **out_handle);
void network_timer_advance(network_timer_pair *timer);
void network_timer_decrement_floored(network_timer_pair *timer, int32_t decrement);
void network_timer_increment_clamped(network_timer_pair *timer, int32_t upper_bound, int32_t increment);
void network_timer_start(network_timer_pair *timer, int32_t duration_ms);
uint32_t network_update(void);
int32_t parse_time_duration_string(char *string, char default_unit, uint8_t *unit_table);
int32_t player_data_iterator_advance(int16_t player_index);
void player_update_client_local_player_update_from_network(message_delta_context *context);
void player_update_client_local_player_vehicle_update_from_network(message_delta_context *context);
void player_update_client_remote_player_action_update_from_network(message_delta_context *context);
void player_update_client_remote_player_position_delta_from_network(message_delta_context *context);
void player_update_client_remote_player_position_update_from_network(datum_index player_index, int32_t update_id, int32_t control_sequence, real x, real y, real z);
void player_update_client_remote_player_total_biped_update_from_network(message_delta_context *context);
void player_update_client_remote_player_total_vehicle_update_from_network(message_delta_context *context);
void player_update_client_remote_player_vehicle_position_delta_from_network(message_delta_context *context);
void player_update_client_remote_player_vehicle_update_from_network(datum_index player_index, int32_t update_id, int32_t control_sequence, vehicle_update_body vehicle);
uint8_t player_update_history_add(datum_index unit_index, player_update_history *history, int32_t tick_count, player_action control, int32_t *out_update_id);
void player_update_history_destroy(player_update_history *history);
player_update_history_node * player_update_history_find_and_prune(player_update_history *history, int32_t target_id, uint8_t prune);
void player_update_history_free_all(player_update_history *history);
void player_update_history_log_printf_filtered(player *target_player, int32_t unused_arg, const char *format, ...);
void player_update_history_log_set_name_filter(char *name);
void player_update_history_log_write(uint32_t category_flags, int32_t use_filtered_mask, const char *format, ...);
int32_t player_update_history_play(uint8_t prune, int32_t prune_target_id, player_update_history *history, datum_index unit_index, float server_x, float server_y, float server_z, local_player_vehicle_update_ack *vehicle_ack);
void player_update_history_play_for_update_index(datum_index player_index);
void player_update_history_play_local_player(int32_t target_update_id);
void player_update_queue_flush_by_name(char *name);
int32_t player_update_queue_offset_from_head(player *plr, int32_t new_update_id);
void player_update_remote_player_action_update_apply(int32_t **decode_context);
void qr2_register_key(int32_t keyid, const char *key);
void rcon(int32_t argument_count, char **arguments);
void rcon_send_request(char *command, char *password);
uint32_t registry_get_dist_id(void);
char * registry_get_halo_version(void);
void server_browser_column_header_update(network_ui_widget *header, int32_t sort_direction);
char * server_browser_custom_options_pack(server_browser_custom_options *options);
void server_browser_custom_options_unpack(char *text, server_browser_custom_options *out);
void server_browser_filter_headers_refresh(network_ui_widget *row);
void server_browser_filter_panel_set_mode(network_ui_widget *panel, uint8_t internet_mode);
int32_t server_browser_filter_widget_clicked(network_ui_widget *clicked);
uint32_t server_browser_gametype1_flags_pack(server_browser_gametype1_options *options);
void server_browser_gametype1_flags_unpack(uint32_t code, server_browser_gametype1_decoded *out);
uint32_t server_browser_gametype2_flags_pack(uint8_t *flags);
uint32_t server_browser_gametype3_flags_pack(server_browser_gametype3_options *options);
void server_browser_gametype3_flags_unpack(uint32_t code, server_browser_gametype3_options *out);
uint32_t server_browser_gametype5_flags_pack(int32_t *values);
void server_browser_gametype5_flags_unpack(uint32_t code, int32_t *out);
void server_browser_latch_join_target(void);
void server_browser_list_row_gather(network_ui_widget *row, uint8_t flag, void *entry);
void server_browser_list_row_populate(network_ui_widget *row, uint8_t flag1, uint8_t flag2, const char *server_name, wchar_t *map_name, const char *gametype_name, uint8_t flag3, int32_t count_a, int32_t count_b, int32_t ping);
int32_t server_browser_open(network_ui_widget *root);
int32_t server_browser_player_list_populate(void *entry);
void server_browser_query_results_ingest(server_list_globals *list);
void server_browser_result_array_sort(server_list_globals *array);
int32_t server_browser_selected_variant_description_build(void *entry);
uint8_t server_browser_server_passes_filter(void *entry);
server_browser_sort_comparator server_browser_sort_comparator_select(void);
void server_browser_total_players_compute(server_list_globals *array);
void server_browser_ui_refresh(void);
int32_t server_list_compare_by_gametype(const void *a, const void *b);
int32_t server_list_compare_by_hostname(const void *a, const void *b);
int32_t server_list_compare_by_mapname(void **a, void **b);
int32_t server_list_compare_by_mapname_then_hostname(void **a, void **b);
int32_t server_list_compare_by_ping_then_hostname(void **a, void **b);
int32_t server_list_compare_by_players(const void *a, const void *b);
int32_t server_list_compare_by_string_key(void **a, void **b, const char *key);
server_list_globals * server_list_mutex_try_lock(uint32_t timeout_ms);
void server_list_mutex_unlock(server_list_globals **list_slot);
void server_list_reset(server_list_globals *entry);
uint32_t server_list_result_count_get(void);
void server_list_result_reset(server_list_globals *entry);
void server_list_scroll_clamp(server_list_globals *results);
void server_list_scroll_page_down(uint8_t jump_to_bottom);
void server_list_scroll_page_up(uint8_t jump_to_top);
uint32_t __stdcall sig__setup_master_server_connection_sig(void *parameter);
uint8_t string_is_numeric(char *string);
void string_trim_whitespace(char **string_ptr);
void sv_ban(uint32_t argument_count, int32_t *arguments);
void sv_ban_penalty(uint32_t argument_count, int32_t *arguments);
void sv_banlist_file(uint32_t argument_count, int32_t *arguments);
network_player_entry * sv_find_client_by_name_or_index(char *name_or_index);
void sv_friendly_fire(uint32_t argument_count, int32_t *arguments);
void sv_kick(char *name_or_index);
void sv_map(uint32_t argument_count, uint16_t **arguments);
void sv_map_reset(void);
void sv_maxplayers(uint32_t argument_count, int32_t *arguments);
void sv_name(uint32_t argument_count, char **arguments);
void sv_password(uint32_t argument_count, char **arguments);
void sv_players(void);
uint32_t sv_players_find_by_team_index_desired(int8_t team_index_desired);
void sv_rcon_password(uint32_t argument_count, int32_t *arguments);
void sv_single_flag_force_reset(uint32_t argument_count, char **arguments);
void sv_status(void);
void sv_timelimit(uint32_t argument_count, int32_t *arguments);
void sv_tk_cooldown(uint32_t argument_count, int32_t *arguments);
void sv_tk_grace(uint32_t argument_count, int32_t *arguments);
void ticker_text_buffer_advance(network_ui_widget *widget, ticker_text_buffer *self);
void ticker_text_buffer_append(wchar_t *text, int32_t reset_column, ticker_text_buffer *self);
void ticker_text_buffer_reset(ticker_text_buffer *self);
char update_server_send_update(int32_t tick_count, char frame_time_overflow);
void vector3d_from_yaw_pitch(real_vector3d *out_direction, real yaw, real pitch);
void vector3d_lerp_by_mode_denominator(vector3d_lerp_table *table, real_vector3d *out_point, int32_t *ratios);
void vector3d_quantize(int32_t *out_indices, int32_t *descriptor, real *point);
void vector3d_to_angles(real *out, real_vector3d vector);
uint8_t waypoint_table_quantize_initialize(message_delta_field_type *field_type);

}
