/* standalone/image/pieces.c -- generated by tools/gen_link_sources.py from pieces.json; do not edit.
   The data image pieces (standalone/image/<label>.asm) the loader copies to their original addresses. */
#include "../standalone_tables.h"

extern const unsigned char halo_image_rdata[];
extern const unsigned char halo_image_data[];
extern const unsigned char halo_image_tls[];
extern const unsigned char halo_image_rsrc[];

const standalone_piece standalone_pieces[] = {
    { "rdata", 0x0063a000UL, halo_image_rdata, 0x0003c000UL },
    { "data", 0x00676000UL, halo_image_data, 0x0002a088UL },
    { "tls", 0x00881000UL, halo_image_tls, 0x00001000UL },
    { "rsrc", 0x00882000UL, halo_image_rsrc, 0x0000f000UL },
};
const int standalone_piece_count = 4;
