/**
 * standalone/data/layout_check.cpp -- generated by tools/gen_layout_check.py from eq_bss.cpp and eq_data.cpp; do not edit.
 * standalone_data_layout_check() reports every clustered global whose offset from its cluster start differs from
 * the original image (a toolchain that does not keep the eq_*.cpp order).
 */
#include <stdint.h>

extern "C" {
void __cdecl standalone_log(const char *format, ...);
extern uint8_t DAT_006b5e60[];
extern uint8_t DAT_006b5e64[];
extern uint8_t DAT_006b5e68[];
extern uint8_t DAT_006b5e6c[];
extern uint8_t DAT_006b5e7c[];
extern uint8_t DAT_006b5e80[];
extern uint8_t DAT_006b5e84[];
extern uint8_t DAT_006b5e88[];
extern uint8_t DAT_007193be[];
extern uint8_t actor_mode_default_look_weights[];
extern uint8_t actor_mode_guard_look_weights_a5[];
extern uint8_t actor_mode_guard_look_weights_a6[];
extern uint8_t actor_mode_guard_look_weights_ambush[];
extern uint8_t actor_mode_guard_look_weights_idle[];
extern uint8_t actor_mode_uncover_look_weights_active[];
extern uint8_t actor_type_procs[];
extern uint8_t ambient_noise[];
extern uint8_t cache_file_current_header[];
extern uint8_t cache_file_current_header_crc32[];
extern uint8_t cached_network_engine_index[];
extern uint8_t camera_field_of_view[];
extern uint8_t camera_forward_x[];
extern uint8_t camera_forward_y[];
extern uint8_t camera_forward_z[];
extern uint8_t camera_leaf[];
extern uint8_t camera_point[];
extern uint8_t camera_position[];
extern uint8_t camera_position_y[];
extern uint8_t camera_position_y_table[];
extern uint8_t camera_position_z[];
extern uint8_t camera_position_z_table[];
extern uint8_t camera_script[];
extern uint8_t camera_script_time_remaining[];
extern uint8_t camera_up[];
extern uint8_t chat_hotkey_all[];
extern uint8_t chat_hotkey_team[];
extern uint8_t chat_hotkey_vehicle[];
extern uint8_t chimera_contrail_scale[];
extern uint8_t chimera_loading_screen_cleanup_gate[];
extern uint8_t collideable_cluster_first[];
extern uint8_t collideable_cluster_partition[];
extern uint8_t collideable_object_references[];
extern uint8_t console_color_00685214[];
extern uint8_t console_message_default_color[];
extern uint8_t control_binding_device_type[];
extern uint8_t control_gamepad_action_scan_buttons[];
extern uint8_t control_gamepad_axis_scan_table[];
extern uint8_t control_gamepad_button_scan_table[];
extern uint8_t control_gamepad_pov_scan_table[];
extern uint8_t control_keyboard_scan_table[];
extern uint8_t control_mouse_axis_scan_table[];
extern uint8_t control_mouse_button_scan_table[];
extern uint8_t control_word_primary[];
extern uint8_t control_word_secondary[];
extern uint8_t controls_action_name_buffer[];
extern uint8_t controls_action_table[];
extern uint8_t controls_captured_binding[];
extern uint8_t controls_current_binding_table[];
extern uint8_t controls_device_sensitivity_a[];
extern uint8_t controls_device_sensitivity_b[];
extern uint8_t controls_input_capture_buffer[];
extern uint8_t controls_input_capture_flags[];
extern uint8_t controls_row_device_mask_table[];
extern uint8_t coop_profile_globals_block_00714ddc[];
extern uint8_t ctf_active_team[];
extern uint8_t ctf_flag_auto_return_ticks[];
extern uint8_t ctf_flag_capture_limit_006b0ea0[];
extern uint8_t ctf_globals_live[];
extern uint8_t ctf_neutral_flag_id[];
extern uint8_t ctf_notify_throttle_tick[];
extern uint8_t ctf_team_captured_flags_mask[];
extern uint8_t ctf_team_flag_object[];
extern uint8_t ctf_team_flag_stand_position[];
extern uint8_t ctf_team_flag_touch_count[];
extern uint8_t ctf_team_return_credit_active[];
extern uint8_t ctf_team_return_credit_ticks[];
extern uint8_t default_axis_b[];
extern uint8_t default_color_a[];
extern uint8_t default_color_b[];
extern uint8_t director_camera_mode[];
extern uint8_t director_camera_target[];
extern uint8_t director_camera_target_changed[];
extern uint8_t directors[];
extern uint8_t environment_effect_slot[];
extern uint8_t environment_techniques_no[];
extern uint8_t environment_techniques_ps14[];
extern uint8_t escape_key_state[];
extern uint8_t font_glyph_cache_slots[];
extern uint8_t g_006f1cf4[];
extern uint8_t g_006f1d25[];
extern uint8_t g_control_binding_id[];
extern uint8_t g_control_binding_region_e0[];
extern uint8_t g_control_binding_region_e4[];
extern uint8_t g_control_binding_region_ec[];
extern uint8_t g_control_binding_value[];
extern uint8_t g_font_glyph_cache[];
extern uint8_t game_engine_bucket_scores[];
extern uint8_t game_engine_bucket_scores_extra[];
extern uint8_t game_engine_dedicated_idle[];
extern uint8_t game_engine_dedicated_idle_timer[];
extern uint8_t game_engine_map_table_value[];
extern uint8_t game_engine_nameplate_fade_opacity_array[];
extern uint8_t game_engine_pending_variant[];
extern uint8_t game_engine_round_reset_tick[];
extern uint8_t game_engine_teams_enabled_flag[];
extern uint8_t game_engine_unknown_1cfc[];
extern uint8_t game_engine_variant[];
extern uint8_t game_engine_variant_score_limit[];
extern uint8_t game_screen_rect[];
extern uint8_t game_screen_rect_bottom[];
extern uint8_t game_screen_rect_left[];
extern uint8_t game_screen_rect_right[];
extern uint8_t game_time_unknown_48[];
extern uint8_t game_time_unknown_49[];
extern uint8_t game_variant_saved_default[];
extern uint8_t game_variant_saved_default_valid[];
extern uint8_t game_window_bottom_right[];
extern uint8_t game_window_top_left[];
extern uint8_t gamepad_action_buttons[];
extern uint8_t gamepad_axis_bindings[];
extern uint8_t gamepad_button_bindings[];
extern uint8_t gamepad_pov_bindings[];
extern uint8_t global_real_rgb_green_pointer[];
extern uint8_t global_white_argb[];
extern uint8_t global_white_color[];
extern uint8_t hill_pulse_fade_done[];
extern uint8_t hill_pulse_grow_done[];
extern uint8_t hud_text_draw_background_mode[];
extern uint8_t hud_text_draw_box_field_474e[];
extern uint8_t hud_text_draw_box_field_4756[];
extern uint8_t hud_text_draw_color_a[];
extern uint8_t hud_text_draw_color_b[];
extern uint8_t hud_text_draw_color_g[];
extern uint8_t hud_text_draw_color_or_flags[];
extern uint8_t hud_text_draw_color_r[];
extern uint8_t hud_text_draw_column[];
extern uint8_t hud_text_draw_tabstop_c[];
extern uint8_t hud_text_message_hold_color[];
extern uint8_t hud_text_message_normal_color[];
extern uint8_t input_controls_live_006b3a48[];
extern uint8_t input_device_to_slot[];
extern uint8_t input_devices[];
extern uint8_t input_event_queue_active[];
extern uint8_t input_globals[];
extern uint8_t keyboard_bindings[];
extern uint8_t king_alt_player_score[];
extern uint8_t king_alt_player_scores_network[];
extern uint8_t king_alt_score_target[];
extern uint8_t king_alt_scores_network_tail[];
extern uint8_t king_alt_team_score[];
extern uint8_t king_alt_team_scores_network[];
extern uint8_t king_alt_team_scores_network2[];
extern uint8_t king_bucket_credit_ticks[];
extern uint8_t king_bucket_last_credit_tick[];
extern uint8_t king_hill_boundary_center[];
extern uint8_t king_hill_boundary_extra[];
extern uint8_t king_hill_boundary_max_z[];
extern uint8_t king_hill_boundary_min_z[];
extern uint8_t king_hill_boundary_points[];
extern uint8_t king_hill_broadcast_overrun_value[];
extern uint8_t king_hill_index_006b1058[];
extern uint8_t king_hill_move_ticks_006b1068[];
extern uint8_t king_hill_occupant_last_tick[];
extern uint8_t king_hill_occupant_table[];
extern uint8_t king_hill_player_in_hill[];
extern uint8_t king_hill_single_occupant_flag[];
extern uint8_t king_hill_state_006b1054[];
extern uint8_t king_hill_state_globals[];
extern uint8_t king_starting_location_count[];
extern uint8_t king_starting_location_type[];
extern uint8_t king_team_hill_seconds_network[];
extern uint8_t known_solo_level_index_00712f00[];
extern uint8_t length_error_throw_info[];
extern uint8_t lens_flare_applied_key[];
extern uint8_t lens_flare_batch_mode[];
extern uint8_t lens_flare_current_key[];
extern uint8_t lens_flare_effect[];
extern uint8_t lens_flare_marker_visibility[];
extern uint8_t level_select_current_path_00719068[];
extern uint8_t level_select_flags_0071916a[];
extern uint8_t level_select_flags_0071916b[];
extern uint8_t level_select_flags_0071916c[];
extern uint8_t level_select_frame_00719168[];
extern uint8_t light_cluster_first[];
extern uint8_t light_cluster_references[];
extern uint8_t light_object_references[];
extern uint8_t loading_thread[];
extern uint8_t loading_thread_result[];
extern uint8_t local_player_0_cluster_index[];
extern uint8_t local_player_globals[];
extern uint8_t local_player_hud_status_table[];
extern uint8_t local_player_input_frozen[];
extern uint8_t local_player_input_states[];
extern uint8_t local_player_look_frozen[];
extern uint8_t local_team_00714dd8[];
extern uint8_t main_menu_music_pending[];
extern uint8_t map_per_map_table[];
extern uint8_t material_table_bad_index[];
extern uint8_t material_table_fallback[];
extern uint8_t message_delta_field_type_table[];
extern uint8_t message_delta_unknown_table_0069a304[];
extern uint8_t motion_sensor_override_value[];
extern uint8_t mouse_axis_bindings[];
extern uint8_t mouse_button_bindings[];
extern uint8_t multiplayer_maps[];
extern uint8_t network_buffer_pair_pool[];
extern uint8_t network_buffer_pair_pool_count[];
extern uint8_t network_buffer_pair_pool_data[];
extern uint8_t network_host_edit_field_00719410[];
extern uint8_t network_join_error_code[];
extern uint8_t network_scenario_round_counter_a[];
extern uint8_t network_server_storage[];
extern uint8_t network_stats_overlay_text_rect_max[];
extern uint8_t network_stats_overlay_text_rect_min[];
extern uint8_t new_profile_name_buffer_006b37f4[];
extern uint8_t new_profile_name_terminator_006b380a[];
extern uint8_t noncollideable_cluster_first[];
extern uint8_t noncollideable_cluster_partition[];
extern uint8_t noncollideable_object_references[];
extern uint8_t object_ambient_lightmap_default[];
extern uint8_t object_data[];
extern uint8_t object_type_definitions[];
extern uint8_t object_type_definitions_ex[];
extern uint8_t observers[];
extern uint8_t oddball_ball_timers_006b11cc[];
extern uint8_t os_platform_refresh_default[];
extern uint8_t out_of_range_throw_info[];
extern uint8_t player_control_look_rates_0070facc[];
extern uint8_t portal_visibility_tolerance[];
extern uint8_t profile_globals_block[];
extern uint8_t profile_load_complete[];
extern uint8_t profile_slot_flag[];
extern uint8_t profile_slot_id[];
extern uint8_t quit_confirm_error_is_error[];
extern uint8_t quit_confirm_error_modal[];
extern uint8_t quit_confirm_error_string_index[];
extern uint8_t quit_confirm_error_unknown_ae[];
extern uint8_t race_used_location_count[];
extern uint8_t race_used_locations[];
extern uint8_t race_vehicle_counts[];
extern uint8_t rasterizer_camera_forward[];
extern uint8_t rasterizer_camera_position[];
extern uint8_t rasterizer_capability_007c10e4[];
extern uint8_t rasterizer_caps[];
extern uint8_t rasterizer_depth_prepass_vertex_shader[];
extern uint8_t rasterizer_desktop_display_mode[];
extern uint8_t rasterizer_device_version[];
extern uint8_t rasterizer_dynamic_vertex_caches[];
extern uint8_t rasterizer_effects[];
extern uint8_t rasterizer_fog_atmospheric_color[];
extern uint8_t rasterizer_fog_atmospheric_max_density[];
extern uint8_t rasterizer_fog_atmospheric_max_distance[];
extern uint8_t rasterizer_fog_atmospheric_min_distance[];
extern uint8_t rasterizer_fog_flags[];
extern uint8_t rasterizer_fog_planar_color[];
extern uint8_t rasterizer_fog_plane[];
extern uint8_t rasterizer_model_vertex_declaration[];
extern uint8_t rasterizer_screen_flash_effect[];
extern uint8_t rasterizer_time[];
extern uint8_t rasterizer_vertex_declarations[];
extern uint8_t rasterizer_vertex_shaders[];
extern uint8_t rasterizer_window[];
extern uint8_t render_camera_facing_basis[];
extern uint8_t render_camera_world_to_view[];
extern uint8_t render_frustum_global[];
extern uint8_t render_unknown_7bf04c[];
extern uint8_t render_unknown_d98f0[];
extern uint8_t render_viewport_bottom[];
extern uint8_t render_viewport_left[];
extern uint8_t render_viewport_right[];
extern uint8_t render_viewport_top[];
extern uint8_t renderer_unknown_69e468[];
extern uint8_t renderer_unknown_6e1af0[];
extern uint8_t renderer_unknown_6e1af8[];
extern uint8_t s_stand[];
extern uint8_t saved_item_disk_copy[];
extern uint8_t saved_item_working_copy[];
extern uint8_t saved_player_profile_slots_handle[];
extern uint8_t screen_fade_progress[];
extern uint8_t screen_safe_area_bottom[];
extern uint8_t screen_safe_area_right[];
extern uint8_t selected_saved_item[];
extern uint8_t server_browser_player_ticker[];
extern uint8_t server_browser_query_elapsed_ms[];
extern uint8_t server_browser_variant_ticker[];
extern uint8_t server_list[];
extern uint8_t server_list_block_capacity[];
extern uint8_t server_list_block_used[];
extern uint8_t slayer_player_score[];
extern uint8_t slayer_team_score[];
extern uint8_t team_data[];
extern uint8_t text_tab_stops[];
extern uint8_t ui_input_batch_mode[];
extern uint8_t ui_pause_depth[];
extern uint8_t ui_pause_pending_count_00718fa0[];
extern uint8_t ui_pending_error_alternate[];
extern uint8_t ui_pending_errors[];
extern uint8_t ui_root_widget[];
extern uint8_t ui_time_milliseconds[];
extern uint8_t ui_widget_history[];
extern uint8_t ui_widget_show_path_flag[];
extern uint8_t unit_base_animation_state_names[];
extern uint8_t unknown_00699f40[];
extern uint8_t unknown_006ac568[];
extern uint8_t unknown_006ac620[];
extern uint8_t unknown_006ac624[];
extern uint8_t unknown_006e1b58[];
extern uint8_t unknown_007124a0[];
extern uint8_t unknown_00712ccc[];
extern uint8_t unknown_00714eb8[];
extern uint8_t unknown_00714f14[];
extern uint8_t unknown_00746280_block[];
extern uint8_t unknown_00861d4e[];
extern uint8_t unknown_00861d4f[];
extern uint8_t unknown_0087aa7f[];
extern uint8_t unknown_0087aaec[];
extern uint8_t unknown_0087aaf8[];
extern uint8_t update_client_base_tick[];
extern uint8_t update_client_held_control_flags[];
extern uint8_t update_client_history[];
extern uint8_t update_client_initialized[];
extern uint8_t update_client_latest_tick[];
extern uint8_t update_client_queues[];
extern uint8_t update_client_staged[];
extern uint8_t update_client_staged_count[];
extern uint8_t update_client_ticks_remaining[];
extern uint8_t update_client_unknown_ea8[];
extern uint8_t update_client_unknown_eac[];
extern uint8_t update_server_history[];
extern uint8_t update_server_initialized[];
extern uint8_t update_server_queues[];
extern uint8_t update_server_tick[];
extern uint8_t variant_defaults_source[];
extern uint8_t vehicle_network_update_period[];
extern uint8_t virtual_keyboard[];
extern uint8_t waypoint_fade_far[];
extern uint8_t waypoint_fade_near[];
extern uint8_t weather_frame_counter[];
extern uint8_t weather_particle_system_count[];
extern uint8_t weather_wind_states[];
extern uint8_t widget_creating_children[];
extern uint8_t widget_memory_pool_valid[];
}

namespace {

struct layout_entry {
    const uint8_t *object;
    uint32_t original_address;
    const char *name;
};

const layout_entry k_cluster_0[] = {
    {cache_file_current_header, 0x006a8154u, "cache_file_current_header"},
    {cache_file_current_header_crc32, 0x006a81b8u, "cache_file_current_header_crc32"},
};
const layout_entry k_cluster_1[] = {
    {directors, 0x006ac560u, "directors"},
    {unknown_006ac568, 0x006ac568u, "unknown_006ac568"},
    {local_player_look_frozen, 0x006ac5b1u, "local_player_look_frozen"},
    {local_player_input_frozen, 0x006ac5b2u, "local_player_input_frozen"},
    {unknown_006ac620, 0x006ac620u, "unknown_006ac620"},
    {unknown_006ac624, 0x006ac624u, "unknown_006ac624"},
};
const layout_entry k_cluster_2[] = {
    {observers, 0x006ac65cu, "observers"},
    {camera_point, 0x006ac6d0u, "camera_point"},
    {camera_position_y_table, 0x006ac6d4u, "camera_position_y_table"},
    {camera_position_z_table, 0x006ac6d8u, "camera_position_z_table"},
    {camera_leaf, 0x006ac6dcu, "camera_leaf"},
    {local_player_0_cluster_index, 0x006ac6e0u, "local_player_0_cluster_index"},
};
const layout_entry k_cluster_3[] = {
    {ctf_team_flag_stand_position, 0x006b0e88u, "ctf_team_flag_stand_position"},
    {ctf_team_flag_object, 0x006b0e90u, "ctf_team_flag_object"},
    {ctf_team_flag_touch_count, 0x006b0e98u, "ctf_team_flag_touch_count"},
    {ctf_flag_capture_limit_006b0ea0, 0x006b0ea0u, "ctf_flag_capture_limit_006b0ea0"},
    {ctf_team_return_credit_active, 0x006b0ea4u, "ctf_team_return_credit_active"},
    {ctf_team_return_credit_ticks, 0x006b0ea8u, "ctf_team_return_credit_ticks"},
    {ctf_flag_auto_return_ticks, 0x006b0eb0u, "ctf_flag_auto_return_ticks"},
    {ctf_notify_throttle_tick, 0x006b0eb4u, "ctf_notify_throttle_tick"},
    {ctf_active_team, 0x006b0eb8u, "ctf_active_team"},
};
const layout_entry k_cluster_4[] = {
    {king_bucket_credit_ticks, 0x006b0ec0u, "king_bucket_credit_ticks"},
    {king_bucket_last_credit_tick, 0x006b0f00u, "king_bucket_last_credit_tick"},
    {king_hill_player_in_hill, 0x006b0f40u, "king_hill_player_in_hill"},
    {king_starting_location_count, 0x006b0f50u, "king_starting_location_count"},
    {king_hill_boundary_points, 0x006b0f54u, "king_hill_boundary_points"},
    {king_hill_boundary_extra, 0x006b0fe4u, "king_hill_boundary_extra"},
    {king_hill_boundary_center, 0x006b1044u, "king_hill_boundary_center"},
    {king_hill_state_globals, 0x006b1050u, "king_hill_state_globals"},
    {king_hill_state_006b1054, 0x006b1054u, "king_hill_state_006b1054"},
    {king_hill_index_006b1058, 0x006b1058u, "king_hill_index_006b1058"},
    {king_hill_boundary_max_z, 0x006b105cu, "king_hill_boundary_max_z"},
    {king_hill_boundary_min_z, 0x006b1060u, "king_hill_boundary_min_z"},
    {king_starting_location_type, 0x006b1064u, "king_starting_location_type"},
    {king_hill_move_ticks_006b1068, 0x006b1068u, "king_hill_move_ticks_006b1068"},
};
const layout_entry k_cluster_5[] = {
    {king_alt_score_target, 0x006b1148u, "king_alt_score_target"},
    {king_alt_team_score, 0x006b114cu, "king_alt_team_score"},
    {king_alt_player_score, 0x006b118cu, "king_alt_player_score"},
    {oddball_ball_timers_006b11cc, 0x006b11ccu, "oddball_ball_timers_006b11cc"},
    {king_hill_occupant_table, 0x006b120cu, "king_hill_occupant_table"},
    {king_hill_occupant_last_tick, 0x006b124cu, "king_hill_occupant_last_tick"},
    {ctf_globals_live, 0x006b1290u, "ctf_globals_live"},
    {ctf_team_captured_flags_mask, 0x006b12d4u, "ctf_team_captured_flags_mask"},
    {ctf_neutral_flag_id, 0x006b1314u, "ctf_neutral_flag_id"},
    {game_engine_bucket_scores, 0x006b1318u, "game_engine_bucket_scores"},
    {game_engine_bucket_scores_extra, 0x006b1358u, "game_engine_bucket_scores_extra"},
    {race_used_locations, 0x006b139cu, "race_used_locations"},
    {race_used_location_count, 0x006b13bcu, "race_used_location_count"},
    {race_vehicle_counts, 0x006b13c0u, "race_vehicle_counts"},
    {slayer_team_score, 0x006b13d8u, "slayer_team_score"},
    {slayer_player_score, 0x006b1418u, "slayer_player_score"},
};
const layout_entry k_cluster_6[] = {
    {input_devices, 0x006b1868u, "input_devices"},
    {input_device_to_slot, 0x006b1a98u, "input_device_to_slot"},
};
const layout_entry k_cluster_7[] = {
    {new_profile_name_buffer_006b37f4, 0x006b37f4u, "new_profile_name_buffer_006b37f4"},
    {new_profile_name_terminator_006b380a, 0x006b380au, "new_profile_name_terminator_006b380a"},
};
const layout_entry k_cluster_8[] = {
    {input_controls_live_006b3a48, 0x006b3a48u, "input_controls_live_006b3a48"},
    {controls_action_name_buffer, 0x006b3d48u, "controls_action_name_buffer"},
};
const layout_entry k_cluster_9[] = {
    {server_browser_player_ticker, 0x006b5e58u, "server_browser_player_ticker"},
    {DAT_006b5e60, 0x006b5e60u, "DAT_006b5e60"},
    {DAT_006b5e64, 0x006b5e64u, "DAT_006b5e64"},
    {DAT_006b5e68, 0x006b5e68u, "DAT_006b5e68"},
    {DAT_006b5e6c, 0x006b5e6cu, "DAT_006b5e6c"},
    {server_browser_variant_ticker, 0x006b5e74u, "server_browser_variant_ticker"},
    {DAT_006b5e7c, 0x006b5e7cu, "DAT_006b5e7c"},
    {DAT_006b5e80, 0x006b5e80u, "DAT_006b5e80"},
    {DAT_006b5e84, 0x006b5e84u, "DAT_006b5e84"},
    {DAT_006b5e88, 0x006b5e88u, "DAT_006b5e88"},
};
const layout_entry k_cluster_10[] = {
    {network_buffer_pair_pool, 0x006b85a8u, "network_buffer_pair_pool"},
    {network_buffer_pair_pool_count, 0x006b85acu, "network_buffer_pair_pool_count"},
    {network_buffer_pair_pool_data, 0x006b85b0u, "network_buffer_pair_pool_data"},
};
const layout_entry k_cluster_11[] = {
    {lens_flare_marker_visibility, 0x006be810u, "lens_flare_marker_visibility"},
    {king_hill_single_occupant_flag, 0x006c0f3fu, "king_hill_single_occupant_flag"},
};
const layout_entry k_cluster_12[] = {
    {g_font_glyph_cache, 0x006d8828u, "g_font_glyph_cache"},
    {font_glyph_cache_slots, 0x006d8838u, "font_glyph_cache_slots"},
};
const layout_entry k_cluster_13[] = {
    {rasterizer_dynamic_vertex_caches, 0x006d98e8u, "rasterizer_dynamic_vertex_caches"},
    {render_unknown_d98f0, 0x006d98f0u, "render_unknown_d98f0"},
};
const layout_entry k_cluster_14[] = {
    {environment_techniques_no, 0x006e17f4u, "environment_techniques_no"},
    {environment_techniques_ps14, 0x006e180cu, "environment_techniques_ps14"},
};
const layout_entry k_cluster_15[] = {
    {rasterizer_vertex_declarations, 0x006e1a90u, "rasterizer_vertex_declarations"},
    {rasterizer_model_vertex_declaration, 0x006e1ac0u, "rasterizer_model_vertex_declaration"},
    {renderer_unknown_6e1af0, 0x006e1af0u, "renderer_unknown_6e1af0"},
    {renderer_unknown_6e1af8, 0x006e1af8u, "renderer_unknown_6e1af8"},
    {unknown_006e1b58, 0x006e1b58u, "unknown_006e1b58"},
};
const layout_entry k_cluster_16[] = {
    {material_table_fallback, 0x006e3208u, "material_table_fallback"},
    {material_table_bad_index, 0x006e3578u, "material_table_bad_index"},
};
const layout_entry k_cluster_17[] = {
    {hud_text_draw_color_or_flags, 0x006e4734u, "hud_text_draw_color_or_flags"},
    {hud_text_draw_column, 0x006e4736u, "hud_text_draw_column"},
    {hud_text_draw_color_a, 0x006e4738u, "hud_text_draw_color_a"},
    {hud_text_draw_color_r, 0x006e473cu, "hud_text_draw_color_r"},
    {hud_text_draw_color_g, 0x006e4740u, "hud_text_draw_color_g"},
    {hud_text_draw_color_b, 0x006e4744u, "hud_text_draw_color_b"},
    {hud_text_draw_background_mode, 0x006e4748u, "hud_text_draw_background_mode"},
    {text_tab_stops, 0x006e474au, "text_tab_stops"},
    {hud_text_draw_box_field_474e, 0x006e474eu, "hud_text_draw_box_field_474e"},
    {hud_text_draw_tabstop_c, 0x006e4752u, "hud_text_draw_tabstop_c"},
    {hud_text_draw_box_field_4756, 0x006e4756u, "hud_text_draw_box_field_4756"},
};
const layout_entry k_cluster_18[] = {
    {game_engine_variant, 0x006f1c88u, "game_engine_variant"},
    {control_binding_device_type, 0x006f1cb8u, "control_binding_device_type"},
    {game_engine_teams_enabled_flag, 0x006f1cbcu, "game_engine_teams_enabled_flag"},
    {motion_sensor_override_value, 0x006f1cc0u, "motion_sensor_override_value"},
    {game_engine_variant_score_limit, 0x006f1ce0u, "game_engine_variant_score_limit"},
    {control_word_primary, 0x006f1ce8u, "control_word_primary"},
    {control_word_secondary, 0x006f1cecu, "control_word_secondary"},
    {vehicle_network_update_period, 0x006f1cf0u, "vehicle_network_update_period"},
    {g_006f1cf4, 0x006f1cf4u, "g_006f1cf4"},
    {game_engine_unknown_1cfc, 0x006f1cfcu, "game_engine_unknown_1cfc"},
    {hill_pulse_grow_done, 0x006f1d04u, "hill_pulse_grow_done"},
    {hill_pulse_fade_done, 0x006f1d05u, "hill_pulse_fade_done"},
};
const layout_entry k_cluster_19[] = {
    {game_engine_map_table_value, 0x006f1d24u, "game_engine_map_table_value"},
    {g_006f1d25, 0x006f1d25u, "g_006f1d25"},
};
const layout_entry k_cluster_20[] = {
    {game_time_unknown_48, 0x006f1d48u, "game_time_unknown_48"},
    {game_time_unknown_49, 0x006f1d49u, "game_time_unknown_49"},
};
const layout_entry k_cluster_21[] = {
    {update_server_initialized, 0x006f1d88u, "update_server_initialized"},
    {update_server_tick, 0x006f1d8cu, "update_server_tick"},
    {update_server_queues, 0x006f1d90u, "update_server_queues"},
    {update_server_history, 0x006f1d94u, "update_server_history"},
    {update_client_initialized, 0x006f7e98u, "update_client_initialized"},
    {update_client_base_tick, 0x006f7e9cu, "update_client_base_tick"},
    {update_client_latest_tick, 0x006f7ea0u, "update_client_latest_tick"},
    {update_client_staged, 0x006f7ea4u, "update_client_staged"},
    {update_client_unknown_ea8, 0x006f7ea8u, "update_client_unknown_ea8"},
    {update_client_unknown_eac, 0x006f7eacu, "update_client_unknown_eac"},
    {update_client_ticks_remaining, 0x006f7ec4u, "update_client_ticks_remaining"},
    {update_client_held_control_flags, 0x006f7ec8u, "update_client_held_control_flags"},
    {update_client_staged_count, 0x006f7eccu, "update_client_staged_count"},
    {update_client_queues, 0x006f7ed0u, "update_client_queues"},
    {update_client_history, 0x006f7ed4u, "update_client_history"},
    {player_control_look_rates_0070facc, 0x0070faccu, "player_control_look_rates_0070facc"},
};
const layout_entry k_cluster_22[] = {
    {input_globals, 0x00710328u, "input_globals"},
    {keyboard_bindings, 0x00710330u, "keyboard_bindings"},
    {mouse_button_bindings, 0x0071040au, "mouse_button_bindings"},
    {mouse_axis_bindings, 0x0071041au, "mouse_axis_bindings"},
    {gamepad_button_bindings, 0x00710426u, "gamepad_button_bindings"},
    {gamepad_action_buttons, 0x00710526u, "gamepad_action_buttons"},
    {gamepad_axis_bindings, 0x00710536u, "gamepad_axis_bindings"},
    {gamepad_pov_bindings, 0x00710736u, "gamepad_pov_bindings"},
    {local_player_input_states, 0x00712498u, "local_player_input_states"},
    {unknown_007124a0, 0x007124a0u, "unknown_007124a0"},
    {chimera_loading_screen_cleanup_gate, 0x007124a1u, "chimera_loading_screen_cleanup_gate"},
    {local_player_hud_status_table, 0x007124a4u, "local_player_hud_status_table"},
    {chat_hotkey_all, 0x007124a7u, "chat_hotkey_all"},
    {chat_hotkey_team, 0x007124a8u, "chat_hotkey_team"},
    {chat_hotkey_vehicle, 0x007124a9u, "chat_hotkey_vehicle"},
    {controls_input_capture_flags, 0x00712542u, "controls_input_capture_flags"},
    {controls_input_capture_buffer, 0x00712544u, "controls_input_capture_buffer"},
    {controls_captured_binding, 0x007127c4u, "controls_captured_binding"},
    {escape_key_state, 0x007127d1u, "escape_key_state"},
    {controls_current_binding_table, 0x007127d4u, "controls_current_binding_table"},
};
const layout_entry k_cluster_23[] = {
    {input_event_queue_active, 0x00712cc0u, "input_event_queue_active"},
    {unknown_00712ccc, 0x00712cccu, "unknown_00712ccc"},
};
const layout_entry k_cluster_24[] = {
    {profile_globals_block, 0x00712dd8u, "profile_globals_block"},
    {known_solo_level_index_00712f00, 0x00712f00u, "known_solo_level_index_00712f00"},
    {profile_slot_flag, 0x00712f07u, "profile_slot_flag"},
    {saved_player_profile_slots_handle, 0x00714dd4u, "saved_player_profile_slots_handle"},
    {local_team_00714dd8, 0x00714dd8u, "local_team_00714dd8"},
    {coop_profile_globals_block_00714ddc, 0x00714ddcu, "coop_profile_globals_block_00714ddc"},
    {profile_slot_id, 0x00714ddeu, "profile_slot_id"},
    {game_variant_saved_default, 0x00714de0u, "game_variant_saved_default"},
    {game_variant_saved_default_valid, 0x00714e78u, "game_variant_saved_default_valid"},
    {selected_saved_item, 0x00714e7cu, "selected_saved_item"},
    {saved_item_working_copy, 0x00714e80u, "saved_item_working_copy"},
    {unknown_00714eb8, 0x00714eb8u, "unknown_00714eb8"},
    {unknown_00714f14, 0x00714f14u, "unknown_00714f14"},
    {control_keyboard_scan_table, 0x00714fb4u, "control_keyboard_scan_table"},
    {control_mouse_button_scan_table, 0x0071508eu, "control_mouse_button_scan_table"},
    {control_mouse_axis_scan_table, 0x0071509eu, "control_mouse_axis_scan_table"},
    {control_gamepad_button_scan_table, 0x007150aau, "control_gamepad_button_scan_table"},
    {control_gamepad_action_scan_buttons, 0x007151aau, "control_gamepad_action_scan_buttons"},
    {control_gamepad_axis_scan_table, 0x007151bau, "control_gamepad_axis_scan_table"},
    {control_gamepad_pov_scan_table, 0x007153bau, "control_gamepad_pov_scan_table"},
    {controls_device_sensitivity_a, 0x007157d4u, "controls_device_sensitivity_a"},
    {controls_device_sensitivity_b, 0x007157d8u, "controls_device_sensitivity_b"},
    {saved_item_disk_copy, 0x00716e7cu, "saved_item_disk_copy"},
    {profile_load_complete, 0x00718e78u, "profile_load_complete"},
};
const layout_entry k_cluster_25[] = {
    {ui_root_widget, 0x00718f94u, "ui_root_widget"},
    {ui_widget_history, 0x00718f98u, "ui_widget_history"},
    {ui_time_milliseconds, 0x00718f9cu, "ui_time_milliseconds"},
    {ui_pause_pending_count_00718fa0, 0x00718fa0u, "ui_pause_pending_count_00718fa0"},
    {network_join_error_code, 0x00718fa4u, "network_join_error_code"},
    {ui_pause_depth, 0x00718fa6u, "ui_pause_depth"},
    {screen_fade_progress, 0x00718fa8u, "screen_fade_progress"},
    {quit_confirm_error_string_index, 0x00718facu, "quit_confirm_error_string_index"},
    {quit_confirm_error_unknown_ae, 0x00718faeu, "quit_confirm_error_unknown_ae"},
    {quit_confirm_error_modal, 0x00718fb0u, "quit_confirm_error_modal"},
    {quit_confirm_error_is_error, 0x00718fb1u, "quit_confirm_error_is_error"},
    {ui_pending_error_alternate, 0x00718fb2u, "ui_pending_error_alternate"},
    {ui_pending_errors, 0x00718fb6u, "ui_pending_errors"},
    {loading_thread, 0x00718fbcu, "loading_thread"},
    {loading_thread_result, 0x00718fc0u, "loading_thread_result"},
    {widget_memory_pool_valid, 0x00718fc2u, "widget_memory_pool_valid"},
    {widget_creating_children, 0x00718fc3u, "widget_creating_children"},
    {ui_widget_show_path_flag, 0x00718fc4u, "ui_widget_show_path_flag"},
    {ui_input_batch_mode, 0x00718fc5u, "ui_input_batch_mode"},
    {main_menu_music_pending, 0x00718fc6u, "main_menu_music_pending"},
};
const layout_entry k_cluster_26[] = {
    {level_select_current_path_00719068, 0x00719068u, "level_select_current_path_00719068"},
    {level_select_frame_00719168, 0x00719168u, "level_select_frame_00719168"},
    {level_select_flags_0071916a, 0x0071916au, "level_select_flags_0071916a"},
    {level_select_flags_0071916b, 0x0071916bu, "level_select_flags_0071916b"},
    {level_select_flags_0071916c, 0x0071916cu, "level_select_flags_0071916c"},
};
const layout_entry k_cluster_27[] = {
    {virtual_keyboard, 0x007193a8u, "virtual_keyboard"},
    {DAT_007193be, 0x007193beu, "DAT_007193be"},
    {network_host_edit_field_00719410, 0x00719410u, "network_host_edit_field_00719410"},
};
const layout_entry k_cluster_28[] = {
    {server_list, 0x007196bcu, "server_list"},
    {server_list_block_used, 0x007196c0u, "server_list_block_used"},
    {server_list_block_capacity, 0x007196c4u, "server_list_block_capacity"},
    {server_browser_query_elapsed_ms, 0x007196c8u, "server_browser_query_elapsed_ms"},
};
const layout_entry k_cluster_29[] = {
    {unknown_00746280_block, 0x00746280u, "unknown_00746280_block"},
    {ambient_noise, 0x00746284u, "ambient_noise"},
    {weather_particle_system_count, 0x00746b84u, "weather_particle_system_count"},
    {weather_wind_states, 0x00746b88u, "weather_wind_states"},
    {weather_frame_counter, 0x00746f88u, "weather_frame_counter"},
};
const layout_entry k_cluster_30[] = {
    {lens_flare_current_key, 0x00746fb0u, "lens_flare_current_key"},
    {lens_flare_batch_mode, 0x00746fbcu, "lens_flare_batch_mode"},
};
const layout_entry k_cluster_31[] = {
    {lens_flare_applied_key, 0x007bf040u, "lens_flare_applied_key"},
    {render_unknown_7bf04c, 0x007bf04cu, "render_unknown_7bf04c"},
};
const layout_entry k_cluster_32[] = {
    {rasterizer_caps, 0x007c10c0u, "rasterizer_caps"},
    {rasterizer_capability_007c10e4, 0x007c10e4u, "rasterizer_capability_007c10e4"},
    {rasterizer_device_version, 0x007c118cu, "rasterizer_device_version"},
    {rasterizer_desktop_display_mode, 0x007c11f0u, "rasterizer_desktop_display_mode"},
    {os_platform_refresh_default, 0x007c11f8u, "os_platform_refresh_default"},
    {rasterizer_time, 0x007c1200u, "rasterizer_time"},
    {chimera_contrail_scale, 0x007c1208u, "chimera_contrail_scale"},
    {rasterizer_window, 0x007c1220u, "rasterizer_window"},
    {rasterizer_camera_position, 0x007c1228u, "rasterizer_camera_position"},
    {rasterizer_camera_forward, 0x007c1234u, "rasterizer_camera_forward"},
    {network_stats_overlay_text_rect_min, 0x007c1254u, "network_stats_overlay_text_rect_min"},
    {network_stats_overlay_text_rect_max, 0x007c1258u, "network_stats_overlay_text_rect_max"},
    {rasterizer_fog_flags, 0x007c1408u, "rasterizer_fog_flags"},
    {rasterizer_fog_atmospheric_color, 0x007c140cu, "rasterizer_fog_atmospheric_color"},
    {rasterizer_fog_atmospheric_max_density, 0x007c1418u, "rasterizer_fog_atmospheric_max_density"},
    {rasterizer_fog_atmospheric_min_distance, 0x007c141cu, "rasterizer_fog_atmospheric_min_distance"},
    {rasterizer_fog_atmospheric_max_distance, 0x007c1420u, "rasterizer_fog_atmospheric_max_distance"},
    {rasterizer_fog_plane, 0x007c1428u, "rasterizer_fog_plane"},
    {rasterizer_fog_planar_color, 0x007c1438u, "rasterizer_fog_planar_color"},
};
const layout_entry k_cluster_33[] = {
    {camera_position, 0x007c3114u, "camera_position"},
    {camera_position_y, 0x007c3118u, "camera_position_y"},
    {camera_position_z, 0x007c311cu, "camera_position_z"},
    {camera_forward_x, 0x007c3120u, "camera_forward_x"},
    {camera_forward_y, 0x007c3124u, "camera_forward_y"},
    {camera_forward_z, 0x007c3128u, "camera_forward_z"},
    {camera_up, 0x007c312cu, "camera_up"},
    {camera_field_of_view, 0x007c313cu, "camera_field_of_view"},
    {render_viewport_top, 0x007c3140u, "render_viewport_top"},
    {render_viewport_left, 0x007c3142u, "render_viewport_left"},
    {render_viewport_bottom, 0x007c3144u, "render_viewport_bottom"},
    {render_viewport_right, 0x007c3146u, "render_viewport_right"},
    {screen_safe_area_right, 0x007c3148u, "screen_safe_area_right"},
    {screen_safe_area_bottom, 0x007c314cu, "screen_safe_area_bottom"},
    {portal_visibility_tolerance, 0x007c3154u, "portal_visibility_tolerance"},
    {render_frustum_global, 0x007c3168u, "render_frustum_global"},
    {render_camera_world_to_view, 0x007c3178u, "render_camera_world_to_view"},
    {render_camera_facing_basis, 0x007c31e0u, "render_camera_facing_basis"},
    {waypoint_fade_near, 0x007c3240u, "waypoint_fade_near"},
    {waypoint_fade_far, 0x007c3244u, "waypoint_fade_far"},
};
const layout_entry k_cluster_34[] = {
    {object_data, 0x008603b0u, "object_data"},
    {noncollideable_cluster_first, 0x008603c0u, "noncollideable_cluster_first"},
    {noncollideable_object_references, 0x008603c4u, "noncollideable_object_references"},
    {noncollideable_cluster_partition, 0x008603c8u, "noncollideable_cluster_partition"},
};
const layout_entry k_cluster_35[] = {
    {collideable_cluster_first, 0x008603d0u, "collideable_cluster_first"},
    {collideable_object_references, 0x008603d4u, "collideable_object_references"},
    {collideable_cluster_partition, 0x008603d8u, "collideable_cluster_partition"},
};
const layout_entry k_cluster_36[] = {
    {g_control_binding_region_e0, 0x008603e0u, "g_control_binding_region_e0"},
    {g_control_binding_region_e4, 0x008603e4u, "g_control_binding_region_e4"},
    {g_control_binding_region_ec, 0x008603ecu, "g_control_binding_region_ec"},
    {g_control_binding_id, 0x008603f0u, "g_control_binding_id"},
    {g_control_binding_value, 0x008603f6u, "g_control_binding_value"},
};
const layout_entry k_cluster_37[] = {
    {light_cluster_first, 0x00860b20u, "light_cluster_first"},
    {light_cluster_references, 0x00860b24u, "light_cluster_references"},
    {light_object_references, 0x00860b28u, "light_object_references"},
};
const layout_entry k_cluster_38[] = {
    {network_server_storage, 0x00861340u, "network_server_storage"},
    {unknown_00861d4e, 0x00861d4eu, "unknown_00861d4e"},
    {unknown_00861d4f, 0x00861d4fu, "unknown_00861d4f"},
};
const layout_entry k_cluster_39[] = {
    {local_player_globals, 0x0087a478u, "local_player_globals"},
    {team_data, 0x0087a47cu, "team_data"},
};
const layout_entry k_cluster_40[] = {
    {king_alt_team_scores_network, 0x0087a680u, "king_alt_team_scores_network"},
    {king_alt_team_scores_network2, 0x0087a684u, "king_alt_team_scores_network2"},
    {king_alt_player_scores_network, 0x0087a6c4u, "king_alt_player_scores_network"},
    {king_alt_scores_network_tail, 0x0087a744u, "king_alt_scores_network_tail"},
    {king_team_hill_seconds_network, 0x0087a7e0u, "king_team_hill_seconds_network"},
    {king_hill_broadcast_overrun_value, 0x0087a984u, "king_hill_broadcast_overrun_value"},
};
const layout_entry k_cluster_41[] = {
    {game_engine_nameplate_fade_opacity_array, 0x0087aa14u, "game_engine_nameplate_fade_opacity_array"},
    {game_engine_dedicated_idle, 0x0087aa18u, "game_engine_dedicated_idle"},
    {game_engine_dedicated_idle_timer, 0x0087aa1cu, "game_engine_dedicated_idle_timer"},
    {game_engine_round_reset_tick, 0x0087aa20u, "game_engine_round_reset_tick"},
};
const layout_entry k_cluster_42[] = {
    {variant_defaults_source, 0x0087aa40u, "variant_defaults_source"},
    {unknown_0087aa7f, 0x0087aa7fu, "unknown_0087aa7f"},
    {game_engine_pending_variant, 0x0087aa80u, "game_engine_pending_variant"},
    {cached_network_engine_index, 0x0087aab0u, "cached_network_engine_index"},
    {unknown_0087aaec, 0x0087aaecu, "unknown_0087aaec"},
    {unknown_0087aaf8, 0x0087aaf8u, "unknown_0087aaf8"},
};
const layout_entry k_cluster_43[] = {
    {length_error_throw_info, 0x00673524u, "length_error_throw_info"},
    {out_of_range_throw_info, 0x00673560u, "out_of_range_throw_info"},
};
const layout_entry k_cluster_44[] = {
    {hud_text_message_hold_color, 0x006851f4u, "hud_text_message_hold_color"},
    {global_white_argb, 0x006851fcu, "global_white_argb"},
    {hud_text_message_normal_color, 0x00685200u, "hud_text_message_normal_color"},
    {actor_mode_uncover_look_weights_active, 0x00685204u, "actor_mode_uncover_look_weights_active"},
    {actor_mode_guard_look_weights_idle, 0x00685208u, "actor_mode_guard_look_weights_idle"},
    {console_color_00685214, 0x00685214u, "console_color_00685214"},
    {console_message_default_color, 0x00685218u, "console_message_default_color"},
    {actor_mode_guard_look_weights_ambush, 0x0068521cu, "actor_mode_guard_look_weights_ambush"},
    {actor_type_procs, 0x006853b8u, "actor_type_procs"},
};
const layout_entry k_cluster_45[] = {
    {camera_script, 0x006869d0u, "camera_script"},
    {director_camera_target_changed, 0x006869d1u, "director_camera_target_changed"},
    {director_camera_mode, 0x006869d2u, "director_camera_mode"},
    {camera_script_time_remaining, 0x006869d8u, "camera_script_time_remaining"},
    {director_camera_target, 0x00686a04u, "director_camera_target"},
};
const layout_entry k_cluster_46[] = {
    {actor_mode_default_look_weights, 0x00686af8u, "actor_mode_default_look_weights"},
    {actor_mode_guard_look_weights_a5, 0x00686afcu, "actor_mode_guard_look_weights_a5"},
    {actor_mode_guard_look_weights_a6, 0x00686b00u, "actor_mode_guard_look_weights_a6"},
    {global_white_color, 0x00686b04u, "global_white_color"},
    {object_ambient_lightmap_default, 0x00686b08u, "object_ambient_lightmap_default"},
    {default_axis_b, 0x00686b0cu, "default_axis_b"},
    {default_color_a, 0x00686b10u, "default_color_a"},
    {global_real_rgb_green_pointer, 0x00686b14u, "global_real_rgb_green_pointer"},
    {default_color_b, 0x00686b18u, "default_color_b"},
};
const layout_entry k_cluster_47[] = {
    {multiplayer_maps, 0x0068e588u, "multiplayer_maps"},
    {map_per_map_table, 0x0068e590u, "map_per_map_table"},
};
const layout_entry k_cluster_48[] = {
    {controls_action_table, 0x00692fe8u, "controls_action_table"},
    {controls_row_device_mask_table, 0x00692ffcu, "controls_row_device_mask_table"},
};
const layout_entry k_cluster_49[] = {
    {unknown_00699f40, 0x00699f40u, "unknown_00699f40"},
    {network_scenario_round_counter_a, 0x00699f44u, "network_scenario_round_counter_a"},
};
const layout_entry k_cluster_50[] = {
    {message_delta_field_type_table, 0x0069a2f0u, "message_delta_field_type_table"},
    {message_delta_unknown_table_0069a304, 0x0069a304u, "message_delta_unknown_table_0069a304"},
};
const layout_entry k_cluster_51[] = {
    {object_type_definitions, 0x0069bfdcu, "object_type_definitions"},
    {object_type_definitions_ex, 0x0069bfe0u, "object_type_definitions_ex"},
};
const layout_entry k_cluster_52[] = {
    {game_window_top_left, 0x0069c634u, "game_window_top_left"},
    {game_window_bottom_right, 0x0069c638u, "game_window_bottom_right"},
    {game_screen_rect, 0x0069c63cu, "game_screen_rect"},
    {game_screen_rect_left, 0x0069c63eu, "game_screen_rect_left"},
    {game_screen_rect_bottom, 0x0069c640u, "game_screen_rect_bottom"},
    {game_screen_rect_right, 0x0069c642u, "game_screen_rect_right"},
};
const layout_entry k_cluster_53[] = {
    {rasterizer_effects, 0x0069d410u, "rasterizer_effects"},
    {lens_flare_effect, 0x0069da10u, "lens_flare_effect"},
    {rasterizer_screen_flash_effect, 0x0069e270u, "rasterizer_screen_flash_effect"},
    {environment_effect_slot, 0x0069e290u, "environment_effect_slot"},
    {rasterizer_vertex_shaders, 0x0069e350u, "rasterizer_vertex_shaders"},
    {rasterizer_depth_prepass_vertex_shader, 0x0069e460u, "rasterizer_depth_prepass_vertex_shader"},
    {renderer_unknown_69e468, 0x0069e468u, "renderer_unknown_69e468"},
};
const layout_entry k_cluster_54[] = {
    {unit_base_animation_state_names, 0x0069fde4u, "unit_base_animation_state_names"},
    {s_stand, 0x0069fdecu, "s_stand"},
};

struct cluster {
    const layout_entry *entries;
    uint32_t count;
};

const cluster k_clusters[] = {
    {k_cluster_0, 2},
    {k_cluster_1, 6},
    {k_cluster_2, 6},
    {k_cluster_3, 9},
    {k_cluster_4, 14},
    {k_cluster_5, 16},
    {k_cluster_6, 2},
    {k_cluster_7, 2},
    {k_cluster_8, 2},
    {k_cluster_9, 10},
    {k_cluster_10, 3},
    {k_cluster_11, 2},
    {k_cluster_12, 2},
    {k_cluster_13, 2},
    {k_cluster_14, 2},
    {k_cluster_15, 5},
    {k_cluster_16, 2},
    {k_cluster_17, 11},
    {k_cluster_18, 12},
    {k_cluster_19, 2},
    {k_cluster_20, 2},
    {k_cluster_21, 16},
    {k_cluster_22, 20},
    {k_cluster_23, 2},
    {k_cluster_24, 24},
    {k_cluster_25, 20},
    {k_cluster_26, 5},
    {k_cluster_27, 3},
    {k_cluster_28, 4},
    {k_cluster_29, 5},
    {k_cluster_30, 2},
    {k_cluster_31, 2},
    {k_cluster_32, 19},
    {k_cluster_33, 20},
    {k_cluster_34, 4},
    {k_cluster_35, 3},
    {k_cluster_36, 5},
    {k_cluster_37, 3},
    {k_cluster_38, 3},
    {k_cluster_39, 2},
    {k_cluster_40, 6},
    {k_cluster_41, 4},
    {k_cluster_42, 6},
    {k_cluster_43, 2},
    {k_cluster_44, 9},
    {k_cluster_45, 5},
    {k_cluster_46, 9},
    {k_cluster_47, 2},
    {k_cluster_48, 2},
    {k_cluster_49, 2},
    {k_cluster_50, 2},
    {k_cluster_51, 2},
    {k_cluster_52, 6},
    {k_cluster_53, 7},
    {k_cluster_54, 2},
};

}  // namespace

/** Logs each misplaced global; returns how many there are (0 when the layout is the original one). */
extern "C" int standalone_data_layout_check(void)
{
    int misplaced = 0;

    for (const cluster &c : k_clusters) {
        // the pad in front of a cluster keeps its start congruent with the original address modulo 16
        if ((reinterpret_cast<uintptr_t>(c.entries[0].object) & 15) != (c.entries[0].original_address & 15)) {
            standalone_log("data layout: %s is not 16-byte congruent with 0x%08x", c.entries[0].name, c.entries[0].original_address);
            misplaced++;
        }
        for (uint32_t i = 1; i < c.count; i++) {
            intptr_t actual = c.entries[i].object - c.entries[0].object;
            intptr_t expected = static_cast<intptr_t>(c.entries[i].original_address - c.entries[0].original_address);

            if (actual != expected) {
                standalone_log("data layout: %s at +0x%lx from %s, the original has +0x%lx", c.entries[i].name,
                    static_cast<long>(actual), c.entries[0].name, static_cast<long>(expected));
                misplaced++;
            }
        }
    }
    return misplaced;
}
