/* standalone/data/tables.h -- the tables and zero-filled objects of standalone/data/tables.c (generated by
   tools/materialize_image.py). */
#ifndef HALO_DATA_TABLES_H
#define HALO_DATA_TABLES_H

#include <stdint.h>

extern uint32_t table_0063acac[2104];
extern uint32_t table_0064efb0[59];
extern uint32_t table_0065512c[1];
extern uint32_t global_white_argb_00655138[387];
extern uint32_t hs_function_definitions_00657660[4086];
extern uint32_t table_00664914[1];
extern uint32_t table_00664954[1];
extern uint32_t table_006649d4[1];
extern uint32_t table_00664a74[1];
extern uint32_t table_00664aac[1];
extern uint32_t table_00664af0[1];
extern uint32_t table_00664b30[1];
extern uint32_t length_error_throw_info_0067359c[496];
extern uint32_t table_00676030[216];
extern uint32_t table_006851f8[1];
extern uint32_t table_0068520c[2];
extern uint32_t table_00685220[102];
extern uint32_t hs_enum_definitions_006853f8[1391];
extern uint32_t recorded_animation_codecs_by_version_00686fd8[4];
extern uint32_t multiplayer_sound_enabled_00687020[9];
extern uint32_t object_network_id_table_006870a8[13];
extern uint32_t table_00687148[1];
extern uint32_t table_006871b0[41];
extern uint32_t message_delta_definitions_006872b8[55];
extern uint32_t table_006873f8[1];
extern uint32_t table_00687468[1];
extern uint32_t machine_table_006874d0[13];
extern uint32_t table_006879b8[1];
extern uint32_t message_delta_definitions_00687a20[52];
extern uint32_t message_delta_definitions_00687b1c[178];
extern uint32_t message_delta_definitions_00687e48[81];
extern uint32_t message_delta_definitions_00687ff0[198];
extern uint32_t table_006883b0[1];
extern uint32_t message_delta_definitions_00688490[31];
extern uint32_t message_delta_definitions_00688570[39];
extern uint32_t message_delta_definitions_00688670[314];
extern uint32_t table_00692e08[1];
extern uint32_t message_delta_definitions_00692e70[29];
extern uint32_t message_delta_definitions_00692f58[36];
extern uint32_t table_00695478[1];
extern uint32_t table_006954e8[1];
extern uint32_t table_00695870[1];
extern uint32_t table_00695bf8[1];
extern uint32_t message_delta_definitions_00695c60[113];
extern uint32_t table_00695ec0[1];
extern uint32_t message_delta_definitions_00695f28[139];
extern uint32_t message_delta_definitions_006961c0[248];
extern uint32_t message_delta_definitions_00697e90[27];
extern uint32_t table_00697f68[1];
extern uint32_t table_00697ff8[1];
extern uint32_t table_00698060[1];
extern uint32_t table_006980d0[1];
extern uint32_t table_00698138[1];
extern uint32_t table_006981a0[1];
extern uint32_t message_delta_definitions_006982ec[64];
extern uint32_t table_00698478[1];
extern uint32_t table_00698638[1];
extern uint32_t table_006986b0[1];
extern uint32_t message_delta_definitions_00698718[888];
extern uint32_t table_00699610[1];
extern uint32_t table_00699680[1];
extern uint32_t message_delta_definitions_006996e8[25];
extern uint32_t message_delta_definitions_006997b0[21];
extern uint32_t table_00699870[1];
extern uint32_t table_006998e0[1];
extern uint32_t message_delta_definitions_00699948[382];
extern uint32_t table_0069a590[1];
extern uint32_t table_0069a600[1];
extern uint32_t table_0069a6f0[1];
extern uint32_t table_0069a838[1];
extern uint32_t table_0069a8a0[27];
extern uint32_t message_delta_definitions_0069a998[309];
extern uint32_t message_delta_definitions_0069aed0[157];
extern uint32_t message_delta_definitions_0069b1a8[909];
extern uint32_t length_error_throw_info_0069ff2c[87];
extern uint8_t bss_006e09e8[3596];

extern void *const network_index_cache_table;
extern void *const flag_render_device_slot;

#endif
