/**
 * @file include/halo/rasterizer/api.hpp
 * Functions of the rasterizer module that other modules and the data tables call (namespace halo::rasterizer). The record types are
 * forward-declared, so the header is light enough for every caller and for the data tables.
 */
#pragma once

#include <stdint.h>

struct d3d_caps9;
struct rasterizer_frame_statistics;

struct BitmapData;
struct ColorARGB;
struct ColorRGB;
struct DetailObjectCollection;
struct Font;
struct FontCharacter;
struct Rectangle2D;
struct ScenarioStructureBSPMaterialCompressedLightmapVertex;
struct ScenarioStructureBSPMaterialCompressedRenderedVertex;
struct Shader;
struct ShaderEnvironment;
struct ShaderModel;
struct ShaderTransparentChicago;
struct ShaderTransparentChicagoExtended;
struct d3d_present_parameters;
struct effect;
struct flag;
struct hud_quad_vertex;
struct lens_flare_batch_key;
struct lens_flare_instance;
struct light;
struct object;
struct rasterizer_detail_object_batches;
struct rasterizer_detail_object_draw;
struct rasterizer_display_mode;
struct rasterizer_effect_slot;
struct rasterizer_frame_time;
struct rasterizer_index_buffer;
struct rasterizer_light;
struct rasterizer_model_draw_context;
struct rasterizer_node_matrices;
struct rasterizer_point_light_constants;
struct rasterizer_vertex_buffer;
struct rasterizer_window_parameters;
struct real_matrix4x3;
struct real_point3d;
struct real_vector3d;
struct render_fog;
struct render_lighting;
struct transparent_geometry_group;
struct transparent_geometry_group_link;
struct ui_quad_render_state;
struct weapon_screen_effect_parameters;
typedef uint32_t datum_index;
typedef uint8_t rasterizer_gamma_settings;

namespace halo::rasterizer {

/**
 * The engine globals the rasterizer module owns (their storage is defined by standalone/data under the original link names);
 * other modules reach them through globals().
 */
struct Globals {
    void *&device;
    int32_t &device_version;
    uint8_t &fullscreen;
    int32_t &gamma_exponent;
    int32_t &window_requested;
    float &default_z_near;
    float &default_z_far;
    int32_t &present_counter_high;
    int32_t &present_counter_low;
    uint8_t &needs_reset;
    int16_t &vertex_buffer_lock_state;
    char *&shader_file_name;
    void *&dynamic_index_buffer;
    uint32_t &decal_vertex_cache_handle;
    uint8_t &render_states_dirty;
    rasterizer_window_parameters &window;
    rasterizer_frame_statistics &frame_statistics;
    d3d_caps9 &caps;
    d3d_present_parameters &present_parameters;
    uint8_t &software_vertex_processing;
    void *&window_handle;
};

Globals &globals();

int16_t bitmap_compute_mipmap_count(BitmapData *bitmap);
int32_t bitmap_compute_texture_data_size(BitmapData *bitmap);
int16_t * chimera__rasterizer_set_texture(uint32_t bitmap_tag_id, int16_t stage, int16_t bitmap_type, int16_t default_index, int16_t frame);
uint8_t chimera__rasterizer_set_texture_direct_d3d9(uint32_t bitmap_tag_id, int16_t stage, int16_t frame);
uint8_t chimera__rasterizer_set_texture_direct_d3dx(uint32_t bitmap_tag_id, int16_t stage, int16_t frame, rasterizer_effect_slot *effect_slot);
uint8_t color_channel_real_to_byte(float channel);
uint8_t rasterizer_bind_texture_d3d9(int16_t stage, BitmapData *bitmap);
namespace rasterizer_bind_texture_d3dx_impl { uint8_t rasterizer_bind_texture_d3dx(int16_t stage, BitmapData *bitmap, rasterizer_effect_slot *effect_slot); }
using rasterizer_bind_texture_d3dx_impl::rasterizer_bind_texture_d3dx;
int32_t rasterizer_bitmap_compute_mipmap_skip_count(BitmapData *bitmap, int16_t *out_width, int16_t *out_height);
namespace rasterizer_bitmap_create_hardware_texture_impl { uint8_t rasterizer_bitmap_create_hardware_texture(BitmapData *bitmap); }
using rasterizer_bitmap_create_hardware_texture_impl::rasterizer_bitmap_create_hardware_texture;
int32_t rasterizer_bitmap_sample_texel(BitmapData *bitmap, float *uv, float mip_bias);
namespace rasterizer_bitmap_upload_2d_mipmaps_impl { void rasterizer_bitmap_upload_2d_mipmaps(BitmapData *bitmap); }
using rasterizer_bitmap_upload_2d_mipmaps_impl::rasterizer_bitmap_upload_2d_mipmaps;
namespace rasterizer_bitmap_upload_cubemap_mipmaps_impl { void rasterizer_bitmap_upload_cubemap_mipmaps(BitmapData *bitmap); }
using rasterizer_bitmap_upload_cubemap_mipmaps_impl::rasterizer_bitmap_upload_cubemap_mipmaps;
namespace rasterizer_bitmap_upload_cubemap_mipmaps_by_face_impl { void rasterizer_bitmap_upload_cubemap_mipmaps_by_face(BitmapData *bitmap); }
using rasterizer_bitmap_upload_cubemap_mipmaps_by_face_impl::rasterizer_bitmap_upload_cubemap_mipmaps_by_face;
namespace rasterizer_force_bilinear_filtering_impl { void rasterizer_force_bilinear_filtering(void); }
using rasterizer_force_bilinear_filtering_impl::rasterizer_force_bilinear_filtering;
namespace rasterizer_render_target_bind_effect_texture_impl { void rasterizer_render_target_bind_effect_texture(int16_t target_index, rasterizer_effect_slot *effect_slot, int16_t handle_index); }
using rasterizer_render_target_bind_effect_texture_impl::rasterizer_render_target_bind_effect_texture;
void * rasterizer_render_target_bind_texture_stage(int16_t target_index, int16_t stage);
int16_t * rasterizer_resolve_and_cache_submap_b(uint32_t bitmap_tag_id, int16_t bitmap_type, int16_t stage, int16_t default_index, int16_t frame, rasterizer_effect_slot *effect_slot);
uint8_t rasterizer_resolve_and_cache_submap_c(uint32_t bitmap_tag_id, int16_t bitmap_type, int16_t stage, int16_t default_index, int16_t frame);
namespace rasterizer_unbind_stream_and_textures_impl { void rasterizer_unbind_stream_and_textures(void); }
using rasterizer_unbind_stream_and_textures_impl::rasterizer_unbind_stream_and_textures;
uint8_t rasterizer_validate_and_rebind_texture(uint32_t bitmap_tag_id, int16_t stage, int16_t frame);
void bsp_compressed_lightmap_vertex_unpack_normal(ScenarioStructureBSPMaterialCompressedLightmapVertex *vertex, real_vector3d *out);
void bsp_compressed_rendered_vertex_unpack_normal(ScenarioStructureBSPMaterialCompressedRenderedVertex *vertex, real_vector3d *out);
uint32_t vector3d_pack_normal_11_11_10(real_vector3d *direction);
real_vector3d * vector3d_unpack_normal_11_11_10(real_vector3d *out, uint32_t packed);
void chimera__cinematic_screen_effect(rasterizer_frame_time *time_source);
void chimera__gamma(void);
void chimera__registry_check_3(void);
void chimera__registry_check_4(void);
namespace rasterizer_fog_screen_overlay_set_states_impl { void rasterizer_fog_screen_overlay_set_states(void); }
using rasterizer_fog_screen_overlay_set_states_impl::rasterizer_fog_screen_overlay_set_states;
void rasterizer_gamma_brightness_to_exponent(rasterizer_gamma_settings *settings);
namespace rasterizer_motion_sensor_begin_impl { void rasterizer_motion_sensor_begin(void); }
using rasterizer_motion_sensor_begin_impl::rasterizer_motion_sensor_begin;
namespace rasterizer_motion_sensor_blip_draw_impl { void rasterizer_motion_sensor_blip_draw(const float *position, const float *color, float brightness, float size); }
using rasterizer_motion_sensor_blip_draw_impl::rasterizer_motion_sensor_blip_draw;
namespace rasterizer_motion_sensor_end_impl { void rasterizer_motion_sensor_end(const float *position, float sweep); }
using rasterizer_motion_sensor_end_impl::rasterizer_motion_sensor_end;
namespace rasterizer_screen_effect_compute_uv_transform_impl { void rasterizer_screen_effect_compute_uv_transform(uint32_t width, uint32_t height, weapon_screen_effect_parameters *params, int16_t pass, int16_t pass_count, uint8_t shift_down); }
using rasterizer_screen_effect_compute_uv_transform_impl::rasterizer_screen_effect_compute_uv_transform;
uint8_t rasterizer_screen_effect_init_shaders(void);
namespace rasterizer_screen_effect_render_impl { void rasterizer_screen_effect_render(weapon_screen_effect_parameters *input); }
using rasterizer_screen_effect_render_impl::rasterizer_screen_effect_render;
namespace rasterizer_screen_effect_render_fixed_function_impl { void rasterizer_screen_effect_render_fixed_function(weapon_screen_effect_parameters *input); }
using rasterizer_screen_effect_render_fixed_function_impl::rasterizer_screen_effect_render_fixed_function;
int rasterizer_screen_flash_init_shaders(void);
namespace rasterizer_screen_flash_render_impl { void rasterizer_screen_flash_render(void); }
using rasterizer_screen_flash_render_impl::rasterizer_screen_flash_render;
namespace rasterizer_sun_glow_blur_impl { int16_t rasterizer_sun_glow_blur(int16_t first, int16_t second, int16_t passes); }
using rasterizer_sun_glow_blur_impl::rasterizer_sun_glow_blur;
namespace rasterizer_sun_glow_capture_impl { void rasterizer_sun_glow_capture(const float *rect, int16_t target_index); }
using rasterizer_sun_glow_capture_impl::rasterizer_sun_glow_capture;
uint8_t rasterizer_sun_glow_project_point(real_point3d *point, float radius, float *out_screen, float *out_scale);
namespace rasterizer_sun_glow_render_impl { void rasterizer_sun_glow_render(lens_flare_instance *instance); }
using rasterizer_sun_glow_render_impl::rasterizer_sun_glow_render;
namespace rasterizer_ui_quad_draw_impl { void rasterizer_ui_quad_draw(ui_quad_render_state *state, hud_quad_vertex *vertices); }
using rasterizer_ui_quad_draw_impl::rasterizer_ui_quad_draw;
void rasterizer_underwater_tint_jitter_update(BitmapData *lightmap);
namespace rasterizer_underwater_tint_set_states_impl { void rasterizer_underwater_tint_set_states(void); }
using rasterizer_underwater_tint_set_states_impl::rasterizer_underwater_tint_set_states;
void chimera__draw_16_bit_text(Rectangle2D *clip_rect_override, int32_t *dest_rect_override, uint32_t position_or_color1, uint32_t position_or_color2, const int16_t *text);
void chimera__draw_8_bit_text(Rectangle2D *clip_rect_override, int32_t *dest_rect_override, uint32_t position_or_color1, uint32_t position_or_color2, const char *text);
void chimera__widescreen_text_scaling(void);
void font_glyph_cache_allocate_and_upload(Font *font, FontCharacter *character);
void font_glyph_cache_clear_all(void);
void rasterizer_draw_text_begin(ui_quad_render_state *state);
namespace rasterizer_draw_text_end_impl { void rasterizer_draw_text_end(void); }
using rasterizer_draw_text_end_impl::rasterizer_draw_text_end;
void rasterizer_editbox_log_dump(void);
namespace text_draw_glyph_callback_impl { void text_draw_glyph_callback(void *state, void *font, uint8_t *character, uint32_t color, int16_t x, int16_t y, int16_t source_x, int16_t source_y, int16_t width, int16_t height); }
using text_draw_glyph_callback_impl::text_draw_glyph_callback;
int32_t text_font_system_initialize(void);
void chimera__rasterizer_dispose_free_memory(void);
void chimera__rasterizer_draw_dynamic_triangles_static_vertices(int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_index_slot, int32_t first_primitive);
namespace chimera__rasterizer_draw_dynamic_triangles_static_vertices2_impl { void chimera__rasterizer_draw_dynamic_triangles_static_vertices2(int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_index_slot, int32_t first_primitive, rasterizer_vertex_buffer *second_stream); }
using chimera__rasterizer_draw_dynamic_triangles_static_vertices2_impl::chimera__rasterizer_draw_dynamic_triangles_static_vertices2;
void * chimera__rasterizer_memory_alloc(void *source, uint32_t size);
namespace rasterizer_dynamic_geometry_chain_draw_impl { void rasterizer_dynamic_geometry_chain_draw(int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, rasterizer_index_buffer *index_buffer); }
using rasterizer_dynamic_geometry_chain_draw_impl::rasterizer_dynamic_geometry_chain_draw;
void rasterizer_dynamic_geometry_dispose(void);
void rasterizer_dynamic_geometry_draw_dispatch(rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, rasterizer_vertex_buffer *vertex_buffer, int32_t primitive_count, int32_t first_primitive, int32_t dynamic_vertex_slot);
namespace rasterizer_dynamic_index_cache_draw_impl { void rasterizer_dynamic_index_cache_draw(int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, int32_t dynamic_vertex_slot); }
using rasterizer_dynamic_index_cache_draw_impl::rasterizer_dynamic_index_cache_draw;
int32_t rasterizer_dynamic_index_cache_reserve(int32_t count);
namespace rasterizer_dynamic_light_technique_ps2_set_states_impl { void rasterizer_dynamic_light_technique_ps2_set_states(void); }
using rasterizer_dynamic_light_technique_ps2_set_states_impl::rasterizer_dynamic_light_technique_ps2_set_states;
namespace rasterizer_dynamic_vertex_cache_lock_impl { void * rasterizer_dynamic_vertex_cache_lock(int32_t slot_index); }
using rasterizer_dynamic_vertex_cache_lock_impl::rasterizer_dynamic_vertex_cache_lock;
int32_t rasterizer_dynamic_vertex_cache_reserve(int16_t vertex_type, int32_t count);
namespace rasterizer_dynamic_vertex_draw_impl { void rasterizer_dynamic_vertex_draw(int32_t first_primitive, int32_t primitive_count, int32_t dynamic_vertex_slot, int16_t primitive_kind); }
using rasterizer_dynamic_vertex_draw_impl::rasterizer_dynamic_vertex_draw;
namespace rasterizer_dynamic_vertex_draw_indexed_impl { void rasterizer_dynamic_vertex_draw_indexed(rasterizer_index_buffer *index_buffer, int32_t primitive_count, int32_t dynamic_vertex_slot); }
using rasterizer_dynamic_vertex_draw_indexed_impl::rasterizer_dynamic_vertex_draw_indexed;
namespace rasterizer_dynamic_vertex_process_and_get_handle_impl { uint32_t rasterizer_dynamic_vertex_process_and_get_handle(rasterizer_vertex_buffer *vertex_buffer); }
using rasterizer_dynamic_vertex_process_and_get_handle_impl::rasterizer_dynamic_vertex_process_and_get_handle;
namespace rasterizer_geometry_draw_fixed_function_impl { void rasterizer_geometry_draw_fixed_function(uint32_t flags, int32_t dynamic_vertex_slot, rasterizer_vertex_buffer *vertex_buffer, rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, int32_t primitive_count); }
using rasterizer_geometry_draw_fixed_function_impl::rasterizer_geometry_draw_fixed_function;
namespace rasterizer_geometry_part_draw_impl { void rasterizer_geometry_part_draw(transparent_geometry_group *group); }
using rasterizer_geometry_part_draw_impl::rasterizer_geometry_part_draw;
void chimera__rasterizer_set_framebuffer_blend_function(int16_t mode);
namespace chimera__rasterizer_set_frustum_z_func_impl { void chimera__rasterizer_set_frustum_z_func(uint32_t z_near, uint32_t z_far); }
using chimera__rasterizer_set_frustum_z_func_impl::chimera__rasterizer_set_frustum_z_func;
void display_mode_get_current(rasterizer_display_mode *out);
void rasterizer_begin_frame(rasterizer_window_parameters *source);
void rasterizer_build_present_parameters(d3d_present_parameters *dest, rasterizer_display_mode *source);
namespace rasterizer_capture_and_present_impl { void rasterizer_capture_and_present(const int16_t *tile, BitmapData *bitmap); }
using rasterizer_capture_and_present_impl::rasterizer_capture_and_present;
uint32_t rasterizer_create_game_window(int32_t height, int32_t width);
namespace rasterizer_device_reset_impl { uint8_t rasterizer_device_reset(d3d_present_parameters *present_parameters); }
using rasterizer_device_reset_impl::rasterizer_device_reset;
uint8_t rasterizer_display_mode_differs(rasterizer_display_mode *requested);
namespace rasterizer_end_frame_impl { void rasterizer_end_frame(void); }
using rasterizer_end_frame_impl::rasterizer_end_frame;
int32_t rasterizer_get_refresh_rate(int32_t requested_rate);
namespace rasterizer_initialize_direct3d_impl { uint8_t rasterizer_initialize_direct3d(void); }
using rasterizer_initialize_direct3d_impl::rasterizer_initialize_direct3d;
uint8_t rasterizer_parse_vidmode_commandline(int32_t *width_out, int32_t *height_out, long *refresh_out);
namespace rasterizer_reset_device_if_needed_impl { uint8_t rasterizer_reset_device_if_needed(void); }
using rasterizer_reset_device_if_needed_impl::rasterizer_reset_device_if_needed;
void rasterizer_resize_game_window(int32_t height, int32_t width);
int32_t rasterizer_round_up_resolution_height(int32_t height);
void rasterizer_select_hardware_codepaths(void);
namespace rasterizer_service_deferred_windowed_ops_impl { void rasterizer_service_deferred_windowed_ops(void); }
using rasterizer_service_deferred_windowed_ops_impl::rasterizer_service_deferred_windowed_ops;
namespace rasterizer_set_default_render_states_impl { void rasterizer_set_default_render_states(void); }
using rasterizer_set_default_render_states_impl::rasterizer_set_default_render_states;
void rasterizer_shutdown(void);
void chimera__rasterizer_set_model_skinning(uint8_t upload, rasterizer_node_matrices *nodes);
void chimera__rasterizer_set_up_node_parts(int32_t node_part_count, uint8_t *node_part_indices);
namespace rasterizer_model_draw_prepare_states_impl { void rasterizer_model_draw_prepare_states(rasterizer_model_draw_context *context, uint8_t mode); }
using rasterizer_model_draw_prepare_states_impl::rasterizer_model_draw_prepare_states;
namespace rasterizer_model_draw_restore_states_impl { void rasterizer_model_draw_restore_states(void); }
using rasterizer_model_draw_restore_states_impl::rasterizer_model_draw_restore_states;
namespace rasterizer_object_shadow_begin_impl { uint8_t rasterizer_object_shadow_begin(const real_matrix4x3 *projection, const ColorRGB *color, float radius, float *out_radius); }
using rasterizer_object_shadow_begin_impl::rasterizer_object_shadow_begin;
namespace rasterizer_object_shadow_blur_impl { void rasterizer_object_shadow_blur(void); }
using rasterizer_object_shadow_blur_impl::rasterizer_object_shadow_blur;
namespace rasterizer_object_shadow_model_draw_impl { void rasterizer_object_shadow_model_draw(const ShaderModel *shader, int16_t frame, rasterizer_index_buffer *index_buffer, rasterizer_vertex_buffer *vertex_buffer); }
using rasterizer_object_shadow_model_draw_impl::rasterizer_object_shadow_model_draw;
namespace rasterizer_object_shadow_structure_draw_impl { void rasterizer_object_shadow_structure_draw(rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count); }
using rasterizer_object_shadow_structure_draw_impl::rasterizer_object_shadow_structure_draw;
namespace rasterizer_shader_model_draw_fixed_function_impl { void rasterizer_shader_model_draw_fixed_function(uint8_t *shader, int16_t frame, rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_vertex_slot); }
using rasterizer_shader_model_draw_fixed_function_impl::rasterizer_shader_model_draw_fixed_function;
namespace rasterizer_shader_model_draw_limited_impl { void rasterizer_shader_model_draw_limited(uint8_t *shader, int16_t frame, rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_vertex_slot); }
using rasterizer_shader_model_draw_limited_impl::rasterizer_shader_model_draw_limited;
namespace rasterizer_shader_model_draw_pixel_shader_impl { void rasterizer_shader_model_draw_pixel_shader(uint8_t *shader, int16_t frame, rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_vertex_slot); }
using rasterizer_shader_model_draw_pixel_shader_impl::rasterizer_shader_model_draw_pixel_shader;
namespace rasterizer_shader_model_select_technique_impl { rasterizer_effect_slot * rasterizer_shader_model_select_technique(const ShaderModel *shader); }
using rasterizer_shader_model_select_technique_impl::rasterizer_shader_model_select_technique;
void chimera__transparent_decal_zbias(void);
void decal_and_font_system_reset(void);
void decal_geometry_cache_restore_procs(void);
uint8_t decal_vertex_cache_in_use(datum_index handle);
void decal_vertex_cache_release(datum_index handle);
void rasterizer_apply_decal_zbias(void);
void rasterizer_clear_decal_zbias(void);
namespace rasterizer_decal_index_buffer_initialize_impl { uint8_t rasterizer_decal_index_buffer_initialize(void); }
using rasterizer_decal_index_buffer_initialize_impl::rasterizer_decal_index_buffer_initialize;
namespace rasterizer_decal_pass_begin_impl { void rasterizer_decal_pass_begin(int16_t stage); }
using rasterizer_decal_pass_begin_impl::rasterizer_decal_pass_begin;
namespace rasterizer_decal_vertex_cache_lock_impl { void * rasterizer_decal_vertex_cache_lock(uint32_t decal_index, int32_t byte_count); }
using rasterizer_decal_vertex_cache_lock_impl::rasterizer_decal_vertex_cache_lock;
int rasterizer_decal_zbias_active(void);
namespace rasterizer_decals_draw_cluster_impl { void rasterizer_decals_draw_cluster(int16_t cluster_index); }
using rasterizer_decals_draw_cluster_impl::rasterizer_decals_draw_cluster;
namespace rasterizer_decals_initialize_impl { void rasterizer_decals_initialize(void); }
using rasterizer_decals_initialize_impl::rasterizer_decals_initialize;
void rasterizer_end_decal_pass(void);
namespace rasterizer_shader_decal_pass_set_states_impl { void rasterizer_shader_decal_pass_set_states(void); }
using rasterizer_shader_decal_pass_set_states_impl::rasterizer_shader_decal_pass_set_states;
void lens_flare_add_instance(lens_flare_instance *candidate);
float lens_flare_compute_rotation(lens_flare_instance *flare, int16_t mode);
uint8_t * lens_flare_get_visibility_byte(lens_flare_instance *flare);
void lens_flare_render_all(void);
void lens_flare_update_samples(void);
void lens_flare_update_visibility(void);
uint8_t rasterizer_lens_flare_batch_apply_material(lens_flare_batch_key *key);
void rasterizer_lens_flare_batch_draw_slot(int32_t batch_index);
int32_t rasterizer_lens_flare_batch_find_slot(void);
void rasterizer_lens_flare_batch_flush_all(void);
namespace rasterizer_lens_flare_batching_select_mode_impl { void rasterizer_lens_flare_batching_select_mode(int16_t mode, uint32_t flags); }
using rasterizer_lens_flare_batching_select_mode_impl::rasterizer_lens_flare_batching_select_mode;
namespace rasterizer_lens_flare_occlusion_queries_create_impl { uint8_t rasterizer_lens_flare_occlusion_queries_create(void); }
using rasterizer_lens_flare_occlusion_queries_create_impl::rasterizer_lens_flare_occlusion_queries_create;
namespace rasterizer_lens_flare_occlusion_query_get_result_impl { int32_t rasterizer_lens_flare_occlusion_query_get_result(int32_t slot_index); }
using rasterizer_lens_flare_occlusion_query_get_result_impl::rasterizer_lens_flare_occlusion_query_get_result;
void rasterizer_lens_flare_occlusion_sample_add(void *procedure, const real_point3d *position, uint32_t id_1, uint32_t id_2);
namespace rasterizer_lens_flare_occlusion_test_issue_impl { int32_t rasterizer_lens_flare_occlusion_test_issue(int32_t slot_index, const real_point3d *position, float radius); }
using rasterizer_lens_flare_occlusion_test_issue_impl::rasterizer_lens_flare_occlusion_test_issue;
uint8_t rasterizer_lens_flare_project_to_screen(const real_point3d *position, float radius, float *out_screen, float *out_inverse_w, float *out_billboard_size);
void rasterizer_lens_flare_quad_add(const float *scale, uint32_t diffuse, const real_point3d *position, float radius, float rotation_degrees);
void structure_cluster_add_lens_flares(int16_t cluster_index);
uint8_t rasterizer_detail_object_vertex_buffer_create(void);
namespace rasterizer_detail_objects_begin_impl { void rasterizer_detail_objects_begin(void); }
using rasterizer_detail_objects_begin_impl::rasterizer_detail_objects_begin;
namespace rasterizer_detail_objects_draw_impl { void rasterizer_detail_objects_draw(const rasterizer_detail_object_batches *list); }
using rasterizer_detail_objects_draw_impl::rasterizer_detail_objects_draw;
void rasterizer_detail_objects_expand_quad_vertices(int32_t quad_count, uint32_t *vertices, const uint8_t *instances, const DetailObjectCollection *collection, const rasterizer_detail_object_draw *draw);
namespace rasterizer_detail_objects_vertex_buffer_fill_impl { void rasterizer_detail_objects_vertex_buffer_fill(rasterizer_detail_object_batches *list); }
using rasterizer_detail_objects_vertex_buffer_fill_impl::rasterizer_detail_objects_vertex_buffer_fill;
void * rasterizer_dx9_create_vertex_buffer(int32_t vertex_type, uint32_t length, uint32_t fvf, uint8_t not_dynamic);
uint8_t rasterizer_dx9_effects_initialize(void);
int32_t rasterizer_dx9_pixel_shader_effect_load(int32_t effect_index, const void *data, uint32_t size);
uint8_t rasterizer_dx9_pixel_shaders_load_all(void);
void rasterizer_dx9_pixel_shaders_release(void);
namespace rasterizer_dx9_shaders_init_effect_impl { int32_t rasterizer_dx9_shaders_init_effect(int32_t effect_index); }
using rasterizer_dx9_shaders_init_effect_impl::rasterizer_dx9_shaders_init_effect;
void rasterizer_dx9_shaders_release_all(void);
void rasterizer_dx9_vertex_declarations_release(void);
uint8_t rasterizer_dx9_vertex_shaders_initialize(void);
namespace rasterizer_dx9_vertex_shaders_load_all_impl { uint32_t rasterizer_dx9_vertex_shaders_load_all(void); }
using rasterizer_dx9_vertex_shaders_load_all_impl::rasterizer_dx9_vertex_shaders_load_all;
uint8_t rasterizer_dx9_vertex_shaders_reload(void);
void * rasterizer_get_capture_surface(uint8_t *object, void *fallback);
namespace rasterizer_index_buffer_create_impl { uint8_t rasterizer_index_buffer_create(int32_t count, int16_t type, rasterizer_index_buffer *out, const void *source); }
using rasterizer_index_buffer_create_impl::rasterizer_index_buffer_create;
void rasterizer_ksml_ui_shutdown(void);
uint32_t rasterizer_load_file_and_verify(void **out_buffer, uint32_t *out_size, const char *path);
namespace rasterizer_misc_vertex_buffer_create_impl { uint8_t rasterizer_misc_vertex_buffer_create(void); }
using rasterizer_misc_vertex_buffer_create_impl::rasterizer_misc_vertex_buffer_create;
namespace rasterizer_render_target_capture_frame_impl { void rasterizer_render_target_capture_frame(void); }
using rasterizer_render_target_capture_frame_impl::rasterizer_render_target_capture_frame;
namespace rasterizer_render_target_dispose_impl { void rasterizer_render_target_dispose(void); }
using rasterizer_render_target_dispose_impl::rasterizer_render_target_dispose;
namespace rasterizer_render_target_initialize_impl { uint8_t rasterizer_render_target_initialize(void); }
using rasterizer_render_target_initialize_impl::rasterizer_render_target_initialize;
namespace rasterizer_render_target_set_active_impl { void rasterizer_render_target_set_active(int16_t target_index, uint32_t clear_color, uint8_t clear); }
using rasterizer_render_target_set_active_impl::rasterizer_render_target_set_active;
uint8_t rasterizer_resource_file_verify_signature(uint8_t *buffer, uint32_t size);
namespace rasterizer_vertex_buffer_create_impl { uint8_t rasterizer_vertex_buffer_create(rasterizer_vertex_buffer *record, int16_t vertex_type, int32_t count, uint32_t *source_data, int32_t second_stream, uint32_t size); }
using rasterizer_vertex_buffer_create_impl::rasterizer_vertex_buffer_create;
int32_t rasterizer_vertex_buffer_slot_allocate(int32_t vertex_type, uint32_t fvf, uint32_t length);
void rasterizer_vertex_buffer_slot_recreate_lost(void);
uint8_t rasterizer_dx9_shaders_initialize(void);
namespace rasterizer_dx9_vertex_declarations_create_impl { uint8_t rasterizer_dx9_vertex_declarations_create(void); }
using rasterizer_dx9_vertex_declarations_create_impl::rasterizer_dx9_vertex_declarations_create;
namespace rasterizer_render_loading_screen_impl { void rasterizer_render_loading_screen(int32_t mode); }
using rasterizer_render_loading_screen_impl::rasterizer_render_loading_screen;
void rasterizer_glass_diffuse_draw(transparent_geometry_group *group);
namespace rasterizer_glass_diffuse_draw_fixed_function_impl { void rasterizer_glass_diffuse_draw_fixed_function(transparent_geometry_group *group); }
using rasterizer_glass_diffuse_draw_fixed_function_impl::rasterizer_glass_diffuse_draw_fixed_function;
void rasterizer_glass_draw_procedures_select(void);
namespace rasterizer_glass_reflection_draw_impl { void rasterizer_glass_reflection_draw(transparent_geometry_group *group, int16_t reflection_kind); }
using rasterizer_glass_reflection_draw_impl::rasterizer_glass_reflection_draw;
namespace rasterizer_glass_reflection_draw_fixed_function_impl { void rasterizer_glass_reflection_draw_fixed_function(transparent_geometry_group *group, uint32_t reflection_kind); }
using rasterizer_glass_reflection_draw_fixed_function_impl::rasterizer_glass_reflection_draw_fixed_function;
namespace rasterizer_glass_tint_draw_impl { void rasterizer_glass_tint_draw(transparent_geometry_group *group); }
using rasterizer_glass_tint_draw_impl::rasterizer_glass_tint_draw;
namespace rasterizer_glass_tint_draw_fixed_function_impl { void rasterizer_glass_tint_draw_fixed_function(transparent_geometry_group *group); }
using rasterizer_glass_tint_draw_fixed_function_impl::rasterizer_glass_tint_draw_fixed_function;
namespace rasterizer_shader_transparent_chicago_draw_impl { void rasterizer_shader_transparent_chicago_draw(transparent_geometry_group *group, uint8_t attached); }
using rasterizer_shader_transparent_chicago_draw_impl::rasterizer_shader_transparent_chicago_draw;
namespace rasterizer_shader_transparent_chicago_extended_draw_impl { void rasterizer_shader_transparent_chicago_extended_draw(transparent_geometry_group *group, uint8_t attached); }
using rasterizer_shader_transparent_chicago_extended_draw_impl::rasterizer_shader_transparent_chicago_extended_draw;
namespace rasterizer_shader_transparent_chicago_extended_set_texture_stages_impl { uint8_t rasterizer_shader_transparent_chicago_extended_set_texture_stages(const ShaderTransparentChicagoExtended *shader); }
using rasterizer_shader_transparent_chicago_extended_set_texture_stages_impl::rasterizer_shader_transparent_chicago_extended_set_texture_stages;
namespace rasterizer_shader_transparent_chicago_set_texture_stages_impl { uint8_t rasterizer_shader_transparent_chicago_set_texture_stages(const ShaderTransparentChicago *shader); }
using rasterizer_shader_transparent_chicago_set_texture_stages_impl::rasterizer_shader_transparent_chicago_set_texture_stages;
namespace rasterizer_shader_transparent_plasma_draw_impl { void rasterizer_shader_transparent_plasma_draw(transparent_geometry_group *group); }
using rasterizer_shader_transparent_plasma_draw_impl::rasterizer_shader_transparent_plasma_draw;
namespace rasterizer_water_draw_fixed_function_impl { void rasterizer_water_draw_fixed_function(transparent_geometry_group *group); }
using rasterizer_water_draw_fixed_function_impl::rasterizer_water_draw_fixed_function;
namespace rasterizer_water_draw_pixel_shader_impl { void rasterizer_water_draw_pixel_shader(transparent_geometry_group *group); }
using rasterizer_water_draw_pixel_shader_impl::rasterizer_water_draw_pixel_shader;
namespace rasterizer_water_fade_compute_and_set_states_impl { void rasterizer_water_fade_compute_and_set_states(void); }
using rasterizer_water_fade_compute_and_set_states_impl::rasterizer_water_fade_compute_and_set_states;
namespace rasterizer_water_ripple_draw_impl { void rasterizer_water_ripple_draw(rasterizer_vertex_buffer *vertex_buffer, const Shader *shader, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count); }
using rasterizer_water_ripple_draw_impl::rasterizer_water_ripple_draw;
namespace rasterizer_water_update_ripple_texture_impl { void rasterizer_water_update_ripple_texture(void *water_shader); }
using rasterizer_water_update_ripple_texture_impl::rasterizer_water_update_ripple_texture;
void rasterizer_light_cone_draw(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer);
namespace rasterizer_light_cone_set_orientation_constants_impl { void rasterizer_light_cone_set_orientation_constants(int32_t light_index); }
using rasterizer_light_cone_set_orientation_constants_impl::rasterizer_light_cone_set_orientation_constants;
namespace rasterizer_light_cone_set_texture_stage_states_impl { void rasterizer_light_cone_set_texture_stage_states(void); }
using rasterizer_light_cone_set_texture_stage_states_impl::rasterizer_light_cone_set_texture_stage_states;
namespace rasterizer_light_disable_all_impl { void rasterizer_light_disable_all(void); }
using rasterizer_light_disable_all_impl::rasterizer_light_disable_all;
namespace rasterizer_light_set_impl { void rasterizer_light_set(rasterizer_light *light); }
using rasterizer_light_set_impl::rasterizer_light_set;
void rasterizer_light_set_point_constants(int32_t light_index, int16_t slot, rasterizer_point_light_constants *dest_base);
namespace rasterizer_prepare_lighting_constants_impl { void rasterizer_prepare_lighting_constants(render_lighting *lighting); }
using rasterizer_prepare_lighting_constants_impl::rasterizer_prepare_lighting_constants;
void rasterizer_projected_light_constants_build(int32_t light_index);
void rasterizer_projected_light_constants_build_cube_map(int32_t light_index);
namespace rasterizer_set_fog_constants_impl { void rasterizer_set_fog_constants(const render_fog *fog); }
using rasterizer_set_fog_constants_impl::rasterizer_set_fog_constants;
namespace rasterizer_set_shader_stage_config_impl { void rasterizer_set_shader_stage_config(int16_t mode); }
using rasterizer_set_shader_stage_config_impl::rasterizer_set_shader_stage_config;
namespace rasterizer_shader_technique_for_name_impl { void * rasterizer_shader_technique_for_name(void *effect, const char *name); }
using rasterizer_shader_technique_for_name_impl::rasterizer_shader_technique_for_name;
uint8_t rasterizer_shader_environment_build_technique_table(void);
void rasterizer_shader_environment_draw_dispatch(int32_t dynamic_vertex_slot, uint8_t *shader, int16_t frame, rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer);
void rasterizer_shader_environment_draw_fixed_function(uint8_t *shader, int16_t frame, rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_vertex_slot);
namespace rasterizer_shader_environment_draw_pixel_shader_impl { void rasterizer_shader_environment_draw_pixel_shader(uint8_t *shader, int16_t frame, rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_vertex_slot); }
using rasterizer_shader_environment_draw_pixel_shader_impl::rasterizer_shader_environment_draw_pixel_shader;
namespace rasterizer_shader_environment_draw_single_stream_impl { void rasterizer_shader_environment_draw_single_stream(uint8_t *shader, int16_t frame, rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_vertex_slot); }
using rasterizer_shader_environment_draw_single_stream_impl::rasterizer_shader_environment_draw_single_stream;
namespace rasterizer_shader_environment_dynamic_mirror_draw_impl { void rasterizer_shader_environment_dynamic_mirror_draw(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer); }
using rasterizer_shader_environment_dynamic_mirror_draw_impl::rasterizer_shader_environment_dynamic_mirror_draw;
namespace rasterizer_shader_environment_lightmap_draw_impl { void rasterizer_shader_environment_lightmap_draw(uint8_t *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, void *vertex_buffer); }
using rasterizer_shader_environment_lightmap_draw_impl::rasterizer_shader_environment_lightmap_draw;
namespace rasterizer_shader_environment_lightmap_draw_single_stream_impl { void rasterizer_shader_environment_lightmap_draw_single_stream(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer); }
using rasterizer_shader_environment_lightmap_draw_single_stream_impl::rasterizer_shader_environment_lightmap_draw_single_stream;
namespace rasterizer_shader_environment_lightmap_draw_two_stream_impl { void rasterizer_shader_environment_lightmap_draw_two_stream(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer); }
using rasterizer_shader_environment_lightmap_draw_two_stream_impl::rasterizer_shader_environment_lightmap_draw_two_stream;
namespace rasterizer_shader_environment_lightmap_specular_draw_impl { void rasterizer_shader_environment_lightmap_specular_draw(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer); }
using rasterizer_shader_environment_lightmap_specular_draw_impl::rasterizer_shader_environment_lightmap_specular_draw;
namespace rasterizer_shader_environment_projected_light_draw_impl { void rasterizer_shader_environment_projected_light_draw(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer); }
using rasterizer_shader_environment_projected_light_draw_impl::rasterizer_shader_environment_projected_light_draw;
namespace rasterizer_shader_environment_reflection_draw_impl { void rasterizer_shader_environment_reflection_draw(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer); }
using rasterizer_shader_environment_reflection_draw_impl::rasterizer_shader_environment_reflection_draw;
void rasterizer_shader_environment_select_draw_functions(void);
namespace rasterizer_shader_environment_self_illumination_draw_impl { void rasterizer_shader_environment_self_illumination_draw(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer); }
using rasterizer_shader_environment_self_illumination_draw_impl::rasterizer_shader_environment_self_illumination_draw;
namespace rasterizer_shader_environment_self_illumination_draw_single_stream_impl { void rasterizer_shader_environment_self_illumination_draw_single_stream(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer); }
using rasterizer_shader_environment_self_illumination_draw_single_stream_impl::rasterizer_shader_environment_self_illumination_draw_single_stream;
namespace rasterizer_shader_environment_self_illumination_draw_two_stream_impl { void rasterizer_shader_environment_self_illumination_draw_two_stream(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer); }
using rasterizer_shader_environment_self_illumination_draw_two_stream_impl::rasterizer_shader_environment_self_illumination_draw_two_stream;
void rasterizer_shader_environment_set_lightmap(BitmapData *lightmap);
namespace rasterizer_shader_environment_technique_draw_impl { void rasterizer_shader_environment_technique_draw(rasterizer_vertex_buffer *vertex_buffer, const ShaderEnvironment *shader, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count); }
using rasterizer_shader_environment_technique_draw_impl::rasterizer_shader_environment_technique_draw;
namespace rasterizer_shader_environment_technique_multipurpose_set_states_impl { void rasterizer_shader_environment_technique_multipurpose_set_states(void); }
using rasterizer_shader_environment_technique_multipurpose_set_states_impl::rasterizer_shader_environment_technique_multipurpose_set_states;
namespace rasterizer_shader_environment_technique_ps2_set_states_impl { void rasterizer_shader_environment_technique_ps2_set_states(void); }
using rasterizer_shader_environment_technique_ps2_set_states_impl::rasterizer_shader_environment_technique_ps2_set_states;
namespace rasterizer_shader_environment_technique_self_illumination_set_states_impl { void rasterizer_shader_environment_technique_self_illumination_set_states(void); }
using rasterizer_shader_environment_technique_self_illumination_set_states_impl::rasterizer_shader_environment_technique_self_illumination_set_states;
int rasterizer_transparent_decals_enabled(void);
transparent_geometry_group * rasterizer_transparent_geometry_group_build(transparent_geometry_group_link *link, uint8_t *shader, int16_t frame, rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_vertex_slot, const real_point3d *position);
void rasterizer_transparent_geometry_group_draw(transparent_geometry_group *group, uint8_t attached);
namespace rasterizer_transparent_geometry_group_draw_active_camouflage_impl { void rasterizer_transparent_geometry_group_draw_active_camouflage(transparent_geometry_group *group); }
using rasterizer_transparent_geometry_group_draw_active_camouflage_impl::rasterizer_transparent_geometry_group_draw_active_camouflage;
void rasterizer_transparent_geometry_group_draw_vertices(transparent_geometry_group *group, uint8_t flag);
void rasterizer_transparent_geometry_group_new(Shader *shader, int16_t shader_permutation, uint32_t lightmap_bitmap, uint32_t dynamic_index_slot, uint32_t first_index, uint32_t primitive_count, uint32_t vertex_buffer, ColorARGB *tint, uint32_t lighting, uint32_t flags, real_point3d *world_position);
void rasterizer_transparent_object_append(uint32_t lightmap_bitmap, int32_t dynamic_index_slot, int32_t dynamic_vertex_slot, int32_t primitive_count, uint32_t flags, real_point3d *world_position, Shader *shader);
transparent_geometry_group * transparent_geometry_group_allocate(void);
transparent_geometry_group * transparent_geometry_group_allocate_secondary(void);
int transparent_geometry_group_compare(int16_t *a, int16_t *b);
void transparent_geometry_group_draw_all(uint8_t resort);
transparent_geometry_group * transparent_geometry_group_get_next_sorted(transparent_geometry_group *group);
uint32_t transparent_geometry_group_get_vertex_type_reference(transparent_geometry_group *group);
int32_t transparent_geometry_group_index_from_pointer(transparent_geometry_group *group);
void transparent_geometry_group_set_drawn_bit(transparent_geometry_group *group, uint8_t clear);
void transparent_geometry_group_sort(void);
uint8_t transparent_geometry_group_test_drawn_bit(transparent_geometry_group *group);
int32_t transparent_geometry_pool_initialize(void);

}
