// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/ai/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_AI_H
#define FN_AI_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "ai.h"

extern uint8_t actor_action_has_queued_secondary(datum_index actor_index);  // 0x417b70, EAX -> actor_index
extern uint8_t actor_alert_from_damage(datum_index actor_index);  // 0x40a500
extern uint8_t actor_alert_from_disturbance(datum_index actor_index);  // 0x40a3d0, EAX
extern uint8_t actor_alert_from_flag_1b4(datum_index actor_index);  // 0x40a6b0, EAX
extern uint8_t actor_alert_from_projectile(datum_index actor_index);  // 0x40a5e0
extern uint8_t actor_alert_from_squad_attack(datum_index actor_index);  // 0x40a460, EDX
extern datum_index actor_allocate_paired_prop_with_kind(datum_index actor_index, datum_index existing_prop, datum_index reference_prop);  // 0x43e980
extern uint8_t actor_apply_perception_scale(datum_index actor_index, const uint8_t *zone, float *in_out_value);  // 0x42aa90, EAX, stack, EDX
extern void actor_apply_queued_look_to_unit(datum_index actor_index);  // 0x42a640, in this rewrite range, not yet written when this file was authored
extern void actor_apply_unit_definition_properties(datum_index actor_variant_tag, datum_index unit_index);  // 0x426cf0, EAX, stack
extern void actor_attach_to_unit(datum_index actor_index, datum_index unit_index);  // 0x427560, stack
extern uint8_t actor_avoid_obstacle_and_project(datum_index actor_index, datum_index vehicle_index, real_point3d *entry, real_point3d *hint, uint8_t *in_out_near_line, real_point3d *out_point, int32_t *out_surface_index);  // 0x4095c0, EAX, ECX, EDX, stack
extern void actor_avoidance_build_direction_tables(void);  // 0x41a2d0, not in this rewrite range (builds the avoidance direction-sample tables)
extern uint8_t actor_avoidance_interpolate_sample(const real_vector3d *direction, const real_vector3d *samples, int16_t count, const float *values, float *out_index, float *out_value);  // 0x419240, ECX, EBX, stack
extern uint8_t actor_build_guard_mode_data(datum_index actor_index, uint8_t *out);  // 0x404360, EDX actor, stack out
extern int32_t actor_build_order_default(uint32_t actor_index, int16_t order_code, actor_order *order, int16_t parameter);  // 0x401090, EAX, ECX, EDX, stack
extern uint32_t actor_build_order_face_seat_marker(uint32_t actor_index, int16_t firing_position_index, uint32_t *order);  // 0x408110, EAX, stack, EDX
extern uint32_t actor_build_order_face_seat_marker_committed(uint32_t actor_index, int16_t firing_position_index, uint8_t byte_a, uint32_t *order);  // 0x407820, EAX, stack, EDX
extern int32_t actor_build_order_flee(uint32_t actor_index, uint8_t byte_a, uint32_t *order);  // 0x4077d0, EAX, stack, EDX
extern int32_t actor_build_order_grenade_or_melee(uint32_t resolved_target, uint8_t use_alt_base, uint32_t actor_index, uint16_t order_code, uint8_t byte_a, uint8_t byte_b, uint16_t *order);  // 0x403630, this module
extern int32_t actor_build_order_guard(uint32_t actor_index, actor_order *order, int16_t guard_at_current_position);  // 0x404510, EAX, EDX, EBX
extern uint8_t actor_build_order_investigate_encounter_point(uint32_t vehicle_index, uint32_t actor_index, int16_t seat_index, uint8_t *order);  // 0x408a30, EBX, stack
extern int32_t actor_build_order_look(uint32_t actor_index, actor_order *order, actor_look_request *request);  // 0x4046c0, EAX, ESI, EBX
extern int32_t actor_build_order_minimal_stop(uint32_t actor_index, uint32_t *order);  // 0x4078f0, EAX, ESI
extern int32_t actor_build_order_random_wait(uint32_t actor_index, uint8_t byte_a, uint32_t *order);  // 0x409a90, EAX, stack, ECX
extern int32_t actor_build_order_return_to_anchor(uint32_t actor_index, actor_order *order);  // 0x4044b0, EAX, EDX
extern uint8_t actor_build_order_search_object(uint32_t vehicle_index, uint32_t actor_index, float radius_a, float radius_b, uint8_t *order);  // 0x408920, EBX, stack
extern int32_t actor_build_order_search_wait(uint32_t actor_index, actor_order *order);  // 0x4045a0, EAX, ESI
extern int32_t actor_build_order_wait_byte(uint32_t actor_index, uint8_t byte_a, uint32_t *order);  // 0x4080c0, EAX, stack, ESI
extern void actor_build_path_find_request(datum_index actor_index, path_find_request *request);  // 0x41a9c0, EAX, EBX
extern uint8_t actor_can_throw_grenade_at_target(datum_index actor_index);  // 0x40d9c0, this module
extern uint8_t actor_check_grenade_facing_and_commit(datum_index actor_index, uint8_t force_commit);  // 0x40db00, this module
extern void actor_check_melee_target_reachable(uint32_t actor_index, int16_t *order);  // 0x403f00, stack, EBX order
extern uint8_t actor_check_pain_reaction(uint32_t resolved_target, uint8_t use_alt_base, uint16_t order_code, datum_index actor_index);  // 0x40de20, stack, DL, CX, ESI
extern uint8_t actor_check_step_obstruction(datum_index actor_index, real_vector2d *direction, float step_distance, float step_up, uint8_t *out_flag, void *extra_param);  // 0x417bb0, EAX, EDI, stack
extern uint8_t actor_check_vehicle_mode_timeout(datum_index actor_index);  // 0x428270, blam-cc: ECX -> actor_index (object+0x1f4 at both call sites)
extern uint8_t actor_check_vehicle_target_available(datum_index vehicle_object_index, datum_index actor_index, uint8_t flag_pursue);  // 0x42b810, EAX, ECX, stack
extern uint8_t actor_check_weapon_pickup_reachable(uint32_t actor_index, uint8_t *record);  // 0x4041d0, EAX, stack
extern void actor_choose_best_target(datum_index actor_index);  // 0x4203a0
extern void actor_choose_random_point_near(real_point3d *inout_point, float radius);  // 0x40faf0, this module
extern int16_t actor_claim_firing_position(datum_index actor_index, datum_index previous_owner, path_find_context *path_context, int16_t firing_position_index, uint8_t path_ok);  // 0x414060, stack, CX, AL
extern int32_t actor_classify_communication_object_type(datum_index actor_index);  // 0x42f9a0, this batch
extern void actor_clear_perceived_props(datum_index actor_index);  // 0x427e00
extern void actor_clear_recognition_history(datum_index actor_index, uint8_t keep_when_typed);  // 0x414140, EAX -> actor_index
extern void actor_clear_target_state(datum_index actor_index);  // 0x4286c0
extern uint8_t actor_combat_status_should_hold(datum_index actor_index, int16_t threshold_a, int16_t threshold_b);  // 0x40d520
extern uint8_t actor_command_list_permits_escalation(datum_index actor_index);  // 0x40d580, EAX
extern void actor_command_list_reset_record(uint32_t actor_index, datum_index unit_index, uint16_t extra, void *component_record, int32_t secondary_record, uint32_t callback_extra);  // 0x406dd0
extern uint32_t actor_commit_grenade_toss(datum_index actor_index, real_point3d *point, uint32_t object_handle, uint32_t exclude_object_index);  // 0x411180, this module
extern float actor_compute_accuracy_scale(datum_index actor_index);  // 0x429620, not yet rewritten (an engagement-range radius)
extern uint32_t actor_compute_grenade_aim_direction(datum_index actor_index, real_point3d *target_point, real_vector3d *out_direction, float *out_698);  // 0x40f7e0, EAX, EDX, EDI, stack
extern uint32_t actor_compute_grenade_throw_vector(datum_index actor_index, real_point3d *grenade_position, real_vector3d *out_vector);  // 0x410a60, EBX, stack
extern float actor_compute_target_priority_weight(datum_index prop_index, datum_index actor_index);  // 0x414590, EAX -> prop_index, ECX -> actor_index
extern uint8_t actor_conditional_state_transition_check(datum_index actor_index);  // 0x40d7a0, ESI
extern uint8_t actor_consider_combat_mode(uint32_t actor_index, int16_t consideration_mode, actor_combat_consideration *out);  // 0x401a60
extern uint8_t actor_consider_grenade_throw(datum_index actor_index);  // 0x40dc30
extern uint16_t actor_consider_target_candidate(datum_index actor_index, datum_index candidate_prop_index);  // 0x4208a0, this module;
extern void actor_copy_prop_and_reset(datum_index dest_prop, datum_index src_prop);  // 0x43e840, EAX, ECX
extern uint8_t actor_danger_register_point(datum_index actor_index, datum_index source_object_index, float radius, float distance, char accept_flag, uint8_t unknown_byte);  // 0x41ec90, EAX, EDX, stack
extern uint8_t actor_danger_register_stationary_object(const float *reference, datum_index actor_index, datum_index object_index, uint8_t unknown_byte);  // 0x41ea60, EAX, stack
extern void actor_danger_update_reaction(datum_index actor_index);  // 0x41eda0
extern void actor_delete(datum_index actor_index, uint32_t flag);  // 0x427e60
extern void actor_delete_or_release_unit(datum_index actor_index, uint8_t is_dead);  // 0x4288e0
extern void actor_delete_swarm(datum_index actor_index);  // 0x4280b0
extern void actor_dispatch_perception_reset(datum_index actor_index);  // 0x429000, EAX -> actor_index
extern void actor_dispatch_squad_order(datum_index prop_index, const actor_squad_order_header *order, datum_index actor_index);  // 0x42a540, EAX, ECX, EDX
extern void actor_dispatch_type_vtable_0x10(datum_index actor_index);  // 0x426670
extern void actor_dispatch_type_vtable_0x18(datum_index actor_index);  // 0x4266a0
extern void actor_dispatch_type_vtable_0x1c(datum_index actor_index, uint32_t a, uint32_t b, uint32_t c);  // 0x4266d0, ECX, stack
extern uint8_t actor_escalate_apply(datum_index actor_index, int16_t threshold);  // 0x40aa70, EDI, stack
extern uint8_t actor_escalate_check_leader_flag(datum_index actor_index);  // 0x40a7f0, EAX
extern uint8_t actor_escalate_check_shield_damage(datum_index actor_index);  // 0x40a9e0, EAX
extern uint8_t actor_escalate_check_target_close(datum_index actor_index);  // 0x40a950, EAX
extern uint8_t actor_escalate_check_weapon_range(datum_index actor_index);  // 0x40a860, EAX
extern uint8_t actor_escalate_to_guard_or_combat(datum_index actor_index);  // 0x40aaf0, EDI
extern char actor_evaluate_combat_state_transition(uint32_t actor_index);  // 0x40c620, other half of this session
extern uint8_t actor_evaluate_custom_charge_trigger(datum_index actor_index);  // 0x424090, not yet rewritten
extern int32_t actor_evaluate_engagement_reachability(int16_t self_cluster, int16_t target_cluster, real_point3d *target_position, real_point3d *self_position, int16_t movement_mode, uint8_t allow_wide_mask, datum_index exclude_object_index, uint8_t flying);  // 0x42b270, AX, CX, ESI, EDI, stack
extern uint8_t actor_evaluate_grenade_target_position(datum_index actor_index);  // 0x40de70, EBX
extern uint8_t actor_evaluate_search_node(datum_index actor_index, datum_index vehicle_index, int16_t seat_index, real_point3d *out_entry, real_vector3d *out_direction, real_point3d *out_hint, float *out_score, uint8_t *out_close, uint8_t *out_facing, uint8_t *out_in_front);  // 0x4091d0
extern void actor_fill_unit_position_context(datum_index unit_index, actor_unit_position_context *out_context);  // 0x4296c0, EBX, stack
extern uint32_t actor_find_best_firing_position(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *out_candidate, uint32_t *out_previous_owner, path_find_context *path_context, uint8_t *out_path_ok);  // 0x412ba0
extern int16_t actor_find_best_search_node(datum_index actor_index, datum_index vehicle_index, real_point3d *out_entry, real_vector3d *out_direction, real_point3d *out_hint);  // 0x409070
extern uint8_t actor_find_danger_escape(datum_index actor_index, uint32_t *out_word, uint8_t *out_position, real_vector3d *path_delta, uint8_t *in_danger);  // 0x40bc40
extern uint8_t actor_find_grenade_landing_spot(datum_index actor_index, real_point3d *out_point, datum_index *out_target_handle, int32_t *out_relationship);  // 0x410c90, this module
extern datum_index actor_find_prop_for_object(datum_index object_index, datum_index actor_index);  // 0x43ea80, ECX actor, stack object
extern uint8_t actor_firing_position_compare(int32_t element, int32_t other);  // 0x4127b0, src/ai/actor_firing_position_compare.c
extern uint8_t actor_firing_position_evaluate(actor_firing_position_candidate *candidate, actor_firing_position_query *query, datum_index actor_index);  // 0x412820, this module
extern uint8_t actor_firing_position_probe_reject_rules(actor_firing_position_query *query, datum_index actor_index);  // 0x412770, EDI, EBX
extern uint8_t actor_firing_position_run_reject_rules(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *candidate);  // 0x412730
extern void actor_firing_position_run_score_rules(datum_index actor_index, uint16_t count, actor_firing_position_query *query, actor_firing_position_candidate *candidates);  // 0x4126f0
extern uint32_t actor_flee_look_away(datum_index actor_index);  // 0x40d4c0, EDI
extern void actor_forward_target_object_reference(datum_index actor_index, uint32_t param);  // 0x428420, already rewritten in this module
extern uint8_t actor_gate_jump_traversal(uint32_t actor_index, int16_t threshold, char allow_broadcast, int16_t broadcast_threshold);  // 0x40a700, EAX
extern int16_t actor_gather_nearby_grenade_targets(datum_index source_actor_index, int16_t maximum_count, ai_grenade_avoidance_entry *out_entries);  // 0x0042afc0
extern void actor_get_aim_from_position(datum_index actor_index, uint32_t out_position[3]);  // 0x40f9b0, this module
extern void actor_get_body_axis_vector(uint32_t actor_index, uint32_t unit_index, actor_axis_request *request);  // 0x405390, EAX, EDX, ECX
extern uint8_t actor_get_cached_wander_position(datum_index actor_index, real_vector3d *out_position);  // 0x4281f0, EAX, EDX
extern float actor_get_consideration_wait_threshold(uint32_t actor_index, int16_t mode, actor_combat_consideration *consideration);  // 0x4028e0, EAX, CX, EDI
extern int16_t actor_get_current_mode_combat_grade(datum_index actor_index);  // 0x40e760, EAX
extern uint32_t actor_get_firing_position_group_mask(datum_index actor_index, int16_t kind, int16_t search_override);  // 0x412880, EAX, SI, stack
extern void actor_get_firing_positions(datum_index actor_index, uint32_t *out_block, real_point3d *query_point);  // 0x41c1e0, this batch
extern uint8_t actor_get_grenade_launch_velocity(int16_t grenade_type, real_vector3d *direction, void *origin, float range, real_point3d *point, int32_t max_time, float *speed, void *out_time_or_fraction, real_vector3d *out_velocity, float *out_gravity);  // 0x410980, AX, ESI, stack
extern float *actor_get_idle_facing_range(datum_index actor_index);  // 0x4150f0, EAX
extern uint8_t actor_get_ranged_attack_vector(datum_index target_prop_index, datum_index actor_index, real_vector3d *out_vector);  // 0x420970, EAX, ECX, stack
extern datum_index actor_get_relevant_squad_member_target(uint32_t unused_param, datum_index member_prop_index, char require_is_unit);  // 0x41f550
extern uint8_t actor_get_requested_velocity(uint8_t skip_clamp, datum_index actor_index, real_vector3d *out_velocity, uint32_t object_index, float speed_limit);  // 0x417fa0, AL, ECX, EDX, stack
extern datum_index actor_get_squad_recent_attacker_target(datum_index actor_index, char require_is_unit);  // 0x41f6b0
extern datum_index actor_get_target_prop_object_index(datum_index actor_index);  // 0x4283d0, EAX
extern void actor_get_target_state_flags(int16_t ax_mode, int16_t cx_mode, uint8_t shared_flag, uint32_t actor_index, int16_t mode_b, char force_c, char force_d, uint8_t *out_a, char *out_in_e, uint8_t *out_f, uint8_t *out_g, uint8_t *out_h, uint8_t *out_i);  // 0x40cc70, EAX, ECX, EDX, stack
extern void actor_grenade_avoidance_entry_init(ai_grenade_avoidance_entry *entry, datum_index object_index, datum_index prop_index);  // 0x0042af50
extern uint8_t actor_grenade_behavior_kind_allowed(datum_index actor_index, int16_t kind);  // 0x40f670, EAX, stack
extern uint8_t actor_grenade_parabolic_path_clear(real_vector3d *initial_velocity, datum_index source_actor_index, real_point3d *start_position, real total_time, real vertical_acceleration, datum_index exclude_object_index, uint8_t wide_mask);  // 0x42b5d0, EAX, ECX, EDX, stack
extern int32_t actor_grenade_trace_from_source(uint32_t actor_index, real_point3d *target_point);  // 0x4029e0, EAX, ESI
extern uint8_t actor_grenade_trajectory_blocked(real_vector3d *trajectory_direction, datum_index source_actor_index, datum_index exclude_object_index, real_point3d *landing_position, int32_t *out_blocking_prop);  // 0x42b190, EAX, ECX, stack
extern uint8_t actor_handle_death(datum_index actor_index, uint8_t param_2, uint8_t param_3);  // 0x40dd50
extern uint8_t actor_has_unshielded_threat_weapon(datum_index actor_index);  // 0x428370, EAX
extern void actor_init_prop_from_object(datum_index object_index, datum_index actor_index, datum_index prop_index);  // 0x43e640, EAX, EDX, stack
extern void actor_invoke_type_handler(uint32_t actor_index);  // 0x409e70
extern uint8_t actor_is_burst_pending(datum_index actor_index);  // 0x428180, not yet rewritten (phase2 name: actor_is_ranged_burst_active); UNSURE: no visible args at this call site
extern uint8_t actor_is_target_within_engagement_range(uint32_t actor_index);  // 0x403dc0, EAX
extern uint8_t actor_is_within_alert_range(uint8_t always_in_range, float radius_a, float radius_b, uint8_t vitality_only, uint8_t use_radius_b, uint32_t actor_index, uint32_t object_index);  // 0x408f30, stack, EAX, ECX
extern void actor_issue_multi_target_vocalization(int16_t line, datum_index actor_index, int16_t variant, datum_index vehicle_object_index);  // 0x4303a0, stack, EDI, BX, ESI
extern void actor_issue_order_or_vocalize(datum_index prop_index, datum_index actor_index, datum_index vehicle_object_index, int16_t line, int16_t variant);  // 0x4302e0, EAX, EBX, EDI, stack
extern void actor_iterator_new(actor_iterator_state *out_iterator, uint8_t active_only);  // 0x436a30, this batch
extern actor *actor_iterator_next(actor_iterator_state *iterator);  // 0x436a70, EAX
extern uint8_t actor_link_to_unit_cluster(datum_index actor_index, datum_index unit_index);  // 0x4279f0
extern int32_t actor_look_get_wait_ticks(datum_index actor_index, int16_t mode, uint32_t flags, float *deviation_table);  // 0x415150, EAX, stack, EDI
extern uint8_t actor_look_pick_random_point_in_cone(void *origin, float yaw_min, float yaw_max, float pitch_min, float pitch_max, real_vector3d *base_direction, uint8_t check_obstruction, real_point3d *out);  // 0x415260, this module
extern void actor_look_randomize_direction(datum_index actor_index, float *deviation_table, real_vector3d *base_direction);  // 0x414f50
extern int32_t actor_lookup_small_table_entry(int16_t index);  // 0x40e790, CX
extern void actor_mark_prop_seen_with_delta(datum_index object_index, datum_index actor_index, float delta, const real_vector3d *direction);  // 0x428840, EAX, stack
extern void actor_mark_units_and_release(uint8_t use_alternate_flag, datum_index actor_index, uint8_t suppress_release);  // 0x4289c0, AL, stack; outside this
extern void actor_movement_action_cancel(datum_index actor_index);  // 0x428650
extern void actor_movement_action_complete(datum_index actor_index);  // 0x41a430, this module, EAX -> actor_index
extern uint8_t actor_movement_action_in_progress(datum_index actor_index);  // 0x41a980, EAX
extern uint8_t actor_movement_action_is_complete(datum_index actor_index);  // 0x41a960, EAX
extern uint8_t actor_movement_action_resolve(datum_index actor_index, uint8_t record_distance, path_find_context *context);  // 0x41a460, this module
extern void actor_movement_action_stop(datum_index actor_index);  // 0x417570, this module,
extern void actor_movement_actions_cancel(datum_index actor_index);  // 0x417a30, EAX
extern void actor_movement_advance_waypoint(datum_index actor_index);  // 0x4163e0
extern void actor_movement_apply_steering( int16_t cached_axis, uint8_t keep_z, datum_index actor_index, uint8_t want_avoid_check, float avoid_threshold, uint8_t order_failed, float steering_maximum, float oversteer_min, float oversteer_max, float avoidance_scale, float throttle_maximum, real_vector3d *desired_direction, real_vector3d *out_direction, int16_t *out_axis, real_vector3d *out_heading, uint8_t *out_flag_507, uint8_t *out_flag_506);  // 0x4180c0
extern uint8_t actor_movement_check_arrival(datum_index actor_index);  // 0x416700, this module, EAX -> actor_index
extern void actor_movement_choose_strafe_axis(const real_vector3d *direction, uint8_t use_3d, const real_vector3d *facing, const real_vector3d *reference, real_vector3d *out_axis, int16_t *out_index);  // 0x418a40, EAX, BL, ESI, EDI, stack
extern void actor_movement_collect_obstacle_candidates(actor_movement_context *context);  // 0x418ce0, stack
extern uint8_t actor_movement_flying_needs_steering(datum_index actor_index, const real_point3d *destination, float *out_avoidance_distance);  // 0x41aab0, this module, EAX/ECX/EDI
extern void actor_movement_get_stopping_distances(datum_index actor_index, float *out_accelerate_stop_distance, float *out_stop_distance);  // 0x4173a0, EAX, EBX, EDI
extern void actor_movement_project_into_frame(uint8_t use_3d, const real_vector3d *frame_axis, const real_vector3d *v, real_vector3d *out);  // 0x418c20, AL, ECX, stack
extern uint8_t actor_movement_set_destination_firing_position(datum_index actor_index, int16_t formation_slot, path_find_context *path_context);  // 0x417830, EDI, stack
extern uint8_t actor_movement_set_destination_move_position(datum_index actor_index, int16_t move_position_index);  // 0x417750, EDI, stack
extern uint8_t actor_movement_set_destination_near_target(datum_index target_prop_index, datum_index actor_index, float radius);  // 0x417910, EAX, stack
extern uint8_t actor_movement_set_destination_point(real_point3d *destination, datum_index actor_index, int32_t parameter, uint32_t extra);  // 0x417610, EAX, stack
extern int16_t actor_movement_test_obstacle_ray(real_vector3d *out_elevation, const float *sample, real_point3d *out_end_point, actor_movement_context *context, float *out_distance, uint8_t *out_clear_counter);  // 0x418f70, EAX, ECX, EDX, EDI, stack; AX: 0 clear, 1 obstacle, 2 structure
extern void actor_movement_update(datum_index actor_index);  // 0x416790
extern datum_index actor_new(datum_index actor_variant_tag);  // 0x426760, stack
extern void actor_notify_squad_and_flag_danger(datum_index actor_index, uint8_t alternate_event, uint8_t raise_danger_flag);  // 0x423600, EAX, ECX, stack
extern void actor_notify_squad_of_threat_direction(const real_point3d *point, datum_index actor_index, int16_t event_kind, int16_t grenade_type_code);  // 0x4234f0, EBX, EDI, stack
extern void actor_notify_target_engaged(datum_index target_prop_index, datum_index actor_index, uint8_t alternate_event);  // 0x4220c0, EAX, ECX, DL
extern void actor_notify_weapon_pickup_once(datum_index object_index);  // 0x42c370, ECX
extern void actor_obey_member_advance(uint32_t actor_index, datum_index unit_index, uint16_t command_list_index, void *component_record, int32_t secondary_record, uint32_t callback_extra);  // 0x406f80
extern void actor_obey_member_enter(uint32_t actor_index, datum_index unit_index, uint16_t command_list_index, void *component_record, int32_t secondary_record, uint32_t callback_extra);  // 0x406f30
extern void actor_obey_member_exit(uint32_t actor_index, datum_index unit_index, uint16_t command_list_index, void *component_record, int32_t secondary_record, uint32_t callback_extra);  // 0x406fa0
extern void actor_obey_member_tick(uint32_t actor_index, datum_index unit_index, uint16_t command_list_index, void *component_record, int32_t secondary_record, uint32_t callback_extra);  // 0x406ff0
extern int32_t actor_order_code_is_grenade_throw(int16_t order_code);  // 0x404340, AX
extern int32_t actor_pick_dialogue_variant_a(int16_t category);  // 0x424aa0, AX
extern int32_t actor_pick_dialogue_variant_b(int16_t category);  // 0x424b80, AX
extern datum_index actor_place_new_unit(datum_index actor_variant_or_palette_tag, datum_index encounter_index, int16_t squad_index, uint8_t use_palette_entry, uint16_t unit_type_index, const actor_placement_request *placement_request);  // 0x427080, stack, EAX request
extern uint8_t actor_play_first_valid_vocalization(int16_t *seat_list, datum_index vehicle_index, datum_index actor_index, char *seat_name, int16_t seat_flags, int16_t count);  // 0x40e260, EAX, ECX, stack
extern uint8_t actor_point_in_directional_lane(real_point3d *to_point, real_point3d *forward, real_point3d *cone_axis, float min_cos_threshold, float side_thresholds[2]);  // 0x414990, this module
extern uint8_t actor_probe_step_direction(datum_index actor_index, float step_distance, real_vector2d *direction, uint16_t *variant, float step_up, uint8_t *out_flag, void *extra_param);  // 0x417e50, stack, ECX
extern uint8_t actor_process_pending_command_list(datum_index actor_index);  // 0x40a140
extern uint8_t actor_process_vehicle_seat_exit(datum_index actor_index);  // 0x40b080, EAX
extern void actor_prop_iterator_init(datum_index actor_index, actor_prop_iterator *out_iterator);
extern prop *actor_prop_iterator_next(actor_prop_iterator *iterator);  // 0x43ecf0, EDX
extern void actor_propagate_unit_field(datum_index actor_index, int16_t value);  // 0x4276e0, blam-cc: EAX, ESI
extern void actor_push_recognition_entry(datum_index actor_index, int16_t firing_position_index, uint8_t type);  // 0x4141a0, rewritten in this module
extern void actor_queue_directional_reaction_event(const real_vector3d *direction, datum_index target_prop_index, datum_index actor_index);  // 0x422270, EAX, ECX, stack
extern void actor_queue_point_reaction_dialogue(const real_point3d *point, datum_index actor_index);  // 0x422780, EAX, ECX
extern void actor_queue_recognized_target_dialogue(datum_index actor_index, datum_index target_prop_index);  // 0x422550
extern void actor_queue_search_and_relay_perception(datum_index prop_index, datum_index actor_index);  // 0x4221f0
extern void actor_queue_search_position(datum_index actor_index, real_point3d *position, int16_t priority, real_vector3d *velocity, uint32_t unknown_324, uint32_t unknown_328, uint32_t unknown_33c, uint32_t unknown_340, uint32_t unknown_344, uint8_t unknown_348);  // 0x421af0
extern uint8_t actor_queue_secondary_action(datum_index actor_index, int16_t action, uint32_t payload[2]);  // 0x417a60, EAX, stack
extern void actor_queue_sighted_target_dialogue(datum_index actor_index, datum_index target_prop_index, uint8_t already_noticed);  // 0x421c20
extern void actor_queue_velocity_search_from_prop(datum_index prop_index, datum_index actor_index);  // 0x4221b0, EAX, stack
extern void actor_raise_timer_5f6(datum_index actor_index, int32_t ticks);  // 0x40f7a0
extern float actor_rate_potential_target(datum_index actor_index, datum_index target_prop_index);  // 0x41fd50, this module
extern uint8_t actor_react_to_disturbance(datum_index actor_index, int16_t threshold);  // 0x40a1e0
extern void actor_react_to_flee_point(datum_index actor_index, int32_t flee_source_object, const real_point3d *point);  // 0x422c00, stack
extern void actor_react_to_registered_danger(const real_point3d *point, datum_index actor_index, int32_t danger_object_index);  // 0x422930, EAX, stack
extern void actor_react_to_seen_target(datum_index actor_index, datum_index target_prop_index);  // 0x422ec0
extern void actor_react_to_threat_event(datum_index self_object_index, datum_index other_object_index, int32_t event_kind, real magnitude, uint32_t extra_param, uint8_t suppress_vehicle_relay);  // 0x42be40
extern int32_t actor_reassign_vehicle_seat(datum_index vehicle_object_index, datum_index self_object_index, int32_t seat_selector);  // 0x42b880, EBX, EDI, stack
extern void actor_recompute_grenade_eligibility(datum_index actor_index);  // 0x42f260, this batch
extern void actor_record_look_at_point(datum_index actor_index, const uint32_t *point, int16_t priority, uint32_t data);  // 0x421bc0
extern void actor_record_perception_event(datum_index actor_index, int16_t event, int32_t data);  // 0x422070, EAX, EDX, ESI
extern void actor_refresh_combat_context(datum_index actor_index);  // 0x4297a0, in this rewrite range, not yet written when this file was authored
extern void actor_release_from_cluster_or_delete(datum_index actor_index, datum_index unit_index);  // 0x428e50, EAX, stack
extern void actor_remove_from_unit_cluster(datum_index actor_index, datum_index unit_index);  // 0x427c90
extern void actor_replace_object_reference(datum_index actor_index, uint32_t new_reference, uint32_t old_reference);  // 0x428470, already rewritten in this module
extern int32_t actor_report_command_status(uint32_t actor_index);  // 0x4048b0, EAX
extern void actor_report_firing_position_request(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *candidate);  // 0x4120f0
extern void actor_reseed_movement_pause_timer(datum_index actor_index);  // 0x4104e0
extern void actor_reset_perception_scratch(datum_index unit_index);  // 0x428f40
extern uint8_t actor_reset_queued_look_vector(datum_index actor_index);  // 0x417ae0
extern uint8_t actor_resolve_flee_source_point(actor_flee_source_reason *reason, real_vector3d *out, datum_index actor_index);  // 0x4146c0, EAX, EDI, stack
extern uint8_t actor_resolve_look_target(real_point3d *preferred_direction, datum_index actor_index, float *deviation_table, uint8_t require_trust, uint8_t use_aiming_deviation, uint8_t force_fallback);  // 0x414d00, EAX, stack x5
extern uint8_t actor_resolve_wander_or_look_direction(datum_index actor_index, real_vector3d *out_direction);  // 0x4287a0, EAX, ECX
extern void actor_run_mode_transition_loop(datum_index actor_index);  // 0x429ee0
extern uint8_t actor_scale_value_by_ally_exposure(datum_index actor_index, float *value);  // 0x420c90, EAX, stack
extern void actor_scan_ally_death_panic_reaction(datum_index target_prop_index, datum_index actor_index);  // 0x4233d0
extern void actor_scan_backup_and_panic_reaction(datum_index target_prop_index, datum_index actor_index);  // 0x423220
extern void actor_schedule_grenade_throw(uint32_t actor_index);  // 0x402f80
extern uint8_t actor_score_blast_area_clear(datum_index actor_index, float blast_radius, float safety_radius, real_point3d *point, int16_t *out_count);  // this module
extern uint8_t actor_seek_vehicle_to_board(datum_index actor_index);  // 0x40ac70
extern uint8_t actor_select_facing_target_prop(datum_index actor_index, uint8_t require_trust, uint8_t skip_lane_test, actor_recognition_scan_result *out_result, uint8_t *out_in_front);  // 0x414a90, this module
extern int16_t actor_select_firing_position(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *out_candidate, uint32_t *out_previous_owner, path_find_context *path_context, uint8_t *out_path_ok);  // 0x413e50, stack, EBX query, EDI candidate
extern int32_t actor_select_move_position(uint32_t actor_index, int16_t select_mode, int32_t position_index, uint8_t *direction_flag);  // 0x4014c0, EAX, stack
extern void actor_select_stance_offset_pair(datum_index actor_index, uint8_t *base, uint8_t **out_a, uint8_t **out_b);  // 0x4106b0, this module
extern void actor_set_combat_alert_flag(datum_index actor_index, uint8_t new_flag);  // 0x421a40, EAX, EBX
extern void actor_set_flag_bit1(datum_index actor_index);  // 0x42a5b0, not yet rewritten (this module)
extern void actor_set_mode(datum_index actor_index, int32_t mode, void *mode_data);  // 0x40d8d0, this module
extern void actor_set_override_target(datum_index actor_index, uint8_t enable, datum_index override_target);  // 0x42a5e0, EAX, stack
extern void actor_set_target_alert_stage1(datum_index target_prop_index, datum_index actor_index);  // 0x41fb00, ECX, ESI
extern void actor_set_target_alert_stage2(datum_index target_prop_index, datum_index actor_index);  // 0x41fb60, ECX, ESI
extern void actor_set_target_alert_stage3(datum_index target_prop_index, datum_index actor_index);  // 0x41fbc0, EDX, ESI
extern void actor_set_units_active(datum_index actor_index, uint8_t dormant);  // 0x427860, EAX, BL
extern uint8_t actor_should_hold_position(datum_index actor_index, uint8_t *definition);  // 0x4105c0, EAX, EDX
extern uint8_t actor_should_throw_grenade(uint32_t actor_index, char force);  // 0x40b840, EAX, stack
extern void actor_snapshot_orientation(datum_index actor_index);  // 0x4294d0
extern uint32_t actor_solve_grenade_lob(datum_index actor_index, real_point3d *point);  // 0x410780
extern int16_t actor_spawn_additional_units(datum_index actor_variant_tag, int16_t spawn_count, datum_index source_actor_index, float health_scale);  // 0x427280, EBX, EDX, stack
extern char actor_squad_action_execute(uint8_t *aim_state, uint32_t actor_index, uint32_t check_object_index, int16_t command_list_index, uint8_t *state);  // 0x405520, this session
extern uint8_t actor_squad_action_is_complete(uint8_t *aim_state, uint32_t actor_index, uint32_t check_object_index, int16_t command_list_index, uint8_t *state);  // 0x4066d0, this session
extern void actor_squad_action_list_process(uint32_t actor_index, uint32_t check_object_index, int16_t command_list_index, uint8_t *state, uint8_t *aim_state, uint8_t *out);  // 0x406e30
extern void actor_squad_action_reset_entry(uint32_t actor_index, uint32_t check_object_index, uint8_t *state, int16_t command_list_index, uint8_t *aim_state, uint8_t *next_action_index_out);  // 0x406c50, EAX, ECX, EBX, stack
extern int32_t actor_squad_action_status_broadcast(uint32_t actor_index, int16_t command_list_index, int16_t *record);  // 0x407140
extern void actor_squad_react_to_grenade(datum_index actor_index, datum_index target_prop_index, int16_t grenade_type);  // 0x42a3a0, ESI, stack, EAX
extern void actor_squad_react_to_grenade_for_vehicle_occupants(datum_index vehicle_object_index, datum_index other_object_index);  // 0x42bd70, blam-cc: EAX, EBX
extern void actor_start_search_timer(datum_index actor_index, datum_index prop_index);  // 0x422130, EBX, EDI
extern void actor_swarm_for_each_component(uint32_t actor_index, char reset_first, actor_swarm_member_callback callback, uint32_t callback_extra, uint16_t *caller_record);  // 0x407040, EDI caller_record
extern void actor_swarm_for_each_component_thunk(uint32_t actor_index);  // 0x407240, blam-cc: EAX
extern uint8_t actor_take_danger_escape(real_vector3d *path_delta, datum_index actor_index, uint32_t escape, uint32_t extra, float distance);  // 0x40e060, EAX path_delta, stack
extern uint8_t actor_target_data_acquire(datum_index actor_index, datum_index object_index, datum_index owner_reference, datum_index pair_reference);  // 0x41f7d0
extern uint32_t actor_target_data_release(datum_index target_prop_index, uint32_t actor_index, uint8_t *out_conflict_flag);  // 0x41b980
extern void actor_target_evaluate_squad_link(uint32_t actor_index, datum_index object_cursor, int16_t *candidates_a, int16_t *candidates_b);  // 0x41e320, this module
extern uint8_t actor_target_get_backup_priority(datum_index target_prop_index);  // 0x420e50, this module
extern uint16_t actor_target_get_priority_class(datum_index actor_index, datum_index target_prop_index);  // 0x41be10, not yet rewritten
extern void actor_target_get_relationship_object(datum_index target_prop_index);  // 0x41f3a0, this module,
extern uint8_t actor_target_has_conflicting_neighbor(datum_index actor_index, datum_index target_prop_index);  // 0x41f410, EAX, stack
extern uint16_t actor_target_hearing_check(void *record, int16_t stance, datum_index actor_index, void *target_ref, int16_t gate, real_point3d *listener_position);  // 0x41c030, stack, EAX, ECX, BX, ESI
extern uint8_t actor_target_is_close_and_recognized(datum_index object_index, uint32_t param_2, datum_index actor_index);  // 0x42f480
extern uint8_t actor_target_is_visible_or_object_count_ok(datum_index actor_index, int16_t kind);  // 0x40f700, EAX, stack
extern void actor_target_mark_engaged(datum_index target_prop_index, datum_index actor_index, uint8_t mark_engaged);  // 0x41fa80, EAX, EBX, stack
extern void actor_target_relationship_think(datum_index actor_index);  // 0x41abd0
extern void actor_target_reset_combat_flags(datum_index target_prop_index, datum_index actor_index, uint32_t unused, uint8_t already_noticed);  // 0x41baf0, ECX, stack
extern void actor_target_reset_seen_flags(datum_index actor_index);  // 0x41f9d0, EAX
extern void actor_target_reset_shot_counters(datum_index actor_index);  // 0x41fa20, EAX
extern uint8_t actor_target_update_active_flag(datum_index actor_index, datum_index target_prop_index);  // 0x41fc60, EAX, EDI
extern uint8_t actor_targets_share_descriptor(datum_index actor_a, datum_index actor_b);  // 0x40e380, EAX, ECX
extern uint8_t actor_toggle_active_state(uint8_t activate, datum_index actor_index);  // 0x4277c0, blam-cc: AL, EDI
extern uint8_t actor_try_grenade_evasion(datum_index actor_index, uint8_t allow_pain_reaction, uint8_t use_alt_base);  // 0x40c530, EAX, stack
extern void actor_unlink_prop(datum_index actor_index, datum_index prop_to_remove);  // 0x43ea20, EAX, EDI
extern void actor_unlink_unit(datum_index actor_index);  // 0x427bc0
extern void actor_update_activation_state(datum_index actor_index);  // 0x429160
extern void actor_update_aim_wander(datum_index actor_index);  // 0x40fcb0
extern void actor_update_awareness_level(datum_index actor_index);  // 0x420290, this module, EAX -> actor_index
extern uint8_t actor_update_combat_behavior(datum_index actor_index, uint8_t param_1, uint8_t param_2);  // 0x40d610, EDI
extern void actor_update_crouch_state(datum_index actor_index);  // 0x4213b0
extern uint8_t actor_update_danger_avoidance(datum_index actor_index);  // 0x40c040
extern void actor_update_facing_change_timer(datum_index actor_index);  // 0x423670, EAX
extern void actor_update_firing_state(datum_index actor_index);  // 0x40e7b0
extern char actor_update_grenade_and_morale_reactions(uint32_t actor_index);  // 0x40b920, EAX
extern void actor_update_grenade_eligibility_state(datum_index actor_index);  // 0x42f370
extern uint8_t actor_update_grenade_throw_decision(datum_index actor_index);  // 0x40b770, EDI
extern void actor_update_idle_stagger(datum_index actor_index);  // 0x429430, in this rewrite range, not yet written when this file was authored
extern void actor_update_look_target(datum_index actor_index);  // 0x415480
extern uint8_t actor_update_melee_combat_action(datum_index actor_index);  // 0x40cdf0, stack
extern uint8_t actor_update_special_mode(datum_index actor_index);  // 0x40d820, EAX
extern uint8_t actor_update_squad_link_state(datum_index actor_index);  // 0x429270
extern void actor_update_swarm_component_position(datum_index component_index, datum_index unit_index);  // 0x428130, already rewritten in this module
extern void actor_update_target_combat_status(datum_index actor_index);  // 0x4200d0, this module, EAX -> actor_index
extern void actor_update_target_lead_position(datum_index actor_index);  // 0x429570, EAX -> actor_index
extern uint8_t actor_validate_grenade_ally_candidate(datum_index candidate_actor, uint8_t caller_type_flag);  // 0x40e4a0, ECX, BL
extern uint8_t actor_validate_grenade_impact_point(datum_index actor_index, real_point3d *candidate_point);  // 0x410710, EAX, EDI
extern uint8_t actor_vehicle_not_recently_left(datum_index actor_index, datum_index vehicle_index);  // 0x40ac30, EAX, stack
extern void actors_initialize(void);  // 0x426710
extern int32_t ai_actor_get_activity_stage(datum_index actor_index);  // 0x435680, this batch
extern void ai_actor_link_to_unassigned_list(datum_index actor_index);  // 0x436940, EAX
extern uint32_t ai_actor_type_get_morale_grade(int16_t actor_type_index, uint8_t *command_reference);  // 0x434ed0, AX, EDX
extern void ai_actor_unlink_from_unassigned_list(datum_index actor_index);  // 0x436990, EDI -> actor_index
extern void ai_alert_actors_in_grenade_radius(datum_index source_unit_index, int16_t stimulus, int16_t gate);  // 0x42a0e0
extern void ai_broadcast_communication_event(int16_t gate, real_point3d *point, int32_t source_object, int16_t event_type, int16_t unused);  // 0x429fc0, EAX, ECX, stack
extern void ai_category_matches_wildcard(int16_t category, int16_t other_category);  // 0x433ba0, blam-cc: stack, AX
extern void ai_communication_gate_line_played(int16_t event_id, ai_communication_record *record, datum_index object_index);  // 0x42e970, CX, EDX, stack
extern void ai_communication_initialize(void);  // 0x42cf20, not in this rewrite range
extern int16_t ai_communication_line_fade_multiplier(uint32_t unit_index, int16_t priority, int16_t extra_delay, uint8_t follow_fallback, uint8_t apply_fade, float *volume, int32_t *chain_value, int16_t *dialogue_index, int16_t line_class);  // 0x42f8c0, stack, EAX, ECX, BX
extern void ai_communication_play_event_line(datum_index object_index, int16_t event_id, uint8_t force, datum_index explicit_speaker_actor_index, uint32_t *event_record);  // 0x42eee0
extern void ai_communication_record_line_played(datum_index object_index, int16_t tier, int16_t communication_line_id, int16_t conversation_line_id);  // 0x42f9e0, EAX + stack
extern void ai_communication_reset(void);  // 0x42d230, not in this rewrite range (resets communication timestamp tables)
extern uint8_t ai_conversation_activate(int16_t conversation_definition_index, uint8_t allow_eviction);  // 0x4307c0, AX, stack
extern uint8_t ai_conversation_activate_next_participant(datum_index instance_handle);  // 0x431d10, EAX
extern void ai_conversation_clear_object_references(datum_index object_index, uint8_t force_full_scan);  // 0x430d30
extern void ai_conversation_clear_participant(datum_index actor_index);  // 0x430c70, UNSURE signature, not in this rewrite range
extern uint8_t ai_conversation_current_line_is_ready(datum_index instance_handle);  // 0x431e70, EAX
extern int32_t ai_conversation_get_run_to_player_range(ai_conversation_range_lookup *out, uint32_t conversation_index);  // 0x402cf0, EDX, ESI
extern int32_t ai_conversation_get_status(int16_t conversation_definition_index);  // 0x430830, stack
extern int16_t ai_conversation_get_unknown_48(int16_t conversation_definition_index);  // 0x430960, BX
extern void ai_conversation_mark_all(int16_t conversation_definition_index);  // 0x430a20, blam-cc: SI
extern datum_index ai_conversation_new(int16_t conversation_definition_index, uint8_t allow_eviction);  // 0x431590, this batch
extern void ai_conversation_stop(datum_index instance_handle, uint8_t reason_a, uint8_t reason_b);  // 0x430ea0
extern void ai_conversation_stop_all(int16_t conversation_definition_index);  // 0x4309c0, blam-cc: SI
extern void ai_conversation_update(void);  // 0x430a70, UNSURE signature, not in this rewrite range
extern int16_t ai_count_actors_in_mode9_group(int32_t group_id);  // 0x433e20, stack
extern void ai_dispatch_queued_order(ai_queued_order *order, datum_index prop_index, datum_index actor_index);  // 0x42f840, ECX, EDX, stack
extern uint8_t ai_drift_zone_bias(datum_index encounter_index, int16_t squad_offset, float bias);
extern int32_t ai_encounter_record_recent_zone(datum_index encounter_index, int16_t zone_id);  // 0x437820, blam-cc: EAX, SI
extern void ai_encounter_stamp_team_from_unit(datum_index encounter_index, datum_index unit_index);  // 0x436710, EAX, ECX
extern void ai_get_difficulty_request(int16_t request_code, uint8_t *out_flag_a, uint8_t *out_flag_b, float *out_value);
extern void ai_initialize_for_new_map(void);  // 0x42a7c0, ai module
extern uint8_t ai_insert_scored_candidate_pair(ai_scored_candidate *list, datum_index handle, float score, datum_index payload, datum_index key);  // 0x4383f0
extern void ai_mark_recognized_objects_for_reaction(int16_t team_a, int16_t team_b, uint8_t status);  // 0x42ba80
extern uint8_t ai_navigate_around_obstacles(path_find_context *context, int16_t count, path_find_waypoint *waypoints, int16_t *out_count, path_find_waypoint *out_waypoints, uint8_t *out_valid);  // 0x43be90, stack
extern void ai_notify_actors_of_encounter_state_change(int16_t team_a, int16_t team_b, uint8_t active, uint8_t clear_secondary);  // 0x42b940
extern void ai_object_attention_remove(datum_index object_index);  // 0x435990, EAX
extern void ai_object_list_clear_orders_with_weapon(datum_index object_list_header_handle);  // 0x432ad0, blam-cc: ECX
extern void ai_object_list_detach_actors_from_encounters(datum_index object_list_header_handle);  // 0x435260, EAX
extern void ai_object_list_initialize_shield_stun_thresholds(datum_index object_list_header_handle, float override_max_body_vitality, float override_max_shield_vitality);  // 0x561ab0, blam-cc: ECX list, stack body, shield
extern int16_t ai_object_list_max_flee_grade(datum_index object_list_header_handle);  // 0x434f20, blam-cc: EAX
extern void ai_object_list_remap_units_and_children(datum_index object_list_header, uint32_t packed_reference, char notify);  // 0x433a70, ECX list, EBX reference
extern void ai_object_list_reset_or_wake_awareness(datum_index object_list_header_handle, char flag);  // 0x434590, EAX, stack
extern void ai_object_list_respawn_members(datum_index object_list_header_handle, uint32_t packed_reference);  // 0x432e80, blam-cc: EAX, EBX
extern void ai_object_list_set_unit_flag_400(datum_index object_list_header_handle, char flag);  // 0x4347b0, EAX, stack
extern void ai_object_list_set_unit_flag_800(datum_index object_list_header_handle, char flag);  // 0x4348c0, EAX, stack
extern void ai_object_list_set_unit_flag_800000(datum_index object_list_header_handle, char flag);  // 0x561d50, EAX, stack
extern void ai_object_list_spawn_members(datum_index object_list_header_handle, uint32_t packed_reference);  // 0x432a40, blam-cc: EAX, EDI
extern void ai_object_list_update_vitality_fractions(datum_index object_list_header_handle, float body_delta, float shield_delta);  // 0x561cb0, blam-cc: EAX, stack
extern void ai_object_process_nearby_actors(uint32_t ai_reference, datum_index vehicle_index, char *seat_name, char allow_boarding_actors);  // 0x433cc0, EAX ai reference, stack (vehicle, seat name, allow)
extern int16_t ai_pick_weighted_candidate(ai_scored_candidate *table, ai_scored_candidate *out_entry);  // 0x438480, blam-cc: EBX -> table
extern void ai_platoon_range_clear_unknown_00(uint32_t packed_reference);  // 0x433200, EAX
extern uint8_t ai_platoon_range_has_available(uint32_t packed_reference);  // 0x433180, blam-cc: EAX
extern void ai_platoon_range_set_unknown_00(uint32_t packed_reference);  // 0x433270, blam-cc: EAX
extern void ai_platoon_range_set_unknown_01(uint32_t packed_reference);  // 0x4332e0, blam-cc: EAX
extern void ai_platoon_range_set_unknown_02(uint32_t packed_reference, char flag);  // 0x433350, EAX, stack
extern void ai_process_vehicle_entry_queue(void);  // 0x42bf90
extern void ai_propagate_communication_reaction(datum_index object_index, ai_communication_order *order);  // 0x42e9c0
extern uint8_t ai_pursuit_check_object(datum_index object_index, datum_index encounter_index, int16_t type, int32_t min_last_tick, char create_if_missing, int16_t *out_count, uint32_t *out_last_tick);
extern uint8_t ai_pursuit_note_object(datum_index object_index, datum_index encounter_index, int16_t type, int32_t min_last_tick);  // 0x436b10, EDX, stack, CX, EAX
extern void ai_recompute_all_relationship_flags(void);  // 0x42bbb0, outside this rewrite's range, UNSURE signature
extern void ai_reference_activate_squads(uint32_t packed_reference);  // 0x432b80, stack
extern void ai_reference_actor_iterator_init_cursor(int32_t encounter_index, datum_index *cursor);  // 0x4369f0, EAX, ECX
extern datum_index ai_reference_build_object_list(uint32_t packed_reference);  // 0x432740, stack
extern void ai_reference_clear_search_target(uint32_t packed_reference);  // 0x434c80, blam-cc: EAX
extern void ai_reference_detach_actors_from_encounters(uint32_t packed_reference);  // 0x4351c0, blam-cc: EAX
extern void ai_reference_expand_to_platoon_range(uint32_t packed_reference, ai_reference_platoon_range *out_range);  // 0x432420, this batch
extern void ai_reference_face_starting_location(uint32_t packed_reference, uint8_t idle_only);  // 0x4349d0, EAX, stack
extern void ai_reference_flee_if_ready(uint32_t packed_reference, uint32_t readiness_param);  // 0x434d90, blam-cc: EAX, EBX
extern void ai_reference_for_each_squad(uint32_t packed_reference);  // 0x432f50, blam-cc: EAX
extern uint32_t ai_reference_get_stat_pair(uint32_t packed_reference, int16_t stat_kind, int32_t *out_member_count, uint32_t *out_extra);  // 0x432f90, blam-cc: EAX, EDI, stack
extern void ai_reference_invoke_squad_callback_406f80(uint32_t packed_reference);  // 0x434e60, blam-cc: EAX
extern void ai_reference_mark_squads_unknown_11(uint32_t packed_reference);  // 0x432f10, blam-cc: EAX
extern int16_t ai_reference_max_activity_stage(uint32_t packed_reference);  // 0x435700, EAX
extern void ai_reference_notify_actors(uint32_t packed_reference, uint8_t flag);  // 0x432bd0, blam-cc: EAX, BL
extern void ai_reference_notify_squad_index(uint32_t packed_reference);  // 0x432c20, stack
extern uint8_t ai_reference_parse(char *reference_string, Scenario *scenario, uint32_t *out_packed_reference);
extern void ai_reference_refill_grenades(uint32_t packed_reference);  // 0x434af0, EAX
extern void ai_reference_reset_or_wake_awareness(uint32_t packed_reference, char flag);  // 0x434500, blam-cc: EAX, stack
extern int32_t ai_reference_resolve_squad_datum(uint32_t packed_reference);  // 0x432c80, stack
extern void ai_reference_respawn_all_players(uint32_t packed_reference);  // 0x432d90, ESI
extern void ai_reference_respawn_member(uint32_t packed_reference, datum_index unit_index);  // 0x432df0, this batch
extern void ai_reference_respawn_placed_members(uint32_t packed_reference, uint32_t respawn_reference);
extern void ai_reference_set_combat_alert_flag(uint32_t packed_reference, uint8_t new_flag);  // 0x435af0, blam-cc: EAX, CL
extern void ai_reference_set_search_target_area(uint32_t packed_reference);  // 0x434d00, blam-cc: EAX
extern void ai_reference_set_search_target_point(uint32_t packed_reference, uint32_t reference_value);
extern void ai_reference_set_squads_unknown_14(uint32_t packed_reference, char flag);  // 0x435bc0, EAX, stack
extern void ai_reference_set_unknown_1cb(uint32_t packed_reference, char flag);  // 0x434d40, blam-cc: EAX, stack
extern void ai_reference_spawn_starting_location_object(datum_index unit_index, uint32_t packed_reference);  // 0x4328c0, this batch
extern void ai_reference_squad_iterator_new(uint32_t packed_reference, ai_reference_squad_iterator *out_iterator);  // 0x4324f0, this batch
extern encounter_squad_state *ai_reference_squad_iterator_next(ai_reference_squad_iterator *iterator);  // 0x4325b0, this batch
extern void ai_reference_squad_set_unknown_10(uint32_t packed_reference, uint8_t value);  // 0x435ab0, EAX, BL
extern void ai_reference_units_exit_vehicles(uint32_t packed_reference);  // 0x433ea0, EAX
extern void ai_refresh_unit_stimulus_and_alert(datum_index object_index, int16_t priority, int16_t stimulus_value);  // 0x42c2a0, EDX, BX, DI (post-fire cue)
extern void ai_release_actors_and_swarms(void);  // 0x428ea0
extern void ai_release_actors_filtered(datum_index encounter_index, int32_t platoon_index, int32_t squad_index, uint8_t is_dead);  // 0x42ab00, EAX, EDI, stack, BL
extern void ai_reset_all_actors_perception(void);  // 0x429080
extern void ai_reset_for_new_map(void);  // 0x42a840
extern uint8_t ai_search_append_obstacle(ai_search_obstacle_list *list, uint16_t flags, uint32_t object_index, real_point2d *position, float radius);  // 0x43c4b0, EDX list, ESI position, stack
extern uint8_t ai_search_choose_shorter_corner(real_point2d *p, real_point2d *corner_a, real_point2d *q, real_point2d *corner_b, real_point2d *r, real_point2d *out_point);  // 0x43d240, ECX, EBX, EDX, stack
extern void ai_search_compute_point_tangents(ai_search_obstacle_list *list, int16_t point_index, real_point2d *position, real_vector2d *edge_neg, float radius, real_vector2d *out_a, real *out_b);  // 0x43c9a0, ECX, AX, EDX, ESI, stack
extern void ai_search_context_init(ai_search_context *context, uint8_t unknown_04, uint32_t unknown_00, ai_search_obstacle_list *obstacles, real_point2d *origin, uint32_t unknown_0c, real_point2d *position, int32_t surface_index, uint32_t unknown_18, uint8_t unknown_29, uint8_t unknown_2a);  // 0x43b790
extern uint8_t ai_search_evaluate_edge_cost(void *context, uint8_t ignore_permission, ai_search_obstacle_list *obstacle_list, int16_t exclude_index, real_point2d *point, int32_t start_surface_index, float distance, float base_cost, uint8_t skip_direct, uint8_t apply_offset, uint8_t require_unflagged, ai_search_edge_result *out_result, real_vector2d *direction);  // 0x43b830, EBX direction, stack
extern void ai_search_expand_point_neighbors(ai_search_context *context, int16_t node_index, int16_t start_point_id);  // 0x43ba60, stack, DX
extern void ai_search_find_circle_portal_crossing(real_point2d *center, real_point2d *portal, real_point2d *out_point, real_point2d *fallback_reference, float radius);  // 0x43d100, ECX, EDX, ESI, EDI, stack
extern void ai_search_find_circle_tangent_point(real_point2d *center, real_point2d *target, real_point2d *out_point, float radius, uint8_t side);  // 0x43cf60, ECX, EDX, ESI, stack
extern int16_t ai_search_find_covering_point(ai_search_obstacle_list *list, real_point2d *position, int16_t exclude_index, float extra_radius);  // 0x43c890
extern uint8_t ai_search_find_nearest_visible_point(ai_search_obstacle_list *list, int16_t exclude_index, real_point2d *origin, real_vector2d *direction, float radius, float max_distance, uint8_t require_unflagged, ai_search_nearest_point_result *out_result);
extern void ai_search_flood_fill_group(ai_search_obstacle_list *list, float radius, uint32_t *out_bitmask, int16_t start_index);  // 0x43ca40
extern void ai_search_gather_obstacles(ai_search_obstacle_list *list, real_point3d *center, float radius, real_vector3d *direction, uint32_t self_object_a, uint32_t self_object_b);  // 0x43c510, stack
extern void ai_search_heap_sift_down(ai_search_context *context, int16_t index);  // 0x43b4d0, ECX, DX
extern void ai_search_heap_sift_up(ai_search_context *context, int16_t index);  // 0x43b450, EDX context, CX index
extern void ai_search_partition_into_groups(ai_search_obstacle_list *list, float radius);  // 0x43cb60, ESI, stack
extern uint8_t ai_search_run(ai_search_context *context, uint8_t unknown_04, ai_search_obstacle_list *obstacles, uint32_t unknown_00, real_point2d *position, int32_t surface_index, real_point2d *origin, uint32_t unknown_18, uint8_t unknown_29, uint8_t unknown_2a);  // 0x43be20, ESI, EDX, ECX, EAX, stack
extern uint8_t ai_search_step(ai_search_context *context);  // 0x43bcb0, EAX
extern int32_t ai_select_communication_target(uint32_t param_a, uint32_t param_b, int16_t line_id, int16_t sub_id, float *out_weight);  // 0x42ec90
extern int32_t ai_squad_find_best_matching_member(uint32_t packed_reference, int16_t requested_squad_index, uint8_t *requested_actor_data, uint8_t *requested_actor_variant_data, char match_by_index);  // 0x4333d0, this batch
extern int16_t ai_squad_resolve_actor_type(ScenarioSquad *squad);  // 0x4374a0, blam-cc: ECX -> squad
extern void ai_squads_merge(uint32_t source_reference, uint32_t target_encounter_index, char notify, char is_platoon_merge);  // 0x433590, blam-cc: EDX, stack
extern void ai_starting_location_derive_placement_flags(datum_index encounter_index, int16_t starting_location_index, uint8_t *out_a, int16_t *out_b, uint8_t *out_c, int16_t *out_d, int16_t *out_edx, int16_t *out_esi);  // 0x436d40, EAX, stack, EDX, ESI
extern int ai_target_distance_qsort_compare(void *record_a, void *record_b);  // 0x41d7a0, this module
extern void ai_tick_dispatcher(void);  // UNSURE module
extern void ai_unit_clear_actor_vocalization(datum_index unit_index);  // 0x435a50, blam-cc: EAX
extern void ai_unit_create_actor(datum_index actor_variant_tag, datum_index unit_index);  // 0x435420, blam-cc: EAX, stack
extern void ai_unit_dispatch_actor_event_d(datum_index unit_index, int32_t unused);  // 0x435a00, blam-cc: EAX, ECX
extern void ai_unit_flee_if_ready(datum_index unit_index, uint32_t readiness_param);  // 0x434df0, blam-cc: ECX, stack
extern void ai_unit_remap_actor_to_squad(datum_index unit_index, uint32_t packed_reference, char notify);  // 0x433970, this batch
extern void ai_unit_set_actor_unknown_0a(datum_index unit_index, uint8_t value);  // 0x435540, blam-cc: EAX, stack
extern void ai_unit_set_squad_reference(datum_index object_index, uint32_t packed_reference);  // 0x435750, stack
extern int32_t ai_weighted_random_index(int16_t weight_offset, void *base, int16_t stride, uint16_t count, uint32_t *exclude_mask);  // 0x432100, EDX, stack
extern void encounter_add_actor(int16_t squad_index, datum_index actor_index, datum_index encounter_index, uint8_t keep_team);  // 0x436770, DX, stack
extern void encounter_advance_grenade_timers(datum_index encounter_index);  // 0x438db0
extern void encounter_build_firing_position_claims(datum_index encounter_index, datum_index *out_claims);  // 0x4360d0, EAX, EBX
extern void encounter_choose_vocalizations(datum_index encounter_index);  // 0x438580
extern void encounter_deactivate(datum_index encounter_index);  // 0x437870, EAX
extern void encounter_decay_squad_spawn_delays(datum_index encounter_index);  // 0x4392f0
extern int32_t encounter_definition_find_platoon_index_by_name(ScenarioEncounter *encounter_definition, char *name);  // 0x4322c0, this batch
extern int32_t encounter_definition_find_squad_index_by_name(ScenarioEncounter *encounter_definition, char *name);  // 0x432260, this batch
extern uint8_t encounter_evaluate_platoon_condition(datum_index encounter_index, const ai_platoon_condition *condition);  // 0x439f20, EAX, EDI
extern void encounter_evaluate_support_needs(datum_index encounter_index, datum_index self_actor_index, int16_t mode, uint8_t phase, uint8_t *out_crowded, uint8_t *out_flanked, uint8_t *out_a, uint8_t *out_b, uint8_t *out_reachable_a, uint8_t *out_reachable_b, uint8_t *out_any);  // 0x436dc0, EAX, stack
extern void encounter_gather_occupied_clusters(datum_index encounter_index, uint32_t *out_clusters, uint8_t record_per_actor, uint32_t *other_clusters);  // 0x436190
extern void encounter_new(int16_t *squad_cursor, ScenarioEncounter *definition, int16_t *platoon_cursor);  // 0x437060, blam-cc: EAX -> squad_cursor, EBX -> definition, stack -> platoon_cursor
extern void encounter_process_squad_reinforcements(datum_index encounter_index);  // 0x4390a0
extern void encounter_propagate_platoon_state_to_actors(datum_index encounter_index);  // 0x439d80
extern void encounter_recompute_morale(datum_index encounter_index);  // 0x437940
extern void encounter_redistribute_squads_toward_targets(datum_index encounter_index);  // 0x4394a0
extern void encounter_release_stale_props(datum_index encounter_index);  // 0x4382b0
extern void encounter_remove_actor(datum_index actor_index, uint8_t skip_counters);  // 0x436620, blam-cc: EAX -> actor_index, stack -> skip_counters
extern void encounter_set_team(datum_index encounter_index, int16_t team);  // 0x435b30, blam-cc: EAX, CX
extern void encounter_squad_clear_spawn_delay(datum_index encounter_index, int16_t squad_index);  // 0x439270, ECX, EDX
extern void encounter_squad_reset_starting_location_mask(datum_index encounter_index, int16_t squad_index);  // 0x436f90, blam-cc: EAX -> encounter_index, ECX -> squad_index
extern uint8_t encounter_squad_spawn_actor(datum_index encounter_index, int16_t squad_index, uint32_t unit_type_index, uint32_t unused);  // 0x438e20, four stack arguments (0x43769b..0x4376a0: encounter, squad, type, 0)
extern uint32_t encounter_squad_spawn_reinforcement(datum_index encounter_index, int16_t squad_index);  // 0x438f60, ECX, AX
extern void encounter_update_platoon_defending_flag(datum_index encounter_index);  // 0x4393b0
extern void encounters_initialize(void);  // 0x435c00, not in this rewrite range
extern void encounters_note_hostile_object(datum_index object_index);  // 0x435f90, EAX (0x42b92b: EAX = self_object_index, tail jump)
extern void encounters_recompute_dirty(void);  // 0x435f00
extern void encounters_reset(void);  // 0x435cb0, not in this rewrite range
extern void encounters_spawn_initial(void);  // UNSURE module
extern void encounters_update(void);  // 0x435e00, UNSURE signature, not in this rewrite range
extern void encounters_update_activation(void);  // 0x437e20
extern datum_index object_find_nearest_squad_member(datum_index actor_index, void *reference, datum_index exclude_index, char stamp_group);  // 0x41c2c0, this batch
extern uint8_t path_find_compute_heuristic(path_find_context *context, uint32_t vertex_id, real_point3d *point, float *out_distance, float *out_secondary, real_vector3d *out_direction);  // 0x43a310, EDI, EAX, stack
extern uint8_t path_find_find_unobstructed_ancestor(path_find_context *context, uint32_t vertex_id, real_point3d *point, uint8_t *out_used_start, real_point3d *out_position);  // 0x43a220, ECX, EAX, stack
extern int16_t path_find_gather_adjacent_edges(void *map, int32_t vertex_id, path_find_adjacent_edge *out_edges);  // 0x43b1c0, EAX map, stack
extern int16_t path_find_hash_lookup_vertex(path_find_context *context, uint32_t vertex_id);  // 0x43b2b0, EDX, ESI
extern void path_find_heap_push(path_find_context *context, int16_t node, int16_t key);  // 0x43b0f0
extern void path_find_heap_sift_down(path_find_context *context, int16_t index);  // 0x43b010, EAX, ECX
extern void path_find_heap_sift_up(path_find_context *context, int16_t index);  // 0x43af70
extern uint8_t path_find_heights_are_close(ScenarioStructureBSP *structure_bsp, real_point2d *point, int32_t surface_a, int32_t surface_b);  // 0x43d910; EAX structure_bsp, EDX point, ECX surface_a, stack surface_b
extern uint8_t path_find_push_start_node(path_find_context *context);  // 0x43a760, ESI
extern uint8_t path_find_reconstruct_path(path_find_context *context, uint8_t *out_reachable);  // 0x43a4d0, not yet rewritten, EBX -> context
extern uint8_t path_find_run(path_find_context *context);  // 0x43a8b0, EAX
extern float path_find_score_avoidance_penalty(path_find_context *context, const real_point3d *segment_start, const real_point3d *segment_end, float *out_distance);  // 0x43b3b0, EBX, ECX, EDX, stack
extern void path_find_set_goal(path_find_context *context, const real_point3d *position, uint32_t goal_vertex_id, float goal_cost);  // 0x43a730, not yet rewritten, EAX -> context, ECX -> destination
extern void path_find_simplify_waypoints(path_find_context *context, int16_t count, path_find_waypoint *waypoints, int16_t *out_count, path_find_waypoint *out_waypoints, uint8_t *out_valid);  // 0x43cc00, stack
extern uint8_t path_find_test_direct_reachability(const real_point3d *point_a, const real_point3d *point_b, real_point3d *out_position, void *context, uint8_t *out_success);  // 0x43a0a0, EAX, ECX, ESI, stack
extern uint8_t path_find_test_segment_unobstructed(void *map, real_point3d *point_a, uint8_t ignore_permission, int32_t surface_a, real_point3d *point_b, int32_t surface_b, float radius, uint8_t flags, path_find_boundary_crossing *out_result);  // 0x43de90, EBX map, EAX point A, stack
extern uint8_t path_find_trace_cluster_boundary(void *map, int32_t edge_index, real_point2d *origin, float radius, uint8_t side, uint8_t ignore_permission, real_point2d *out_point);  // 0x43d4b0, ECX map, EAX edge, stack
extern uint8_t path_find_trace_cluster_boundary_from_vertex(void *context, uint8_t ignore_permission, real_point2d *point, int32_t start_index, real_vector2d *direction, float max_distance, path_find_boundary_trace_result *out);
extern float path_find_vertex_distance(ScenarioStructureBSP *structure_bsp, int32_t surface, real_point3d *point_a, real_point3d *out_point);  // 0x43b130; blam-cc: EAX structure_bsp, ECX surface, stack point_a, out_point
extern uint8_t projectile_get_aiming_vector(real_point3d *target, real *speed_in, Projectile *tag, real_point3d *origin, void *unused_param_3, real *max_time, real *max_speed_override, uint8_t use_high_arc, real_vector3d *out_direction, real *out_speed, real *out_time_or_fraction, real *out_range_or_length, uint8_t *out_used_straight_line);
extern uint8_t projectile_solve_ballistic_arc(real_point3d *target, real_point3d *origin, real speed_limit, real gravity_scale, real *max_time, uint8_t use_high_arc, real_vector3d *out_direction, real *max_speed_override, real *out_speed, real *out_time_of_flight, real *out_range, real *out_half_gravity_term, real *out_horizontal_speed);  // 0x4beb30, EAX, ECX, ESI, EDI, stack
extern uint8_t projectile_solve_straight_line(real_point3d *target, real_point3d *origin, real speed, real *out_time_of_flight, real_vector3d *out_direction, real *out_speed_echo, real *out_length);  // 0x4bee20, this module (same batch)
extern int32_t scenario_find_encounter_index_by_name(Scenario *scenario, char *name);  // 0x432200, this batch
extern void squad_members_assign_team_and_request_order(uint32_t packed_reference, int16_t value);  // 0x435590, blam-cc: EAX, SI
extern void squad_members_request_order(uint32_t packed_reference, int16_t order_code);  // 0x435630, blam-cc: EAX, SI
extern int16_t squad_pick_random_starting_location(datum_index encounter_index, int16_t squad_index);  // 0x437220, blam-cc: EAX -> squad_index, ECX -> encounter_index
extern datum_index squad_recent_object_get_or_create(datum_index encounter_index, int16_t type, int32_t min_last_tick, char create_if_missing);  // 0x436c60, this batch
extern void squad_recent_object_list_clear(datum_index encounter_index);  // 0x436c10
extern void swarm_add_component(datum_index component_index, uint32_t unit_index, datum_index swarm_index);  // 0x4279a0
extern void unit_get_move_speed_for_range(datum_index actor_index, float param_a, float param_b, float param_dist, float *out_a, float *out_b);  // 0x41bed0, EAX, stack

#endif
