// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/bitmaps/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_BITMAPS_H
#define FN_BITMAPS_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "bitmaps.h"
#include "game.h"
#include "interface.h"
#include "saved_games.h"

extern uint32_t bitmap_data_calculate_mip_dimension(BitmapData *bitmap, int32_t mip_level);  // 0x43fbb0, UNSURE signature
extern uint32_t bitmap_data_calculate_mip_level_byte_size(BitmapData *bitmap, int32_t mip_level);  // 0x43fcb0, UNSURE signature
extern uint32_t bitmap_data_calculate_mip_row_byte_size(BitmapData *bitmap, int32_t mip_level);  // 0x43fce0, UNSURE signature
extern uint32_t bitmap_data_calculate_pixel_data_size(BitmapData *bitmap);  // 0x43fb70, this module (src/bitmaps)
extern uint32_t bitmap_data_depth_valid_for_type(int32_t depth, BitmapDataType_t type);  // 0x43fe30, this module
extern void *bitmap_data_get_cube_map_pixel_address(BitmapData *bitmap, int32_t mip_level, int16_t x, int16_t y, int16_t face);  // 0x43fa90, this module
extern void *bitmap_data_get_pixel_address(BitmapData *bitmap, int32_t mip_level);  // 0x43fb20, UNSURE signature
extern void *bitmap_data_get_volume_pixel_address(BitmapData *bitmap_data, int16_t x, int16_t y, int16_t z, int16_t mip_level);  // 0x43f990, this module
extern uint8_t bitmap_data_verify(BitmapData *bitmap, uint8_t require_runtime);  // 0x43fd30, this module (src/bitmaps)
extern void color_565_unpack_to_rgb888(uint16_t *packed, ColorARGBInt *out);  // 0x43ff80, this module
extern void color_argb_int_to_real(ColorARGB *out, uint32_t packed);  // 0x43f5a0
extern ColorRGB *color_hsv_to_rgb(real_hsv_color *hsv, ColorRGB *color);  // 0x43f460, this batch
extern void color_rgb_int_to_real(ColorRGB *out, uint32_t packed);  // 0x43f630, blam-cc: EAX out, ECX packed
extern real_hsv_color *color_rgb_to_hsv(ColorRGB *color, real_hsv_color *hsv);  // 0x43f330, this batch
extern char * targa_export(BitmapData *bitmap, file_reference_record *destination);  // 0x43fe60, foreign

#endif
