// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/cseries/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_CSERIES_H
#define FN_CSERIES_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "cseries.h"

extern void function_do_nothing(void);  // 0x44ad80
extern void md5_digest_to_hex(const uint8_t *digest, char *out);  // 0x619c90
extern void profile_path_initialize(void);  // 0x00449390
extern void qsort_dword_array(uint32_t count, int32_t *elements, qsort_dword_compare_proc compare);  // 0x449590, EAX count, ECX elements, stack compare
extern void qsort_dword_array_shortsort(int32_t *last, int32_t *first, qsort_dword_compare_proc compare);
extern void tea_decrypt_block(uint32_t *block, const uint32_t *key);  // 0x6182b0
extern void tea_decrypt_buffer(int32_t length, uint8_t *data, const uint32_t *key);  // 0x618350, TEA over 8-byte blocks
extern void tea_encrypt_block(uint32_t *block, const uint32_t *key);  // 0x6181c0

#endif
