// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/camera/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_CAMERA_H
#define FN_CAMERA_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "camera.h"

extern void camera_control(uint8_t enable);  // 0x445cc0, this module
extern datum_index camera_dead_find_next_teammate(datum_index reference_player, datum_index current_target, uint8_t require_same_team);  // this module
extern uint8_t camera_dead_player_has_teammate(datum_index reference_player);  // this module
extern void camera_debug_compute_pov(director_camera_data *data, camera_input *input, observer_command *command);  // 0x444d50, this module (the scripted camera pov)
extern void camera_debug_load_from_file(void);  // 0x445940
extern void camera_debug_save_to_file(void);  // 0x445880
extern void camera_debug_start(int16_t camera_point_index, int16_t ticks, datum_index relative_object);
extern void camera_first_person_compute_pov(director_camera_data *data, camera_input *input, observer_command *command);  // 0x446d60, this module
extern int16_t camera_get_seat_camera_state(datum_index unit, int16_t *out_state);  // 0x445b20, this module
extern void camera_initialize(void);  // 0x445580, this module
extern void camera_input_axes_update(int16_t local_player_index, uint32_t key_bits, float zoom);  // 0x446170, this module
extern uint8_t camera_is_local_player_default_first_person(void);  // 0x4455f0, foreign (camera)
extern void camera_script_set_animation(datum_index animation_tag, char *name);  // 0x444b30, blam-cc: EBX tag, stack name
extern void camera_third_person_compute_pov(director_camera_data *data, camera_input *input, observer_command *command);  // 0x447370, this module
extern void camera_track_compute_pov(director_camera_data *data, camera_input *input, observer_command *command);  // this module
extern void camera_update(float dt);  // 0x445640, this module
extern dead_camera_data *dead_camera_new(dead_camera_data *this, int16_t local_player_index, datum_index unit);  // this module
extern uint8_t director_build_camera_input(int16_t local_player_index, camera_input *input);  // 0x445f90, this module;
extern void director_choose_gameplay_camera(int16_t local_player_index, uint8_t reset);  // 0x445dc0, this module
extern void director_set_flying_camera(int16_t local_player_index, uint8_t force);  // 0x445f40, this module
extern void director_update_seat_camera(int16_t local_player_index, uint8_t force);  // 0x445c00, this module
extern void editor_camera_compute_pov(director_camera_data *data, camera_input *input, observer_command *command);  // 0x446e90, this module
extern void editor_camera_set_position_and_direction(editor_camera_data *out, Vector3D *direction, Point3D *position);  // 0x446e30, this module
extern void first_person_camera_apply_weapon_offset(real_point3d *position, datum_index unit, real_vector3d *aiming_direction);  // 0x447290, EAX, EBX, ESI
extern void first_person_camera_command_for_unit(datum_index unit, observer_command *command);  // 0x446d30, this module
extern void first_person_camera_deterministic(Point3D *out_position, datum_index unit, Vector3D *out_direction);  // 0x446a90, EAX, ECX, stack
extern void first_person_camera_for_unit_and_vector(observer_command *command, Vector3D *vector, datum_index unit);  // 0x446b70, this module
extern void first_person_camera_track_offset(unit_camera_properties *properties, float angle, Vector3D *out);
extern void flying_camera_attach_to_object(datum_index object_index);  // 0x446470, this module
extern void flying_camera_compute_pov(director_camera_data *data, camera_input *input, observer_command *command);  // 0x4464f0, this module
extern void flying_camera_initialize(editor_camera_data *data, int16_t local_player_index);  // 0x446350, this module
extern void observer_advance(int16_t local_player_index);  // 0x447b50, this module
extern void observer_avoid_collision(real_vector3d *forward, real_point3d *position, real_vector3d *up, float *distance, float radius_scale);
extern uint8_t observer_collision_test_ray(real_point3d *origin, uint8_t use_alternate_mask, real_point3d *target, float *out_fraction);
extern void observer_commit(int16_t local_player_index);  // 0x448900, this module
extern void observer_compute_remaining_offset(float *target, float *current, float *out);
extern void observer_compute_spline_coefficients(int16_t local_player_index);
extern void observer_evaluate_spline_acceleration(int16_t local_player_index);
extern void observer_evaluate_spline_value_and_orthonormalize(int16_t local_player_index);
extern void observer_evaluate_spline_velocity(int16_t local_player_index);
extern observer_camera *observer_get_camera(int16_t player_index);  // 0x4479a0, CX
extern void observer_new(observer *this);  // 0x447740, this module
extern void observer_set_command(int16_t local_player_index);  // 0x447ab0, this module
extern void observer_update(float dt, uint8_t add_bob);  // 0x447880, foreign (camera)
extern uint8_t real_is_valid(float value);  // 0x4476c0
extern double scalar_catmull_rom_interpolate(float value0, float value1, float value2, float value3, float time0, float dt, float time);
extern unit_camera_properties *unit_get_camera_properties(datum_index unit);
extern void vector3d_rotate_basis_by_axis_angle(Vector3D *axis_angle, Vector3D *forward, Vector3D *up);

#endif
