// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/cutscene/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_CUTSCENE_H
#define FN_CUTSCENE_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "units.h"
#include "cutscene.h"

extern void chimera__letterbox(void);  // 0x4499c0
extern void cutscene_start(void);  // 0x449720
extern void cutscene_stop(void);  // 0x449eb0
extern void cutscene_title_queue(int16_t title_index, float delay_seconds);  // 0x449960
extern void recorded_animation_angle_to_vector(real_vector3d *out, recorded_animation_angles *angles);  // 0x44a190, this batch
extern void recorded_animation_apply_char_difference(recorded_animation_angles *angles, recorded_animation_char_difference *delta);  // 0x44a110, this batch
extern void recorded_animation_apply_short_difference(recorded_animation_angles *angles, recorded_animation_short_difference *delta);  // 0x44a150, this batch
extern int16_t recorded_animation_find_by_name(const char *name, Scenario *scenario);  // 0x449f80, EBX, ESI
extern recorded_animation *recorded_animation_find_by_object(datum_index unit_index, datum_index *out_index);  // 0x44ad20, this module (same batch); blam-cc: EBX unit_index, stack out_index
extern uint8_t recorded_animation_object_is_playing(datum_index unit_index);  // 0x44acc0, ESI
extern uint8_t recorded_animation_start(datum_index unit_index, int16_t scenario_animation_index, uint16_t extra_flags);
extern void recorded_animations_update(void);  // 0x44aa90, UNSURE module
extern void unit_control_data_unpack(unit_control_data *control, uint8_t **cursor, uint8_t version);  // 0x449fd0, this module

#endif
