// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/cache/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_CACHE_H
#define FN_CACHE_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "cache.h"

extern void cache_file_download_finish(void);  // this module, 0x443540
extern int16_t cache_file_download_poll(float *progress_out);  // blam-cc: stack; this module, 0x442720
extern void cache_file_download_stop(void);  // 0x443510
extern uint8_t cache_file_exists(char *name, cache_file_header *header_out);  // blam-cc: EAX, ESI; 0x442bb0
extern int16_t cache_file_find_oldest_slot(cache_file_slot_category slot_category, int32_t required_size);  // blam-cc: EAX, stack; 0x4437b0
extern datum_index cache_file_load(char *path);  // 0x442290, cache module, blam-cc: EAX -> path
extern uint8_t cache_file_open_by_name(char *name, uint8_t report_fatal_error);  // blam-cc: EAX,
extern void cache_file_slot_read_header(int32_t slot_index);  // blam-cc: EAX; this module, 0x4435e0
extern void cache_file_unload(void);  // 0x442430
extern void cache_io_completion_routine(uint32_t error_code, uint32_t bytes_transferred, cache_io_request *overlapped);
extern void cache_io_read_file_ex_retry(void *read_file_ex, void *file, void *buffer, cache_io_request *request, uint32_t size, uint32_t offset, void *completion_routine);
extern void __stdcall cache_io_request_completion_routine(uint32_t error_code, uint32_t bytes_transferred, cache_io_request *overlapped);  // 0x443ae0
extern int16_t cache_io_request_find_free_slot(void);  // this module, 0x443270
extern uint32_t cache_io_thread_proc_async(void *unused);  // this module, cache_io_thread_proc_async.c
extern uint32_t cache_io_thread_proc_sync(void *unused);  // this module, cache_io_thread_proc_sync.c
extern void cache_io_thread_start(void);  // this module, 0x4438d0
extern void cache_io_wait_all_requests(void);  // this module, 0x4432b0
extern uint8_t cache_io_wait_for_flag(uint8_t *flag);
extern void cache_reserve_map_memory(void);  // 0x4448d0
extern void data_file_close(void);  // 0x00442a50
extern uint8_t data_file_read_data_block(data_file *file);  // blam-cc: ESI; this module, 0x443ba0
extern int32_t data_file_read_header(data_file *file, int32_t expected_file_id);  // blam-cc:
extern uint8_t data_file_read_offset_table(data_file *file);  // blam-cc: EDI; this module, 0x443c20
extern void model_dispose_vertex_buffers(void);  // Ghidra: FUN_00442f00, misattributed name
extern void model_load_vertex_buffers(cache_file_tag_header *header);  // blam-cc: header in EAX.
extern void sound_cache_decode_permutation(SoundPermutation *permutation);  // 0x443d60, this module
extern void sound_cache_dispose(void);  // this module, 0x443f30
extern void sound_cache_dump_to_file(void);  // this module, sound_cache_dump_to_file.c
extern void sound_cache_new(void);  // 0x443ca0
extern void sound_cache_page_allocate(SoundPermutation *permutation, uint8_t priority);  // blam-cc:
extern void sound_cache_release_unused(void);  // 0x443fd0
extern void sound_permutation_release_page(SoundPermutation *permutation);  // this module, sound_permutation_release_page.c
extern void sound_tag_touch_permutations(TagID tag);  // this module, sound_tag_touch_permutations.c
extern void structure_bsp_dispose(ScenarioBSP *bsp);  // src/cache/structure_bsp_dispose.c, 0x442520
extern void structure_bsp_dispose_material_vertex_buffers( ScenarioStructureBSPCompiledHeader *compiled_header);  // blam-cc: EAX // blam-cc: EAX;
extern uint32_t structure_bsp_load(ScenarioBSP *bsp);  // src/cache/structure_bsp_load.c, 0x4424b0
extern void structure_bsp_load_material_vertex_buffers( ScenarioStructureBSPCompiledHeader *compiled_header);  // blam-cc: EAX // Ghidra: FUN_00443020; this batch
extern datum_index tag_iterator_next(tag_iterator *iterator);  // blam-cc: ESI; this module, 0x4425d0
extern void texture_cache_new(void);  // 0x4444d0
extern uint32_t texture_cache_page_allocate(BitmapData *bitmap, uint8_t priority);  // this module, texture_cache_page_allocate.c

#endif
