// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/dialogs/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_DIALOGS_H
#define FN_DIALOGS_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "dialogs.h"

extern int32_t dialog_box_show_localized(dialog_window_proc_fn dialog_proc, void *module, const char *template_name, void *parent_window);  // 0x57e1f0, EBX proc, ESI module; the template is MAKEINTRESOURCE(id) // 0x57e1f0, blam-cc: dialog_proc in EBX, module
extern int32_t dialog_static_hyperlink_install(void *control);  // 0x57e4c0, this module; blam-cc: ESI -> control
extern int32_t __stdcall dialog_static_hyperlink_parent_proc(void *window, uint32_t message, uint32_t wparam, int32_t lparam);  // 0x57e2a0, not a Ghidra function
extern int32_t __stdcall dialog_static_hyperlink_subclass_proc(void *window, uint32_t message, uint32_t wparam, int32_t lparam);  // 0x57e350, this module
extern int32_t __stdcall fatal_error_dialog_proc(void *dialog, uint32_t message, uint32_t wparam, int32_t lparam);  // 0x57e5a0, the DLGPROC for this dialog; a

#endif
