// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/devices/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_DEVICES_H
#define FN_DEVICES_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "objects.h"
#include "devices.h"

extern void device_control_touched(uint32_t object_index);  // 0x44c090, EAX
extern uint8_t device_frontfacing(uint32_t device_index, real_vector3d *forward);  // 0x44c130
extern uint8_t device_group_set_value(uint16_t group_index, float value);  // 0x44bd70, this batch
extern void device_group_set_value_immediate(uint16_t group_index, float value);  // 0x44bea0
extern void device_groups_initialize(void);  // 0x44c220 (tail call)
extern void device_machine_melee_attacked(uint32_t object_index);  // 0x44b5d0, ECX
extern void device_play_state_change_effect(uint32_t object_index, TagID tag_id);  // 0x44c1a0 (out of range)

#endif
