// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/effects/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_EFFECTS_H
#define FN_EFFECTS_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "objects.h"
#include "projectiles.h"
#include "cache.h"
#include "effects.h"

extern void ambient_color_for_marker(int16_t weather_row, real_point3d *position, uint8_t flags, real_vector3d *out);  // 0x53f940, blam-cc: AX, stack, stack, EDI
extern uint8_t ambient_color_marker_visible(bsp_leaf_reference *location, real_point3d *position, real_vector3d *out, uint32_t filter_flags);  // 0x53f860, blam-cc: EAX, stack
extern void ambient_color_randomize(void);  // UNSURE module
extern void contrail_advance(datum_index contrail_handle, uint8_t detach, real delta_time);  // 0x44ca60, EDI, stack
extern void contrail_age_points(datum_index contrail_handle, real delta_time);  // 0x44d470,
extern void contrail_generate_points(datum_index contrail_handle, int16_t point_count, uint8_t force);  // 0x44d020, this module;
extern datum_index contrail_new(int16_t attachment_index, datum_index object_index, datum_index definition_index);
extern void contrail_next_sequence(contrail *self);  // 0x44ced0, this module; blam-cc: EAX -> self
extern int16_t contrail_points_due(datum_index contrail_handle, real elapsed_time);  // 0x44cf80,
extern void contrail_update(real delta_time);  // 0x44cb50
extern void contrails_initialize(void);  // 0x44c8b0
extern void decal_build_projection(real_matrix4x3 *placement, real *box, decal_projection *out);
extern void decal_clear_flags(uint8_t clear_object_attached);  // 0x44e220, BL
extern void decal_delete(datum_index decal_index);  // 0x44e3c0, blam-cc: EDX -> decal_index
extern void decal_flood_surfaces(decal_projection *projection, decal_flood_accumulator *accumulator, int32_t surface_index, uint8_t is_first_surface, real radius, int16_t decal_type, int32_t *surface_queue, uint16_t *surface_queue_count, int32_t *fallback_queue, uint16_t *fallback_queue_count);  // 0x44e730
extern void decal_link(int16_t cluster_index, datum_index decal_index, int16_t layer);  // 0x44dd30,
extern datum_index decal_new(datum_index requested_handle, int16_t cluster_index, int16_t layer, datum_index insert_before, uint8_t object_attached);  // 0x44dd90, EAX requested_handle
extern void decal_place(datum_index decal_tag_index, collision_result *placement, real_vector3d *direction, real radius_scale, uint8_t object_attached, int16_t sequence_index);  // 0x44edc0
extern void decal_spawn_for_response(datum_index response_tag_index, uint8_t deterministic, real_point3d *origin, real_vector3d *direction, real radius, int32_t marker_index);  // 0x44ece0, ESI, BL, ECX, stack
extern void decal_update_fade(datum_index decal_index);  // 0x44dc30, this module; blam-cc: EAX -> decal_index
extern void decals_initialize(void);  // 0x44df90
extern void decals_update_fade(void);  // 0x44e2b0
extern void effect_event_apply(effect *self, EffectPart *part, effect_location_marker *marker, real_vector3d *up, real_vector3d *forward, real_point3d *position, real scale);
extern uint8_t effect_first_person_screen_timer_active(datum_index object_index);  // 0x450680, ECX object_index
extern void effect_marker_from_node_table(int16_t entry_index, uint8_t *context, object_marker *out);  // 0x451930, AX, EBX, stack
extern effect_location_marker *effect_marker_next(effect *self, datum_index *marker, int32_t mode);  // 0x453180, this module
extern int32_t effect_marker_node_table_resolver(uint32_t object_index, const char *location, object_marker *out, uint32_t max_count);  // 0x451850, a thunk/label Ghidra did not split out;
extern datum_index effect_new(datum_index definition_index, datum_index creator_object_index, uint8_t force_create);  // 0x451500, this module
extern datum_index effect_new_at_texture_coordinate(datum_index definition_index, datum_index object_index, int16_t change_color_index, int16_t u, int16_t v);  // 0x4506d0, EAX, EDX, CX, stack
extern real effect_property_random_value(uint8_t bit_index, effect *self, uint32_t a_bitset, uint32_t b_bitset, random_seed *seed, real base_min, real base_max);  // 0x451290, this module
extern void effect_random_direction_from_table(real_point3d *out);  // 0x4505e0, this module
extern void effect_random_direction_vector(random_seed *seed, real_point3d *out, real min, real max, effect *self, uint32_t a_bitset, uint32_t b_bitset);  // 0x451450, stack, EBX self, ESI a, EDI b
extern real effect_random_scaled_range(uint32_t flags, real scale, real base_min, real base_max, uint8_t bit_index);  // 0x44c840, this module; blam-cc: EDX -> flags, stack -> the rest
extern void effect_random_velocity_vector(effect *self, random_seed *seed, real_vector3d *direction, real_vector3d *out_direction, real_vector3d *out_velocity, real min, real max, real angle_max, uint32_t a_bitset, uint8_t b_bitset);  // 0x451310, EAX self
extern void effect_set_placement(effect *self, const ColorRGB *color, const effect_tint_source *tint_source, real a_scale, real b_scale);  // 0x451600, this module
extern void effect_spawn_particles(effect *self);  // 0x451f90
extern void effect_start_event(datum_index effect_handle, int16_t event_index);  // 0x451660,
extern void effect_stop(datum_index effect_handle, uint8_t stop_immediately);  // 0x450b20, blam-cc: EAX, stack
extern void effect_update(datum_index effect_handle, real delta_time);  // 0x451a30, this module
extern void material_effects_play_at_marker(uint32_t material_effects_tag, int16_t material_type, int16_t sub_effect_index, uint32_t *location_bundle, uint32_t sound_param, real_point3d *position, real_vector3d *offset);  // 0x453490, this module
extern void object_change_color_evaluate(effect *self);  // 0x4529d0
extern uint8_t particle_advance_animation(datum_index particle_handle, real delta_time);  // 0x4560c0,
extern uint8_t particle_advance_frame(datum_index particle_handle);  // 0x456000, this module
extern real particle_current_radius(datum_index particle_handle);  // 0x4566f0, this module
extern void particle_impact(datum_index particle_handle);  // 0x456550, this module
extern void particle_impact_response_dispatch(particle *self, tag_group fourcc, datum_index definition_index, real intensity);  // 0x4565a0, EAX self, ECX fourcc, ESI definition_index, stack intensity
extern void particle_new(particle_creation_data *creation_data);  // 0x455740, this module
extern uint8_t particle_next_sequence(datum_index particle_handle);  // 0x455e60, this module
extern void particle_system_delete(datum_index handle);  // 0x453f60
extern uint8_t particle_system_new_type_states(datum_index handle);  // 0x4538b0, this module
extern void particle_system_render(datum_index particle_system_handle);  // 0x454bf0, this module
extern void particle_system_spawn(particle_system *self, int32_t type_index, float dt);  // 0x453b10, this module
extern void particle_system_update_physics_default(particle_system *system, real dt);  // 0x4552a0, this batch
extern void particle_systems_delete_all(void);  // UNSURE module
extern void particle_systems_render(void);  // 0x454b40, effects module
extern uint8_t particle_update_motion(datum_index particle_handle, real delta_time);  // 0x4561a0,
extern void particles_update(real tick_delta_time);  // UNSURE module
extern void player_effect_clear_dead_players(void);  // UNSURE module
extern void player_effect_fade_damage_indicators(int16_t local_player_index, uint32_t *out_previous_indicators);  // 0x457220, blam-cc: EAX index, EDX out
extern void player_effect_mark_damage_direction(datum_index player_index, const damage_data *dd, const real_vector3d *direction, float random_blend, float damage_amount);  // 0x456cf0, EAX, stack
extern void player_effect_mark_damage_direction_dispatch(void **context);  // 0x456ad0, EAX
extern void player_effect_random_shake_offset(real_matrix4x3 *out, real magnitude, real angle);  // 0x457280,
extern void player_effect_send_network_update(datum_index player_handle, const real_vector3d *direction, const damage_data *dd, float random_blend, float damage_amount);  // 0x456bc0, EAX, EBX, stack
extern int32_t player_weapon_locality_for_object(datum_index weapon_object_index);  // 0x453a10
extern void weather_instance_activate(datum_index definition_index, int16_t instance_index, real intensity);  // 0x457e20, this module
extern void weather_instance_adjust_count(int16_t instance_index, int16_t type_index, real target_value);  // 0x457fc0, this module
extern void weather_instance_build_render_geometry(int16_t instance_index);  // 0x458bf0, this module
extern void weather_instance_deactivate(int16_t instance_index);  // 0x457f00, this module
extern void weather_instance_update(int16_t instance_index);  // 0x458420, this module
extern datum_index weather_particle_new(int16_t instance_index, int16_t type_index);  // 0x458070,
extern void weather_update(void);  // 0x53f5c0
extern void weather_update_local_player(void);  // 0x458a90, effects module

#endif
