// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/game/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_GAME_H
#define FN_GAME_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "game.h"
#include "objects.h"

extern uint32_t XCreateSaveGame(const uint16_t *save_game_name, const char *root_path, int32_t mode, char *out_path, uint32_t out_path_size);  // 0x551710, blam-cc: EAX save_game_name (src/game/XCreateSaveGame.c: validity_token)
extern uint32_t XDeleteSaveGame(const uint16_t *save_game_name, const char *root_path);  // 0x5519a0, blam-cc: EAX save_game_name, ECX root_path
extern uint32_t camera_observer_get_target_angles(real *out_weight_primary, real *out_weight_secondary, real *out_yaw_pitch, real *out_yaw_pitch_rate, int16_t local_player_slot);  // this batch, 0x4596f0
extern uint32_t camera_observer_get_target_id(datum_index *out_id, int16_t local_player_slot);
extern int32_t camera_observer_target_compare(const observer_target_candidate *a, const observer_target_candidate *b);  // this batch, 0x45a4a0
extern uint32_t camera_observer_update(datum_index player_index, real_point3d *observer_position, real_vector3d *fallback_facing);  // 0x4593b0, EAX, stack
extern void cheat_all_weapons(void);  // 0x45a530
extern uint32_t cheat_get_target_object_index(void);  // this batch, 0x45a7a0
extern void cheat_make_selected_object_invincible(void);  // 0x45a6c0
extern void cheat_spawn_objects_near_camera(TagDependency *tag_array, int16_t count);  // this batch, 0x45a800
extern void cheat_spawn_warthog(void);  // 0x45a5c0
extern void cheat_teleport_to_camera(void);  // 0x45a630
extern void chimera__kill_feed(datum_index recipient, int32_t hash_key, uint32_t message_type, datum_index subject, char broadcast);  // 0x460a30
extern void chimera__spectate_fp_camera_position(camera_basis_out *out, int16_t local_player_index);
extern int32_t circular_queue_count(circular_queue *queue);  // blam-cc: EDX -> queue; 0x47a230
extern uint8_t circular_queue_pop(circular_queue *queue, void **out_record);  // this batch, 0x47a200
extern real control_axis_sign(real value);  // this batch, 0x471070
extern void ctf_flag_object_clear_carrier(datum_index flag_object_index, real_point3d *position);  // 0x4666c0
extern void custom_waypoint_get_position(real_point3d *out, int16_t slot);  // 0x462230, blam-cc: EAX out, CX slot; EAX still holds out afterwards
extern uint8_t custom_waypoint_matches_filter(int32_t candidate, custom_waypoint *slot, int32_t reference_team);  // 0x4620c0, this batch
extern real distance_falloff_fraction(real value, real max_range);  // this batch, 0x459360
extern void game_dispose(void);  // 0x45acd0, foreign (game module)
extern int32_t game_engine_accumulate_simulation_ticks(float elapsed_seconds, char keep_remainder);  // this batch, 0x470b30
extern void game_engine_advance_simulation_ticks(float dt);  // 0x470bf0, foreign (game module)
extern void game_engine_allocate_tick_record(void);  // 0x470a80
extern void game_engine_animate_hill_pulse_icons(datum_index fading_player, datum_index growing_player);  // 0x46f450, blam-cc: EAX fading, ECX growing
extern void game_engine_apply_catchup_speed_boost(void);  // 0x46e310
extern void game_engine_apply_current_custom_variant(void);  // 0x463b90, this batch
extern void game_engine_apply_player_grenade_counts(uint32_t player_index);  // 0x4613c0
extern uint8_t game_engine_apply_player_interaction_message(void **context);  // 0x478f10, EAX
extern void game_engine_apply_player_join_message(void **context);  // 0x4778c0, EAX
extern void game_engine_apply_player_spawn_loadout_message(void **context);  // 0x477c70, EAX
extern uint8_t game_engine_attach_players_to_new_bsp(void);  // 0x473e90, foreign (game)
extern void game_engine_attribute_player_death(datum_index victim_unit, datum_index killer, datum_index death_object, int32_t killer_team, char credit_kills);  // 0x46ff00
extern void game_engine_begin_end_game_sequence(void);  // 0x45fd90
extern void game_engine_broadcast_kill_feed_by_relationship(uint32_t source_player, int32_t no_source_message, int32_t message_a, int32_t message_b, uint32_t subject, uint8_t broadcast);  // 0x460c10, blam-cc: BL broadcast
extern void game_engine_broadcast_kill_feed_to_team(int32_t message_type, int32_t team, uint8_t broadcast);  // 0x460ba0, blam-cc: ESI message_type, BL broadcast, stack team
extern void game_engine_build_end_game_result_text(datum_index player, wchar_t *out);  // 0x45cf30, not in this batch
extern void game_engine_build_local_player_control_input(int16_t local_player_index, real delta_time, player_control_input *out);  // this batch, 0x4710b0
extern uint8_t game_engine_build_message_text(wchar_t *out, uint32_t buffer_size, datum_index subject, uint32_t param_1, uint32_t message_type);  // 0x460890, this batch
extern void game_engine_check_bucket_scores_and_end_round(void);  // 0x46db70, this batch
extern void game_engine_cleanup_dropped_objects(void);  // 0x45f320, this batch
extern void game_engine_cleanup_stray_items(void);  // 0x468010, this batch
extern void game_engine_cleanup_stray_projectiles(void);  // 0x467f70, this build's tail call target
extern void game_engine_clear_unit_shields_when_disabled(datum_index player_handle);  // 0x45fd20, this batch
extern void game_engine_client_apply_team_assignment(void **context);  // 0x470a10, EAX
extern uint32_t game_engine_compare_score_to_others(uint32_t subject, int32_t team_mode);  // 0x463480
extern void game_engine_compute_local_player_look_vector(real_vector3d *out_forward, int16_t local_player_index);  // 0x471f40, EAX out, CX local player
extern void game_engine_compute_look_angles_from_vector(real_vector3d *facing, int16_t local_player_index);  // 0x470d80. CORRECTED by review: objdump 0x4619f1..0x4619fb
extern float game_engine_compute_time_scale(int32_t param_a, int32_t param_b);  // 0x461550, EDX, ESI
extern void game_engine_ctf_assign_flag_ids(void);  // 0x46d800, this batch
extern datum_index game_engine_ctf_create_flag_object(real_point3d *position, uint16_t name_index);  // 0x468360, blam-cc: EAX position
extern uint8_t game_engine_ctf_is_flag_eligible_for_capture(uint32_t team, int32_t flag_id);  // 0x46df30, this batch
extern void game_engine_ctf_notify_both_teams(int32_t team);  // 0x468460, blam-cc: EAX team
extern void game_engine_ctf_on_flag_captured(uint32_t flag_index);  // 0x46dde0, this batch
extern void game_engine_ctf_player_drop_flag(uint32_t player_index, datum_index flag_object_index);  // 0x4688b0, blam-cc: EAX player_index
extern void game_engine_ctf_player_touch_flag(uint32_t player_index, int32_t team);  // 0x468910, blam-cc: EAX team
extern uint8_t game_engine_ctf_point_within_team_flag_radius(float radius, int32_t team, real_point3d *point);  // 0x468990, blam-cc: EAX team, ECX point
extern void game_engine_ctf_reset_team_return_credit(uint32_t object_index);  // 0x468840, this batch
extern void game_engine_ctf_respawn_team_flag(int32_t team, real_point3d *forwarded_position, uint16_t forwarded_name_index);  // 0x468430, this batch
extern void game_engine_ctf_score_flag(uint32_t team, int32_t scenario_flag_index);  // 0x46e080, blam-cc: EAX scenario_flag_index (the first argument is a player)
extern void game_engine_digitize_control_input(player_control_input *input);  // this batch, 0x472760
extern void game_engine_dispatch_item_pickup_event(int32_t machine_id, int32_t picked_tag, int32_t param_2);  // 0x45f850, this batch; UNSURE real args at call site
extern void game_engine_end_game_sequence_stage1(void);  // 0x4670c0, this batch
extern void game_engine_end_game_sequence_stage2(void);  // 0x4670f0, this batch
extern void game_engine_end_game_sequence_stage3(void);  // 0x467180, this batch
extern uint8_t game_engine_find_first_eligible_player_on_team(int32_t team);  // 0x45c9e0
extern int32_t game_engine_find_nearest_unused_type4_location(int32_t *excluded_indices, int32_t excluded_count, real_point3d *reference_point);  // 0x46d520, blam-cc: EDI excluded_count, EBX reference_point
extern int32_t game_engine_find_one_valid_starting_location(int16_t type, int16_t team, real_point3d *origin, float max_horizontal_dist, float max_height_delta);  // 0x461180, blam-cc: ECX type, EDX team, EBX origin
extern void game_engine_find_player_by_name(char *source_name);  // 0x473430, blam-cc: EBX
extern datum_index game_engine_find_player_holding_object(datum_index target_object);  // 0x468b50, this batch
extern void game_engine_flag_local_player_units(void);  // 0x45b590, this module
extern void game_engine_free_custom_variant_cache(void);  // 0x4638b0, this batch
extern void game_engine_gather_team_score_totals(uint32_t out_count[2], uint32_t out_score[2], int32_t filter_value);  // this batch, 0x470690
extern int32_t game_engine_get_current_tick(void);  // 0x470cd0
extern wchar_t *game_engine_get_default_multiplayer_string(int16_t string_index);  // 0x45ce90, this batch
extern real game_engine_get_max_look_pitch(int16_t local_player_index);  // 0x471f90, game module
extern int32_t game_engine_get_multiplayer_sound_duration_ticks(int32_t sound_index);  // 0x46bde0, this batch
extern wchar_t *game_engine_get_multiplayer_text_list(uint32_t rank);  // 0x4633f0
extern void game_engine_get_player_scoreboard_entry(datum_index player_handle, scoreboard_entry *out);  // 0x45cee0, this batch
extern int32_t game_engine_get_scoreboard_place(datum_index player, int32_t mode, uint8_t invert_low_stat);  // 0x45d440, this module; blam-cc: EDI -> player, EAX -> mode,
extern uint8_t game_engine_get_teams_enabled(void);  // 0x462bf0; returns a bool in AL
extern int32_t game_engine_get_time_remaining(void);  // 0x45cab0, this batch
extern uint8_t game_engine_get_variant_by_name(const char *name, game_variant *out);
extern void game_engine_init_player_look_state_from_object(datum_index unit, int16_t local_player_index);  // 0x470e80
extern void game_engine_init_tick_record_for_mode(void);  // 0x470ae0, foreign (game module)
extern void game_engine_initialize_for_new_game(void);  // this batch, 0x45c370
extern uint8_t game_engine_is_inactive(void);  // 0x461610
extern uint8_t game_engine_is_valid_team_player(uint32_t identifier);  // 0x466b60
extern void game_engine_koth_alt_scorer_tick(uint32_t player_index);  // 0x46c230, this batch
extern void game_engine_koth_build_hill_boundary(void);  // 0x46a240
extern void game_engine_koth_find_marker_position(real_point3d *out_position, int16_t type_filter);  // 0x46beb0, this batch
extern uint8_t game_engine_koth_player_in_hill_bounds(uint32_t player_index);  // 0x46aa60, this batch
extern void game_engine_koth_relocate_hill_marker(int32_t ball_index);  // 0x46bfe0, blam-cc: ESI ball_index
extern void game_engine_koth_relocate_object_hill(uint32_t object_index);  // 0x46c1a0, blam-cc: EAX object_index
extern void game_engine_koth_reset_hill_marker_history(void);  // 0x46b250
extern void game_engine_koth_submit_hill_marker_geometry(uint32_t tag_handle_as_uint, uint32_t *position_override, uint32_t *orientation_override, uint32_t param_4, uint32_t param_5, float *vertex_source);  // 0x46b2f0, this batch
extern void game_engine_koth_update_hill_occupancy_state(void);  // 0x46acb0
extern void game_engine_koth_update_occupant_table(uint32_t index);  // 0x46c320, this batch
extern uint8_t game_engine_local_player_score_is_nonpositive(datum_index player_index);  // 0x466340, blam-cc: EAX player_index; UNSURE: a per player HUD visibility test
extern uint8_t game_engine_location_blocked_by_vehicle(real_point3d *point);  // 0x461e60, this
extern void game_engine_maybe_render_post_game(void);  // 0x461a80
extern void game_engine_multiplayer_sound_queue_tick(void);  // 0x46bd80
extern int32_t game_engine_multiplayer_ui_state_id(void);  // 0x4655d0, this batch
extern void game_engine_notify_item_expired(datum_index object_index);  // 0x45f510, this batch
extern void game_engine_notify_player_interaction(uint32_t primary_key, uint32_t edi_key, uint32_t mode, int32_t interaction_type, int32_t interaction_seat, int32_t secondary_key);  // 0x478ff0, ECX, EDI, stack
extern uint8_t game_engine_notify_weapon_ready_state_change(datum_index unit_index, datum_index weapon_index);  // 0x462000, UNSURE signature
extern void game_engine_on_player_death(datum_index killer, datum_index death_object, datum_index victim, char is_suicide);  // 0x460200
extern uint32_t game_engine_pack_object_flags_or_passthrough(uint32_t input);  // 0x462bd0, this batch
extern int32_t game_engine_pick_random_recent_location(int32_t exclude_value, int32_t fallback);  // 0x46a1b0, blam-cc: ECX fallback
extern void game_engine_play_multiplayer_sound(int32_t sound_index, datum_index recipient_player, uint8_t broadcast);  // 0x46bd00, this batch
extern void game_engine_player_changed_object(uint32_t param);  // 0x45c570, this module (already
extern uint8_t game_engine_player_is_eliminated(uint32_t player_index);  // 0x460f30, this batch
extern uint8_t game_engine_player_ready_to_respawn(uint32_t player_index);  // 0x460f70
extern uint8_t game_engine_player_respawn_priority_gate(uint32_t player_index);  // 0x463100, blam-cc: EDX player_index
extern void game_engine_player_select_random_target(datum_index player_or_all);  // 0x46f1a0
extern uint8_t game_engine_players_ready_for_bsp_switch(void);  // 0x45c750
extern uint8_t game_engine_players_ready_for_bsp_switch_strict(void);  // 0x45c830, this batch
extern void game_engine_players_update_client(void);  // 0x474590, UNSURE module (client path)
extern void game_engine_players_update_server(void);  // 0x4740a0, UNSURE module (host/offline path)
extern void game_engine_post_rasterize_post_game(void);  // 0x45d700
extern void game_engine_queue_multiplayer_sound(int32_t sound_index, datum_index player, uint8_t broadcast);  // 0x46be40, blam-cc: ESI sound, EDI player, stack broadcast
extern void game_engine_queue_status_sound_message(int32_t machine_index);  // 0x46bbd0, this batch
extern void game_engine_rasterize_in_game_score(datum_index subject_player, float opacity);  // 0x465690, blam-cc: stack -> subject_player, opacity
extern float game_engine_rate_location_ally_bonus(uint32_t self_index, real_point3d *point);  // 0x461c60, this batch
extern float game_engine_rate_location_crowding(uint32_t self_index, real_point3d *point);  // 0x461ad0, this batch
extern real game_engine_rate_player_starting_location(ScenarioPlayerStartingLocation *location, datum_index player_handle);  // 0x461d90, this module; blam-cc: EAX -> location,
extern void game_engine_reattach_player_unit_unused(uint32_t player_index, uint32_t target_object, void *local_offset);  // 0x475270
extern uint32_t game_engine_remap_placement_by_type(uint32_t handle);  // 0x4630b0, EAX handle; returns it, or the remapped tag
extern void game_engine_reset_all_players(void);  // 0x45b8b0, foreign (game module)
extern void game_engine_reset_all_unit_grenade_counts(void);  // 0x467de0
extern void game_engine_reset_player_look_state(void);  // 0x470de0
extern void game_engine_reset_player_profile_stats(void);  // 0x468150, this batch
extern void game_engine_reset_respawns_and_cleanup_bipeds(void);  // 0x467e60
extern void game_engine_reset_round_objects(void);  // 0x468260, UNSURE
extern void game_engine_reset_vehicles_or_race_cleanup(void);  // 0x4681a0, this batch
extern uint32_t game_engine_resolve_multiplayer_placement(uint32_t handle);  // 0x462c30, this batch
extern int32_t game_engine_resolve_netgame_flag_role(uint32_t handle);  // 0x462df0, this batch
extern void game_engine_resolve_player_team(uint32_t player_index);  // 0x4611b0
extern void game_engine_scan_netgame_flags_noop(int16_t needle);  // 0x4637c0, this batch
extern uint8_t game_engine_scores_tracked_individually(void);  // 0x4635e0, UNSURE name: here it gates the motion sensor
extern void game_engine_send_end_game_notification(uint32_t reason);  // blam-cc: EAX reason; // 0x4671d0, not in this batch
extern void game_engine_send_player_profile_update(void *has_payload, void *profile_tail, int32_t target);  // 0x467010, this batch
extern void game_engine_send_round_reset_message(void);  // 0x4682c0, UNSURE
extern void game_engine_send_team_allegiance_message(char broadcast);  // 0x4704d0
extern void game_engine_server_update_player_positions(void);  // UNSURE module
extern void game_engine_spawn_player_starting_loadout(uint32_t starting_equipment_index, int32_t *frag_count, int32_t *plasma_count);  // 0x4611f0, this batch
extern void game_engine_sync_variant_defaults(void);  // 0x45fc80, UNSURE
extern uint8_t game_engine_team_close_game_check(int32_t side, int32_t filter_value);  // this batch, 0x470790
extern uint8_t game_engine_team_has_scoring_capacity(int32_t team);  // 0x46e250
extern void game_engine_tick(void);  // 0x45ff30, this module
extern void game_engine_touch_multiplayer_predicted_resources(void);  // UNSURE module
extern void game_engine_update_custom_waypoint_navpoints(int16_t local_player_slot);  // 0x462a90, blam-cc: BX local_player_slot
extern void game_engine_update_end_game_sequence(float delta_time);  // 0x45fdf0, foreign (game)
extern void game_engine_update_item_scale_and_pickup(void);  // 0x45f560, this batch
extern void game_engine_update_lead_change_state(void **envelope, uint8_t *message);  // 0x470810
extern void game_engine_update_local_player_look(int16_t local_player_index, real yaw_delta, real pitch_delta);  // 0x472160, AX, stack
extern void game_engine_update_netgame_equipment(char force_respawn);  // 0x45f9f0
extern void game_engine_validate_scenario_placements_noop(void);  // UNSURE module
extern uint32_t game_engine_variant_add_to_history(char *name, game_variant *options, char *path);  // 0x463980, this batch
extern game_variant *game_engine_variant_defaults_stalker(game_variant *out);  // 0x467450, not in
extern void game_initialize(void);  // 0x45a9c0, foreign (game)
extern uint32_t game_no_player_is_dead(void);  // 0x45bbe0
extern uint32_t game_safe_to_pause(void);  // 0x45b9e0
extern void game_simulate_tick(uint32_t predict_pass);  // 0x45b780
extern void game_start_new_map(void);  // 0x45b050, foreign (game module)
extern void game_stop_current_map(void);  // 0x45b370, foreign (game module)
extern void game_time_format_minutes_seconds_ascii(uint32_t ticks, uint32_t count, char *dest);  // 0x466600, blam-cc: ECX ticks
extern void game_unload_map(void);  // 0x45afb0, foreign (game module)
extern void game_variant_sanitize_options(game_variant *variant);  // 0x466730, this module
extern void hud_draw_scoreboard_row_text(int16_t row, wchar_t *text, int16_t column);  // 0x45d670, this batch
extern void hud_draw_teammate_nameplate(datum_index player_handle);  // 0x45e520, this batch
extern void hud_draw_teammate_nameplate_text(wchar_t *text, int32_t value);  // 0x461f20, not in this batch
extern int32_t hud_draw_world_relative_text(hud_world_text_params *params, int16_t row, wchar_t *text, uint8_t highlighted);  // 0x4653f0, this module; blam-cc: EAX -> params,
extern datum_index hud_find_nearby_teammate_for_nameplate(datum_index player_handle);  // 0x45e340, this batch
extern uint8_t hud_nameplate_candidate_filter(uint32_t object_index, void *player_handle);  // 0x45e2e0
extern void hud_update_teammate_nameplate_fade(void);  // 0x45f220, UNSURE
extern int32_t local_player_find_free_slot_index(void);  // 0x473730, foreign (game module)
extern int32_t local_player_get_zoom_level(int16_t local_player_index);  // 0x472740, src/game; blam-cc: CX -> local_player_index
extern void main_switch_structure_bsp(void);  // 0x4749a0, UNSURE module
extern uint8_t netgame_equipment_game_type_matches(int16_t *types, int32_t count, int32_t current_engine_index);  // 0x45f7c0, this batch
extern void network_queue_destroy(circular_queue *queue);  // 0x47a090, this batch's neighbor,
extern void network_server_broadcast_object_type_changes(void);  // 0x45b680, this module
extern void object_placement_data_set_change_colors(real *color, object_placement_data *placement);  // 0x477670, EAX, ECX
extern uint8_t player_add_kill_streak(int32_t slot, int16_t amount, uint32_t player_handle);  // this batch, 0x479ba0
extern void player_check_assassination_opportunity(uint32_t player_index, uint32_t candidate_object);  // 0x478770, this module. CORRECTED by review for the same
extern void player_check_vehicle_boarding_interaction(uint32_t player_index, uint32_t candidate_object);  // 0x4788a0, this
extern void player_check_vehicle_boarding_interaction_lightweight(uint32_t player_index, uint32_t candidate_object);  // 0x478c40, this
extern void player_check_vehicle_interaction(uint32_t player_index, uint32_t candidate_object);  // this batch, 0x478600
extern uint8_t player_customization_slot_set(uint8_t *base, uint8_t new_value, int8_t key);  // this batch, 0x4705f0
extern uint8_t player_find_placement_position(uint32_t player_index, datum_index target_object, real_point3d *point);  // 0x4757b0
extern uint8_t player_is_busy_with_interaction(uint32_t candidate_object, uint32_t unit_or_player_index);  // 0x478820, ESI, EDI
extern void player_notify_kill_streak_update(int32_t slot, int16_t amount, uint32_t player_handle);  // this batch,
extern int16_t player_pick_random_starting_location(datum_index player_handle);  // 0x4776d0, stack
extern void player_profile_cache_initialize(void);  // 0x466c20
extern void player_set_pending_interaction_action(int16_t priority_type, int16_t seat, uint32_t player_index, uint32_t candidate_object);  // this batch, 0x478e00
extern void player_set_team_by_color(uint8_t new_team, int8_t target_team_index_desired);  // this batch, 0x470630
extern uint8_t player_swap_to_weapon(uint32_t player_index, datum_index target_weapon);  // 0x479240, EAX player, stack weapon
extern void player_trigger_full_health_effect(uint32_t player_index);  // this batch, 0x479890
extern void player_trigger_kill_streak_effect(uint32_t player_index);  // this batch, 0x4797d0
extern void player_trigger_shield_recharge_effect(uint32_t player_index);  // this batch, 0x479710
extern uint8_t player_update_queue_pop_current(player_update_record *out, player_update_queue *queue);  // 0x479fb0, this module; blam-cc: EAX -> out, EBX -> queue
extern uint8_t players_any_pending_seat_or_respawn(void);  // UNSURE module: "any_player_is_in_the_air"
extern uint8_t players_any_without_unit(void);  // 0x475210
extern void players_client_catchup_on_server_updates(void);  // 0x476d40, UNSURE module
extern void players_dispose(void);  // 0x473670
extern void players_initialize(void);  // 0x4735b0
extern void players_server_catchup_on_client_updates(void);  // 0x4768c0
extern void point3d_array_project_to_xy_plane(real_point3d *source, Point2D *destination, int32_t count);  // 0x46a130, this batch (CORRECTED name)
extern void position_update_queue_create(circular_queue *queue);  // 0x47a020, blam-cc: ESI -> queue
extern uint8_t position_update_queue_find_and_remove(circular_queue *queue, int32_t target_tick, real_point3d *out);  // this module (a later batch), 0x47a100
extern uint8_t position_update_queue_push(circular_queue *queue, real x, real y, real z, int32_t tick, int32_t sequence);  // blam-cc: EBX -> queue, stack -> the rest; 0x47a0c0
extern int32_t random_advance_draws(TagReflexive *reflexive);  // 0x45f6e0, EAX reflexive: the sum of the element weights
extern real response_curve_evaluate(int16_t table_count, real x, real *table);  // this batch, 0x470fb0
extern uint8_t savegame_index_file_exists(void);  // 0x53e060, FUN_0053e060 (src/game): opens savegame_index_file for reading
extern uint32_t savegame_slot_handle_pack(uint32_t slot_index, uint32_t type_nibble, uint8_t flag_bit_30, uint8_t flag_bit_31);  // 0x53e630, FUN_0053e630 (src/game); blam-cc: EAX slot, ECX type, DL bit 30, stack byte bit 31
extern int32_t scoreboard_entry_compare(const scoreboard_entry *a, const scoreboard_entry *b);  // 0x45cbe0, this batch
extern uint32_t scoreboard_entry_compare_by_unknown_04(const scoreboard_entry *a, const scoreboard_entry *b);  // 0x45cbc0, this batch
extern int32_t tag_reflexive_pick_weighted_random_index(datum_index tag_id);  // 0x45f720, this batch
extern void team_pair_overrides_tick(void);  // 0x45bcf0, this module
extern void team_pair_table_allocate(void);  // this batch, 0x45bc30
extern void team_pair_table_init_defaults(void);  // this batch, 0x45bc80
extern wchar_t *unicode_string_list_get_string(char *path, int16_t index);  // 0x4b8d30, this module (src/game/unicode_string_list_get_string.c)
extern uint8_t unit_current_weapon_prevents_camo_depower(datum_index player_handle);  // 0x466390
extern uint8_t unit_has_must_be_readied_weapon(uint32_t player_index);  // 0x463300, blam-cc: ECX player_index
extern void unit_set_local_player_weapon_index(datum_index unit, int16_t weapon_index);  // 0x472100, EAX unit
extern void unit_update_active_camouflage_depower(datum_index player_handle);  // 0x466420, EBX
extern void update_client_dispose(void);  // this batch, 0x472fa0
extern uint32_t update_client_distribute_staged_entry(uint8_t *out);  // 0x473270, established
extern uint32_t update_client_new(void);  // 0x472f40; only AL is meaningful
extern uint32_t update_client_queue_apply_tick(player_action *out_actions, client_update_carry *out_carry);  // 0x4730d0; only AL is meaningful (see that file)
extern update_record *update_client_queue_get_slot(int32_t tick);  // this batch, 0x473500
extern void update_queues_dispose(void);  // 0x472b00
extern void update_run_catchup_ticks(int16_t tick_count);  // 0x473310, blam-cc: BX -> tick_count
extern void update_server_dispose(void);  // this batch, 0x472b70
extern void update_server_push_player_tick_history(void);  // 0x472cc0
extern void update_server_queue_get_history_entry(int32_t *out_record, int32_t *out_tick, datum_index queue_handle);
extern void update_server_queue_push_history(int16_t machine_index, int32_t tick_count, uint32_t *source, uint32_t extra);  // 0x473390, blam-cc: EAX -> machine_index, EDX -> tick_count, stack -> source, extra
extern uint32_t user_profile_signin_state_is_valid(void);  // 0x551620, foreign (game), UNSURE name
extern char *user_save_path_lookup(uint32_t user_id);  // this batch, 0x5516a0
extern int32_t user_save_path_register(uint32_t user_id, char *path);  // this batch, 0x551650
extern void value_step_toward_target(float *value, float target, float max_step);  // 0x470d40, ECX, stack
extern void vehicle_update_queue_create(circular_queue *queue);  // 0x47a250, blam-cc: ESI -> queue
extern uint8_t vehicle_update_queue_find_and_remove(circular_queue *queue, int32_t target_tick, vehicle_update_record *out);  // this module (a later batch), 0x47a2c0
extern real weapon_get_zoom_fov(int16_t zoom_table_index, int16_t magnification);  // 0x46fe10, stack, CX (difficulty value)

#endif
