// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/gamespy/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_GAMESPY_H
#define FN_GAMESPY_H

#include "tags.h"
#include "memory.h"
#include "math.h"

extern void B64Encode(char *output, const unsigned char *input, int len);
extern int IsPrivateIP(struct in_addr *addr);
extern int NTSLengthSB(const char *buf, int len);
extern int SBIsReservedKey(const char *key);
extern void SBServerFree(void *elem);
extern void *SBServerGetNext(void *server);
extern int SBServerListCount(void *slist);
extern void *SBServerListNth(void *slist, int i);
extern void SBServerSetNext(void *server, void *next);
extern char *ServerBrowserGetMyPublicIP(void *handle);  // hostname/address string
extern int gcd_init_common(int game_id);
extern void gcd_process(char *buf, int len, const struct sockaddr *from);
extern void gcd_process_auth_reply(const char *buf, int authorized);
extern void gcd_send_is_online(const char *buf, const struct sockaddr *to);
extern void gcd_send_user_count(const char *buf, const struct sockaddr *to);
extern void gcd_shutdown(void);  // outside this batch, foreign
extern void gcd_think(void);  // 0x61b7e0, foreign
extern struct hostent *getlocalhost(void);
extern void ghttpStartup(void);  // foreign, UNSURE
extern void ghttpThink(void);  // foreign, UNSURE
extern void gs_encrypt(const unsigned char *key, int key_len, unsigned char *buffer, int len);
extern int gt2StringToAddress(const char *string, unsigned int *ip, unsigned short *port);
extern void gt2_bignum_from_hex(char *hex, unsigned char *number);
extern void gt2_bignum_mul_mod(unsigned char *a, const unsigned char *b);
extern void gti2CloseConnectionHardMap(void *elem, void *client_data);
extern void gti2ClosedConnectionFree(void *elem);
extern int gti2ConnectionCompare(const void *elem1, const void *elem2);
extern int gti2ConnectionHash(const void *elem, int num_buckets);
extern void gti2FreeConnection(void *connection);
extern int gti2VerifyChallenge(const unsigned char *challenge);
extern char *ptaGetKeyValue(const char *buffer, const char *key);
extern void qr2_register_natneg_callback(void *qrec, void *callback);  // 0x615530 qr2_register_natneg_callback

#endif
