// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/hs/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_HS_H
#define FN_HS_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "hs.h"

extern char hs_add_global(datum_index node_index);  // 0x00485b60, this batch
extern char hs_add_script(datum_index node_index);  // 0x00485d50, this batch
extern void hs_allocate_script_node_table(void);  // 0x00483100, this batch
extern void hs_autocomplete_add_startup(void);  // 0x00483860, this batch (table entry only)
extern int16_t hs_autocomplete_gather(uint32_t category_mask, char **results, char *prefix, int16_t maximum_count, uint16_t gametype_mask);  // 0x483c90, blam-cc: EAX -> prefix, CX -> maximum_count, DX -> gametype_mask,
extern void hs_autocomplete_scan_candidates(char **table, int16_t end, int16_t start);  // 0x004836f0, this batch
extern void hs_autocomplete_scan_globals(TagReflexive *table, int16_t name_offset, int32_t stride);  // 0x483770
extern void hs_autocomplete_test_candidate(char *candidate);  // 0x00483690, this batch
extern char hs_call_script_by_name(char *name);  // 0x48a2d0, EAX
extern int32_t hs_coerce_value(int32_t value, hs_type_t dest_type, hs_type_t source_type);
extern void hs_compile(int32_t source_length, char *source_text, char **error_message, int32_t *error_offset);  // 0x00485770, this batch
extern char hs_compile_and_evaluate(const char *command);  // 0x484400, foreign (hs module)
extern datum_index hs_compile_expression(char *text, uint32_t length, char **error_message, char **error_offset);  // 0x00485540, this batch
extern char hs_compile_postprocess(char **error_message, int32_t *error_offset);  // 0x004858c0, this batch
extern char hs_compile_source(void);  // 0x00484090, this batch
extern void hs_damage_apply_at_location(int16_t location_index, uint32_t damage_effect);  // 0x488960, blam-cc: DX, stack
extern void hs_damage_apply_with_sound(datum_index object_index, uint32_t damage_effect);  // 0x488a40, EBX object, stack effect
extern void hs_dispose_dynamic_globals(void);  // 0x48a130, hs module
extern void hs_doc(void);  // 0x484270
extern void hs_effect_spawn_at_location(int16_t location_index, uint32_t effect);  // 0x488870, blam-cc: AX, stack
extern void hs_effect_spawn_on_marker(datum_index object_index, datum_index effect, char *marker_name);
extern void hs_enumerate_special_form_names(void);  // 0x00483840, this batch (table entry only)
extern int32_t *hs_evaluate_typed_arguments(uint32_t thread_index, int16_t parameter_count, int16_t *expected_types, char first);  // 0x48a850
extern char hs_evaluate_variadic_arguments(uint32_t thread_index, int32_t value, uint32_t *out_count, int32_t **out_values);  // this module, 0x0048ad60
extern int16_t hs_find_function_by_name(char *name);  // 0x00483520, this batch
extern hs_global_reference hs_find_global_by_name(char *name);  // 0x00483480, this batch
extern void hs_format_function_signature(int16_t function_index, char *out);  // 0x00484300, this batch
extern char hs_gametype_flag_satisfied(uint8_t bit_index, uint8_t flags);  // 0x004835b0, this batch
extern uint8_t hs_gametype_flags_applicable(uint8_t flags);  // 0x483600, blam-cc: BL -> flags
extern char hs_get_parameter_indices(char *function_name, int16_t required_count, datum_index node_index, datum_index *out_indices);  // 0x00484fb0, ECX node, EBX out
extern char *hs_global_get_name(hs_global_reference global);  // 0x00483450, this batch
extern hs_type_t hs_global_get_type(hs_global_reference global);  // 0x00483420, this batch
extern int32_t hs_global_get_value(hs_global_reference reference);  // 0x48a720
extern void hs_global_read_value(hs_global_reference reference);  // this module, 0x48aec0
extern void hs_global_write_value(hs_global_reference reference);  // 0x48b030
extern void hs_help_print_function(char *name);  // 0x4841b0, blam-cc: EDX
extern uint8_t hs_object_angle_predicate_helper(datum_index object_index, datum_index viewer_unit, float angle_degrees);  // this module, 0x4878f0
extern void hs_object_create_name_index_if_absent(int32_t name_index);  // 0x487cf0
extern void hs_object_detach_and_place_at_location(int16_t location_index, datum_index object_index, char detach_from_parent, char reorient);  // 0x487f50, blam-cc: AX, stack
extern char hs_object_hierarchy_test(datum_index object_index);  // 0x487c10, hs module
extern uint32_t hs_object_list_any_angle_match(datum_index header_index, datum_index target_object, float angle_degrees);  // 0x4879b0, blam-cc: EAX, stack
extern uint32_t hs_object_list_any_angle_match_gated(datum_index header_index, int16_t gate, float angle_degrees);  // 0x487ad0, blam-cc: EAX, BX, stack
extern datum_index hs_object_list_collect_player_units(void);  // 0x487630
extern void hs_object_list_for_each(datum_index header_index);  // 0x488740, blam-cc: EAX
extern char hs_object_list_test_trigger_volume(int32_t trigger_volume_index, datum_index header_index, char all_mode);  // 0x487820
extern void hs_object_name_cache_validate(int16_t object_name_index);  // 0x487d20
extern void hs_object_name_destroy(int32_t object_name_index);  // 0x487d90
extern void hs_object_runtime_cleanup(void);  // 0x487dd0
extern void hs_object_set_health_fraction(datum_index object_index, float fraction);  // 0x488600, blam-cc: EAX object, stack fraction
extern void hs_object_set_permutation_by_name(datum_index object_index, void *permutation_name, char *name);  // 0x488670,
extern void hs_objects_delete_by_type(uint32_t tag_id);  // 0x4887d0, blam-cc: ESI tag_id
extern char hs_parse(datum_index node_index, hs_type_t expected_type);  // 0x00486420, this batch
extern datum_index hs_parse_cond_recursive(datum_index cond_node_index, datum_index pair_index);  // 0x004848f0
extern char hs_parse_nonprimitive(datum_index node_index);  // 0x00486710, this batch
extern char hs_parse_object_name(datum_index node_index);  // 0x487230
extern char hs_parse_primitive(datum_index node_index);  // 0x00486480, this batch
extern char hs_parse_scenario_datum(datum_index node_index, int16_t name_offset, TagReflexive *array, int32_t stride);
extern char hs_parse_variable(datum_index node_index);  // 0x00486560, this batch
extern char hs_rebuild_source(void);  // 0x00483e20, this batch
extern void hs_reposition_players_outside_trigger_volume(int32_t trigger_volume_index, int32_t location_index);  // 0x487750
extern void hs_resolve_identifier_as_function_or_script(datum_index node_index);  // 0x00486680, this batch
extern void hs_runtime_initialize(void);  // 0x489e70
extern void hs_runtime_update(void);  // 0x48a1a0, hs module
extern void hs_scenario_scripts_initialize(void);  // 0x00489ef0, outside this batch's assigned range
extern int16_t hs_script_find_by_name(char *name);  // 0x004833a0, this batch
extern char hs_scripts_compile_and_link(char restore_previous);  // 0x00483190, this batch
extern void hs_scripts_free(void);  // 0x4832b0
extern void hs_scripts_reload(void);  // 0x483250
extern float *hs_sound_get_gain_reference(char *name);  // 0x488b10, blam-cc: EAX name
extern char *hs_source_buffer_append(char *text, uint32_t length);  // 0x004856f0, this batch
extern void hs_syntax_node_garbage_collect(void);  // 0x483310, below this batch's range
extern void hs_thread_evaluate_step(datum_index thread_handle);  // this module, 0x48a370
extern datum_index hs_thread_find_by_script_index(int16_t script_index);  // 0x48a960
extern datum_index hs_thread_find_by_script_name(char *name);  // this module, 0x48a9f0
extern datum_index hs_thread_new(int32_t script_index, uint8_t type);  // this module, 0x48a2f0
extern void hs_thread_pop_frame(uint32_t thread_index);
extern void hs_thread_push(datum_index node, uint32_t thread_index, void *result_address);
extern void hs_thread_restart(uint32_t thread_index);  // this module, 0x48a790
extern void hs_thread_return(int32_t value, uint32_t thread_index);  // 0x48a640, blam-cc: EAX value, ECX thread_index
extern datum_index hs_tokenize(char **cursor);  // 0x00486120, this batch
extern void hs_tokenize_nonprimitive(datum_index node_index, char **cursor);  // 0x00486290, this batch
extern void hs_tokenize_primitive(char **cursor, datum_index node_index);  // 0x004861b0, this batch
extern char hs_type_mask_is_subset(int16_t subtype_index, int16_t supertype_index);
extern char hs_types_are_compatible(hs_type_t destination_type, hs_type_t source_type);  // 0x0048ac90, outside this batch's assigned range
extern char hs_verify_source_offset(int32_t offset);  // 0x004858a0, this batch
extern datum_index object_list_get_first(datum_index header_index, object_list_iterator *iterator_out);  // 0x48b2f0
extern int32_t object_list_nth_reference(datum_index header_index, int16_t n);  // 0x488570, blam-cc: EAX, ECX
extern void object_list_reference_add(datum_index header_index, datum_index object_index);  // 0x48b2a0, src/hs
extern void object_list_reference_chain_delete(data_array *reference_array, datum_index chain_head);
extern void object_lists_dispose_empty(void);  // this module, 0x48b340
extern void object_lists_initialize(void);  // 0x48b250
extern void skip_whitespace(char **cursor);  // 0x00486350, this batch

#endif
