// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/input/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_INPUT_H
#define FN_INPUT_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "game.h"
#include "interface.h"
#include "saved_games.h"
#include "input.h"

extern void chimera__axis_text(int16_t axis_index, uint8_t direction, uint16_t *out_text);  // this module, 0x491340
extern void chimera__button_text(int16_t button_index, uint16_t *out_text);  // this module, 0x491270
extern void chimera__pov_text(int16_t pov_index, int16_t direction_index, uint16_t *out_text);  // this module, 0x4914c0
extern void control_binding_table_initialize(void);  // 0x4f3700
extern uint8_t control_binding_table_query(int32_t target, int32_t raw_id);  // 0x4f3ad0, EDX target, stack raw_id
extern void control_binding_table_register_single(int32_t target, int32_t selector, int32_t raw_id, uint32_t raw_value);  // 0x4f37d0, blam-cc: EDX -> target, EAX -> selector, EDI -> raw_id, EBX -> raw_value
extern void control_binding_table_update_a(void);  // 0x4f3890
extern void control_binding_table_update_b(void);  // 0x4f39d0
extern uint32_t control_word_extract_field(uint32_t which_word, uint32_t field_index);  // 0x4f3680, same pass
extern void hs_bind_control(const char *device_class_name, const char *input_name, const char *action_name);  // 0x48b750, blam-cc: EAX device, stack input, action
extern void hs_unbind_control(const char *device_class_name, const char *input_name);  // 0x48b8d0, blam-cc: EDI, EBX
extern void input_accumulate_axis_value(player_control_settings *settings, local_player_input_state *state, int16_t action);  // 0x0048ca10, blam-cc: EAX, ECX, DX
extern uint8_t input_accumulator_is_idle(local_player_input_state *current, local_player_input_state *previous);  // 0x0048fce0, blam-cc: ECX, EDX
extern uint8_t input_apply_control_binding(control_binding_descriptor *binding, int32_t action_index);
extern int16_t input_axis_direction_name_to_index(char *name);  // this module, 0x4911f0
extern void input_bind_capture_reset(void);  // 0x48b5f0, foreign (input module)
extern void input_bind_scan_set_active(uint8_t enable_scan);  // 0x48b6b0, blam-cc: AL
extern float input_clamp_unit_float(float value);  // 0x48c8a0
extern void input_clear_control_binding(control_binding_descriptor *binding);
extern int32_t input_device_count_by_guid(const uint32_t *guid);  // 0x491d30
extern void input_device_list_print(void);  // 0x491750
extern void input_device_release(int16_t slot_index);  // 0x491f80, ESI
extern void input_directinput_acquire_devices(void);  // this module, 0x490620
extern void input_directinput_poll_devices(void);  // 0x490760, foreign (input)
extern void input_directinput_release_devices(void);  // this module, 0x490580
extern void input_directinput_unacquire_devices(void);  // 0x4906e0
extern int32_t __stdcall input_enumerate_gamepad_callback(const di_device_instance *instance, void *reference);  // 0x491d70
extern int32_t __stdcall input_enumerate_gamepad_object_callback(const di_device_object_instance *object, void *reference);  // 0x491c50
extern void input_error_log_once(int32_t error_code, char *description, ...);  // this module, 0x492150
extern void input_game_action_update(void);  // 0x0048cca0 (body runs on through 0x48d270 to 0x48ea4f)
extern void input_get_axis_direction_name(int16_t direction_index, uint16_t *out_name);  // this module, 0x491180
extern void input_get_keyboard_key_name(int16_t key_index, uint16_t *out_name);  // this module, 0x490e30
extern void input_get_mouse_axis_name(int16_t axis_index, uint8_t direction, uint16_t *out_name);  // this module, 0x491010
extern void input_get_mouse_button_name(int16_t button_index, uint16_t *out_name);  // this module, 0x490f20
extern uint8_t input_get_mouse_button_state(int16_t button_index);  // 0x490e00
extern uint8_t input_guid_parse_ansi(input_guid *out_guid, char *ansi);  // this module, 0x491670,
extern int16_t input_joystick_axis_name_to_index(char *name, uint8_t *out_direction);  // this module, 0x4913e0, blam-cc: EAX
extern int16_t input_joystick_button_name_to_index(char *name);  // this module, 0x4912e0, blam-cc: EAX
extern int16_t input_joystick_pov_direction_name_to_index(char *name);  // this module, 0x491480,
extern int16_t input_joystick_pov_name_to_index(char *name, int16_t *out_direction);  // this module, 0x491590, blam-cc: EAX
extern void input_joystick_set_axis_scale_x(int16_t slot, float value);  // 0x48c930, blam-cc: CX, stack
extern void input_joystick_set_axis_scale_y(int16_t slot, float value);  // 0x48c9a0, blam-cc: CX, stack
extern void input_joystick_state_process(joystick_raw_state *raw, joystick_state *dest, input_device *device);  // this module, 0x491fd0, blam-cc: device in EBX
extern void input_key_block_timer_set(int16_t key, int32_t duration_ms);  // 0x490bf0, foreign (input);
extern void input_key_block_timers_expire(void);  // 0x00490ca0
extern uint8_t input_keyboard_device_create(void);  // this module, 0x4918a0 (result ignored here)
extern uint32_t input_keyboard_key_name_to_index(char *name);  // this module, 0x490ea0
extern void input_last_used_binding_set(int16_t action, int16_t device_type, int16_t device_index, int16_t input_kind, int16_t input_index, int32_t direction);  // 0x00490050
extern void input_menu_generate_events(void);  // 0x0048ec50 (see input_types_notes.md)
extern float input_mouse_acceleration_evaluate(float sensitivity, int32_t magnitude);  // 0x0048cb60
extern uint32_t input_mouse_axis_name_to_index(char *name, uint8_t *out_direction);  // this module, 0x4910c0
extern uint32_t input_mouse_button_name_to_index(char *name);  // this module, 0x490f90
extern uint8_t input_mouse_device_create(void);  // this module, 0x4919c0 (result ignored here)
extern void input_mouse_state_process(mouse_state *dest, di_mouse_state2 *raw);  // this module, 0x491bc0,
extern void input_print_bound_controls(void);  // 0x48bea0
extern uint8_t input_profile_copy_bindings_by_device(int32_t category, saved_player_profile *dst, saved_player_profile *src);  // this module, 0x490280
extern void input_queue_initialize(void);  // UNSURE module
extern void input_queue_push_event(int16_t queue_index, ui_input_event *record);  // this module, 0x492340
extern void input_queue_sample_time_update(void);  // 0x492210, UNSURE
extern uint8_t input_refresh_last_used_binding(int32_t device_class, int16_t action);
extern void input_reset_state_and_axis_configs(void);  // 0x490aa0, foreign (input module)
extern void input_scan_any_bound_input(void);  // 0x0048f8c0 (already named)
extern float input_sensitivity_to_turn_rate(float sensitivity);  // 0x48c8e0
extern uint8_t input_should_invert_look(int16_t local_player_index);  // 0x0048fd60, blam-cc: AX
extern void input_state_initialize(void);  // 0x48b3e0
extern uint32_t input_system_initialize(void);  // this module, 0x491a80 (result ignored here)
extern void input_time_base_resync(void);  // 0x48b470
extern void input_update_tick(void);  // 0x48b4b0, foreign (input)
extern void test_input_device_defaults_find(char *device_id_ansi);  // 0x490090, blam-cc: ESI (ECX loaded here)

#endif
