// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/interface/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_INTERFACE_H
#define FN_INTERFACE_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "game.h"
#include "interface.h"
#include "objects.h"
#include "items.h"

extern int32_t bitmap_group_sequence_get_bitmap_offset(datum_index bitmap_tag, int16_t sequence_index, int16_t frame_index);  // 0x4ab630, blam-cc: ECX bitmap_tag, AX sequence_index, DI frame_index
extern uint8_t blip_type_get(int16_t local_player_index, datum_index object_index);  // 0x4b3450, blam-cc: EBX object_index
extern int32_t chat_default_team_channel(void);  // 0x4ab1e0
extern uint8_t chat_poll_hotkeys(void);  // 0x4aaa90, foreign (interface)
extern void chat_submit_input(void);  // 0x4aa9b0, foreign (interface)
extern uint8_t checkpoint_list_add_row(int32_t index, const char *name, int32_t level_index, int32_t difficulty, int32_t game_time, const void *time, void *user_data);  // 0x4a4280
extern void chimera__chat_open(int32_t chat_scope);  // 0x4aa700
extern void chimera__chat_out(uint8_t team_index);  // 0x4aab00
extern void chimera__console_out_copy(char *text);  // 0x496e90
extern void chimera__do_show_loading_screen(void);  // 0x497410
extern void chimera__load_main_menu(void);  // 0x4989f0
extern widget_instance *chimera__load_ui_widget(char *tag_path, datum_index tag_index, widget_instance *parent, uint16_t controller_index, datum_index history_definition, datum_index history_list_definition, int16_t history_selection);  // 0x497a70, 7 stack args (objdump)
extern void chimera__main_menu_music(uint8_t finalize_render_frame);  // 0x4921a0, blam-cc: BL
extern void chimera__motion_sensor_update(void);  // 0x4b3920, UNSURE signature
extern uint32_t color_argb_scale_alpha(uint32_t packed_color, float scale);  // 0x497970; blam-cc: EAX -> packed_color
extern void console_clear_screen(void);  // 0x496f90
extern void console_close(terminal_console *console);  // 0x496580, foreign (interface); blam-cc: EAX -> console
extern void console_draw_input_line(void);  // 0x4970a0
extern void console_draw_overlay(void);  // 0x496730
extern void console_message_delete(datum_index message);  // 0x496490
extern void console_message_expire_old(void);  // 0x4966e0, foreign (interface)
extern datum_index console_message_new(void);  // 0x496420
extern uint8_t console_open(terminal_console *console);  // 0x496510, blam-cc: EDI -> console
extern void console_position_cursor(void);  // 0x4971a0
extern void console_process_input_events(void);  // 0x496c80, foreign (interface)
extern uint8_t console_process_queued_input(void);  // 0x4965e0, foreign (interface)
extern void console_restore_cursor(void);  // 0x496c20
extern void console_update_display(void);  // 0x496d40, foreign (interface)
extern uint8_t controls_action_column_is_bindable(int32_t slot, int32_t action_index);  // 0x4b4df0, blam-cc: ECX slot, EDX action_index
extern uint16_t *controls_action_display_name(int32_t device, const char *action_name);  // 0x4b44c0, blam-cc: EAX device, EDI action_name
extern uint8_t controls_binding_clear(int32_t action_index, int32_t device);  // 0x4b4e20, blam-cc: EAX action_index
extern int32_t controls_binding_list_refresh_rows(widget_instance *widget, int32_t page);  // 0x4b4790, blam-cc: EAX widget
extern void controls_binding_row_widget_update(int32_t action_index, widget_instance *row, int32_t device);  // 0x4b4520, blam-cc: EAX action_index
extern void controls_binding_rows_toggle_device_mode(widget_instance *widget, uint8_t mode);  // 0x4b53a0, blam-cc: ESI widget
extern void controls_device_label_add(const uint16_t *name, int32_t device_type);  // 0x4b4830, this module
extern uint8_t controls_enumerate_next_assignable_action(int32_t device, int16_t *record, const char *action_name, uint8_t accept_reserved_on_retry);  // 0x4b43e0, blam-cc: EAX device, ECX record, EDI action_name
extern uint8_t controls_gamepad_list_add(const controls_gamepad_record *entry, controls_gamepad_record *list);  // 0x4b5800, blam-cc: EAX list
extern int32_t controls_gamepad_list_find(const controls_gamepad_record *entry, controls_gamepad_record *list);  // 0x4b5760, this module
extern uint8_t controls_gamepad_list_remove(const controls_gamepad_record *entry, controls_gamepad_record *list);  // 0x4b5850, blam-cc: EDI list
extern void controls_gamepad_lists_refresh(widget_instance *screen);  // 0x4b55d0, blam-cc: ECX screen
extern void controls_gamepad_widget_nodes_collect(widget_instance **out, widget_instance *screen);  // 0x4b5560, blam-cc: EAX out, ECX screen
extern uint8_t controls_key_is_bindable(int32_t control);  // 0x4b43c0, blam-cc: EDX control (returns 0 for a reserved one)
extern void debug_fp_clip_note(const float *world, int32_t effect_type);
extern void debug_fp_dispatch_note(int32_t toggle, int32_t mode, int32_t shader_type, int32_t primitives, void *draw, void *draw_simple, void *overlay);  // TEMPORARY
extern void debug_fp_draw_state_note(const char *site, int32_t hresult, uint32_t primitive_type, uint32_t vertex_count, uint32_t primitive_count);  // TEMPORARY first-person diagnostics
extern void debug_fp_pre_draw(void);  // TEMPORARY
extern void debug_fp_render_model_note(uint32_t model_tag, float pixels, int32_t lod, const float *node0, const float *center, int32_t early_out);
extern void debug_fp_state_arm(int32_t armed);  // TEMPORARY
extern void debug_play_diagnostics(void);  // TEMPORARY play-test logging, src/interface/debug_play_diagnostics.c
extern void first_person_weapon_center_flashlight(datum_index unit_index, real_point3d *out_origin, real_vector3d *out_extents, real_vector3d *out_direction);  // 0x492b80
extern void first_person_weapon_interface_initialize(int16_t local_player_index);  // 0x493c60, this module (movsx di at 0x493c6f)
extern void first_person_weapon_interface_tick(void);  // UNSURE module (hs-related, guarded by
extern void first_person_weapon_interface_tick_reset(int16_t local_player_index);  // 0x4942e0, this module -- UNSURE
extern void first_person_weapon_set_attached(int16_t local_player_index, uint8_t attached);  // 0x493e50, this module
extern void first_person_weapon_set_state(int16_t local_player_index, uint8_t force_pose_snapshot, int16_t new_state);  // 0x492e60
extern void first_person_weapon_snapshot_pose(int16_t local_player_index, int16_t blend_gap);  // 0x4930b0, this module
extern void first_person_weapon_update_active_state(void);  // 0x492430, interface module
extern void first_person_weapon_update_animation_controls(int16_t local_player_index);  // 0x493740, this module
extern void first_person_weapon_update_lighting(void);  // 0x4924b0, foreign; called on the pass that does not render
extern void first_person_weapon_update_screen_effects(void);  // 0x494730, interface module
extern void first_person_weapon_update_state(int16_t local_player_index);  // 0x492d20, DX
extern void first_person_weapon_update_zoom_static_tint(uint8_t enabled);  // 0x494af0; AL
extern void globals_color_table_get_cyclic_color(int16_t table_index, int16_t color_index, ColorARGB *out);  // 0x494430
extern void hud_add_item_message(int16_t local_player_index, int32_t source, uint8_t source_kind, int16_t count);  // 0x4ae400, EAX, ECX, BL, stack
extern void hud_anchor_offset_to_screen_position(uint16_t *anchor, uint8_t has_scale, float scale, const int16_t *offset, int16_t *out, int32_t selector);  // 0x4ab690, blam-cc: AL has_scale, EDX offset, ECX child placement (selector)
extern void hud_bitmap_anchor_extents(uint8_t pixel_uvs, const BitmapData *bitmap, const float *uv, float *out_extents, int16_t anchor);  // 0x4acc50, blam-cc: CL, ESI, EDX, EAX
extern void hud_chat_listbox_clear(void);  // 0x4ab400
extern uint32_t hud_chat_listbox_remove_oldest(void);  // 0x4ab240
extern void hud_chat_listbox_update(void);  // 0x4ab300, the caller reloads AL from 0x006b3858 afterwards
extern void hud_display_checkpoint_message(uint8_t is_begin);  // 0x4aa310, foreign (interface)
extern void hud_display_loading_message(uint8_t is_begin);  // 0x4aa2a0, AL
extern void hud_draw_bitmap_at(const float *uv, BitmapData *bitmap, uint8_t pixel_uvs, int16_t anchor, const Point2DInt *screen_position, float scale, float rotation, uint32_t color);  // 0x4acbb0, blam-cc: EAX uv, EDX bitmap, CL pixel_uvs
extern void hud_draw_bitmap_element(const float *uv, const hud_element_placement *placement, uint8_t pixel_uvs, void *meter_parameters, BitmapData *bitmap, uint16_t *anchor, float scale, float rotation, uint32_t color, uint8_t split_screen);  // 0x4acad0, blam-cc: EAX uv, EDX placement, BL pixel_uvs
extern void hud_draw_damage_indicators(int16_t local_player_index);  // 0x4b14c0, blam-cc: EAX
extern void hud_draw_grenade_interface(int16_t local_player_index, datum_index unit_index);  // 0x4b2ac0
extern void hud_draw_message_icon(const hud_messaging_information *information, Rectangle2D *cursor, uint32_t color);  // 0x4ad970, blam-cc: ESI information
extern void hud_draw_message_text_span(Rectangle2D *cursor, Rectangle2D *origin, const uint16_t *text, uint8_t allow_button_prompts);  // 0x4ad8e0, blam-cc: EAX cursor, ECX origin
extern void hud_draw_multitexture_overlay(const float *scale, const HUDInterfaceMultitextureOverlay *overlay, int16_t local_player_index, const Point2DInt *screen_position, const float *uv, const float *extents, float rotation, uint32_t color);  // 0x4acfe0, blam-cc: EAX scale
extern void hud_draw_number(void *unused, uint16_t *anchor, const hud_number_placement *placement, int16_t value, int16_t fraction, uint32_t flags, int32_t flash_start_time, float scale);  // 0x4ac0b0
extern void hud_draw_overlays(uint16_t *anchor, const hud_overlay_list *list, uint32_t type_mask, int32_t flash_start_time, uint32_t draw_flags, uint8_t split_screen);  // 0x4ac950
extern void hud_draw_rotated_bitmap_quad(const Point2DInt *screen_position, const float *scale, void *meter_parameters, BitmapData *bitmap, const float *uv, const float *extents, float rotation, uint32_t color);  // 0x4acd50, blam-cc: EAX, ESI
extern void hud_draw_static_element(int16_t local_player_index, uint16_t *anchor, const hud_static_element_placement *element, uint32_t draw_flags, int32_t flash_start_time);  // 0x4ac6f0
extern void hud_draw_weapon_interface(player *p);  // 0x4b1e20, cdecl
extern uint16_t *hud_get_message_string(int32_t message_index);  // 0x4aa3f0
extern void hud_message_broadcast_to_local_players(const uint16_t *text);  // 0x495f50, blam-cc: ESI text
extern int32_t hud_message_compare(const void *a, const void *b);  // 0x4ae500
extern hud_message_slot *hud_message_find_slot(int32_t source, hud_player_messaging_state *record, uint8_t source_kind);  // 0x4ae480, blam-cc: ESI source
extern void hud_messaging_update(int16_t local_player_index);  // 0x4ae550, blam-cc: EAX
extern void hud_meter_draw_fill(void *dest, uint8_t value_a, uint8_t value_b, uint32_t flags, float fraction, float fraction_2, const hud_meter_placement *meter);  // 0x4abbc0, blam-cc: ESI meter
extern uint8_t hud_meter_find_matching_elements(uint32_t source_tag_ref, uint32_t target_tag_ref, int16_t *out);  // 0x493f00, this module
extern uint32_t hud_meter_flash_color_blend(const hud_flash_parameters *flash, int32_t start_time);  // 0x4ab980, blam-cc: ESI flash, EDI start_time
extern void hud_meter_permute_node_records(uint8_t *dest, uint8_t *source, uint32_t target_tag_ref, int16_t *lookup);  // 0x493ea0
extern void hud_meter_resolve_bitmap_frame(datum_index bitmap_tag, int16_t sequence_index, uint16_t frame_index, void **out_data, int32_t *out_offset);  // 0x4ab8d0, blam-cc: EAX frame_index
extern void hud_pause_timer(uint8_t paused);  // 0x4adc60, blam-cc: DL
extern void hud_play_pickup_notification(uint32_t object_or_slot_index, int16_t item_type_code);  // 0x492990, this module
extern uint8_t hud_player_weapon_ammo_state(const player *p, weapon_hud_ammo_state *out);  // 0x4acef0, blam-cc: EAX player
extern void hud_post_item_message(int16_t count, int32_t source, uint8_t kind, int16_t local_player_index, int8_t machine_id);  // 0x4ae350, EAX count, ECX source, DL kind, stack (local player, machine)
extern void hud_receive_item_message(void **context);  // 0x4ae200, EAX
extern void hud_render_unit_interface(player *p);  // 0x4b0320, cdecl
extern void hud_set_action_text_shown(int16_t local_player_index, uint8_t shown);  // 0x4ae110, blam-cc: EAX local_player_index, BL shown
extern void hud_set_help_text(int16_t message_index);  // 0x4adb30
extern void hud_set_message_icon_argument(int16_t local_player_index, int16_t slot, const hud_messaging_information *information);  // 0x4ae050, blam-cc: EAX local_player_index, ESI slot
extern void hud_set_message_string_argument(int16_t local_player_index, int16_t slot, int16_t string_index, uint8_t from_scenario_names);  // 0x4ae0b0, blam-cc: EAX local_player_index, ESI slot
extern void hud_set_objective_text(int16_t message_index);  // 0x4adb80
extern void hud_set_player_message(int16_t message_index, int16_t local_player_index);  // 0x4adfc0, blam-cc: EAX message_index
extern void hud_set_timer_time(int32_t minutes, int32_t seconds);  // 0x4adbf0, blam-cc: ECX, EAX
extern void hud_state_allocate(void);  // 0x4a9780
extern void hud_state_reset(void);  // 0x4a98d0
extern int32_t hud_text_message_queue_add(uint16_t *text, int32_t start_time, int32_t tag);
extern void hud_timer_draw(void);  // 0x4add10
extern uint32_t hud_timer_get_ticks(void);  // 0x4adcc0
extern void hud_unit_meter_apply_predictive_damage(datum_index player_index, float damage);  // 0x4b16e0, ECX, stack
extern void hud_unit_meters_update(void);  // 0x4b0110
extern void hud_unit_meters_update_for_player(int16_t local_player_index);  // 0x4b0160, blam-cc: DI local_player_index
extern void hud_unit_sounds_play(uint32_t active_mask, const TagReflexive *sounds, int32_t *handles, uint16_t *playing);  // 0x4afd30
extern void hud_unit_sounds_update(player *p, uint8_t hud_enabled);  // 0x4afee0, blam-cc: EAX player
extern void hud_update_dispatch(void);  // UNSURE module
extern void hud_update_interaction_prompt(datum_index player_index);  // 0x4a9b80, blam-cc: player_index -> EDX
extern void hud_update_player(void);  // 0x4a99f0
extern void hud_waypoint_activate_for_player(datum_index player_index, datum_index target, int16_t kind, int16_t arrow_index, float vertical_offset);  // 0x4af0d0, blam-cc: EAX, EBX, DX, stack
extern void hud_waypoint_activate_for_team(datum_index target, int16_t arrow_index, int16_t team, int16_t kind, float vertical_offset);  // 0x4af1b0, blam-cc: EAX, stack
extern void hud_waypoint_deactivate_for_player(datum_index player_index, datum_index target, int16_t kind);
extern void hud_waypoint_deactivate_for_team(int16_t kind, int16_t team, datum_index target);  // 0x4af2b0, EAX, stack
extern void hud_waypoint_draw_all_for_player(void);  // 0x4aa5f0
extern void hud_waypoint_draw_one(datum_index player_index);  // 0x4aa440, blam-cc: EAX
extern void hud_waypoints_draw_for_player(int16_t local_player_index);  // 0x4afb90, cdecl
extern void hud_waypoints_update(void);  // 0x4af320
extern void hud_waypoints_update_for_player(int16_t local_player_index);  // 0x4af370
extern void hud_weapon_crosshairs_draw(datum_index hud_tag, const player *p, const weapon_hud_ammo_state *ammo);  // 0x4b2cf0, blam-cc: EAX hud_tag, ECX player
extern void hud_weapon_interface_draw_elements(datum_index hud_tag, int16_t local_player_index, const Weapon *weapon_tag, const weapon_hud_ammo_state *ammo, const uint16_t *parent_state_flags, const uint16_t *parent_overlay_types, const int16_t *parent_numbers);  // 0x4b1ff0
extern void hud_weapon_interface_meters_evaluate(datum_index hud_interface_tag_id, int16_t local_player_index, int32_t weapon_or_vehicle_index, void *state_ptr);  // 0x4b1970, blam-cc: EAX hud_interface_tag_id
extern void hud_weapon_interface_state_update(void);  // 0x4b1740
extern void interface_draw_cursor(void);  // 0x497380
extern void interface_globals_allocate(void);  // UNSURE module
extern void interface_handle_quit_request(void);  // 0x499170
extern void interface_loading_screen_reset(void);  // 0x4978d0, foreign
extern void interface_loading_screen_set_text(const char *text);  // 0x4978a0, foreign; blam-cc: EAX -> text
extern void interface_local_player_state_reset(void);  // UNSURE module
extern void interface_tick(void);  // 0x497e80, foreign (interface)
extern void interface_update_for_resolution_change(int32_t new_cursor_x, int32_t new_cursor_y);  // 0x497250
extern int16_t item_type_to_animation_stage(int16_t message_stage);  // 0x492880, this module
extern int16_t item_type_to_message_stage(int16_t item_type_code);  // 0x4927c0, this module
extern void list_node_pop(widget_history_node *out, widget_history_node **head);  // 0x499460
extern void list_node_prepend(widget_history_node *template_record, widget_history_node **head);  // 0x499430
extern int32_t local_player_get_weapon_hud_interface(float *out_intensity);  // 0x494560
extern int32_t local_player_index_for_object(datum_index object_index);  // 0x4926f0, ESI
extern int32_t local_player_index_for_unit(datum_index unit_index);  // 0x4940a0, this module
extern void main_menu_on_shown(int32_t fade_milliseconds);  // 0x498ab0, foreign (interface module)
extern void main_menu_play_title_music(void);  // 0x4993e0
extern void map_list_add_entry(char *path, int32_t map_id);  // 0x4950c0, foreign (interface)
extern void map_list_free_all(void);  // 0x495260, foreign (interface module)
extern void motion_sensor_blip_fill(int16_t local_player_index, datum_index object_index, motion_sensor_blip *blip);  // 0x4b35f0, blam-cc: EAX, ECX, ESI
extern uint8_t motion_sensor_object_is_detected(datum_index unit_index);  // 0x4b36a0
extern void motion_sensor_plot_blip(const float *position, uint8_t type, const motion_sensor_frame *frame, int8_t subtype, float pixels_per_unit, float alpha, float size_factor);  // 0x4b37a0, blam-cc: EAX position, BL type
extern void motion_sensor_render(uint8_t splitscreen, const int16_t *screen_center, int16_t local_player_index);  // 0x4b4120, blam-cc: EAX screen_center, CX local_player_index
extern void motion_sensor_update_for_player(int16_t local_player_index);  // 0x4b3e10
extern uint8_t multiplayer_host_session_start(void);  // 0x49d210
extern uint8_t network_autojoin_from_command_line(void);  // 0x4c9c80, foreign (interface)
extern void network_game_host_start(char *map_name, char *variant_name, uint8_t disconnect_timeout_flag);  // 0x495ac0, cdecl
extern void network_game_setup_teardown(void);  // 0x495520, tears down the multiplayer game-setup UI widget
extern uint32_t network_server_reset_game_stats(void);  // 0x4a1670
extern int16_t object_get_hud_text_message_index(datum_index object_index);  // 0x4a9b40, blam-cc: EAX
extern datum_index player_get_vehicle(datum_index player_index);  // 0x4ab170, ECX
extern void player_help_screen_select_by_name(int16_t value);  // 0x4991f0
extern void player_profile_apply_audio_options(uint8_t *settings);  // 0x4957d0
extern uint8_t player_profile_apply_video_options(uint8_t *settings);  // 0x495580
extern void player_profile_auto_select(void);  // 0x4952c0
extern void player_profile_details_widget_refresh(widget_instance *widget, const uint8_t *profile_record);  // 0x4a6100, blam-cc: EAX widget
extern int16_t player_profile_find_index_by_id(int16_t id);  // 0x4954f0
extern uint8_t player_profile_get_flag_by_id(int16_t local_player_index);  // 0x495a60; blam-cc: EDX; UNSURE identity
extern void player_profile_load(int16_t player_index, void *source_profile, int32_t profile_id);  // 0x495970, blam-cc: AX player_index, EDX source_profile
extern void player_profile_refresh_settings_cache(int16_t player_index);  // 0x496060, BX
extern uint8_t player_profile_save(void);  // 0x495d40
extern void player_profile_save_495fb0(uint8_t flag);  // 0x495fb0, blam-cc: AL
extern void player_profile_select_list_widget_build(widget_instance *widget);  // 0x4a85f0
extern void player_profile_subsystem_initialize(void);  // UNSURE module
extern void *registry_get_product_id(void);  // 0x4a8790
extern uint8_t saved_item_has_unsaved_changes(void);  // 0x495ea0
extern int32_t saved_item_name_changed(void);  // 0x495c90
extern uint8_t saved_item_name_edit_begin(void);  // 0x495cf0
extern void set_profile_name(widget_instance *widget, const uint16_t *name_source);  // 0x49c710, blam-cc: EBX widget
extern void string_replace_all_in_place(char *buffer, char *search, char *replacement);  // 0x496df0
extern void terminal_initialize(void);  // 0x4963d0
extern void ui_build_level_select_list_coop(widget_instance *widget, void *param_2, void *param_3);  // 0x49cc80
extern void ui_button_prompt_draw_icon(HUDGlobalsButtonIcon *icon);  // 0x49ac80; blam-cc: ESI -> icon
extern int16_t ui_button_prompt_index_from_string(uint16_t *text);  // 0x49ac30, blam-cc: EBX -> text; -1 when no token matches
extern void ui_chat_window_reset_position(void);  // 0x4aa6b0, foreign (interface)
extern void ui_controls_populate_bind_rows(widget_instance *widget, uint32_t packed);  // 0x4a3180
extern void ui_controls_populate_input_row(widget_instance *widget, const uint8_t *profile_record);  // 0x4a22e0, blam-cc: EAX widget, EDI profile_record
extern void ui_controls_populate_sensitivity_row(widget_instance *widget, const uint8_t *profile_record);  // 0x4a20f0
extern void ui_cursor_update(void);  // 0x4972c0, foreign (interface)
extern void ui_draw_rotated_screen_quad(int16_t *origin, int32_t source_record, float *corner_uvs, float scale, float rotation_radians, float alpha_fraction);  // 0x494d70, blam-cc: EAX origin
extern void ui_draw_trouble_brewing_indicator(void);  // 0x49c870
extern void ui_error_modal_update(void);  // 0x494ca0
extern ColorRGB *ui_get_saved_color(ColorRGB *out);  // 0x49c5c0, flash color (ui_saved_color); blam-cc: EAX -> out, fills three floats
extern ColorARGB *ui_get_saved_pulse_color(ColorARGB *out);  // 0x49c620, highlight color; blam-cc: EAX -> out
extern void ui_level_carousel_row_refresh(widget_instance *widget, int32_t slot_index);  // 0x4a4e20, blam-cc: ECX widget, EAX index
extern void ui_list_add_entry(int32_t group_index, const uint16_t *name, int32_t id, const void *data_blob, uint32_t data_size, uint8_t is_default);  // 0x4a7ba0, blam-cc: EAX group_index, CL is_default
extern uint8_t ui_list_default_item_format(void *item_buffer, int32_t item_index, void *list_items);  // 0x4a8310, UNSURE: not analyzed separately
extern int32_t ui_list_find_default(int32_t group_index);  // 0x4a7cb0, blam-cc: group_index -> ECX
extern void ui_list_free_all(void);  // 0x4a7b20
extern void *ui_list_get_data(int32_t index);  // 0x4a7c50, blam-cc: EDX index
extern int32_t ui_list_get_id(int32_t index);  // 0x4a7c80, blam-cc: EDX index
extern uint8_t ui_list_item_format_name_and_cache_flag(uint16_t *out_name, int32_t item_index);  // 0x4a83d0
extern int32_t ui_list_widget_compute_scroll_start(widget_instance *widget);  // 0x4a7d00, blam-cc: widget -> EAX
extern void ui_list_widget_rebuild_rows(widget_instance *widget, ui_list_item_format_function format_item);  // 0x4a7db0
extern uint8_t ui_network_game_options_populate(widget_instance *widget, const uint8_t *options_record);  // 0x4a3960, blam-cc: ECX widget, ESI options_record
extern void ui_network_wait_timeout_check(void);  // 0x49c7b0, outside this batch
extern void ui_network_wait_timeout_start(void);  // 0x49c810, not in this batch
extern uint8_t ui_new_profile_name_entry_open(void *widget, int16_t *event, uint8_t *out_handled);  // 0x4a1940, new profile name entry
extern void ui_profile_carousel_slot_cache_populate(int32_t count, const int32_t *candidate_ids);  // 0x4a74b0, blam-cc: EBX candidate_ids
extern int32_t ui_real_to_int_truncate(float value);  // 0x4ab590
extern uint32_t ui_restart_saved_game(void);  // 0x4a1110
extern const uint16_t *ui_search_replace_function_call(int16_t function, widget_instance *widget);  // 0x4a8730, blam-cc: AX function, ECX widget
extern uint32_t ui_start_campaign_from_level_one(void *widget, int16_t *event);  // 0x49cfd0
extern uint8_t ui_string_has_button_prompt_token(uint16_t *text);  // 0x49ada0; blam-cc: EAX -> text
extern void ui_variant_carousel_slot_cache_populate(int32_t *candidate_ids, int32_t count);  // 0x4a7570, blam-cc: EBX candidate_ids
extern uint8_t ui_variant_name_is_available(const uint16_t *name);  // 0x4a8b50, blam-cc: EDI
extern void ui_widget_draw_prompt_span(const uint16_t *text, Rectangle2D *cursor, Rectangle2D *origin);  // 0x49ad30
extern uint8_t unit_get_first_person_marker_transform(datum_index object_index, const char *marker_name, real_point3d *out_position, real_vector3d *out_extents, real_vector3d *out_direction);  // 0x492c30
extern void video_display_modes_enumerate(uint32_t format);  // 0x4baba0, blam-cc: EBX format
extern uint32_t video_refresh_rate_find_index(int32_t resolution_index, int32_t refresh_rate);  // 0x4bae80, blam-cc: ECX resolution_index, EDI refresh_rate
extern void video_resolution_add(int32_t height, int32_t width, int32_t refresh_rate);  // 0x4badc0, blam-cc: EAX height
extern void virtual_keyboard_backspace(void);  // 0x4a96f0
extern uint8_t virtual_keyboard_close(void);  // 0x4a9250
extern void virtual_keyboard_draw_text(Rectangle2D *bounds);  // 0x4a9300
extern void virtual_keyboard_process_input(void);  // 0x4a8be0
extern void virtual_keyboard_render(void);  // 0x4a9510
extern void weapon_action_notify_for_unit(datum_index unit_index, int32_t action_code);  // 0x492730, EAX, stack
extern void weapon_action_notify_for_weapon(datum_index weapon_index, int32_t action_code);  // 0x492790, EAX, EDI
extern uint8_t weapon_hud_ammo_state_is_empty(const weapon_hud_ammo_state *state);  // 0x4a9750, blam-cc: EAX
extern void widget_close_all(void);  // 0x498650, widget module
extern void widget_column_list_sync_selected(widget_instance *widget);  // 0x49c040, column_list upkeep; blam-cc: ECX -> widget
extern uint8_t widget_create_children_from_tag(widget_instance *widget, UIWidgetDefinition *tag);  // 0x499540
extern int32_t widget_cursor_side_of_midpoint(widget_instance *widget);  // 0x4a1ff0
extern void widget_draw_fullscreen_region(int16_t controller_index);  // 0x4984c0, interface
extern widget_instance *widget_find_by_tag_id(widget_instance *widget, datum_index tag_id);  // 0x499950
extern void widget_focus_next_child(widget_instance *widget);  // 0x49c080, walks next_sibling with wrap; blam-cc: EDX -> widget
extern void widget_focus_previous_child(widget_instance *widget);  // 0x49c0f0, walks previous_sibling with wrap; blam-cc: EDX -> widget
extern int32_t widget_get_sibling_index(widget_instance *widget);  // 0x498e30, blam-cc: ESI -> widget
extern void widget_initialize_from_tag(widget_instance *widget, datum_index tag_index, widget_instance *parent, uint16_t controller_index, UIWidgetDefinition *tag);  // 0x499780
extern void widget_instance_close_and_restore_previous(widget_instance *widget);  // 0x49c3e0
extern widget_instance *widget_instance_find_at_point(widget_instance *root, int32_t x, int32_t y, int32_t initial_hint);  // 0x499ad0
extern float widget_instance_get_cumulative_scale(widget_instance *widget);  // 0x499c20
extern uint8_t widget_instance_is_input_eligible(widget_instance *widget);  // 0x499c40
extern uint8_t widget_instance_is_top_of_stack(widget_instance *widget);  // 0x499cb0
extern uint8_t widget_instance_point_in_bounds(widget_instance *widget);  // 0x4999f0
extern void widget_instance_relink_focus(widget_instance *widget, widget_instance *child);  // 0x49bba0, focus change; blam-cc: EAX -> widget, ECX -> child (objdump 0x49bba0: walks EAX up +0x30, tests ECX+0x12)
extern void widget_instance_render(widget_instance *widget, Rectangle2D *dest, int32_t offset_xy, uint32_t flag1, int32_t flag2);  // 0x49a8c0, as defined in widget_instance_render.c
extern void widget_instance_render_column_list_items(widget_instance *widget, UIWidgetDefinition *tag, Rectangle2D *dest, int32_t offset_xy, uint32_t flags);  // 0x49bac0, blam-cc: EDI widget
extern void widget_instance_set_state_recursive(widget_instance *widget, uint8_t state);  // 0x498e60
extern uint8_t widget_instance_verify_stack_chain(widget_instance *node);  // 0x499aa0
extern widget_instance *widget_list_get_child_by_index(widget_instance *list, int32_t index);  // 0x498630, blam-cc: EAX -> list, EDX -> index
extern void widget_list_scroll_window(int32_t out[3], widget_instance *widget);  // 0x4a7400, blam-cc: EAX out, ECX widget
extern uint8_t widget_list_select_next(widget_instance *widget);  // 0x4986b0, UNSURE: called here with 3 args by Ghidra (widget, event, &out); own file's signature takes just widget -- extern arity disagreement, not resolved
extern uint8_t widget_list_select_previous(widget_instance *widget);  // 0x498820, same UNSURE as above
extern void widget_memory_pool_initialize(void);  // 0x4979b0
extern void widget_play_sound_effect_tag(datum_index sound_tag);  // 0x49bdd0, UNSURE signature
extern void widget_relink_focus_by_tag_id(widget_instance *widget, datum_index child_definition);  // 0x49bb60; blam-cc: EAX -> widget, stack -> child_definition (objdump 0x498713)
extern widget_instance *widget_reopen_as_root_with_history(widget_instance *widget, datum_index open_tag);  // 0x49c4c0, per src/interface/widget_close.c
extern void widget_spinner_list_sync_selected(widget_instance *widget, UIWidgetDefinition *tag);  // 0x49c000, spinner_list upkeep; blam-cc: ECX -> widget, EAX -> tag (objdump 0x499f79)
extern void widget_text_edit_clamp_selection(text_edit_state *state);  // 0x44c780
extern uint32_t widget_text_edit_get_selection(text_edit_state *state, int16_t *out_start, int16_t *out_end);  // 0x44c5e0, this module
extern void widget_text_edit_insert_string(text_edit_state *state, char *insert_str);  // 0x44c640, blam-cc: ESI -> state, EAX -> insert_str
extern void widget_text_edit_process_key(text_edit_state *state, ui_key_event *event);  // 0x44c290
extern void widget_text_edit_reset_length(text_edit_state *state);  // 0x44c5b0, blam-cc: ESI -> state

#endif
