// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/items/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_ITEMS_H
#define FN_ITEMS_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "objects.h"
#include "items.h"

extern void equipment_build_creation_message(uint32_t item_index, uint32_t unused_arg2, uint32_t unused_arg3, uint32_t object_flags);  // 0x4bbc90, this module
extern int32_t weapon_add_ammunition(void **context);  // 0x4c25a0, EAX
extern void weapon_apply_ammo_correction(void **context);  // 0x4c3870, EAX
extern void weapon_apply_ammo_correction_and_resync(void **context);  // 0x4c4ac0, EAX
extern void weapon_build_creation_message(datum_index item_index, uint32_t unused_param_2, uint32_t unused_param_3, uint32_t object_flags);  // 0x4c5a50, this module
extern void weapon_build_hud_ammo_state(datum_index item_index, weapon_hud_ammo_state *out);  // 0x4c29d0, blam-cc: EAX item_index
extern real weapon_clamp_zoom_fov(datum_index item_index, int16_t zoom_level, real base_fov);  // 0x4c2e50, DX zoom, stack (item, fov)
extern void weapon_force_settled_state(datum_index item_index);  // 0x4c5630
extern int16_t weapon_get_first_person_animation_time(datum_index item_index, int16_t animation_index, int16_t category, int16_t mode);  // 0x4c2f80
extern char *weapon_get_label(datum_index item_index);  // 0x4c24d0, ECX
extern int32_t weapon_get_next_zoom_level(int32_t current_level, datum_index item_index);
extern real weapon_get_zoom_magnification(datum_index item_index, int16_t zoom_level);  // 0x4c2d70, EAX, DX
extern int32_t weapon_is_reloading(datum_index item_index);  // 0x4c2ad0, this module
extern void weapon_magazine_begin_chamber(datum_index item_index, int16_t magazine_index);  // 0x4c3b00
extern void weapon_magazine_reload_tick(datum_index item_index, int16_t magazine_index);  // 0x4c3900
extern void weapon_magazine_reload_tick_predicted(datum_index item_index, int16_t magazine_index);  // 0x4c3a20
extern void weapon_notify_ammo_pickup(datum_index item_index, int16_t magazine_index, int16_t rounds);  // 0x4c2510
extern void weapon_notify_reload_begin(datum_index item_index, int16_t magazine_index);  // 0x4c3470
extern void weapon_notify_reload_cancel(datum_index item_index, int16_t magazine_index);  // 0x4c4a00, ECX, BX
extern void weapon_notify_reload_step(datum_index item_index, int16_t magazine_index);  // 0x4c37b0
extern uint32_t weapon_play_trigger_tag_effect(datum_index item_index, datum_index tag_id, real scale_a, real scale_b);  // 0x4c47d0, ECX item, EDI tag, stack (scale_a, scale_b)
extern void weapon_predict_ammo(void **context);  // 0x4c3530, EAX
extern uint32_t weapon_prevents_grenade_throwing(datum_index item_index);  // 0x4c2f30, blam-cc: ECX item_index
extern uint32_t weapon_prevents_melee_attack(datum_index item_index);  // 0x4c2ee0, ECX
extern int32_t weapon_put_away(datum_index item_index, int8_t force);  // 0x4c28f0, ESI, AL
extern void weapon_ready(datum_index item_index);  // 0x4c2840, EAX
extern void weapon_reload_recovery_finish(datum_index item_index, int16_t trigger_index);  // 0x4c4940
extern void weapon_set_control_flags(datum_index item_index, uint16_t control_flags, real primary_trigger);  // 0x4c2990
extern void weapon_set_ready_timer(datum_index item_index, real value);  // 0x4c2b20
extern int32_t weapon_set_state(datum_index item_index, int16_t new_state, int8_t force);  // 0x4c5670
extern void weapon_set_state_indicator_flags(datum_index item_index);  // 0x4c5580
extern uint32_t weapon_stop_object_effect(datum_index item_index, datum_index tag_id);  // 0x4c48a0
extern uint32_t weapon_transfer_ammunition(datum_index target_item_index, datum_index source_item_index, int16_t requesting_player_index, int16_t *out_transferred);  // 0x4c2610
extern void weapon_trigger_barrel_spread_offset(real_vector3d *v, real_vector3d *axis, uint16_t barrel_index, int16_t distribution_function, real distribution_angle, uint32_t flags);  // 0x4c54e0, stack + AX
extern void weapon_trigger_become_charged(datum_index item_index, int16_t trigger_index);  // 0x4c3bc0
extern void weapon_trigger_begin_reload(datum_index item_index, int16_t magazine_index, int8_t is_client_predicted);  // 0x4c35b0
extern void weapon_trigger_continue_burst(datum_index item_index, int16_t trigger_index);  // 0x4c3c60
extern void weapon_trigger_effect_clear(datum_index item_index, int16_t trigger_index);  // 0x4c3e40
extern void weapon_trigger_effect_set_out_of_ammo(datum_index item_index, int16_t trigger_index);  // 0x4c3e70
extern void weapon_trigger_effect_set_state(datum_index item_index, int16_t trigger_index, int8_t state, int16_t counter);  // 0x4c49c0
extern void weapon_trigger_enter_recovery(datum_index item_index, int16_t trigger_index);  // 0x4c3d00
extern void weapon_trigger_finish_shot(datum_index item_index, int16_t trigger_index);  // 0x4c48f0
extern void weapon_trigger_fire_or_reload(datum_index item_index, int16_t trigger_index, int8_t force);  // 0x4c3280
extern uint8_t weapon_trigger_get_aiming_vector(datum_index weapon_index, int16_t trigger_index, real_point3d *origin, real_point3d *target, uint8_t use_high_arc, real_vector3d *out_direction, real *out_time, real *out_range, uint8_t *out_used_straight_line);  // 0x4c2b40, EAX, CX, stack
extern real weapon_trigger_get_charge_fraction(datum_index item_index, int16_t trigger_index);  // 0x4c3100, this module
extern void weapon_trigger_handle_empty(datum_index item_index, int16_t trigger_index);  // 0x4c3de0
extern real weapon_trigger_projectile_time_fraction(datum_index item_index, int16_t trigger_index, real elapsed);  // 0x4c2be0, EAX, CX, stack
extern int32_t weapon_trigger_ready_to_fire(datum_index item_index, int16_t trigger_index);  // 0x4c3190
extern void weapon_trigger_reset_tracking(datum_index item_index, int16_t trigger_index);  // 0x4c3eb0
extern int32_t weapon_triggers_idle(datum_index item_index);  // 0x4c30c0

#endif
