// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/math/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_MATH_H
#define FN_MATH_H

#include "tags.h"
#include "memory.h"
#include "math.h"

extern void bit_vector_or(uint32_t *a, int16_t bit_count, uint32_t *b, uint32_t *dst);  // 0x4cb760, EAX a, CX count, EDX b, stack dst
extern float cubic_interpolate_divided_difference(float y0, float y1, float y2, float y3, float x0, float x1, float x2, float x3, float x);  // 0x4fca60, same file
extern real_point3d *decal_plane_solve_third_axis(real_point3d *out, uint32_t component_sign, int32_t dominant_axis, const real_plane3d *plane, const real_point2d *known);  // 0x44d860
extern void euler_angles_to_basis_vectors(real_euler_angles3d *angles, real_vector3d *up_out, real_vector3d *forward_out);  // 0x4cdde0, blam-cc: EAX -> angles, EDX -> up_out, ESI -> forward_out
extern int32_t float_compare_ascending(const void *a, const void *b);  // 0x405360
extern uint8_t lerp_find_threshold_byte(real lo, real hi, real threshold);  // 0x4cf7a0, UNSURE signature
extern void math_initialize(void);  // 0x004cd3f0
extern void matrix3x3_from_forward_up(real_vector3d *up, real_vector3d *forward, real_matrix3x3 *out);  // 0x4cc560
extern void matrix3x3_inverse_transform_vector(real_vector3d *out, real_vector3d *v, real_matrix3x3 *m);  // 0x4cc710
extern void matrix3x3_multiply(real_matrix3x3 *out, real_matrix3x3 *a, real_matrix3x3 *b);  // 0x4cc5f0
extern void matrix3x3_transpose(real_matrix3x3 *out, real_matrix3x3 *in);  // 0x4cc500
extern void matrix4x3_extract_forward_up_position(real_vector3d *up_out, real_vector3d *forward_out, real_matrix4x3 *matrix, real_point3d *position_out);  // 0x4cbd90, foreign, UNSURE signature
extern void matrix4x3_from_axis_angle(real_matrix4x3 *out, real_vector3d *axis, real sin_angle, real cos_angle);  // 0x4cb880, EAX out, ECX axis
extern void matrix4x3_from_euler_angles(real_matrix4x3 *out, real yaw, real pitch, real roll);  // 0x4cba10, math module
extern void matrix4x3_from_forward_up(real_vector3d *up, real_vector3d *forward, real_matrix4x3 *out);  // 0x4cb970
extern void matrix4x3_from_forward_up_position(real_vector3d *up, real_vector3d *forward, real_point3d *position, real_matrix4x3 *out);  // 0x4cbd60, math module
extern void matrix4x3_inverse(real_matrix4x3 *out, real_matrix4x3 *in);  // 0x4cb7a0
extern void matrix4x3_inverse_transform_normal(real_vector3d *out, real_vector3d *normal, real_matrix4x3 *m);  // 0x4cc080
extern void matrix4x3_inverse_transform_point(real_matrix4x3 *m, real_point3d *out, real_point3d *point);  // 0x4cbf80, ECX, EDX, ESI
extern void matrix4x3_multiply_3dnow(real_matrix4x3 *a, real_matrix4x3 *b, real_matrix4x3 *out);  // 0x4cc3a0 -- AMD 3DNow! build, Ghidra names it matrix4x3_multiply_sse
extern void matrix4x3_multiply_sse(real_matrix4x3 *a, real_matrix4x3 *b, real_matrix4x3 *out);  // 0x4cc250 -- true SSE build, see header note
extern void matrix4x3_transform_normal(real_vector3d *out, real_vector3d *normal, real_matrix4x3 *m);  // 0x4cbec0
extern int object_sort_by_flag_then_distance(const void *a, const void *b);  // 0x433c70, library code, not rewritten in this batch
extern void path_find_closest_point_on_segment(const real_point3d *point, const real_point3d *segment_start, const real_point3d *segment_end, real_point3d *out);  // 0x43b2f0, EAX, ECX, EDX, ESI
extern void periodic_function_build_noise_table(real *table);  // 0x4ccbb0, table in EDX
extern void periodic_function_build_table(periodic_function_t type, uint8_t *out);  // 0x4ccdb0
extern void periodic_function_build_transition_table(transition_function_t type, uint8_t *table);  // 0x4cccb0
extern void periodic_function_tables_free(void);  // 0x004cc960
extern void periodic_function_tables_init(void);  // 0x4cc8d0
extern real_plane2d *plane2d_from_points(real_plane2d *out_plane, const real_point2d *a, const real_point2d *b);  // 0x44d950, math module, no file yet;
extern uint8_t plane3d_intersect_pair_to_line(real_vector3d *direction_out, real_plane3d *p2, real_plane3d *p1, real_point3d *point_out);  // 0x4cf1e0, blam-cc: ECX direction_out, EDX p2, ESI p1, EDI point_out
extern uint8_t plane3d_intersect_three(real_plane3d *p1, real_plane3d *p2, real_plane3d *p3, real_point3d *out);  // 0x4cf040, blam-cc: stack p1, EBX p2, EDI p3, ESI out
extern void point3d_project_onto_line(real_point3d *point, real_vector3d *direction, real_point3d *line_origin, real_point3d *out_result);  // 0x5066e0, blam-cc: stack point, EAX direction, ECX line_origin, EDX out
extern int point3d_within_radius(const real_point3d *a, const real_point3d *b, real radius);  // 0x43c340, EAX, ECX, stack
extern int16_t polygon2d_clip_to_plane(real_point2d *out, int16_t count, real_point2d *in, real_plane2d *plane, int16_t maximum_count, uint32_t *edge_bitmask, uint8_t *clipped_flag, real epsilon);  // 0x4caff0, math module; out in EDX
extern int16_t polygon2d_clip_to_planes(int16_t vertex_count, real_point2d *vertices, int16_t clip_point_count, real_point2d *clip_points, int16_t maximum_count, real_point2d *out, real epsilon);  // 0x4caee0
extern uint8_t polygon2d_point_inside_tolerance(real_point2d *vertices, int16_t count, real_point2d *point, real tolerance);
extern int16_t polygon2d_points_classify(real_point2d *points, int16_t count);  // 0x4caa40
extern int16_t polygon3d_clip_to_plane(int16_t count, real_point3d *in, real_plane3d *plane, int16_t max_count, real_point3d *out, uint8_t *clipped_flag, real epsilon, char keep_coplanar);  // 0x4cb380
extern real_quaternion *quaternion_from_matrix3x3(real_matrix3x3 *m, real_quaternion *out);  // 0x4cc780, ECX, stack
extern void quaternion_from_matrix4x3(real_matrix4x3 *m, real_quaternion *out);  // 0x4cbc00, math module
extern void quaternion_lerp(real_quaternion *a, real_quaternion *b, real_quaternion *out, real t);  // 0x4cdcc0
extern void quaternion_multiply(real_quaternion *a, real_quaternion *b, real_quaternion *out);  // 0x4cdbf0
extern void quaternion_normalize(real_quaternion *q);  // 0x4cdb20
extern void quaternion_rotate_vector(real_quaternion *q, real_vector3d *v, real_vector3d *out);  // 0x4cdd40, q on the stack, v in ECX, out in EDX
extern void quaternion_to_axis_angle(real_quaternion *quat, real_vector3d *axis_out, real *angle_out);  // 0x4cdb90
extern int32_t random_int_range(int16_t min, int16_t max);  // 0x405320, ECX -> min, stack -> max
extern real random_real_range(real min, real max);  // 0x401050
extern real random_real_range_seeded(random_seed *seed, real min, real max);  // 0x4cd170
extern uint32_t random_seed_generate(void);  // 0x4cd070
extern uint8_t ray2d_intersect_circle_distance(const real_vector2d *direction, const real_point2d *origin, const real_point2d *center, real *out_distance, real radius);  // 0x43c380, EAX, ECX, EDX, ESI, stack
extern real ray_intersect_sphere_distance(real_point3d *origin, real_point3d *center, real_vector3d *direction, real radius);  // 0x4ce7d0
extern uint8_t ray_intersects_cylinder(real height, real radius, real_vector3d *hit_out, real *t_out, real_point3d *center, real_point3d *origin, real_vector3d *direction);  // 0x4ce4e0, stack x3, EAX, ECX, EBX, ESI // 0x4ce4e0, EAX/ECX + stack
extern uint8_t ray_intersects_sphere(real_point3d *origin, real_vector3d *normal_out, real_vector3d *direction, real *t_out, real_point3d *center, real radius);  // 0x4ce3a0
extern uint8_t ray_intersects_sphere_test(real_point3d *center, real_point3d *origin, real_vector3d *direction, real radius);  // 0x4ce6c0
extern void real_lerp_clamped(real *out, real a, real b, real t);  // 0x4cd900, math module;
extern uint8_t real_matrix4x3_rotation_is_orthonormal(real_vector3d *forward, real_vector3d *left, real_vector3d *up);  // 0x5579e0
extern void real_matrix4x3_rotation_rebuild_orthonormal(real_vector3d *forward, real_vector3d *left, real_vector3d *up);  // 0x558860
extern uint8_t real_seek_toward_clamped(int wrap, real *velocity, real *value, real target, real accel, real max_speed, real range_min, real range_max);  // 0x4cf360, established
extern int segment3d_within_radius_of_segment(real_point3d *a_start, real_point3d *b_start, real_vector3d *a_direction, real_vector3d *b_direction, real radius);  // 0x4ceae0
extern void sphere_mesh_build_face(int16_t *next_point_index, sphere_mesh *mesh, int16_t vertex_a, int16_t vertex_b, int16_t apex, int16_t *strip_cursor, sphere_mesh_edge_cache *edge_cache);  // 0x4ca5f0
extern sphere_mesh *sphere_mesh_generate(int16_t subdivisions);  // 0x4ca4b0, blam-cc: subdivisions in EAX
extern int16_t sphere_mesh_get_edge_point(int16_t vertex_a, int16_t vertex_b, sphere_mesh *mesh, int16_t position, int16_t *next_point_index, sphere_mesh_edge_cache *edge_cache);  // 0x4ca8c0
extern int16_t sphere_mesh_get_face_point(sphere_mesh *mesh, int16_t *next_point_index, int16_t apex, int16_t vertex_a, int16_t vertex_b, int16_t row, int16_t col, sphere_mesh_edge_cache *edge_cache, sphere_mesh_face_cache *face_cache);  // 0x4ca7c0
extern void sphere_mesh_interpolate_vertex(int16_t position, int16_t total, sphere_mesh *mesh, int16_t new_index, int16_t vertex_lo, int16_t vertex_hi);  // 0x4ca9a0
extern void sphere_point_table_init(void);  // 0x4cd0e0
extern uint8_t triangle_point_barycentric_2d(real_point3d *a, real_point3d *v_ecx, real_point3d *v_edx, real_point3d *p, real *out_u, real *out_v);  // 0x4ce8c0, src/math: EAX a, ECX v_ecx, EDX v_edx, ESI p
extern int32_t uint32_log2_floor(uint32_t value);  // 0x4cb740, math module (src/math/uint32_log2_floor.c)
extern real vector2d_angle_between(real_vector2d *a, real_vector2d *b);  // 0x4cd480, ESI a, EDI b
extern void vector2d_normalize(real_vector2d *v);  // 0x4cd2e0
extern real vector2d_normalize_with_length(real_vector2d *v);  // 0x4018e0, ECX
extern void vector2d_tangent_edge_directions(const real_vector2d *direction, real_vector2d *edge_pos, real_vector2d *edge_neg, real distance, real extent, real *adjacent_out);  // 0x43c400, math helper, not rewritten here; blam-cc: ECX -> direction, EDX -> edge_pos, ESI -> edge_neg
extern real vector3d_angle_between_4cd4f0(real_vector3d *a, real_vector3d *b);  // 0x4cd4f0, ECX, EDX
extern void vector3d_barycentric_interpolate(real_vector3d *out, real_vector3d *v1, real_vector3d *v2, real_vector3d *v0, float w2, float w1);
extern void vector3d_build_perpendicular(real_vector3d *out, real_vector3d *dir);  // 0x4cd670
extern real vector3d_cross_product_length(real_vector3d *a, real_vector3d *b);  // 0x4cd380, math
extern void vector3d_delta_toward_gravity_biased_clamp_length(real_point3d *origin, real_point3d *target, real_vector3d *out_delta, real max_length_aligned, real max_length_default);  // 0x572a90, EAX, ECX, ESI, stack
extern real vector3d_length(real_vector3d *v);  // 0x401960, EAX
extern void vector3d_lerp(real_vector3d *out, real_vector3d *a, real_vector3d *b, real t);  // 0x4cd8c0, blam-cc: EAX out, ECX a, EDX b
extern int16_t vector3d_major_axis_index(real_vector3d *v);  // 0x44d820, EAX
extern void vector3d_normalize(real_vector3d *v);  // 0x4cd320, ECX
extern real vector3d_normalize_with_length(real_vector3d *v);  // 0x401990, ECX
extern void vector3d_project_onto_axis(real_vector3d *parallel_out, real_vector3d *axis, real_vector3d *v, real_vector3d *perp_out);  // 0x4cda90, src/math/vector3d_project_onto_axis.c
extern void vector3d_project_onto_unit_axis(real_vector3d *parallel_out, real_vector3d *axis, real_vector3d *v, real_vector3d *perp_out);  // 0x4cda30, EAX, ECX, EDX, ESI
extern void vector3d_rotate_about_axis_perpendicular(real_vector3d *v, real_vector3d *axis, real sin_angle, real cos_angle);  // 0x4cd700, EAX, ECX, stack
extern void vector3d_rotate_pair_in_plane(real_vector3d *a, real_vector3d *b, real sin_angle, real cos_angle);  // 0x4cd790, EAX, ECX, stack
extern uint8_t vector3d_rotate_toward(real_vector3d *target, real_vector3d *source, real_vector3d *out, real sin_angle, real cos_angle);  // 0x4cd950, ECX, ESI, EDI, stack
extern void vector3d_rotate_toward_with_acceleration(real_vector3d *direction, real_vector3d *target_direction, real_vector3d *angular_velocity, real maximum_velocity, real acceleration);  // 0x4cf530, ESI, EDI, stack

#endif
