// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/memory/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_MEMORY_H
#define FN_MEMORY_H

#include "tags.h"
#include "memory.h"
#include "math.h"

extern uint32_t bit_stream_read_bit(uint8_t *out_bit, bit_stream *stream);  // 0x4cfb80, memory module
extern uint32_t bit_stream_read_bits(uint32_t bit_count, uint32_t *out_value, bit_stream *stream);
extern int32_t bit_stream_read_bits_chunked(int32_t total_bit_count, uint32_t *buffer, bit_stream *stream);
extern uint8_t bit_stream_write_bits(uint32_t bit_count, uint32_t value, bit_stream *stream);
extern int32_t bit_stream_write_bits_chunked(bit_stream *stream, const uint32_t *values, int32_t total_bit_count);  // 0x4cf8f0, EAX stream, ECX values, stack bits
extern int32_t block_list_allocate(memory_pool *arena, int32_t requested_size, void **owner);  // this batch
extern void block_list_compact(memory_pool *arena);  // 0x4d1eb0, EBX
extern int32_t block_list_reallocate(void **owner_cell, int32_t new_size, memory_pool *arena);  // 0x4d1de0,
extern void block_list_unlink(void **payload_ptr, memory_pool *arena);  // this batch
extern uint32_t byte_stream_read_long(byte_stream *stream);  // blam-cc: stream in ESI
extern uint32_t byte_stream_read_ranged_integer(int32_t maximum, byte_stream *stream);
extern char *byte_stream_read_string(byte_stream *stream);
extern uint32_t byte_stream_write_ranged_integer(int32_t maximum, uint32_t value, byte_stream *stream);
extern uint32_t byte_stream_write_string(char *string, int16_t max_length, byte_stream *stream);
extern uint32_t circular_buffer_read(uint8_t *destination, uint32_t byte_count, char consume, circular_buffer *stream);  // 0x4d0240, memory module
extern void crc32_build_table(crc32_table *table);  // blam-cc: table in EDX
extern void data_delete_all(data_array *array);  // 0x4d0580, blam-cc: ESI -> array
extern data_array *data_new(int16_t element_size, char *name, int16_t maximum_count);  // 0x4d0370
extern int32_t data_packet_group_append_packet_header(uint8_t *buffer, data_packet_group *group, int16_t *cursor, uint8_t header_byte);
extern uint8_t data_packet_group_decode_packet_body(uint8_t *buffer, struct_definition *definition, int16_t remaining_length, void *dest, uint16_t *out_version_used, int16_t *out_bytes_consumed);  // 0x4d0c70, EAX buffer, ESI definition
extern int32_t data_packet_group_encode_packet_body(int16_t version, struct_definition *definition, uint8_t *version_byte_dest, byte_stream *output, void *source, int16_t *out_wrote_version_byte, int16_t capacity_check);
extern void datum_element_initialize(data_array *array, void *element);
extern datum_index datum_new(data_array *array);  // 0x4d0480, EDX
extern datum_index datum_new_at_index(int16_t index, data_array *array);  // 0x4d0430,
extern void growable_array_remove_element(growable_array *array, uint32_t index);  // 0x4cf890, blam-cc: ESI, EDI
extern void heap_advance_free_slot(heap *self);  // this batch
extern void *heap_allocate(uint32_t size, heap *self);  // 0x4d1f10
extern uint32_t heap_allocate_raw(uint32_t size, heap *self);  // this batch
extern void heap_compact(heap *self);  // this batch
extern uint32_t heap_find_first_free_slot(heap *self);  // this batch
extern int32_t heap_find_free_block(heap *self, uint32_t size_needed, void **out_predecessor);  // this batch
extern int32_t heap_get_free_bytes(heap *self);  // this batch
extern void *heap_reallocate(void *old_payload, uint32_t new_size, heap *self);  // 0x4d1f80, blam-cc: EAX old, ESI self
extern void *heap_resize_block(uint32_t new_size, heap_block *old_block, heap *self);  // this batch
extern void heap_unlink_block(heap_block *block, heap *self);  // 0x4d20a0
extern void struct_definition_compute_size(struct_definition *definition, int16_t *out_size, struct_definition_field *fields, int16_t *out_field_count);
extern void struct_definition_decode(struct_definition *definition, byte_stream *input, int16_t version, void *dest, int16_t *out_dest_size, struct_definition_field *fields, int16_t *out_field_count);
extern void struct_definition_encode(struct_definition *definition, byte_stream *output, int16_t version, void *source, int16_t *out_source_size, struct_definition_field *fields, int16_t *out_field_count);
extern void struct_definition_table_compute_sizes(data_packet_group *group);  // 0x4d0980

#endif
