// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/main/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_MAIN_H
#define FN_MAIN_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "camera.h"
#include "game.h"
#include "interface.h"
#include "main.h"
#include "networking.h"
#include "rasterizer.h"
#include "render.h"

extern void campaign_level_advance(void);  // this module, 0x4c9bd0
extern void chimera__exec_init(void);  // this module, 0x4c6390
extern void console_autocomplete_command(void);  // this module, 0x4c6bc0
extern uint32_t console_command_context_mask(uint32_t context_flags);  // this module, 0x4c69c0
extern void console_deactivate(void);  // this module, 0x4c64b0
extern void console_initialize(void);  // 0x4c62d0 (Ghidra splits it at 0x4c62f0 / 0x4c6340)
extern uint32_t console_paste_clipboard_text(void);  // this module, 0x4c6570
extern void console_print_va(const char *format, ...);  // 0x4c6920
extern uint8_t console_process_key_events(void);  // this module, 0x4c65c0
extern void console_toggle(void);  // this module, 0x4c6530
extern void credits_load_directly_for_endgame(void);  // 0x4c8d40, this module
extern void game_engine_flush_pending_simulation_ticks(void);  // this module, 0x4c99e0
extern uint32_t game_frame_rate_average_update(void);  // this module, 0x4c6e80
extern void game_scenario_session_begin(network_scenario_load_request *request);  // 0x4c95f0, this module
extern void game_start_new_single_player_map(void);  // this module, 0x4c9dd0
extern void game_timer_reset(void);  // this module, 0x4c9f30
extern void main_ensure_local_players(void);  // 0x4c8800, this module
extern void main_level_transition_update(void);  // this module, 0x4c9770
extern void main_loop(void);  // 0x4c7610 (Ghidra: game_state_save_core, see header)
extern void main_loop_frame_pacer(void);  // this module, 0x4c9f90
extern void main_loop_shutdown_cleanup(void);  // this module, 0x4c9e90
extern void main_menu_music_stop(void);  // 0x4c8b40, this module
extern void main_menu_return_and_reset(void);  // 0x4c8a60, this module
extern void main_save_map_private(void);  // this module, 0x4c9a70
extern void main_switch_structure_bsp_and_notify(void);  // this module, 0x4c9b60
extern void movie_capture_frame_export(void);  // 0x4c9530
extern void movie_play_bink(const char *movie_path);  // 0x43ed20, foreign (main module)
extern uint32_t __stdcall network_game_client_connect_by_hostname(char *host_port_string);  // 0x4c83e0, this module (thread proc)
extern void network_game_client_connect_to_resolved_address(void);  // this module, 0x4c8660
extern uint32_t network_hostname_resolve_thread_proc(char *hostname);  // 0x4c8340, this module
extern char network_hostname_resolve_with_timeout(char *hostname);  // 0x4c8370, this module
extern void render_frame_all_views(float time_since_tick, float time_since_frame);  // this module, 0x4c9260
extern void render_pregame_view_initialize(void);  // UNSURE module
extern void render_view_camera_fill(observer_camera *observer, render_view *view);  // 0x4c9050, this module
extern void screenshot_render(render_view *views);  // 0x4ca1a0, this module
extern void timedemo_benchmark_update(void);  // this module, 0x4c6f30
extern void viewport_split_rect_compute(int32_t view_count, int32_t view_index, Rectangle2D *window, Rectangle2D *out_viewport);  // 0x4c8da0, this module

#endif
