// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/models/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_MODELS_H
#define FN_MODELS_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "models.h"
#include "rasterizer.h"

extern void *animation_get_frame_data(ModelAnimationsAnimation *animation, int16_t frame);  // 0x4d4810
extern void animation_get_frame_info_distance(ModelAnimationsAnimation *animation, float *dx_to_key_frame, float *dx_total);  // 0x4d4850, ECX, stack
extern void animation_get_root_node_matrix(real_matrix4x3 *out, int16_t frame, ModelAnimationsAnimation *animation, GBXModel *model);  // 0x4d49b0, model animation module, not yet rewritten;
extern int16_t animation_keyframe_time_search(uint16_t *times, int16_t count, int16_t frame);  // 0x4d6b10, this batch
extern void animation_quaternion16_decode(int16_t *source, real_quaternion *out);  // 0x4d6330, this batch
extern void animation_quaternion48_decode(animation_quaternion48 *source, real_quaternion *out);  // 0x4d6380
extern int16_t model_marker_group_index_from_name(datum_index model_tag_id, const char *name);  // 0x4d77c0, this batch
extern void model_render_parts(GBXModel *model, uint8_t *region_permutations, rasterizer_node_matrices *node_matrices, model_level_of_detail lod, uint16_t forced_shader_permutation, uint32_t flags);  // 0x4d72a0, this batch

#endif
