// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/networking/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_NETWORKING_H
#define FN_NETWORKING_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "game.h"
#include "networking.h"

extern int32_t autopatch_check_for_update_start(void);  // 0x577240, UNSURE args
extern void autopatch_current_version_string_get(char *out);  // 0x578190, blam-cc: EAX out
extern uint32_t autopatch_download_complete_callback(int32_t request_id, int32_t error, uint8_t *data, uint32_t size);  // 0x576ad0, this module
extern uint32_t autopatch_download_pool_shutdown(void);  // 0x576db0
extern int32_t autopatch_download_pool_tick(void);  // 0x576bc0, this module
extern void autopatch_download_progress_callback(int32_t request, int32_t state, const char *buffer, int32_t buffer_length, int32_t bytes_received, int32_t total_size, void *param);  // 0x576a70
extern uint32_t autopatch_download_worker_thread(void);  // 0x576b80, this module
extern uint8_t autopatch_launch_updater(void);  // 0x577310
extern uint32_t __stdcall autopatch_proxy_initialize(void *parameter);  // 0x5771c0, the proxy thread
extern char *autopatch_temp_name_generate(void);  // other module (UNSURE): source string for the machine's short name
extern uint32_t autopatch_version_check_request(void);  // 0x5771e0, this module
extern ban_list_entry *ban_list_find_by_name(char *key);  // this batch, 0x4e37d0
extern ban_list_entry *ban_list_get_or_add_entry(char *name, char *cd_key_hash);  // this batch, 0x4e3890
extern void build_remote_player_action_update(uint32_t player_index, uint32_t network_key, uint8_t update_id_byte, player_action control);  // this module, 0x4e7890
extern int8_t chimera__on_connect(const uint32_t *target_address, network_client_globals *client, const uint32_t *session_info);  // 0x4d8ed0, this module
extern void console_command_bool_get_set(uint32_t argument_count, uint8_t *value, char **arguments, const char *name);  // 0x4e2990, this module
extern void digital_throttle_decode_vector(real *out, uint32_t code);  // 0x4eb0c0
extern int32_t digital_throttle_encode_vector(real_vector3d vector);  // 0x4eb050
extern int32_t dynamic_pointer_array_add_unique(void *value, server_list_globals *array);  // 0x4ba8a0
extern int32_t dynamic_pointer_array_find_index(server_list_globals *array, void *value);  // 0x4ba870
extern void dynamic_pointer_array_remove_at(int32_t index, server_list_globals *array);  // 0x4ba940
extern void *gamespy_array_nth(void *array, int32_t index);  // 0x61dc00
extern void gamespy_think_all(void);  // 0x6154f0, GameSpy
extern void join_game_ticker_string_copy(uint16_t *buffer, int32_t capacity, int32_t string_index);  // 0x4b6160, ESI, EBX
extern int32_t master_server_connection_start(void);  // 0x4b6000, this module
extern void master_server_connection_wait_thread(void);  // 0x4b6070
extern void master_server_ensure_list_connection(void);  // 0x4b66c0
extern void master_server_list_refresh_request(void);  // 0x4b6660
extern void master_server_process_pending_requests(void);  // 0x4b5d70, this module
extern int32_t message_delta_decode_array_field(void **context);  // 0x4ec510, EAX
extern int32_t message_delta_decode_begin(message_delta_decode_state *state, bit_stream *stream);  // 0x4ec490, EAX, EDI
extern int32_t message_delta_decode_field_changed_flags(void **context);  // 0x4ed070, this module
extern int32_t message_delta_decode_message_header(bit_stream *stream, message_delta_decode_state *state);  // 0x4ece70, this module
extern int32_t message_delta_decode_static_fields(int32_t message_type, bit_stream *stream, int32_t offset);  // 0x4ed290, this module
extern void message_delta_definitions_invoke_field_bindings(void);  // 0x4ec390
extern void message_delta_definitions_teardown_field_bindings(void);  // 0x4ec750, this module
extern uint8_t message_delta_encode_all_fields(uint8_t *ctx, int32_t static_base, int32_t item, int32_t type_base);  // 0x4ecc00, EAX ctx
extern uint8_t message_delta_encode_field(int32_t changed_offset, uint8_t *ctx, int32_t field_index, int32_t type_offset);  // 0x4ecde0, EAX changed_offset, ESI ctx
extern uint8_t message_delta_encode_message_header(uint8_t *ctx);  // 0x4ecd00, ESI ctx
extern uint8_t message_delta_encode_prepare_item(uint8_t *ctx);  // 0x4ecb60, EAX ctx
extern void message_delta_field_bindings_invoke(message_delta_static_fields *list);  // 0x4ec700, this module
extern uint8_t message_delta_field_bindings_lazy_init(message_delta_static_fields *list);  // 0x4ec840, this module
extern void message_delta_field_bindings_teardown(message_delta_static_fields *list);  // 0x4ec900, this module
extern void message_delta_field_layout_compute_size(message_delta_definition *definition);  // 0x4ec790, this module
extern int32_t message_delta_float_array_encode(message_delta_field_type *field_type, float *previous, float *values, bit_stream *stream);  // 0x4e9db0
extern void message_delta_metrics_dump(char *suffix);  // 0x4ec3d0, blam-cc: ESI
extern void message_delta_parameters_protocol_dump_to_config_file(void);  // 0x4ec330, outside this batch
extern void message_delta_parameters_protocol_format_received_values(int32_t *values);  // 0x4ec230, this module
extern void message_delta_parameters_protocol_format_registered_values(void);  // 0x4ec050, this module
extern void message_delta_parameters_protocol_free_registered(void);  // 0x4ebd50, this module
extern void message_delta_parameters_protocol_receive_update(void **context);  // 0x4ec000, EAX
extern void message_delta_parameters_protocol_register(char *scope, char *name, int32_t type, void *value);  // 0x4ebe00, EAX scope
extern void message_delta_parameters_protocol_reload_from_config_file(void);  // 0x4ebda0
extern void message_delta_parameters_protocol_send_update(void);  // 0x4ebf50
extern void message_delta_protocol_initialize(void);  // 0x4ec2f0, outside this batch
extern void message_delta_sample_record_and_append(int32_t a, int32_t c, int32_t b, message_delta_sample_ring_buffer *ring);  // 0x4ed310, blam-cc: EAX a, ECX c, EDX b, stack ring
extern void message_delta_sample_ring_buffer_append(message_delta_sample_ring_buffer *ring, const int32_t *entry);  // 0x4ed390, this module
extern int32_t message_delta_sample_ring_buffer_average(message_delta_sample_ring_buffer *ring);  // 0x4ed350, blam-cc: ECX ring
extern int32_t mutex_create(network_mutex_record **out_handle);  // 0x440510, this module
extern char network_address_parse_port(char *address_string, int32_t *port_out);  // 0x4dc560, foreign
extern char network_address_string_is_valid(char *address_string);  // 0x4dc730, foreign (networking module)
extern char network_address_string_normalize(char *address_string, char *out_buffer, uint8_t *out_is_any);  // 0x4dc5e0, foreign
extern int32_t network_bandwidth_graph_find_peak_sample(int32_t *out_peak_countdown, network_bandwidth_graph *graph);  // 0x4d8140, this batch
extern void network_bandwidth_graph_instance_init(network_bandwidth_graph *graph, int32_t units_index, int32_t direction_index);  // 0x4d7de0, this batch
extern void network_bandwidth_graph_instance_update_layout(network_bandwidth_graph *graph, uint8_t force_refresh);  // 0x4d7e20, already committed
extern void network_bandwidth_graph_new_sample(network_bandwidth_graph *graph);  // 0x4d8430, this batch
extern uint32_t network_bandwidth_graph_reset(void);  // 0x4d7980, foreign (networking)
extern uint32_t network_bandwidth_graph_set_units_command(const char *units_name, const char *direction_name);  // 0x4d7d90, blam-cc: ECX, stack
extern void network_bandwidth_graph_tick(network_bandwidth_graph *graph);  // 0x4d84d0, blam-cc: EAX -> graph
extern void network_bandwidth_graph_update(void);  // 0x4d7ad0, networking module
extern void network_bandwidth_graph_update_columns(int32_t new_sample, network_bandwidth_graph *graph);  // 0x4d81c0, this batch
extern void network_bandwidth_rate_compute(network_bandwidth_graph *graph);  // 0x4d8540, blam-cc: ESI -> graph
extern void network_banlist_load(void);  // 0x4e3160, foreign (networking)
extern void network_banlist_print(void);  // 0x4e34e0
extern void network_banlist_save(void);  // 0x4e3380
extern void network_buffer_pair_pool_clear(void);  // 0x4e3ed0, foreign (networking module)
extern void network_channel_connected_callback(void *connection, int32_t result, const uint8_t *message, int32_t length);  // 0x441e00
extern void network_channel_delete(network_channel *channel);  // 0x4dcae0, this batch
extern char network_channel_dispatch_bitstream_unit(network_server_globals *server, uint32_t unit, bit_stream *stream, network_machine *machine);  // 0x4e18b0, stack, stack, ECX, ESI
extern char network_channel_drain_bitstream(network_server_globals *server, network_machine *machine);  // 0x4e1290, this batch
extern int32_t network_channel_incoming_read_item(network_channel *channel, uint8_t *destination, int32_t *out_bit_offset, int32_t *out_remaining_bits, s_network_address *out_address, int32_t max_item_bits);  // 0x4dcf10, stack x5, EAX max bits
extern uint8_t network_channel_key_resolve_target(network_player_entry *entry);  // 0x4ddcc0, this batch
extern int32_t network_channel_list_add(network_receive_queue *entry, network_channel_list *list);  // 0x441a40, this module
extern int32_t network_channel_list_mark_readable(network_channel_list *list);  // 0x4419d0, this module
extern network_channel_list *network_channel_list_new(int16_t requested_capacity);  // 0x441960, this module
extern int32_t network_channel_list_remove(network_receive_queue *entry, network_channel_list *list);  // 0x441b00, this module
extern char network_channel_listen_service(network_channel *channel, network_channel **out_new_child);  // 0x4dd4e0
extern network_channel *network_channel_new(uint32_t flags);  // 0x4dc9b0, this batch
extern network_channel *network_channel_new_child(network_receive_queue *endpoint);  // 0x4dd430, this batch
extern void network_channel_receive_callback(void *handle, uint8_t *data, int32_t length);  // 0x441ed0
extern void network_channel_record_timestamp(network_channel *channel);  // 0x4dd930, this batch
extern int32_t network_channel_reliable_pool_ensure_capacity(network_channel *channel, int32_t body_capacity_needed, int32_t header_capacity_needed);  // 0x4dcc30, this batch
extern void network_channel_remote_address_or_default(network_channel *channel, network_resolved_address *out_address);  // 0x4dd390, this module
extern void network_channel_scan_retransmit_timeouts(network_channel *channel);  // 0x4dd9d0, this batch
extern int32_t network_channel_service_close_if_disconnected(network_channel *channel);  // 0x4dd3f0
extern char network_channel_stream_flush(network_channel_stream *stream, network_channel *channel, char mode);  // 0x4ddb60, ESI stream (channel +0x10), stack channel, mode
extern void network_channel_stream_init(network_channel_stream *stream);  // 0x4dd980, this batch
extern char network_channel_transmit(network_channel *channel);  // 0x4dd730, this batch
extern void network_channels_close(void);  // 0x441480
extern void network_channels_open(void);  // 0x441300
extern void network_client_connection_handshake_tick(int16_t state, network_server_globals *owner);  // 0x4e0590, EAX, ECX
extern char network_client_drain_queued_updates(network_server_globals *server, network_machine *machine, bit_stream *stream);  // 0x4e1f40, stack, stack, ECX
extern void network_client_globals_dispose(void);  // 0x4dde70, UNSURE
extern void network_client_rejoin_check(int8_t machine_player_index);  // 0x4de390
extern void network_client_send_local_player_updates(void);  // 0x4e77e0, UNSURE module
extern void network_client_timer_default_or_disconnect(network_client_globals *client);  // 0x4d9ce0, this batch
extern char network_client_update_dispatch(void);  // 0x4dded0, foreign (networking)
extern int32_t network_connection_finalize_join(uint16_t *connection);  // 0x4d9960, this batch
extern int32_t network_connection_initiate(network_client_globals *connection, const uint32_t *target, const uint32_t *session_info);  // 0x4d8cf0
extern void network_connection_retransmit_if_overdue(const uint32_t *sender_address, network_client_globals *client, uint32_t deadline_ms, int32_t remote_time);
extern void network_connection_send_keepalive(network_client_globals *client);  // 0x4d9400
extern void network_connection_stats_log_tick(void);  // 0x440d80, this module
extern int32_t network_connection_stats_lookup_or_add(int32_t connection_id, uint16_t connection_key);  // 0x440a80, this module
extern void network_connection_stats_record_packet(void *gamespy_connection, int32_t payload_length, uint8_t is_sent, uint8_t is_reliable, uint8_t is_resend);  // 0x440b20, blam-cc: EAX connection, ECX length
extern void network_disconnect_notify_dropped_machines(network_client_globals *client);  // 0x4d9340, EBX
extern void network_dispatch_initialize(void);  // 0x4414c0
extern void network_game_action_apply(void **context, network_client_globals *client);  // 0x4da320, EAX, ECX
extern char network_game_action_queue_drain(network_client_globals *client, bit_stream *stream, const uint32_t *sender);  // 0x4db870, stack
extern void network_game_broadcast_team_object_updates(int32_t *object_count, uint32_t param_1, int32_t *bytes_sent);  // 0x4df950, this batch
extern void network_game_client_apply_received_update(network_machine *machine, uint32_t server, void **message);  // 0x4e0280
extern uint32_t network_game_client_handle_map_data(network_server_globals *server, uint8_t *record, int32_t length);  // 0x4e2790
extern uint32_t network_game_client_handle_retry_schedule(network_server_globals *server, network_machine *machine, uint8_t *record, int32_t length);  // 0x4e2870
extern uint32_t network_game_client_handle_settings_relay(network_server_globals *server, uint8_t *record, int32_t length);  // 0x4e2810
extern int8_t network_game_client_update(network_client_globals *client);  // 0x4daf80
extern wchar_t *network_game_get_random_player_name(void);  // 0x4dea80, this batch
extern char network_game_message_decode_dispatch(network_client_globals *client, uint16_t *record, int32_t record_length, const uint32_t *sender);  // 0x4db6b0, EAX, EDX, EDI, stack
extern uint32_t network_game_message_handle_build_version(network_server_globals *server, network_machine *machine, uint8_t *record, int32_t length);  // 0x4e2630
extern uint32_t network_game_message_handle_handshake_forward(network_server_globals *server, uint8_t *record, int32_t length);  // 0x4e25e0
extern uint32_t network_game_message_handle_join_finalize_ack_role2(network_server_globals *server, network_machine *machine, uint8_t *record, int32_t length);  // 0x4e2930
extern uint32_t network_game_message_handle_keepalive(network_channel **channel, int32_t *record);  // 0x4e2110, EAX machine, stack
extern uint32_t network_game_message_handle_ping_timestamp(int32_t **message, network_server_globals *server);  // 0x4e20b0
extern uint32_t network_game_message_handle_player_count_broadcast(network_server_globals *server, uint8_t *record, int32_t length);  // 0x4e2530
extern uint32_t network_game_message_handle_player_entry_update(network_server_globals *server, uint8_t *record, int32_t length);  // 0x4e2580
extern uint32_t network_game_message_handle_retry_schedule(network_server_globals *server, network_machine *machine, uint8_t *record, int32_t length);  // 0x4e26a0
extern uint32_t network_game_message_handle_settings_relay(network_server_globals *server, uint8_t *record, int32_t length);  // 0x4e24d0
extern uint32_t network_game_message_handle_settings_relay_role2(network_server_globals *server, uint8_t *record, int32_t length);  // 0x4e28d0
extern uint32_t network_game_process_incoming_message(int32_t length, network_machine *machine, uint16_t *record, network_server_globals *server);  // 0x4e1c60, EAX, ECX, EDX, stack
extern int32_t network_game_process_incoming_messages(network_client_globals *client);  // 0x4db180
extern char network_game_scenario_load_request(network_game_session *session);  // 0x4de6d0
extern int32_t network_game_search_results_add_or_update(network_game_search_entry *results, const uint8_t *announcement);  // 0x4da7d0, blam-cc: EBX -> announcement, stack -> results
extern void network_game_server_handle_client_join(int32_t *object_count_passthrough, network_server_globals *server, network_machine *machine, uint8_t bl_passthrough);  // 0x4dfc90, stack (server, machine)
extern uint32_t network_game_server_handle_info_request(network_server_globals *server, network_machine *machine, uint8_t *record, int32_t length);  // 0x4e2700
extern char network_game_server_handle_join_confirm(network_machine *machine, network_server_globals *server, uint8_t *buffer, int32_t length);  // 0x4e2400, EAX machine, ECX server, EDX record, stack length
extern char network_game_server_handle_join_password(network_machine *machine, network_server_globals *server, uint8_t *buffer, int32_t length);  // 0x4e21d0, EBX machine, stack (server, record, length)
extern void network_game_server_handoff_object_ownership(int32_t *object_count_passthrough, network_server_globals *server, network_machine *machine);  // 0x4dfa10, this batch
extern char network_game_server_load_scenario(void);  // 0x4e0720, outside this batch, elided args
extern void network_game_session_reset(network_game_session *session);  // 0x4de470, this batch
extern uint32_t network_game_settings_broadcast_send(uint32_t round, uint32_t *record);  // 0x4df0e0, stack (server, record)
extern void network_game_settings_packet_send(network_client_globals *client, const uint8_t *request);  // 0x4d94c0
extern void network_handle_registry_close_all(void);  // 0x441bb0, this module
extern char network_host_channel_service_tick(network_client_globals *client);  // 0x4db100
extern char network_host_lobby_tick(network_client_globals *client);  // 0x4daef0
extern void network_host_presence_broadcast_tick(network_client_globals *client);  // 0x4dadb0
extern int32_t network_host_shutdown_or_defer(void);  // 0x4ddd90, result tested in AL
extern char network_host_update_tick(network_server_globals *host);  // 0x4def80, this module
extern void network_hostname_thread_proc(char *hostname_buffer);  // 0x441510, this module
extern char network_incoming_item_dispatch(network_client_globals *client, uint32_t item_flag, bit_stream *stream, const uint32_t *sender);  // 0x4db630, stack, stack, ECX, ESI
extern int16_t network_initialize(void);  // 0x4415c0, this module
extern void network_join_hostname_resolved_callback(int32_t resolve_failed, uint32_t unused, uint8_t *hostent);  // 0x4ba270, this module
extern uint8_t network_join_request_reset_state(network_machine *machine, const char *response);  // 0x4e0ab0, blam-cc: EAX machine
extern void network_join_status_text_update(int32_t mode, network_client_globals *client);  // 0x4db4c0
extern network_receive_queue *network_listen_accept_pending_connection(void);  // 0x4421b0, this module
extern void network_listen_connection_request_handler(int32_t listen_handle, int32_t reply_socket, uint32_t remote_address, uint32_t remote_port_raw, int32_t transport_handle, uint32_t *payload, uint32_t payload_length);  // 0x442090, this module
extern uint32_t network_listen_reject_pending_connection(int32_t reject_code);  // 0x442250, this module
extern uint32_t network_listen_start(network_receive_queue *queue);  // 0x442170, this module
extern int network_local_hostent_get(void **out_hostent);  // 0x441540, this module
extern void network_machine_check_build_version(const char *remote_version, network_machine *machine);  // 0x4dff20, EAX, EDI
extern uint32_t network_machine_clear_flag_by_id(network_server_globals *server, int32_t machine_id);  // 0x4e0b90,
extern int32_t network_machine_reset(network_machine *machine);  // 0x4df690, blam-cc: ESI machine
extern void network_machine_timer_start(network_machine *machine, int32_t duration_ms);  // 0x4df090, ESI, stack
extern void network_map_cycle_list_broadcast(void);  // 0x4deec0, this batch
extern uint16_t *network_message_read_sized_buffer(uint16_t *buffer, int32_t capacity, bit_stream *stream);  // 0x4de420, EDI, stack, EBX
extern network_mutex_record *network_mutex_slot_allocate(void);  // 0x440420, this module
extern uint8_t network_name_string_is_valid_for_mode(char *name, void *dest, int32_t mode);  // 0x4e4350, this module
extern void network_object_release_ownership_claim(uint8_t slot_index);  // 0x4dfc10, this batch
extern char network_player_entry_find(network_game_session *session, network_player_entry *key);  // 0x4de900, this batch
extern uint32_t network_player_entry_remove(network_player_entry *key, network_game_session *session);
extern uint8_t network_player_entry_update(network_player_entry *incoming, network_game_session *session);  // 0x4de5f0, EAX, ECX
extern void network_player_update_history_log_write(const char *format, ...);  // established name (CEA/Chimera)
extern int32_t network_random_offset(int32_t base);  // 0x4403b0, this module
extern void network_receive_queue_free(network_receive_queue *queue, int32_t connection_id, int16_t connection_key);  // 0x441c80, this module
extern network_receive_queue *network_receive_queue_new(void);  // 0x441bf0, this module
extern uint8_t network_server_any_machine_awaiting_flag(network_server_globals *server);  // 0x4e14e0, this batch
extern char network_server_build_full_game_info_packet(network_machine *machine);  // 0x4e0bd0, stack
extern int32_t network_server_count_connected_machines(network_server_globals *server);  // 0x4e1880, this batch
extern uint8_t network_server_notify_or_resend_challenge(int16_t reason, network_machine *machine, network_server_globals *server);  // 0x4e0af0
extern void network_server_password_get(network_server_globals *server, wchar_t *dest);  // 0x4e0930, blam-cc: EAX server, ESI dest
extern void network_server_password_set(const wchar_t *source, network_server_globals *server);  // 0x4e0910, this module
extern char network_server_service_machines_tick(network_server_globals *host);  // 0x4e11d0, outside this batch, elided arg
extern void network_session_disconnect_with_error(int16_t error_code);  // 0x4d97e0, this batch
extern void network_session_host_cd_key_callback(int32_t game_id, int32_t local_id, int32_t authenticated, const char *message, void *instance);  // 0x5760a0
extern void network_session_host_dispatch_message(int32_t key_id, int32_t index, void *buffer, void *user_data);  // 0x577e40
extern void network_session_host_dispose(void);  // 0x5778f0
extern void network_session_host_natneg_callback(int32_t cookie);  // 0x578160
extern void network_session_host_natneg_completed(int32_t result, uint32_t socket, const uint8_t *remote_address, void *user_data);  // 0x578120
extern void network_session_host_qr2_add_error(int32_t error, char *message, void *user_data);  // 0x578100
extern int32_t network_session_host_qr2_count(int32_t key_type, void *user_data);  // 0x5780c0
extern void network_session_host_qr2_key_list(int32_t key_type, void *keybuffer, void *user_data);  // 0x577fb0
extern void network_session_host_qr2_server_key(int32_t key_id, void *buffer, void *user_data);  // 0x5779c0
extern void network_session_host_qr2_team_key(int32_t key_id, int32_t index, void *buffer, void *user_data);  // 0x577f40
extern uint8_t network_session_host_reject_or_cleanup_client(const char *response, const char *challenge, uint32_t ip, int32_t local_id);  // 0x575ff0, blam-cc: EAX response, ECX challenge, EDX ip, ESI local_id
extern void network_session_host_start_info_set(char *game_name, char *secret_key, char *ip_address, int32_t port);  // 0x576100, blam-cc: EAX, ESI, EDI, stack
extern void network_session_host_update(void);  // 0x577940, foreign
extern void network_session_player_join_notify(network_client_globals *client, const uint32_t *source);  // 0x4d9700, this batch
extern uint8_t network_session_player_table_index_apply(network_client_globals *client, int32_t table_index, const uint8_t *candidate);  // stack client, table index; EBX candidate // 0x4d9190, elided
extern int32_t network_session_reject_pending_connection_callback(void *unused, int32_t reject_code);  // 0x4e1410
extern void network_stats_summary_log_open(void);  // 0x440670, this module
extern void network_stats_summary_log_write(void);  // 0x440820, this module
extern int32_t network_thread_create(uint8_t flags, void *start_address, void *parameter, network_thread_record **out_handle);  // 0x440460, this module
extern void network_timer_advance(network_timer_pair *timer);  // 0x4deb50, this module
extern void network_timer_decrement_floored(network_timer_pair *timer, int32_t decrement);  // 0x4debd0
extern void network_timer_increment_clamped(network_timer_pair *timer, int32_t upper_bound, int32_t increment);  // 0x4debb0
extern void network_timer_start(network_timer_pair *timer, int32_t duration_ms);  // 0x4debf0
extern uint32_t network_update(void);  // 0x4418d0, foreign (networking)
extern player_update_history_node *player_update_history_find_and_prune( player_update_history *history, int32_t target_id, uint8_t prune);  // this module, 0x4e6f60
extern void qr2_register_key(int32_t keyid, const char *key);  // 0x61bb40, GameSpy qr2: custom server key names
extern uint32_t registry_get_dist_id(void);  // 0x577760, this module
extern char *registry_get_halo_version(void);  // 0x5776d0, this module
extern void server_browser_column_header_update(network_ui_widget *header, int32_t sort_direction);  // 0x4b7f10, this module
extern void server_browser_custom_options_unpack(char *text, server_browser_custom_options *out);  // 0x5764a0
extern void server_browser_filter_headers_refresh(network_ui_widget *row);  // 0x4b7f70, this module, see UNSURE below at its call site
extern void server_browser_gametype1_flags_unpack(uint32_t code, server_browser_gametype1_decoded *out);  // 0x576890 (ctf)
extern uint32_t server_browser_gametype2_flags_pack(uint8_t *flags);  // 0x576920, blam-cc: EAX
extern void server_browser_gametype3_flags_unpack(uint32_t code, server_browser_gametype3_options *out);  // 0x576a20 (oddball)
extern uint32_t server_browser_gametype5_flags_pack(int32_t *values);  // 0x576960, blam-cc: EDX
extern void server_browser_gametype5_flags_unpack(uint32_t code, int32_t *out);  // 0x576990 (race), out[0]/out[1]
extern void server_browser_latch_join_target(void);  // 0x4b6730
extern void server_browser_list_row_gather(network_ui_widget *row, uint8_t flag, void *entry);  // 0x4b69c0, this module
extern void server_browser_list_row_populate(network_ui_widget *row, uint8_t flag1, uint8_t flag2, const char *server_name, wchar_t *map_name, const char *gametype_name, uint8_t flag3, int32_t count_a, int32_t count_b, int32_t ping);  // 0x4b67e0, this module
extern int32_t server_browser_selected_variant_description_build(void *entry);  // 0x4b74e0, this module
extern uint8_t server_browser_server_passes_filter(void *server_record);  // 0x4b7080, this module
extern server_browser_sort_comparator server_browser_sort_comparator_select(void);  // 0x4ba970
extern void server_browser_total_players_compute(server_list_globals *array);  // 0x4baa60, this
extern void server_browser_ui_refresh(void);  // 0x4b73a0, this module
extern int32_t server_list_compare_by_gametype(const void *, const void *);  // 0x4b6fb0, outside this batch, UNSURE name
extern int32_t server_list_compare_by_hostname(const void *, const void *);  // 0x4b6cd0, outside this batch, UNSURE name
extern int32_t server_list_compare_by_mapname(void **a, void **b);  // 0x4b6c20, this module
extern int32_t server_list_compare_by_players(const void *, const void *);  // 0x4b6e70, outside this batch, UNSURE name
extern int32_t server_list_compare_by_string_key(void **a, void **b, const char *key);  // 0x4b6be0
extern server_list_globals *server_list_mutex_try_lock(uint32_t timeout_ms);  // 0x4ba760, this module
extern void server_list_mutex_unlock(server_list_globals **list_slot);  // 0x4ba7a0
extern void server_list_result_reset(uint8_t *entry);  // 0x4ba7c0, this module (entry == NULL here)
extern void server_list_scroll_page_down(uint8_t jump_to_bottom);  // 0x4b7bb0, AL
extern void server_list_scroll_page_up(uint8_t jump_to_top);  // 0x4b7b20, AL
extern uint32_t __stdcall sig__setup_master_server_connection_sig(void *parameter);  // 0x4b5f80, the thread routine
extern void sv_map(uint32_t argument_count, uint16_t **arguments);  // 0x4e2b20, blam-cc: EAX, EBX
extern void sv_map_reset(void);  // 0x4e2aa0
extern void sv_players(void);  // 0x4e2c70
extern void sv_status(void);  // 0x4e2e50
extern void ticker_text_buffer_advance(uint8_t *widget, ticker_text_buffer *self);  // 0x4b8b40, this
extern void vector3d_quantize(int32_t *out_indices, int32_t *descriptor, real *point);  // 0x4eb4a0
extern void vector3d_to_angles(real *out, real_vector3d vector);  // 0x4ea720

#endif
