// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/objects/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_OBJECTS_H
#define FN_OBJECTS_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "objects.h"
#include "rasterizer.h"

extern void antenna_render_geometry(Antenna *antenna_tag, antenna *ant);  // 0x4fb340, blam-cc: EDI -> antenna_tag, stack -> ant
extern void breakable_surfaces_reset(void);  // 0x4ffd40, objects (breakable_surface_globals reset, R79)
extern void damage_data_initialize(damage_data *dd, datum_index damage_effect_tag);  // 0x4ed990
extern void damage_effect_new_at_location(datum_index effect_tag, int16_t node_index, real_vector3d *normal, real_vector3d *incident, real_point3d *impact_position, uint32_t object_index);  // 0x4f0010, stack, EAX, ECX, EBX, EDI
extern glow_particle *glow_particle_datum_new(void);  // this module, 0x4fdde0
extern void hash_table_dispose(hash_table *table);  // 0x4f04c0, EDI table
extern void hash_table_grow_freelist(hash_table *table);  // 0x4f0620, ESI = table, same file
extern void hash_table_initialize(hash_table *table, int32_t bucket_count);  // 0x4f0470, ESI table, EAX buckets
extern void hash_table_set_or_remove(hash_table *table, int32_t key, int32_t value);  // 0x4f0530
extern datum_index light_cluster_iterate_begin(datum_index *cursor, int16_t cluster_index);  // 0x4f34c0
extern datum_index light_cluster_iterate_next(datum_index *cursor);  // 0x4f3500
extern int16_t light_collect_object_references(uint32_t light_handle, int16_t max_count, int16_t *out_buffer);
extern void light_get_render_bounds(datum_index handle, real_point3d *center_out, float *radius_out);  // 0x4f3530
extern uint8_t light_mark_this_frame(datum_index handle);  // 0x4f3650
extern datum_index light_new_attached(datum_index light_tag, datum_index owner_object, int16_t marker_index, int16_t marker_index_secondary, int16_t change_color_index);  // 0x4f0af0, all on the stack
extern datum_index light_new_positioned(datum_index light_tag, int32_t marker_index, int16_t marker_sub_index, real_point3d *position, uint32_t param_5, real_vector3d *direction);  // 0x4f0c10
extern uint8_t light_not_marked_this_frame(datum_index handle);  // 0x4f3620
extern void light_volume_render_procedure(uint32_t object_index, datum_index light_volume_handle);  // 0x4fea80
extern void lights_apply_spot_falloff(void);  // 0x4f1780, objects module
extern void lights_apply_spot_falloff_specular(void);  // 0x4f1950, objects module
extern void lights_dispose_all(void);  // 0x4f0aa0
extern void lights_initialize(void);  // 0x4f0a20
extern void object_apply_body_damage(uint32_t target_index, int32_t region_index, int32_t node_index, void *plane, uint8_t *geometry, uint8_t *material, uint8_t *effect_block, damage_data *dd, uint32_t *notify_flags, float *body_damage_out, float *material_multiplier_out, float damage, uint8_t is_local);  // 0x4ef2a0
extern void object_apply_impulse_and_spin(uint32_t object_index, real_vector3d *delta_velocity);  // 0x4bef80, EAX, EDX
extern void object_apply_linked_impulse(void **context);  // 0x4efc80, EAX
extern void object_apply_shield_charge_and_notify(void **context);  // 0x4ee4d0, EAX
extern void object_apply_shield_damage(uint32_t target_index, uint8_t *geometry, uint8_t *material, uint8_t *effect_block, uint32_t *notify_flags, float *shield_damage_out, float *remaining_damage, uint8_t is_local, uint8_t apply_state, object_shield_impulse_result *record);  // 0x4ef820, EBX record
extern void object_build_effect_parameter_block(uint8_t flags, real_vector3d *shading_normal, float intensity, ColorRGB *lightmap_color, real_vector3d *lightmap_normal, ColorRGB *base_map_color, render_lighting *lighting);
extern void object_children_recurse_prune(uint32_t object_index);  // 0x4edc10
extern uint8_t object_cluster_stamp_mark_visited(datum_index object_index);  // 0x4f9720
extern uint8_t object_cluster_stamp_not_visited(datum_index object_index);
extern int16_t object_collect_in_clusters(uint32_t search_mask, int16_t cluster_count, int16_t *cluster_indices, int16_t max_output, datum_index *out_objects);  // 0x4f7180,
extern void object_create_attachments(uint32_t object_index);  // 0x4f9750
extern void object_damage_apply_line_of_sight(damage_data *dd, datum_index target_index, int8_t continue_flag);  // 0x4eddb0
extern void object_damage_notify_and_impulse(uint32_t target_index, damage_data *dd, uint32_t notify_flags, float shield_damage, float body_damage, uint32_t unused_6, int32_t region_index, uint32_t is_local);  // 0x4efcf0
extern void object_delete_teardown(uint32_t object_index);  // 0x4edc80, EAX
extern void object_destroy_region(uint32_t object_index, int32_t region_index);  // 0x4f02d0, EAX, stack
extern void object_dispatch_effect_notify(uint32_t forwarded_eax, uint32_t forwarded_ecx);  // 0x4efff0, EAX, ECX
extern int object_dump_compare_by_total_size(const object_memory_dump_record *a, const object_memory_dump_record *b);  // 0x4fa3a0, this batch
extern void object_get_center_of_mass_and_scale(real_point3d *out_center, uint32_t object_index, float *out_radius);  // 0x4088e0, blam-cc: EAX out_center, ECX object_index
extern int32_t object_get_controlling_player_index(datum_index object_index);  // 0x4ee2e0, EAX
extern real_matrix4x3 *object_get_node_marker_address(uint32_t object_index, int16_t node_index);  // 0x4f6000, EAX, stack
extern void object_hash_clear_flag_bit3(uint32_t key);  // 0x4ef160, blam-cc: EAX
extern void object_hash_set_flag_bit3(uint32_t key);  // 0x4ef200, blam-cc: EAX
extern void object_initialize_shield_stun_thresholds(uint32_t object_index, float *override_max_body_vitality, float *override_max_shield_vitality);  // 0x4ed440, blam-cc: EAX, ESI, EDI
extern void object_lights_update_all(void);  // 0x4f0cf0, objects module
extern datum_index object_new(object_placement_data *placement);  // 0x4f5460, UNSURE signature
extern datum_index object_new_from_scenario_placement(uint8_t *placement, TagReflexive *palette);  // 0x4f9b70,
extern void object_queue_pickup_denied_event(void *param_1, int32_t key, uint32_t *source);  // 0x4efbf0, stack, ECX, EDI
extern void object_recalculate_bounding_radius(uint32_t object_index);  // 0x4f8310
extern void object_regions_reset_permutation_lock(uint32_t object_index, int8_t unlock);  // 0x4f03e0
extern uint8_t object_reposition_to_spawn_location(uint32_t object_index, real_point3d *target_position, uint32_t ignore_object_index);  // 0x4f7b70, stack, ECX
extern datum_index object_resolve_collideable_reference(datum_index *next_reference, int16_t cluster_index);  // 0x4f5f00, objects module
extern uint8_t object_restore_full_body_vitality(uint32_t object_index);  // 0x4ed9d0, UNSURE exact signature
extern void object_sample_ambient_lightmap_point(real_point3d *point, real_vector3d *lightmap_color, real_vector3d *base_map_color, uint8_t wait_for_textures);  // 0x4f1e60, objects module, cdecl
extern void object_sample_total_lighting_at_point(real_point3d *point, bsp_leaf_reference *location, real_vector3d *out_rgb);  // 0x4f1c20, cdecl (orphan pass 4)
extern void object_set_cluster_and_parent(uint32_t object_index, bsp_leaf_reference *location);  // 0x4f5c30
extern void object_set_health_frozen_flag(uint32_t object_index);  // 0x4eda20
extern void object_set_shield_depleted_flag(uint32_t object_index);  // this module, 0x4edb10
extern uint8_t object_shield_recharge_start(uint32_t object_index);  // 0x4edba0, UNSURE exact signature
extern real object_sum_attached_light_luminance(uint32_t object_index);  // 0x4f1b30, UNSURE signature
extern void object_throttled_multiplayer_sound_event(void);  // this module, 0x4ee370 // this module, 0x4ee370 (object_throttled_multiplayer_sound_event)
extern void object_type_definition_chain_build(void);  // 0x4f3db0, this batch
extern void object_type_definitions_notify_two_args_0x2c(uint32_t object_index, uint32_t event_argument);  // 0x4f3f20
extern void object_type_definitions_notify_two_args_0x48(uint32_t object_index, uint32_t event_argument);  // 0x4f4250
extern uint8_t object_type_definitions_query_0x34(uint32_t object_index);  // 0x4f4000, EAX -> object_index
extern uint8_t object_type_definitions_query_0x44(uint32_t object_index);  // this module, 0x4f41d0
extern void object_update_vitality_and_regeneration(uint32_t object_index);  // established
extern void objects_dispose(void);  // 0x4f4db0, objects module
extern void objects_dump_memory(void);  // 0x4fa500
extern void objects_flush_dirty_state(void);  // 0x4f4cc0
extern void objects_garbage_collection(void);  // 0x4f9c60
extern int16_t objects_get_ambient_cluster(void);  // 0x4f7a50, not in this batch; UNSURE exact signature
extern void objects_initialize(void);  // 0x4f4ad0
extern void objects_reset(void);  // 0x4f4bb0
extern void objects_update(void);  // 0x4f4e90, objects module
extern void scenario_objects_place_for_structure_bsp(uint8_t place);  // 0x4f4880, stack -> place
extern void widgets_dispose(void);  // 0x4ffa10
extern void widgets_dispose_clear_flag(void);  // 0x4ffa50
extern void widgets_initialize(void);  // 0x4ff9d0

#endif
