// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/projectiles/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_PROJECTILES_H
#define FN_PROJECTILES_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "projectiles.h"
#include "objects.h"

extern void projectile_request_state(datum_index projectile_index, int16_t requested_state);  // 0x4bf0f0, this batch
extern void projectile_response(datum_index projectile_index, collision_result *hit, real_point3d *out_position, real_vector3d *velocity);  // 0x4bf390, stack + EAX
extern void projectile_send_attach(datum_index projectile_index, datum_index parent_object_index, int16_t marker_index);  // 0x4bf120, this batch
extern int32_t projectile_send_creation(uint32_t projectile_index);  // 0x4c0b10 (pushes the scratch buffer too)
extern void projectile_send_detonation(datum_index projectile_index);  // 0x4bda60

#endif
