// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/physics/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_PHYSICS_H
#define FN_PHYSICS_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "objects.h"
#include "physics.h"
#include "projectiles.h"

extern void breakable_surface_damage_in_blast_radius(damage_data *dd);  // UNSURE: objects module, 0x4fff20 (out of range)
extern void breakable_surface_shatter(uint16_t surface_index, damage_data *damage, int32_t collision_surface_index);  // 0x500090
extern int32_t bsp2d_node_find_leaf(int32_t node_index, TagReflexive *bsp2d_nodes, real_point2d *point);  // 0x501340, this batch
extern uint8_t collision_bsp_query_pill_init(ModelCollisionGeometryBSP *bsp, collision_bsp_pill_result *result, real_point3d *origin, real_vector3d *delta, float radius, float max_fraction);  // 0x502730, EAX, ECX, stack
extern uint8_t collision_bsp_query_pill_leaf_test_surface(collision_bsp_pill_query *query, int32_t surface_index);  // 0x502e70, this batch
extern uint8_t collision_bsp_query_pill_node_recursive(collision_bsp_pill_query *query, int32_t node_index);  // 0x5027a0, this batch
extern uint8_t collision_bsp_query_segment_init(uint32_t flags, collision_bsp_segment_result *result, ModelCollisionGeometryBSP *bsp, int16_t breakable_surface_count, uint32_t *breakable_surfaces, real_point3d *origin, real_vector3d *delta, float max_fraction);
extern uint8_t collision_bsp_query_segment_node_recursive(collision_bsp_segment_query *query, uint32_t node_index, float t_min, float t_max);  // 0x502140, this batch
extern void collision_bsp_query_sphere_collect_geometry(collision_bsp_sphere_query *query, int32_t surface_index);  // 0x501d20, this batch
extern uint32_t collision_bsp_query_sphere_init(ModelCollisionGeometryBSP *bsp, int16_t breakable_surface_count, collision_bsp_sphere_result *result, uint32_t *breakable_surfaces, real_point3d *center, float radius);  // 0x501980, EAX, ECX, ESI, stack
extern void collision_bsp_query_sphere_node_recursive(collision_bsp_sphere_query *query, uint32_t node_index);  // 0x501a10, this batch
extern uint32_t collision_bsp_surface_clip_line_2d(collision_bsp_boundary_clip *clip, ModelCollisionGeometryBSP *bsp, int32_t surface_index, real_point2d *origin, real_vector2d *direction);
extern uint32_t collision_bsp_surface_closest_edge_point_2d(ModelCollisionGeometryBSP *bsp, int32_t surface_index, uint16_t axis, uint8_t sign, real_point2d *point, real_point2d *out_point);
extern int16_t collision_bsp_surface_get_vertices(ModelCollisionGeometryBSP *bsp, int32_t surface_index, real_point3d *out_vertices);  // 0x501400, this batch
extern real_point3d *collision_bsp_surface_solve_third_axis(ModelCollisionGeometryBSP *collision_bsp, int32_t surface_index, uint8_t component_sign, real_point3d *out, int32_t dominant_axis, const real_point2d *known);  // 0x501470, ECX, EAX, stack, stack, ESI, EDI
extern uint8_t collision_bsp_surface_test_point_2d( ModelCollisionGeometryBSP *bsp, int16_t breakable_surface_count, uint32_t *breakable_surfaces, int32_t surface_index, int16_t axis, uint8_t sign, real_point2d *point);  // 0x502600, this batch
extern int32_t collision_bsp_surface_test_point_leaf( ModelCollisionGeometryBSP *bsp, int32_t leaf_index, int16_t breakable_surface_count, uint32_t *breakable_surfaces, uint32_t plane_index, real_point3d *crossing_point, uint8_t two_sided);  // 0x502460, this batch
extern uint8_t collision_bsp_surface_test_point_side_2d(ModelCollisionGeometryBSP *bsp, real_point2d *point, int32_t surface_index, int16_t axis, uint8_t sign);
extern void collision_gather_nearby_object_shapes(uint32_t flags, uint32_t start_object_index, real_point3d *origin, float radius, float x_offset, float y_offset, uint32_t exclude_object_index, physics_model *model);  // 0x5061c0, this module (higher half)
extern uint8_t collision_test_movement_pill(uint32_t flags, real_point3d *origin, float radius, real_vector3d *delta, collision_result *result);  // 0x506040, stack, EDI, ESI
extern int16_t model_collision_geometry_resolve_material_type(int16_t material_index, ModelCollisionGeometry *definition);  // 0x505330, this batch
extern uint8_t object_collision_context_build(uint32_t object_index, object_collision_context *out_context);
extern uint8_t object_collision_context_test_pill(object_collision_context *context, real_point3d *origin, real_vector3d *delta, float radius_scale, object_node_collision_result *out_result);  // 0x5050b0
extern uint32_t object_collision_context_test_point(object_collision_context *context, real_point3d *point);  // 0x504e90, this module
extern uint8_t object_collision_test_cluster_group(uint32_t flags, real_point3d *position, uint32_t exclude_object_index);  // 0x505490, EDI position, stack
extern uint8_t object_collision_test_nearby_chain(uint32_t start_object_index, uint32_t type_mask, real_point3d *position, uint32_t exclude_object_index);  // 0x505350, this batch
extern uint8_t object_collision_test_ray_nearby_chain(uint32_t object_index, uint32_t flags, uint32_t sanitized_flags, real_point3d *origin, real_vector3d *delta, uint32_t exclude_object_index, collision_result *result);  // 0x5055b0, this module (lower half)
extern uint8_t object_physics_add_mass_point_shapes(float x_offset, float y_offset, object_physics_context *context, int16_t *model_counts);  // 0x507790, blam-cc: EBX context
extern void object_physics_blend_friction_axes(int16_t friction_type, float parallel_scale, float perpendicular_scale, float *friction, real_vector3d *forward, real_vector3d *up);  // 0x507c00, stack, EDI friction, ECX forward, EDX up
extern uint8_t object_physics_check_impact_damage(uint32_t *self_object_index, uint32_t candidate_object_index);  // 0x508b70, stack
extern void object_physics_compute_mass_point_forces(object_physics_context *context, powered_mass_point_state *powered_states, uint32_t mass_points, real_vector3d *out_force, real_vector3d *out_torque);  // 0x507cc0
extern uint8_t object_physics_context_build(uint32_t object_index, object_physics_context *out_context);
extern void object_physics_handle_nearby_object_impacts(uint32_t object_index);  // 0x508a10
extern void object_physics_integrate_and_test_at_rest(object_physics_context *context, mass_point_state *mass_point_states, real_vector3d *torque, real_vector3d *force);  // 0x5097e0, stack, ECX force
extern void object_physics_mass_point_resolve_ground_contact(uint32_t exclude_object_index, mass_point_state *mass_point, PhysicsMassPoint *definition);  // 0x507ac0, this module
extern void object_physics_mass_point_update_orientation(real_vector3d *axis, real_vector3d *up, real_vector3d *forward, real_vector3d *fallback_forward, real_vector3d *fallback_up);  // 0x5096f0, this module
extern uint8_t object_physics_resolve_mass_point_overlap(object_physics_context *self, object_physics_context *other);  // 0x5090c0, EDX, stack
extern uint8_t object_physics_test_point_against_mass_points(object_physics_context *context, real_point3d *world_point, int16_t *out_index);  // 0x507590, this module
extern uint8_t object_physics_test_ray_against_mass_points(real_point3d *world_origin, real_vector3d *world_direction, object_physics_ray_result *out_result, object_physics_context *context);  // 0x507610, this module
extern void physics_clamp_value_to_spring_range(float *value, physics_scalar_rates *rates, float step);  // 0x50b370
extern int16_t physics_model_slide_along_contacts(real_point3d *start_position, real_vector3d *delta, physics_model *model, real_point3d *out_position, real_vector3d *out_velocity, int16_t max_contacts, physics_model_contact *contacts);  // 0x5067b0, blam-cc: EAX -> start_position, stack -> the rest
extern uint8_t physics_point_find_clear_position(uint32_t flags, real_point3d *current_position, float sample_radius, float x_margin, float y_margin, uint32_t exclude_object_index, real_point3d *out_position);  // 0x507170, this module
extern uint8_t physics_point_refresh_leaf(real_point3d *point, float radius);  // 0x505540, EDX point, stack radius
extern void physics_point_walk_toward_target(physics_point_walk_state *state, real_point3d *start_position, uint32_t flags, real_vector3d *step_direction, uint32_t exclude_object_index);  // 0x5070d0,
extern int16_t physics_resolve_material_type(uint32_t object_index, int16_t vertex_slot);  // 0x507a40
extern void physics_scalar_advance_and_wrap(physics_scalar_range *range, float *value, uint8_t wrap, float delta);  // 0x50b290
extern float physics_scalar_approach_direction(physics_scalar_range *range, float value, uint8_t wrap, float target);  // 0x50b4d0
extern void physics_shape_add_edge_proxy(int32_t edge_index, ModelCollisionGeometryBSP *bsp, real_matrix4x3 *matrix, float height_offset, float thickness, int32_t object_index, physics_model *model);  // 0x503ae0, blam-cc: EAX edge_index, ECX bsp
extern void physics_shape_add_surface_proxy(ModelCollisionGeometryBSP *bsp, float *moving_frame, int32_t surface_index, float margin, float thickness, int32_t object_index, physics_model *model);  // 0x503c50, blam-cc: EAX bsp, ESI moving_frame
extern void physics_shape_add_vertex_proxy(ModelCollisionGeometryBSP *bsp, uint32_t vertex_index, uint32_t object_index, real_matrix4x3 *matrix, float height_offset, float radius, physics_model *model);  // 0x503a60, blam-cc: ECX bsp, EAX vertex_index, EBX object_index
extern void physics_shape_build_proxies_from_query(collision_bsp_sphere_result *result, real_matrix4x3 *matrix, ModelCollisionGeometryBSP *bsp, float margin, float thickness, int32_t object_index, physics_model *model);  // 0x503d90, blam-cc: EDI result, EAX matrix
extern void physics_shape_edge_to_pill_and_quad( physics_model *model, real_point3d *near_vertex, real_vector3d *edge_dir, float height_offset, float thickness, uint32_t object_index, int32_t surface_index, uint8_t surface_flags, int8_t breakable_surface_index, int16_t material_type);  // 0x503490, this batch
extern uint8_t physics_shape_pill_sweep_test_point(real_point3d *near_vertex, real_vector3d *delta, real_point3d *origin, real_vector3d *edge_dir, float radius, float *out_t, float *out_edge_fraction);  // 0x503050, this batch
extern uint8_t physics_shape_pill_test_point(real_point3d *point, physics_model_pill *pill, real_plane3d *out_normal, float *out_depth);  // 0x503f90, this batch
extern uint8_t physics_shape_pill_test_ray(real_vector3d *delta, real_point3d *origin, real_plane3d *out_plane, physics_model_pill *pill, float *out_t);  // 0x5045c0, this batch
extern uint8_t physics_shape_polygon_test_point(physics_model_shape *shape, real_point3d *point, float *out_depth, real_plane3d *out_normal);  // 0x504120, this batch
extern uint8_t physics_shape_polygon_test_ray(real_point3d *origin, physics_model_shape *shape, real_vector3d *delta, float *out_t, real_plane3d *out_plane);  // 0x5048d0, this batch
extern uint8_t physics_shape_sphere_sweep_test_ray(real_point3d *point, real_point3d *origin, real_vector3d *delta, float *out_t, float radius);  // 0x503290, this batch
extern uint8_t physics_shape_sphere_test_point(real_point3d *point, physics_model_sphere *sphere, real_plane3d *out_normal, float *out_depth);  // 0x503ec0, this batch
extern uint8_t physics_shape_sphere_test_ray(real_point3d *origin, real_vector3d *delta, physics_model_sphere *sphere, real_plane3d *out_plane, float *out_t);  // 0x504430, this batch
extern void physics_shape_surface_to_polygon(int16_t vertex_count, real_point3d *vertices, real_plane3d *plane, float margin, float thickness, uint32_t object_index, int32_t surface_index, uint8_t surface_flags, int8_t breakable_surface_index, int16_t material_type, physics_model *model);  // 0x5038a0, this batch
extern void physics_shape_vertex_to_sphere(physics_model *model, real_point3d *vertex, int16_t material_type, float height_offset, float radius, uint32_t object_index, int32_t surface_index, uint8_t surface_flags, int8_t breakable_surface_index);
extern int16_t physics_sweep_capsule_step(real_point3d *origin, real_vector3d *delta, real_vector3d *out_velocity, uint32_t exclude_object_index, uint32_t flags, float pill_height, float pill_radius, real_point3d *out_position, int16_t max_contacts, physics_model_contact *contacts);
extern void point_physics_interpolate(PointPhysics *out, const PointPhysics *from, const PointPhysics *to, float fraction);  // 0x50b9e0, blam-cc: EAX, ECX, EDX, stack;
extern void vector3d_project_onto_direction(real_vector3d *out, const real_vector3d *axis, const real_vector3d *v);  // 0x506760, blam-cc: ECX out, EAX axis, EDX v

#endif
