// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/rasterizer/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_RASTERIZER_H
#define FN_RASTERIZER_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "rasterizer.h"
#include "interface.h"

extern void bsp_compressed_lightmap_vertex_unpack_normal(ScenarioStructureBSPMaterialCompressedLightmapVertex *vertex, real_vector3d *out);  // 0x5134c0, blam-cc: EAX vertex, ESI out
extern void bsp_compressed_rendered_vertex_unpack_normal(ScenarioStructureBSPMaterialCompressedRenderedVertex *vertex, real_vector3d *out);  // 0x513490, blam-cc: EAX vertex, ESI out
extern void chimera__cinematic_screen_effect(rasterizer_frame_time *time_source);  // 0x517470
extern void chimera__gamma(void);  // 0x5227a0
extern void chimera__rasterizer_draw_dynamic_triangles_static_vertices2(int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_index_slot, int32_t first_primitive, rasterizer_vertex_buffer *second_stream);  // 0x51c310
extern void chimera__rasterizer_set_framebuffer_blend_function(int16_t mode);  // 0x5185d0
extern void chimera__rasterizer_set_frustum_z_func(uint32_t z_near, uint32_t z_far);  // 0x518f40
extern void chimera__rasterizer_set_model_skinning(uint8_t upload, rasterizer_node_matrices *nodes);  // 0x518b40
extern int16_t *chimera__rasterizer_set_texture(uint32_t bitmap_tag_id, int16_t stage, int16_t bitmap_type, int16_t default_index, int16_t frame);  // 0x518960
extern uint8_t chimera__rasterizer_set_texture_direct_d3d9(uint32_t bitmap_tag_id, int16_t stage, int16_t frame);  // 0x518770
extern uint8_t chimera__rasterizer_set_texture_direct_d3dx(uint32_t bitmap_tag_id, int16_t stage, int16_t frame, rasterizer_effect_slot *effect_slot);  // 0x518700
extern void chimera__rasterizer_set_up_node_parts(int32_t node_part_count, uint8_t *node_part_indices);  // 0x526cf0
extern void chimera__registry_check_3(void);  // 0x5226c0
extern void chimera__registry_check_4(void);  // 0x522520
extern void chimera__transparent_decal_zbias(void);  // 0x519530
extern void chimera__widescreen_text_scaling(void);  // 0x531ab0
extern void decal_and_font_system_reset(void);  // UNSURE module
extern void display_mode_get_current(rasterizer_display_mode *out);  // 0x515ca0, blam-cc: EDI out
extern void lens_flare_add_instance(lens_flare_instance *candidate);  // 0x5138a0, EBX candidate
extern float lens_flare_compute_rotation(lens_flare_instance *flare, int16_t mode);  // 0x513540
extern uint8_t *lens_flare_get_visibility_byte(lens_flare_instance *flare);  // 0x5134f0, ECX
extern void lens_flare_render_all(void);  // 0x513cf0, rasterizer module
extern void lens_flare_update_samples(void);  // 0x513ba0, rasterizer module
extern void lens_flare_update_visibility(void);  // 0x513780 (this session)
extern void rasterizer_apply_decal_zbias(void);  // 0x5194e0 (this session)
extern uint8_t rasterizer_bind_texture_d3d9(int16_t stage, BitmapData *bitmap);  // 0x518680
extern uint8_t rasterizer_bind_texture_d3dx(int16_t stage, BitmapData *bitmap, rasterizer_effect_slot *effect_slot);  // 0x5186c0
extern int32_t rasterizer_bitmap_compute_mipmap_skip_count(BitmapData *bitmap, int16_t *out_width, int16_t *out_height);
extern uint8_t rasterizer_bitmap_create_hardware_texture(BitmapData *bitmap);  // 0x523fa0, foreign
extern int32_t rasterizer_bitmap_sample_texel(BitmapData *bitmap, float *uv, float mip_bias);  // 0x524590 (0x4f08e0 calls it)
extern void rasterizer_bitmap_upload_2d_mipmaps(BitmapData *bitmap);  // 0x524100, foreign
extern void rasterizer_bitmap_upload_cubemap_mipmaps(BitmapData *bitmap);  // 0x524270, foreign, EBX
extern void rasterizer_bitmap_upload_cubemap_mipmaps_by_face(BitmapData *bitmap);  // 0x5243c0, foreign
extern void rasterizer_clear_decal_zbias(void);  // 0x519580
extern uint32_t rasterizer_create_game_window(int32_t height, int32_t width);  // 0x515930, EAX height, EBX width
extern uint8_t rasterizer_decal_index_buffer_initialize(void);  // 0x51bb90
extern void rasterizer_decal_pass_begin(int16_t stage);  // 0x51a810; blam-cc: DI -> stage
extern void *rasterizer_decal_vertex_cache_lock(uint32_t decal_index, int32_t byte_count);
extern void rasterizer_decals_draw_cluster(int16_t cluster_index);  // 0x51aa50 (cdecl)
extern uint8_t rasterizer_detail_object_vertex_buffer_create(void);  // 0x51b370
extern void rasterizer_detail_objects_begin(void);  // 0x51b3f0, foreign render module; UNSURE, no visible arguments
extern void rasterizer_detail_objects_expand_quad_vertices(int32_t quad_count, uint32_t *vertices, const uint8_t *instances, const DetailObjectCollection *collection, const rasterizer_detail_object_draw *draw);  // 0x51b150
extern uint8_t rasterizer_display_mode_differs(rasterizer_display_mode *requested);  // 0x515d10, blam-cc: EDI -> requested
extern void rasterizer_draw_text_begin(ui_quad_render_state *state);  // 0x531b80
extern void rasterizer_draw_text_end(void);  // 0x531e90
extern void *rasterizer_dx9_create_vertex_buffer(int32_t vertex_type, uint32_t length, uint32_t fvf, uint8_t not_dynamic);  // 0x530570
extern int32_t rasterizer_dx9_pixel_shader_effect_load(int32_t effect_index, const void *data, uint32_t size);  // 0x52f980
extern uint8_t rasterizer_dx9_pixel_shaders_load_all(void);  // 0x52fa00
extern void rasterizer_dx9_pixel_shaders_release(void);  // 0x52ff60
extern int32_t rasterizer_dx9_shaders_init_effect(int32_t effect_index);  // 0x52f780
extern uint8_t rasterizer_dx9_shaders_initialize(void);  // 0x52fab0
extern void rasterizer_dx9_shaders_release_all(void);  // 0x530090
extern void rasterizer_dx9_vertex_declarations_release(void);  // 0x530540
extern uint8_t rasterizer_dx9_vertex_shaders_initialize(void);  // 0x5307b0
extern uint32_t rasterizer_dx9_vertex_shaders_load_all(void);  // 0x5306e0
extern uint8_t rasterizer_dx9_vertex_shaders_reload(void);  // 0x530800
extern void rasterizer_dynamic_geometry_chain_draw(int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, rasterizer_index_buffer *index_buffer);  // 0x51c5f0
extern void rasterizer_dynamic_geometry_dispose(void);  // 0x51bcd0 (already in tree)
extern void rasterizer_dynamic_geometry_draw_dispatch(rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, rasterizer_vertex_buffer *vertex_buffer, int32_t primitive_count, int32_t first_primitive, int32_t dynamic_vertex_slot);  // 0x51c730
extern void rasterizer_dynamic_index_cache_draw(int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, int32_t dynamic_vertex_slot);  // 0x51c090
extern void rasterizer_dynamic_light_technique_ps2_set_states(void);  // 0x521cc0
extern void rasterizer_dynamic_vertex_draw(int32_t first_primitive, int32_t primitive_count, int32_t dynamic_vertex_slot, int16_t primitive_kind);  // 0x51bec0
extern void rasterizer_dynamic_vertex_draw_indexed(rasterizer_index_buffer *index_buffer, int32_t primitive_count, int32_t dynamic_vertex_slot);  // 0x51c490
extern uint32_t rasterizer_dynamic_vertex_process_and_get_handle(rasterizer_vertex_buffer *vertex_buffer);  // 0x51c790
extern void rasterizer_editbox_log_dump(void);  // 0x5196b0 (this session)
extern void rasterizer_end_decal_pass(void);  // 0x51b0e0
extern void rasterizer_end_frame(void);  // 0x517b90, foreign (rasterizer module)
extern void rasterizer_fog_screen_overlay_set_states(void);  // 0x51def0
extern void rasterizer_force_bilinear_filtering(void);  // 0x51e9f0
extern void rasterizer_gamma_brightness_to_exponent(rasterizer_gamma_settings *settings);  // 0x522890, blam-cc: EAX
extern void rasterizer_geometry_draw_fixed_function(uint32_t flags, int32_t dynamic_vertex_slot, rasterizer_vertex_buffer *vertex_buffer, rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, int32_t primitive_count);  // 0x528ae0
extern void rasterizer_geometry_part_draw(transparent_geometry_group *group);  // 0x533730
extern void *rasterizer_get_capture_surface(uint8_t *object, void *fallback);  // 0x515c30; EAX -> object, ECX -> fallback:
extern int32_t rasterizer_get_refresh_rate(int32_t requested_rate);  // 0x515c70
extern void rasterizer_glass_diffuse_draw(transparent_geometry_group *group);  // 0x523690
extern void rasterizer_glass_diffuse_draw_fixed_function(transparent_geometry_group *group);  // 0x523d10
extern void rasterizer_glass_draw_procedures_select(void);  // 0x523ec0
extern void rasterizer_glass_reflection_draw(transparent_geometry_group *group, int16_t reflection_kind);  // 0x522c60
extern void rasterizer_glass_reflection_draw_fixed_function(transparent_geometry_group *group, uint32_t reflection_kind);  // 0x523b90
extern void rasterizer_glass_tint_draw(transparent_geometry_group *group);  // 0x522930
extern void rasterizer_glass_tint_draw_fixed_function(transparent_geometry_group *group);  // 0x523980
extern uint8_t rasterizer_index_buffer_create(int32_t count, int16_t type, rasterizer_index_buffer *out, const void *source);  // 0x525030, blam-cc: EAX -> count, DX -> type, stack -> out, source
extern uint8_t rasterizer_initialize_direct3d(void);  // 0x5169c0, rasterizer module
extern uint8_t rasterizer_lens_flare_batch_apply_material(lens_flare_batch_key *key);  // 0x536b70
extern void rasterizer_lens_flare_batch_draw_slot(int32_t batch_index);  // 0x536c10
extern int32_t rasterizer_lens_flare_batch_find_slot(void);  // 0x536cb0
extern void rasterizer_lens_flare_batch_flush_all(void);  // 0x536c80
extern void rasterizer_lens_flare_batching_select_mode(int16_t mode, uint32_t flags);  // 0x537130, AX, ECX
extern int32_t rasterizer_lens_flare_occlusion_query_get_result(int32_t slot_index);  // 0x537b40, ESI slot = the loop index (0x5137c0)
extern void rasterizer_lens_flare_occlusion_sample_add(void *procedure, const real_point3d *position, uint32_t id_1, uint32_t id_2);  // 0x536ff0, EAX procedure, EDX position, stack ids
extern int32_t rasterizer_lens_flare_occlusion_test_issue(int32_t slot_index, const real_point3d *position, float radius);  // 0x537800, EDI slot, stack (position, radius)
extern uint8_t rasterizer_lens_flare_project_to_screen(const real_point3d *position, float radius, float *out_screen, float *out_inverse_w, float *out_billboard_size);  // 0x00536d80
extern void rasterizer_light_cone_draw(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer);  // 0x51dc50
extern void rasterizer_light_cone_set_texture_stage_states(void);  // UNSURE: zero visible args; out of range, 0x51d6a0
extern void rasterizer_light_disable_all(void);  // 0x526700
extern void rasterizer_light_set(rasterizer_light *light);  // 0x526760, ESI light
extern void rasterizer_light_set_point_constants(int32_t light_index, int16_t slot, rasterizer_point_light_constants *dest_base);  // 0x518c10
extern uint32_t rasterizer_load_file_and_verify(void **out_buffer, uint32_t *out_size, const char *path);  // 0x5199f0
extern void rasterizer_model_draw_restore_states(void);  // 0x52b530
extern void rasterizer_motion_sensor_begin(void);  // 0x52b690, rasterizer motion sensor blip batch begin
extern void rasterizer_motion_sensor_end(const float *center, float sweep);  // 0x52bc40, rasterizer motion sensor sweep, blam-cc: EBX center
extern void rasterizer_object_shadow_blur(void);  // 0x530830
extern void rasterizer_object_shadow_model_draw(const ShaderModel *shader, int16_t frame, rasterizer_index_buffer *index_buffer, rasterizer_vertex_buffer *vertex_buffer);  // 0x531350
extern uint8_t rasterizer_parse_vidmode_commandline(int32_t *width_out, int32_t *height_out, long *refresh_out);  // 0x5168c0, ESI width_out
extern void rasterizer_prepare_lighting_constants(render_lighting *lighting);  // 0x518ce0
extern void rasterizer_projected_light_constants_build_cube_map(int32_t light_index);  // 0x5215b0
extern void rasterizer_render_loading_screen(int32_t mode);  // 0x5157e0 (this session)
extern void rasterizer_render_target_bind_effect_texture(int16_t target_index, rasterizer_effect_slot *effect_slot, int16_t handle_index);  // 0x52ce10
extern void *rasterizer_render_target_bind_texture_stage(int16_t target_index, int16_t stage);  // 0x52cdd0
extern void rasterizer_render_target_capture_frame(void);  // 0x519b00
extern void rasterizer_render_target_dispose(void);  // 0x52cc50, outside this session's range
extern uint8_t rasterizer_render_target_initialize(void);  // 0x52ca20 render target pool create
extern void rasterizer_resize_game_window(int32_t height, int32_t width);  // 0x515b20, blam-cc: EAX -> height, ECX -> width
extern int16_t *rasterizer_resolve_and_cache_submap_b(uint32_t bitmap_tag_id, int16_t bitmap_type, int16_t stage, int16_t default_index, int16_t frame, rasterizer_effect_slot *effect_slot);  // 0x518860
extern uint8_t rasterizer_resolve_and_cache_submap_c(uint32_t bitmap_tag_id, int16_t bitmap_type, int16_t stage, int16_t default_index, int16_t frame);  // 0x518a60, EAX tag, DI bitmap_type
extern uint8_t rasterizer_resource_file_verify_signature(uint8_t *buffer, uint32_t size);  // 0x519980 (this session)
extern int32_t rasterizer_round_up_resolution_height(int32_t height);  // 0x5195f0 (this session)
extern void rasterizer_screen_effect_compute_uv_transform(uint32_t width, uint32_t height, weapon_screen_effect_parameters *params, int16_t pass, int16_t pass_count, uint8_t shift_down);  // 0x52ce50
extern void rasterizer_screen_effect_render(weapon_screen_effect_parameters *parameters);  // 0x52d8a0
extern void rasterizer_screen_effect_render_fixed_function(weapon_screen_effect_parameters *parameters);  // 0x52e2d0; blam-cc: EAX -> parameters
extern void rasterizer_screen_flash_render(void);  // 0x52ed00, rasterizer module
extern void __cdecl rasterizer_select_hardware_codepaths(void);  // 0x516810
extern void rasterizer_service_deferred_windowed_ops(void);  // 0x5180d0 (rasterizer)
extern void rasterizer_set_fog_constants(const render_fog *fog);  // 0x5176d0, EDX fog
extern void rasterizer_shader_decal_pass_set_states(void);  // 0x520020
extern uint8_t rasterizer_shader_environment_build_technique_table(void);  // 0x526930
extern void rasterizer_shader_environment_draw_fixed_function(uint8_t *shader, int16_t frame, rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_vertex_slot);  // 0x527ae0
extern void rasterizer_shader_environment_draw_single_stream(uint8_t *shader, int16_t frame, rasterizer_index_buffer *index_buffer, int32_t dynamic_index_slot, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer, int32_t dynamic_vertex_slot);  // 0x5276c0
extern void rasterizer_shader_environment_lightmap_draw_single_stream(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer);  // 0x51e8f0
extern void rasterizer_shader_environment_lightmap_draw_two_stream(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer);  // 0x51e570
extern void rasterizer_shader_environment_select_draw_functions(void);  // 0x52b630
extern void rasterizer_shader_environment_self_illumination_draw(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer);  // 0x51f3e0
extern void rasterizer_shader_environment_self_illumination_draw_single_stream(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer);  // 0x51fd80
extern void rasterizer_shader_environment_self_illumination_draw_two_stream(const ShaderEnvironment *shader, int16_t frame, int32_t dynamic_index_slot, int32_t first_primitive, int32_t primitive_count, rasterizer_vertex_buffer *vertex_buffer);  // 0x51fad0
extern void rasterizer_shader_environment_technique_multipurpose_set_states(void);  // 0x520790
extern void rasterizer_shader_environment_technique_ps2_set_states(void);  // UNSURE: zero visible args; out of range, 0x5212d0
extern void rasterizer_shader_environment_technique_self_illumination_set_states(void);  // 0x520b90
extern rasterizer_effect_slot *rasterizer_shader_model_select_technique(const ShaderModel *shader);  // 0x527500
extern void *rasterizer_shader_technique_for_name(void *effect, const char *name);  // 0x530120
extern void rasterizer_shader_transparent_chicago_draw(transparent_geometry_group *group, uint8_t attached);  // 0x531ed0
extern void rasterizer_shader_transparent_chicago_extended_draw(transparent_geometry_group *group, uint8_t attached);  // 0x532a40
extern uint8_t rasterizer_shader_transparent_chicago_extended_set_texture_stages(const ShaderTransparentChicagoExtended *shader);  // 0x537d60
extern uint8_t rasterizer_shader_transparent_chicago_set_texture_stages(const ShaderTransparentChicago *shader);  // 0x537bb0
extern void rasterizer_shader_transparent_plasma_draw(transparent_geometry_group *group);  // 0x52c4a0
extern void rasterizer_sun_glow_capture(const float *rect, int16_t target_index);  // 0x525320, ESI rect, stack target
extern uint8_t rasterizer_sun_glow_project_point(real_point3d *point, float radius, float *out_screen, float *out_scale);  // 0x525130
extern void rasterizer_sun_glow_render(lens_flare_instance *instance);  // 0x525ab0
extern void rasterizer_transparent_geometry_group_draw(transparent_geometry_group *group, uint8_t attached);  // 0x533850
extern void rasterizer_transparent_geometry_group_draw_active_camouflage(transparent_geometry_group *group);  // 0x519f70
extern void rasterizer_transparent_geometry_group_draw_vertices(transparent_geometry_group *group, uint8_t flag);  // 0x533660
extern void rasterizer_unbind_stream_and_textures(void);  // 0x518130
extern void rasterizer_underwater_tint_jitter_update(BitmapData *lightmap);  // 0x51f310, blam-cc: EAX
extern void rasterizer_underwater_tint_set_states(void);  // 0x51f030, foreign render module; UNSURE, no visible arguments
extern uint8_t rasterizer_validate_and_rebind_texture(uint32_t bitmap_tag_id, int16_t stage, int16_t frame);  // 0x5187e0, EAX tag
extern int32_t rasterizer_vertex_buffer_slot_allocate(int32_t vertex_type, uint32_t fvf, uint32_t length);  // 0x5305f0,
extern void rasterizer_vertex_buffer_slot_recreate_lost(void);  // 0x530690, outside this session's range
extern void rasterizer_water_draw_fixed_function(transparent_geometry_group *group);  // 0x5358b0
extern void rasterizer_water_draw_pixel_shader(transparent_geometry_group *group);  // 0x535fd0
extern void rasterizer_water_fade_compute_and_set_states(void);  // 0x51eb20
extern void rasterizer_water_update_ripple_texture(void *water_shader);  // 0x534f80
extern void structure_cluster_add_lens_flares(int16_t cluster_index);  // 0x513a00, CX cluster
extern void text_draw_glyph_callback(void *state, void *font, uint8_t *character, uint32_t color, int16_t x, int16_t y, int16_t source_x, int16_t source_y, int16_t width, int16_t height);  // 0x514ce0
extern int32_t __cdecl text_font_system_initialize(void);  // 0x514820
extern int __cdecl transparent_geometry_group_compare(int16_t *a, int16_t *b);  // 0x5155b0
extern void transparent_geometry_group_draw_all(uint8_t resort);  // 0x5154a0 (cdecl)
extern transparent_geometry_group *transparent_geometry_group_get_next_sorted(transparent_geometry_group *group);  // 0x515290
extern uint32_t transparent_geometry_group_get_vertex_type_reference(transparent_geometry_group *group);  // 0x515400
extern void transparent_geometry_group_set_drawn_bit(transparent_geometry_group *group, uint8_t clear);  // 0x515370
extern uint8_t transparent_geometry_group_test_drawn_bit(transparent_geometry_group *group);  // 0x515310
extern int32_t __cdecl transparent_geometry_pool_initialize(void);  // 0x5151c0
extern uint32_t vector3d_pack_normal_11_11_10(real_vector3d *direction);  // 0x5132d0, ESI
extern real_vector3d *vector3d_unpack_normal_11_11_10(real_vector3d *out, uint32_t packed);  // 0x513400, blam-cc: EAX out, ECX packed

#endif
