// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/render/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_RENDER_H
#define FN_RENDER_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "objects.h"
#include "effects.h"
#include "rasterizer.h"
#include "render.h"

extern void billboard_system_frame_init(void);  // 0x511410, this module
extern void cinematic_screen_effect_set_filter(float light_enhancement_lower, float light_enhancement_upper, float desaturation_lower, float desaturation_upper, uint8_t is_additive, float duration);  // 0x512230
extern void cinematic_screen_effect_set_video(int16_t overbright_mode, float noise_intensity);  // 0x5122a0
extern real object_compute_level_of_detail_pixels(datum_index object_index);  // 0x50f740, this
extern void rasterizer_effect_slot_release_active(void);  // 0x512150
extern void rasterizer_frame_statistics_draw(void);  // this module, below this batch
extern void rasterizer_frame_statistics_graph_init(void);  // 0x512700, this module (fg_init)
extern uint8_t rasterizer_lens_flare_set_current_key(int32_t second_bitmap_tag_index, int16_t bitmap_tag_index, int16_t bitmap_index);  // 0x5120f0, EAX, ECX, stack
extern void rasterizer_lens_flare_set_vertex_specular(float intensity);  // 0x512120, stack
extern void render_billboard_build_orientation_basis(build_sprite_data *data, int16_t render_type, real_vector3d *position, real_vector3d *normal, billboard_basis *out);
extern void render_billboard_compute_scale(build_sprite_data *data, float *scale, int16_t render_type, real_point3d *position, BitmapData *bitmap);
extern real render_billboard_compute_view_fade(real_vector3d *a, real_vector3d *b, int16_t render_type);
extern void render_contrail(contrail *c, Contrail *definition, int16_t instance);  // 0x50e090,
extern void render_lighting_disable_workaround(void);  // 0x511ef0, render module
extern void render_lighting_step_direction_toward(real_vector3d *current, real_vector3d *target, float max_delta);  // 0x50f690, this module;
extern void render_lighting_step_vector4_toward(float *current, float *target, float max_delta);  // 0x50f5c0,
extern int16_t render_local_player_gunner_seat_visible(int16_t local_player_index);  // 0x50fcd0, blam-cc: EAX
extern void render_object_get_cull_sphere(datum_index object_index, real_point3d *center, float *radius);  // 0x50e8d0, this module (cdecl)
extern void render_objects(void);  // 0x50e930, this module
extern void render_objects_collect(void);  // 0x50eac0, this module: rebuilds rendered_objects
extern void render_particles(void);  // 0x50fd90, this module
extern int32_t render_rasterizer_dispatch_537800(int32_t slot_index, real_point3d *point, float radius);  // 0x512190, EDI slot, ECX point, stack radius
extern void render_sky(void);  // 0x510c50, this module
extern void render_sprite_transform_point_and_normal(real_point3d *position, real_vector3d *normal, real_vector3d *out_normal, build_sprite_data *data, uint8_t flags, real_point3d *out_position);
extern void render_window(int16_t local_player_index, render_camera *source_camera, render_frustum *source_frustum, render_camera *rasterizer_camera, render_frustum *rasterizer_frustum, int16_t rasterizer_target, uint8_t has_mirror);  // 0x50bfb0, this module (cdecl)
extern void render_window_structure_lightmap_begin_0x511f90(void *bitmap_data);
extern void render_window_structure_lightmap_begin_0x512010(void *bitmap_data);
extern void render_window_structure_material_0x511f40(void *shader_data, int16_t shader_permutation, int32_t render_context, int32_t first_surface, int32_t surface_count, void *material_extra);  // 0x511f40
extern void render_window_structure_material_0x511f50(void *shader_data, int16_t shader_permutation, int32_t render_context, int32_t first_surface, int32_t surface_count, void *material_extra);  // 0x511f50
extern void render_window_structure_material_0x511f80(void *shader_data, int16_t shader_permutation, int32_t render_context, int32_t first_surface, int32_t surface_count, void *material_extra);  // 0x511f80
extern void sort_adjust_heap(rendered_particle_datum *first, int32_t hole, int32_t bottom, rendered_particle_datum value, int32_t predicate);  // 0x510a90, blam-cc: ECX first, EAX hole, EDI bottom, stack (value, predicate)
extern void sort_heap_sort(rendered_particle_datum *first, rendered_particle_datum *last, int32_t predicate);  // 0x5107e0, blam-cc: EBX first, EAX last, stack predicate
extern void sort_insertion_sort(rendered_particle_datum *first, rendered_particle_datum *last, int32_t predicate);  // 0x510830, cdecl
extern void sort_introsort_loop(rendered_particle_datum *first, rendered_particle_datum *last, int32_t ideal, int32_t predicate);
extern void sort_make_heap(rendered_particle_datum *first, rendered_particle_datum *last, int32_t predicate);  // 0x510980, blam-cc: EAX last, stack (first, predicate)
extern void sort_median(rendered_particle_datum *first, rendered_particle_datum *mid, rendered_particle_datum *last, int32_t predicate);  // 0x5108f0, blam-cc: ECX first, EBX mid, stack (last, predicate)
extern void sort_median_of_three(rendered_particle_datum *first, rendered_particle_datum *mid, rendered_particle_datum *last, int32_t predicate);  // 0x5109d0, blam-cc: ECX first, EAX mid, EDX last, stack predicate
extern void sort_push_heap(rendered_particle_datum *first, int32_t hole, int32_t top, rendered_particle_datum value, int32_t predicate);  // 0x510b20, blam-cc: ESI first, EAX hole, stack (top, value, predicate)
extern void sort_rotate(rendered_particle_datum *first, rendered_particle_datum *mid, rendered_particle_datum *last);  // 0x510ba0, blam-cc: EAX mid, EBX last, stack first

#endif
