// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/scenario/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_SCENARIO_H
#define FN_SCENARIO_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "scenario.h"
#include "objects.h"
#include "rasterizer.h"

extern GlobalsMaterial *globals_material_get(int16_t material_type);  // 0x53e7c0, scenario/globals
extern uint8_t scenario_cluster_visibility_test(int16_t row_cluster, int16_t column_cluster);  // 0x53eb60, stack, CX
extern uint32_t scenario_fog_region_resolve_tag(int16_t fog_region);  // this module, 0x53ed10
extern uint8_t scenario_location_background_sound_is_deafening_to_ais(bsp_leaf_reference *location);  // 0x53e810, EAX
extern int16_t scenario_location_fog_region(bsp_leaf_reference *leaf, real_point3d *point);  // 0x53ec30, EAX, EBX
extern void scenario_location_from_point(bsp_leaf_reference *out, real_point3d *point);  // 0x53e780, ESI, EDX
extern int16_t scenario_object_name_find_index(Scenario *scenario, char *name);
extern void scenario_sky_fog_state_update(int16_t sky_index, int16_t local_player_index, real_point3d *camera_position, render_fog *out);  // 0x53e8c0, blam-cc: AX -> sky_index, stack -> local_player_index,
extern void scenario_structure_bsp_activate_callbacks(void);
extern void scenario_structure_bsp_deactivate_callbacks(void);
extern uint8_t scenario_structure_bsp_locate_point_nudge_up(real_point3d *point);  // 0x53e870, EDX
extern uint8_t scenario_structure_bsp_switch(int16_t structure_bsp_index);  // 0x53eeb0, blam-cc: SI
extern uint8_t scenario_trigger_volume_contains_point(int16_t trigger_volume_index, real_point3d *point);  // 0x53f020, EAX, ECX

#endif
