// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/sound/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_SOUND_H
#define FN_SOUND_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "sound.h"

extern void game_looping_sound_touch_if_valid(datum_index looping_sound_index);  // 0x544290
extern void game_looping_sound_update(datum_index looping_sound_index, int32_t *root_location);  // 0x544330
extern void game_sound_initialize(void);  // 0x543a30
extern void game_sound_revert_scripting_sounds(void);  // 0x543a90
extern void game_sound_stop_loops_conflicting_with_music(void);  // 0x544c70
extern void game_sound_update(void);  // 0x5445c0
extern datum_index looping_sound_new(datum_index object_index, datum_index definition_index, char *marker_name, int16_t function_index);  // 0x543c20, blam-cc: EAX, EDI, ECX, stack
extern int32_t ov_close_thunk(sound_ogg_memory_file *file);  // 0x544dc0
extern uint32_t ov_read_thunk(void *destination, uint32_t size, uint32_t count, sound_ogg_memory_file *file);  // 0x544d50
extern int32_t ov_seek_thunk(sound_ogg_memory_file *file, uint32_t offset_low, int32_t offset_high, int32_t whence);  // 0x544da0
extern int32_t ov_tell_thunk(sound_ogg_memory_file *file);  // 0x544de0
extern void render_debug_sound(datum_index sound_handle);  // this module, 0x54e6d0
extern int32_t sound_adpcm_decode_sample(uint8_t selector, int32_t prediction, uint32_t step);  // 0x54e8c0
extern void sound_assign_channels(void);  // 0x54c020
extern void sound_build_channel_candidates(sound_channel_candidate_list *out, datum_index sound_handle);  // this module, 0x54c1d0
extern void sound_build_cluster_range_bitmap(void);  // 0x544980
extern void sound_channel_bind_hardware(int16_t logical_channel_index);  // 0x5482e0, blam-cc: stack
extern directsound_channel_state sound_channel_check_loop_boundary(int16_t channel_index);  // 0x548050, blam-cc: AX
extern uint32_t sound_channel_claim_if_finished(int16_t channel_index);  // 0x547ff0
extern uint8_t sound_channel_create(int16_t channel_index, uint16_t type_flags);  // 0x546760, blam-cc: stack, CX
extern void sound_channel_fill_pcm_data(int16_t channel_index, uint8_t *destination, int32_t base_position, uint8_t *crosslap, int32_t byte_count);  // 0x547ab0, blam-cc: stack x4, EAX
extern uint8_t sound_channel_lock_and_fill(int16_t channel_index, uint32_t fill_size);  // 0x547a00, blam-cc: BX, stack
extern void sound_channel_parameters_proc_default(int16_t channel_index, sound_channel_parameters *parameters, uint8_t update, int16_t sound_class);  // 0x54ce50, UNSURE, see file header
extern void sound_channel_parameters_proc_eax(int16_t channel_index, sound_channel_parameters *parameters, uint8_t update, int16_t sound_class);  // 0x54cf80, UNSURE, see file header
extern void sound_channel_queue_source(int16_t channel_index, SoundPermutation *source, int16_t sound_class, uint8_t crosslap);  // 0x547c80, blam-cc: stack -> (channel_index, source, sound_class), CL -> crosslap
extern uint32_t sound_channel_refresh_cursor(int16_t channel_index);  // 0x547890, blam-cc: AX
extern int16_t sound_channel_release_detail_buffers(int16_t channel_index);  // this module, 0x54d020
extern void sound_channel_release_permutations(int16_t channel_index);  // 0x54d0d0
extern void sound_channel_reset(int16_t channel_index);  // 0x547f60, blam-cc: AX
extern int32_t sound_channel_restore_buffer(void *buffer, uint8_t *was_restored_out);  // 0x547c10, blam-cc: ESI, EBX
extern void sound_channel_set_next_permutation(int16_t channel_index, SoundPermutation *permutation, int16_t unknown, int16_t sound_class, uint8_t streaming);  // this module, 0x54cd30
extern void sound_channel_set_parameters(int16_t channel_index, sound_channel_parameters *parameters, uint8_t update);
extern void sound_channel_set_spatial(int16_t channel_index, uint8_t spatialized, sound_channel_spatial *spatial, float obstruction, float occlusion, uint8_t underwater, int16_t sound_class);  // 0x5472d0, blam-cc: stack, BL, EDI, stack
extern void sound_channel_stream_update(int16_t channel_index, uint8_t unused);  // 0x5478c0, blam-cc: AX, stack
extern uint8_t sound_channel_type_flags_match(int16_t compressed_requested, int16_t stereo_requested, uint16_t sample_rate_44khz_requested, uint16_t flags, int16_t requested_3d);  // 0x548520, blam-cc: stack x3, DX, stack
extern float sound_clamp_gain_by_ratio(float gain, float compare, float ratio);  // this module, 0x54e660
extern void sound_class_set_muted_by_name(uint8_t enabled, char *name);  // 0x545420, blam-cc: BL, stack
extern void sound_class_update_gain_fade(int32_t ticks);  // 0x545330
extern uint32_t sound_compare_priority(datum_index sound_a, datum_index sound_b, float distance_a_squared);  // this module, 0x54c6b0
extern float sound_compute_class_gain(SoundClass_t sound_class);  // this module, 0x54b100
extern void sound_compute_obstruction_occlusion(sound_location *location, int16_t listener_index, float reference_distance);  // 0x544aa0, blam-cc: EBX -> location, AX -> listener_index, stack
extern float sound_compute_random_pitch(float pitch_bounds_min, float pitch_bounds_max, float zero_pitch_modifier, float one_pitch_modifier, float distance_scale);  // 0x54aec0
extern int32_t sound_decode_dispatch(int16_t channel_count, void *destination, void *source, int32_t source_size);  // 0x54e830; ECX channels, EBX destination, stack (source, size)
extern int16_t sound_definition_check_promotion(TagID sound_tag_id);  // 0x54b050, blam-cc: ECX
extern uint32_t sound_definition_has_audible_permutations(TagID sound_tag_id);  // 0x54af10, blam-cc: EAX
extern float sound_definition_maximum_distance(datum_index sound_definition);  // 0x545460, EAX
extern void sound_directsound_probe_channel_pools(int32_t *mono3d_count, uint32_t mono3d_requested, int32_t *mono_count, uint32_t mono_requested, int32_t *stereo_count, uint32_t stereo_requested, int32_t *stereo44k_count, uint32_t stereo44k_requested, uint32_t pool_mask);  // 0x545a30
extern void sound_dispose(void);  // 0x00549760
extern void sound_driver_dispose(void);  // 0x546a60
extern void sound_driver_set_eax_enabled(uint8_t eax_enabled, uint8_t force);  // 0x548200, blam-cc: stack, CL
extern int32_t sound_effects_object_detect_mode(int16_t channel_index, directsound_channel *channel);  // 0x551270, blam-cc: EAX, EDI
extern int32_t sound_effects_object_initialize_channel(int16_t channel_index);  // 0x551460, blam-cc: EDX
extern float sound_evaluate_fade_gain(datum_index sound_handle);  // 0x54e3c0
extern float sound_evaluate_volume_curve(int32_t attenuation, int32_t minimum, int32_t maximum);  // 0x54cdf0
extern void sound_fade_out_and_stop_all(void);  // UNSURE module
extern int16_t sound_find_lowest_priority_channel(datum_index sound_handle);  // this module, 0x54c440
extern int32_t sound_gain_to_directsound_volume(float gain, int32_t maximum);  // this module, 0x54ee70
extern int __cdecl sound_gain_to_millibels(float gain);  // this module, 0x54eec0
extern void sound_impulse_start(datum_index object_index, datum_index definition_index, float scale);  // 0x543e10, EAX, ECX, stack
extern int32_t sound_impulse_time(datum_index sound_tag_handle);  // 0x543fc0, ECX
extern void sound_instance_apply_pending_definition_switch(datum_index sound_handle);  // this module, 0x54ddc0
extern uint32_t sound_instance_invoke_location_proc(datum_index sound_handle);  // this module, 0x54bcd0
extern void sound_instance_queue_definition_switch(datum_index sound_handle, datum_index new_definition_index);  // 0x54dd90
extern int32_t sound_linear_gain_to_attenuation(float gain, int32_t maximum);  // 0x545710
extern int32_t sound_linear_gain_to_millibels_clamped(int32_t minimum, float gain, int32_t bias_and_maximum);
extern void sound_listener_update(sound_listener_parameters *parameters);  // 0x547070
extern int16_t sound_location_check_audibility(sound_location *location, float max_distance);  // this module, 0x54bb20
extern float sound_location_distance(int16_t listener_index, sound_location *location);  // 0x54bc50, blam-cc: stack, ECX
extern float sound_location_distance_squared(int16_t listener_index, sound_location *location);  // this module, 0x54bbd0
extern uint8_t sound_location_object_marker(datum_index owner, void *callback_data, sound_location *location);  // 0x5448c0
extern void sound_looping_check_audibility_gate(datum_index definition_index, sound_location *location);  // 0x54e740
extern datum_index sound_looping_create_detail_sound(datum_index owner, datum_index definition_index, int16_t track_index, int16_t play_state);  // 0x54d9f0
extern void sound_looping_datum_touch(int32_t owner);  // 0x549f50
extern uint32_t sound_looping_definition_has_music_loop(datum_index looping_definition);  // 0x544c10
extern uint8_t sound_looping_detail_location_proc(datum_index owner, void *callback_data, sound_location *location);  // this module, 0x54dc70
extern datum_index sound_looping_find_by_owner(int32_t owner);  // 0x54e5d0 (stack argument, confirmed)
extern void sound_looping_predict(datum_index looping_definition);  // 0x544000, blam-cc: EAX
extern void sound_looping_set_alternate(datum_index looping_definition, uint8_t alternate);  // 0x544200, EAX, stack
extern void sound_looping_set_scale(datum_index looping_definition, float gain);  // 0x544180, blam-cc: EAX, stack
extern uint8_t sound_looping_set_state(int32_t owner, datum_index definition_index, sound_location *location, int16_t state, uint8_t alternate, float fade_duration);  // 0x549fa0, blam-cc: EAX, ECX, stack
extern datum_index sound_looping_start_ambient(datum_index object_index, datum_index definition_index, float scale);  // 0x544250, blam-cc: EAX, EDX, stack
extern datum_index sound_looping_state_new(datum_index definition_index, int32_t owner, sound_location *location);  // 0x54d140
extern uint8_t sound_looping_track_location_proc(datum_index owner, void *callback_data, sound_location *location);  // 0x54dc10
extern uint32_t sound_ogg_buffer_fill(SoundPermutation *permutation, void *destination, uint32_t requested_size, char *want_crosslap, sound_stream_decoder *decoder, uint32_t *bytes_filled_out);  // 0x545920, blam-cc: stack x4, ECX, EAX
extern void sound_ogg_error_to_string(int32_t vorbis_error_code);  // 0x544f70
extern int32_t sound_ogg_seek_callback(sound_ogg_memory_file *file, uint32_t offset_low, int32_t offset_high, int32_t whence);  // 0x544e00, blam-cc: ESI -> file, EAX -> whence, stack -> (offset_low, offset_high)
extern uint8_t sound_ogg_stream_open(sound_stream_decoder *decoder, void *data, int32_t size);  // 0x544eb0
extern int32_t sound_ogg_stream_read(sound_stream_decoder *decoder, char *buffer, int32_t size, char *want_crosslap);  // 0x5451d0
extern void sound_pause(void);  // 0x548170
extern int32_t sound_pcm_buffer_read(uint32_t *position, SoundPermutation *permutation, uint32_t *bytes_read_out, uint32_t requested_size, void *destination);  // 0x545860, blam-cc: stack (position, permutation, destination), ECX, EBX
extern int16_t sound_permutation_pick_for_pitch(int16_t pitch_range_index, Sound *tag, float target_pitch);  // 0x5454a0, other half of this module
extern int16_t sound_permutation_pick_random(int16_t pitch_range_index, int16_t explicit_permutation_index, Sound *tag);  // 0x545590, other half of this module
extern int16_t sound_pick_channel_for_instance(datum_index sound_handle);  // this module, 0x54c2f0
extern int16_t sound_pick_replaceable_channel(datum_index sound_handle, int16_t *candidate_channels, int16_t count);  // this module, 0x54c5e0
extern void sound_random_detail_direction(SoundLoopingDetail *detail, real_vector3d *out);  // this module, 0x54e4d0
extern uint8_t sound_reopen_device(sound_driver_parameters *new_parameters);  // 0x5494a0 (tail call, stack argument replaced)
extern void sound_resume(void);  // 0x5481a0
extern float sound_reverb_size_scale(float value);  // this module, 0x550c10
extern void sound_schedule_gain_fade(datum_index fade_in_handle, int16_t fade_curve, float duration_seconds, datum_index fade_out_handle);  // 0x54af60, blam-cc: EBX, stack
extern void sound_set_effects_gain(float gain);  // 0x5487b0
extern void sound_set_master_gain(float gain);  // 0x548590
extern void sound_set_music_gain(float gain);  // 0x548680
extern datum_index sound_start_at_location(datum_index definition_index, sound_placement *placement, float scale);  // 0x543d80, EDX, EAX, stack
extern void sound_stop_all(void);  // 0x54adb0, foreign (sound module)
extern void sound_stream_decoder_close_slot(sound_stream_decoder *decoder, uint8_t crosslap);  // 0x545760, blam-cc: ESI, AL
extern void sound_update(void);  // 0x549810, foreign (sound module)
extern void sound_update_active_instances(void);  // 0x54c900
extern void sound_update_clock(void);  // 0x54ae60
extern void sound_update_instance_gain(int16_t channel_index, float gain);  // this module, 0x54c750
extern void sound_update_listener(void);  // 0x54b970
extern void sound_update_looping_gain(int16_t channel_index, float gain);  // this module, 0x54deb0
extern void sound_update_looping_states(void);  // 0x54d270
extern void sound_update_range_and_ducking(void);  // 0x54bd60
extern void sound_update_streaming_channels(void);  // 0x546b40

#endif
