// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/shaders/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_SHADERS_H
#define FN_SHADERS_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "shaders.h"

extern void numeric_countdown_timer_update(void);  // 0x540240

#endif
