// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/saved_games/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_SAVED_GAMES_H
#define FN_SAVED_GAMES_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "interface.h"
#include "game.h"
#include "saved_games.h"

extern void control_profile_fill_default_gamepad_slots(saved_player_profile *profile);  // 0x53b7f0, this module
extern int32_t control_profile_gamepad_slot_find(saved_player_profile *profile, controls_gamepad_record *key);  // 0x53b6b0, this module
extern uint8_t control_profile_is_customized(saved_player_profile *profile, int32_t slot_index);  // 0x53b370, saved_games (below this batch)
extern void control_profile_variant_write_wait_and_clear(void);  // 0x53bae0, this module
extern void directory_ensure_empty(const char *directory_path);  // 0x555520, this module
extern uint8_t file_reference_create(file_reference_record *ref);  // 0x5555b0, src/saved_games/file_reference_create.c
extern file_reference_record *file_reference_init(file_reference_record *ref, const char *component, uint8_t is_file);  // 0x5554c0, this module
extern uint8_t file_reference_set_length(int32_t offset, file_reference_record *ref);  // 0x5559b0, EAX offset, ESI ref
extern uint8_t game_checkpoint_get_next_filename(char *out_name, char *directory);  // 0x538ae0
extern uint8_t game_checkpoint_print_list_entry(int32_t index, const char *name, int32_t level_index, int32_t difficulty, int32_t game_time_ticks, const win32_systemtime *time, void *user_data);  // 0x539110
extern int16_t game_checkpoint_read_stats_file(int32_t *out_difficulty, char *name, int32_t *out_game_time, win32_systemtime *out_time);  // 0x538c60
extern uint8_t game_checkpoint_reclaim_slot_callback(int32_t index, const char *name, int32_t level_index, int32_t difficulty, int32_t game_time_ticks, const win32_systemtime *time, void *user_data);  // 0x538ac0
extern uint8_t game_checkpoint_save_new(void);  // 0x538db0
extern void game_checkpoint_write_stats_file(char *scenario_name, int32_t difficulty);  // 0x538b70
extern void *game_state_allocate_buffer(int32_t cpu_size, int32_t extra_size);  // 0x5385f0
extern void game_state_build_header(void);  // 0x538000
extern void game_state_create_persistent_storage_file(void);  // 0x538690
extern void game_state_dispatch_load_callbacks(void);  // 0x537f70
extern void game_state_load_checkpoint(void);  // 0x538280, foreign (game module)
extern void game_state_load_core(char *name);  // 0x538390, foreign (saved_games)
extern data_array *game_state_new(char *name, int16_t maximum_count, int16_t element_size);  // 0x5380d0, blam-cc: EBX -> element_size, stack -> name, maximum_count
extern memory_pool *game_state_new_pool(char *name, int32_t pool_size);  // 0x538150, stack name, EBX pool_size
extern void game_state_perform_revert(void);  // 0x538200, foreign (saved_games)
extern void game_state_perform_save(uint8_t is_checkpoint);  // 0x5381c0
extern uint8_t game_state_queue_write(uint8_t is_checkpoint);  // 0x538700, returns in AL
extern uint8_t game_state_read_checkpoint_summary(uint8_t *corrupt_flag, int16_t *out_difficulty, char *out_scenario_name);  // 0x538320, EAX corrupt_flag, ESI out_difficulty, EDI out_scenario_name
extern uint8_t game_state_read_persistent_storage(void);  // 0x539330, bool in AL (result unused here)
extern void game_state_read_persistent_storage_block(int32_t size, void *buffer);  // 0x539850, blam-cc: EAX size
extern void game_state_read_profile_file(char *name, int32_t size, void *buffer);  // 0x5394e0
extern uint8_t game_state_read_profile_header(char *name, int32_t size, void *buffer);  // 0x539460
extern void game_state_save_thread_proc(void);  // 0x538980
extern void game_state_startup(void);  // 0x00537f90
extern void game_state_write_persistent_storage(uint32_t *crc_slot, uint8_t *buffer, int32_t header_size, int32_t total_size);  // 0x539710
extern uint8_t game_state_write_profile_file(int32_t size, char *name, const void *buffer);  // 0x5393d0
extern uint32_t game_variant_write_thread_proc(variant_write_request *request);  // 0x53c150, this module
extern void path_append_component(char *destination, const char *component);  // 0x555ec0
extern void path_append_extension(char *destination, const char *suffix);  // 0x555f20, blam-cc: ESI destination, EBX suffix
extern void path_build_full(char *source, char *destination, int16_t location);  // 0x5560d0, blam-cc: EAX, EDX, CX
extern void path_split_components(char **dir_start_out, char *path, char **ext_fallback_out, char **name_end_out, char **ext_start_out, uint8_t split_extension);  // 0x556000, blam-cc: EBX, ESI, EDI, stack
extern uint32_t player_profile_copy_files(const char *source_dir, char *dest_dir);  // 0x53cb70, this module
extern void player_profile_mark_level_visited_and_select(int16_t local_player_index);  // 0x539d50, foreign (saved_games module)
extern uint8_t player_profile_rename(int32_t handle, uint16_t *new_name);  // 0x53ce80, this module, blam-cc: EAX handle
extern void player_profile_save_539bf0(int32_t handle, saved_player_profile *profile);  // saved_games
extern void player_profile_select_local_slot(int16_t local_player_index);  // 0x539cb0, foreign (saved_games module)
extern void player_profile_verify_thread_wait_and_clear(void);  // 0x539a40, outside this batch
extern void player_profile_write_default_files(void);  // 0x53a610, this module
extern void playlist_profile_create_default_profiles_on_disk(void);  // 0x53bc70
extern int32_t saved_game_checkpoint_compare(const checkpoint_file_entry *a, const checkpoint_file_entry *b);  // 0x538e30
extern uint8_t saved_game_copy_files_to_target(char *source_directory, char *source_name, char *target_name);  // 0x5387e0
extern void saved_game_delete_by_display_name(const char *name);  // 0x53b9b0, blam-cc: ECX
extern uint8_t saved_game_delete_by_handle(int32_t handle);  // 0x53c960, blam-cc: EDI handle
extern uint8_t saved_game_file_exists(char *name);  // 0x538770
extern void saved_game_files_dispose(void);  // 0x53c480, saved_games module
extern void saved_game_files_initialize(void);  // 0x53c260
extern uint16_t *saved_game_get_display_name(int32_t handle);  // 0x53c600, not in this batch
extern uint8_t saved_game_index_open_for_write(void);  // 0x53daa0, this module
extern int16_t saved_game_index_register_default_playlists(void);  // 0x53db40, this module
extern int16_t saved_game_index_register_default_profiles(void);  // 0x53dde0, this module
extern void saved_game_last_mp_map_clear(const void *data);  // 0x53d5e0, cdecl
extern uint8_t saved_game_last_mp_map_read(uint8_t *out_data);  // 0x53d670
extern uint8_t saved_game_last_mp_variant_read(uint8_t *out_data);  // 0x53d3f0
extern void saved_game_list_rebuild_index(void);  // 0x53d720, this module
extern uint8_t saved_game_load_checkpoint(char *name);  // 0x539290, blam-cc: EAX
extern uint8_t saved_game_load_checkpoint_by_name(char *name);  // 0x5391a0
extern uint8_t saved_game_name_is_available(const uint16_t *name);  // 0x53d1e0, blam-cc: EAX; profile module name test
extern uint8_t saved_game_validate_crc(int32_t total_size, int32_t header_size, uint8_t *header_buffer, uint32_t *expected_crc, uint8_t *corrupt_flag);  // 0x539570
extern uint8_t saved_game_verify_version_and_checksum(game_state_header *header, uint8_t report_error);  // 0x538430
extern void saved_games_report_last_error(void);  // 0x556170, this module

#endif
