// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/shell/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_SHELL_H
#define FN_SHELL_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "rasterizer.h"
#include "shell.h"

extern uint32_t clipboard_get_text(char *buffer, uint32_t capacity);  // 0x541ac0
extern char **command_line_parse_to_argv(char *command_line, int32_t *out_count);  // 0x5425f0, command_line in EDI
extern uint8_t compute_sha1_hash(const uint8_t *data, uint32_t length, uint8_t *digest_out);  // 0x57f2a0
extern uint8_t compute_sha1_hash_first_qword(const uint8_t *data, uint32_t length, uint32_t *output);  // 0x57f330,
extern void config_reset_system_requirements(void);  // 0x57cfe0
extern hwreq_string_pair *copy_backward_string_pair(hwreq_string_pair *first, hwreq_string_pair *last, hwreq_string_pair *dest_end);  // 0x57cf10, blam-cc: EBX -> first, ECX -> last, EAX -> dest_end
extern int32_t cpu_query_identification(void);  // 0x00540da0
extern void destroy_range_string_pair(hwreq_string_pair *first, hwreq_string_pair *last);  // 0x57be00, EAX first, EDI last
extern int32_t __stdcall dialog_center_on_screen(void *hwnd, uint32_t message, uint32_t wparam, int32_t lparam);  // 0x542f00
extern uint8_t engine_initialize_subsystems(void);  // 0x540ee0
extern void engine_shutdown_subsystems(void);  // 0x541010
extern int32_t __stdcall exception_filter_crash_reporter(win32_exception_pointers *exception_pointers);  // 0x542fa0
extern int32_t extract_product_id_digits(const char *product_id);  // 0x57f360, blam-cc: product_id in EBX
extern void fill_string_pair_range(hwreq_string_pair *first, hwreq_string_pair *last, const hwreq_string_pair *value);  // 0x57cda0
extern void game_single_instance_check(int32_t mode);  // 0x542d70
extern void hex_string_to_bytes(uint8_t *dest, const char *source);  // 0x57d830, dest in ECX, source in EDX
extern int32_t hex_string_to_uint(char *string);  // 0x57d7f0, string in EDX
extern const char *hwreq_d3dcaps_field_resolve(hwreq_parser *this);  // 0x578ff0, blam-cc: this in EAX; below this module's rewrite range; (const char*)0 false, (const char*)1 true, else a real error message string (see UNSURE above)
extern int32_t hwreq_device_list_size(const msvc_std_vector *this);  // 0x57b5b0
extern uint32_t hwreq_device_override_list_find(hwreq_property_set *set, const char *key, char *dest_buffer, uint32_t capacity);  // 0x578630, blam-cc: set in EAX, key in EBX, dest_buffer/capacity on the stack; below this module's rewrite range
extern void hwreq_key_string_destruct(msvc_std_string *key);  // 0x57b560, blam-cc: key in ECX (thiscall); library code, not in the function list
extern hwreq_map_node *hwreq_map_find(msvc_std_map *map, msvc_std_string *key);  // 0x57b7a0, blam-cc: map in EDI, key in ESI, iterator slot in EBX (folded into the return value); library code (std::map<string,T*>::find); returns the found node or the map's head sentinel
extern uint8_t hwreq_map_key_less_than(const msvc_std_string *this, const msvc_std_string *other);  // 0x57bbd0, same pass
extern void hwreq_map_node_key_destruct(hwreq_map_node *node);  // 0x57cde0, same pass
extern hwreq_string_pair **hwreq_pair_vector_insert(msvc_std_vector *this, hwreq_string_pair **result, hwreq_string_pair *where, const hwreq_string_pair *value);  // 0x57b920, blam-cc: EDI -> this, stack -> result, where, value
extern void hwreq_pair_vector_insert_n(msvc_std_vector *this, hwreq_string_pair *where, uint32_t count, const hwreq_string_pair *value);  // 0x57be20, blam-cc: ECX -> value, stack -> this, where, count
extern void hwreq_pair_vector_throw_length_error(void);  // 0x57c130, throws length_error("vector<T> too long")
extern hwreq_parser *hwreq_parser_construct(hwreq_parser *this);  // 0x579ef0
extern hwreq_parser *hwreq_parser_create(void);  // 0x57b4c0
extern void hwreq_parser_destruct(hwreq_parser *parser);  // 0x0057a010
extern const char *hwreq_parser_evaluate_condition(hwreq_parser *parser, int32_t kind, uint32_t value);  // 0x00579690
extern uint8_t hwreq_parser_find_requirements_section(hwreq_parser *parser);  // 0x57ae50, blam-cc: ESI -> parser
extern uint8_t hwreq_parser_parse_audiovendor_block(hwreq_parser *parser);  // 0x57aa40, blam-cc: EAX -> parser
extern uint8_t hwreq_parser_parse_block(hwreq_parser *this, hwreq_property_set *target);  // 0x57af10
extern const char *hwreq_parser_parse_flag_assignment(hwreq_parser *this, hwreq_property_set *target);  // 0x578cf0, blam-cc: this in ECX, target on the stack; below this module's rewrite range; 0 success, else an error message string (see UNSURE above)
extern uint8_t hwreq_parser_parse_propertyset_directive(hwreq_parser *parser);  // 0x57a3e0, blam-cc: ECX -> parser
extern uint8_t hwreq_parser_parse_vendor_block(hwreq_parser *parser);  // 0x57a680, blam-cc: EAX -> parser
extern uint8_t hwreq_parser_scan_for_applytoall(hwreq_parser *parser);  // 0x57a320, blam-cc: ESI -> parser
extern uint8_t hwreq_parser_scan_for_applytoall_or_vendor(hwreq_parser *parser);  // 0x57a220, blam-cc: ESI -> parser
extern void hwreq_property_set_apply(hwreq_property_set *source, hwreq_property_set *target);  // 0x57b470, blam-cc: source in EAX, target on the stack; library code, not in the function list; merges every (name,value) pair of source->flags into target via hwreq_property_set_upsert (0x578410, below this module's rewrite range)
extern void hwreq_property_set_flags_destruct(hwreq_property_set *set);  // 0x57b990, blam-cc: set in EBX; library code (map neighbour), not in the function list
extern hwreq_property_set **hwreq_property_set_map_index(msvc_std_string *key, msvc_std_map *map);  // 0x57b6e0, blam-cc: key in EDI, map on the stack; library code (map::operator[]), not in the function list
extern void hwreq_property_set_upsert(hwreq_property_set *property_set, char *key, char *value);  // 0x00578410
extern msvc_std_string *hwreq_string_assign_cstr(msvc_std_string *dest, const char *source);  // 0x57b590, blam-cc: source in EDX, dest on the stack; library code, not in the function list
extern void hwreq_string_pair_destruct(hwreq_string_pair *pair);  // 0x5785b0, UNSURE: not this pass
extern int32_t hwreq_token_parse_hex_digit(hwreq_parser *parser);  // 0x00578ad0
extern uint32_t hwreq_token_parse_hex_id(hwreq_parser *parser);  // 0x00578ef0
extern int32_t hwreq_token_parse_hex_id_byteswap(hwreq_parser *parser);  // 0x00578f80
extern char *hwreq_token_parse_quoted_string(hwreq_parser *this);  // 0x578c60, blam-cc: this in EAX; below this module's rewrite range; NULL on error
extern void hwreq_token_skip_line(hwreq_parser *this);  // 0x5789d0, blam-cc: this in EAX; below this module's rewrite range
extern void hwreq_vector_throw_out_of_range(void);  // 0x57b9e0, throws out_of_range; never returns
extern void keystone_library_load(void);  // 0x542ad0
extern void keystone_library_unload(void);  // 0x542cf0, UNSURE module
extern void os_platform_identify(void);  // 0x5427e0
extern int32_t security_check_write_access(void);  // 0x542840, UNSURE args
extern char *shell_build_product_id_string(void);  // 0x57f3f0
extern int32_t shell_check_previous_run_crash(void);  // 0x57e850, full EAX result
extern void shell_detect_hardware_specs(void);  // 0x57d880
extern int32_t __stdcall shell_display_adapter_enumerate_callback(void *guid, char *description, char *driver_name, void *context, void *monitor);  // 0x57d370, not a Ghidra function
extern void shell_handle_activate_app(uint8_t inactive);  // 0x5410d0, blam-cc: BL -> inactive;
extern void shell_init_localization_strings(void);  // 0x57efa0
extern int32_t shell_load_string_resource(uint32_t id, uint16_t language, uint32_t buffer_capacity, void *module, char *buffer);  // 0x57e110
extern void shell_pump_windows_messages(void);  // 0x541a20, foreign (shell)
extern void shell_registry_set_exit_flag_clean(void);  // 0x57ea10
extern msvc_std_string *string_assign_substr(msvc_std_string *this, const msvc_std_string *right, uint32_t pos, uint32_t count);  // 0x57b830
extern int32_t string_compare(const msvc_std_string *this, uint32_t n1, uint32_t pos, const char *s, uint32_t n2);  // 0x57ce10
extern void string_erase(msvc_std_string *this, uint32_t pos, uint32_t count);  // 0x57bd80
extern void string_grow_reserve(msvc_std_string *this, uint32_t new_capacity, uint32_t preserve_count);  // 0x57c6d0
extern hwreq_string_pair *string_pair_construct_empty(hwreq_string_pair *dest, const hwreq_string_pair *source);  // 0x57c640 (a copy constructor)
extern void string_throw_length_error(void);  // 0x638eb4, _Xlen: throws length_error("string too long")
extern void string_throw_out_of_range(void);  // 0x638e74, _Xran: throws out_of_range("invalid string position")
extern hwreq_map_node *tree_find_max(hwreq_map_node *node);  // 0x57cd20, blam-cc: EAX
extern hwreq_map_node *tree_find_min(hwreq_map_node **subtree_root_left_field);  // 0x57cb70, blam-cc: EAX
extern hwreq_map_node *tree_head_node_allocate(void);  // 0x57cbf0, allocates a 0x30 byte sentinel node (left/parent/right zeroed, color = black, is_nil = 0)
extern void tree_iterator_decrement(hwreq_map_node **iterator);  // 0x57cd40, same pass
extern void tree_iterator_increment(hwreq_map_node **iterator);  // 0x57c5e0, blam-cc: iterator address in EDX, updated in place
extern hwreq_map_node *tree_lower_bound(msvc_std_map *tree, const msvc_std_string *search_key);  // 0x57c530, blam-cc: EAX tree, ECX key
extern void tree_rotate_left(hwreq_map_node *x, msvc_std_map *tree);  // 0x57cb10
extern void tree_rotate_right(hwreq_map_node *x, msvc_std_map *tree);  // 0x57cb90
extern hwreq_string_pair *uninit_copy_string_pair(hwreq_string_pair *source_begin, hwreq_string_pair *source_end, hwreq_string_pair *dest);  // 0x57cf50, blam-cc: ECX -> source_begin, stack -> source_end, dest
extern void uninit_fill_n_string_pair(hwreq_string_pair *dest, uint32_t count, const hwreq_string_pair *value);  // 0x57ce80, same pass

#endif
