// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/structures/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_STRUCTURES_H
#define FN_STRUCTURES_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "structures.h"
#include "rasterizer.h"

extern structure_bsp_overlap aabb_overlap_classify(real_rectangle3d *box_a, real_rectangle3d *box_b);  // 0x5541b0, this module
extern int16_t bsp3d_node_query_recursive(int32_t node_index, real_rectangle3d *parent_bounds, uint32_t *visited_bits, int32_t *output_array, int32_t max_count, real_point3d *point, float radius, real_rectangle3d *query_box, int16_t plane_count, real_plane3d *planes, int16_t inherited_classification);  // 0x553f10
extern void bsp_lightmap_sample_vertex_color(BitmapData *bitmap, float weight_1, float weight_2, ColorRGB *out, ScenarioStructureBSPMaterial *material, uint16_t *triangle_vertex_indices);
extern void bsp_material_sample_base_map_color(BitmapData *bitmap, float weight_1, float weight_2, ColorRGB *out, ScenarioStructureBSPMaterial *material, uint16_t *triangle_vertex_indices);
extern void camera_cluster_portal_flood_recursive(int16_t cluster_index, polygon2d *view_polygon);  // 0x5545d0, this module // this batch
extern int16_t cluster_flood_fill_with_predicate(real_point3d *position, real_vector3d *facing, real max_distance, real sin_angle, real cos_angle, int16_t max_count, int16_t *output, int16_t start_cluster);  // 0x554e30, AX start
extern void detail_objects_globals_allocate(void);  // UNSURE module
extern void detail_objects_update_render_list(void);  // 0x5522d0, structures module
extern structure_bsp_overlap frustum_planes_classify_box(real_rectangle3d *box, real_plane3d *planes, int16_t plane_count);  // 0x554260, this module
extern uint8_t object_lighting_sample_point(uint8_t flags, real_point3d *point, render_lighting *lighting);  // 0x4f2550, cdecl;
extern void polygon2d_bounds_expand(real_bounds *bounds_xy, polygon2d *polygon);
extern void render_camera_update_leaf_and_cluster(real_point3d *point);  // 0x553490, structures
extern void structure_bsp_build_fog_environment(int16_t cluster_index, structure_fog_environment *out);  // 0x555330,
extern void structure_bsp_camera_visibility_pass(void);  // 0x5544f0, this module: portal flood
extern int32_t structure_bsp_cluster_flood_seed(real_point3d *point, float radius, int16_t start_cluster, int16_t *output, int16_t max_count);
extern void structure_bsp_cluster_visibility_update(void);  // 0x5537c0, structures module
extern int32_t structure_bsp_collect_surfaces_in_clusters( int32_t *out_surfaces, int16_t max_count, real_rectangle3d *query_box, int16_t plane_count, real_plane3d *planes, uint32_t *visited_bits, int16_t cluster_count, int16_t *cluster_indices);  // 0x553c40, this module
extern void structure_bsp_expand_visible_clusters_by_plane(ScenarioStructureBSP *tag);
extern void structure_bsp_expand_visible_clusters_by_subcluster(ScenarioStructureBSP *tag);
extern uint8_t structure_bsp_leaf_find_material_surface(real_point3d *point, int32_t accepted_plane, int16_t *out_lightmap_index, int16_t *out_material_index, int32_t *out_surface, void *out_barycentric_u, void *out_barycentric_v, int32_t raw_child);  // 0x554fa0, this module
extern int16_t structure_bsp_leaf_query(int32_t raw_child, int16_t inherited_classification, real_rectangle3d *parent_bounds, uint32_t *visited_bits, int32_t *output_array, int32_t max_count, real_rectangle3d *query_box, int16_t plane_count, real_plane3d *planes);
extern uint8_t structure_bsp_mirror_query(void *camera_ref, void *camera, structure_bsp_mirror_result *out);  // 0x553560,
extern void structure_bsp_plane_fetch_signed(real_plane3d *out, void *planes_owner, int32_t signed_index);
extern uint8_t structure_bsp_points_within_band(real_point3d *points, int16_t point_count, float tolerance);
extern uint8_t structure_bsp_portal_project(real_plane3d *plane, void *camera_ref, real_point3d *vertices, void *camera, uint32_t vertex_count, int16_t winding, polygon2d *out);
extern uint8_t structure_bsp_portal_sphere_test(ScenarioStructureBSP *global_structure_bsp, real_point3d *point, int16_t portal_index, float tolerance);  // 0x554b00, this module
extern uint8_t structure_bsp_portal_test_and_project(char same_side, int16_t portal_index, polygon2d *out);
extern int16_t structure_bsp_query_surfaces(real_rectangle3d *query_box, real_point3d *query_point, int32_t *out_surfaces, int32_t max_count, float radius, int16_t plane_count, real_plane3d *planes, int16_t cluster_count, int16_t *cluster_indices);  // 0x553d80, this module
extern uint32_t structure_bsp_resolve_fog_tag(int16_t cluster_index, ScenarioStructureBSP *global_structure_bsp, uint8_t use_sky);  // this batch
extern uint8_t structure_bsp_resolve_position_to_surface(real_point3d *start_position, real_point3d *position, int16_t *out_lightmap_index, void *out_barycentric_v, real_vector3d *direction, int16_t *out_material_index, int32_t *out_surface, void *out_barycentric_u);
extern void structure_debug_draw_surfaces_in_box(void *render_point, real_point3d *query_point, float radius, int16_t cluster_count, int16_t *cluster_indices);  // 0x552980
extern void structure_debug_draw_surfaces_in_box_alt(void *render_point, real_point3d *query_point, float radius, int16_t cluster_count, int16_t *cluster_indices);  // 0x552a60
extern void structure_debug_draw_surfaces_simple(real_point3d *query_point, float radius, real_rectangle3d *query_box, real_plane3d *planes, int16_t plane_count);
extern uint8_t structure_leaf_face_index_compare(int32_t element, int32_t other);  // 0x552c00
extern void structure_leaf_faces_gather_masked(int32_t *out_surface_indices, uint32_t *surface_bits, ScenarioStructureBSPSurface *out_faces);  // 0x552c20, this batch
extern void structure_lightmap_uv_rect_build(int16_t sequence_index, int16_t sprite_index, real scale, real *out_extent, real *out_sprite_rect, const Decal *decal_definition);
extern void structure_picked_polygon_draw(void);  // 0x5528f0, structures module
extern void structure_picked_polygon_lightmap_begin(void *bitmap_data);  // 0x511f20
extern void structure_picked_polygon_material(void *shader_data, int16_t shader_permutation, int32_t render_context, int32_t surface_offset, int16_t surface_count, void *material_extra);  // 0x511f30
extern void structure_picked_polygon_refresh(void);  // 0x5527f0, structures module

#endif
