// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/text/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_TEXT_H
#define FN_TEXT_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "text.h"

extern int16_t string_table_index_of(const char *search, int16_t count, const char **table);  // 0x004875c0, library-ish (cseries/text), not this module; blam-cc: search_text in EAX
extern void text_draw_character_range_narrow(Rectangle2D *bounds, text_glyph_draw_proc callback, Point2DInt *pen, Rectangle2D *clip, uint32_t color, void *string, int16_t start_column, int16_t end_column);  // 0x557030
extern void text_draw_character_range_wide(Rectangle2D *bounds, text_glyph_draw_proc callback, Point2DInt *pen, Rectangle2D *clip, uint32_t color, void *string, int16_t start_column, int16_t end_column);  // 0x5572b0
extern uint8_t text_find_character(int16_t target_character, uint8_t *string);  // 0x557870
extern void text_language_initialize_from_string_list(void);  // 0x5561b0
extern void text_measure_glyph_callback(text_parse_state *state, void *font, void *character, uint32_t color, int16_t x, int16_t y, int16_t source_x, int16_t source_y, int16_t width, int16_t height);  // 0x556260
extern int16_t text_parse_next_token_narrow(text_parse_state *state);  // 0x556bb0
extern int16_t text_parse_next_token_wide(text_parse_state *state);  // 0x556f10
extern void text_parse_state_initialize(void *string, int16_t justification, int16_t style, text_parse_state *state, datum_index font, ColorARGB *color);  // 0x556b00

#endif
