// Generated by tools/gen_prototypes.py from the extern declarations that used to be copied into every
// caller: prototypes of the functions defined in src/units/. Do not edit by hand; fix a signature in the
// definition and regenerate (names whose callers disagreed are NOT here).
#ifndef FN_UNITS_H
#define FN_UNITS_H

#include "tags.h"
#include "memory.h"
#include "math.h"
#include "units.h"
#include "objects.h"

extern void biped_advance_frame_counter_trigger(uint32_t object_index, char *state_out);  // 0x55eb90, EAX, stack
extern void biped_apply_idle_fidget(uint32_t object_index, uint8_t *state_out);  // 0x55e940, EDI, stack
extern void biped_check_evade_reaction(uint32_t object_index);  // 0x55e190
extern datum_index biped_get_cached_look_at_position(uint32_t object_index, real_point3d *out_position);  // 0x55ab30
extern void biped_ground_adjust_apply_node_rotations(uint32_t object_index, real_matrix4x3 *nodes, real_point3d *saved_positions);  // 0x558a20
extern void biped_ground_adjust_solve(uint32_t object_index, real_matrix4x3 *nodes);  // 0x558000, stack (0x557b48 pushes nodes, object)
extern char biped_ground_adjust_solve_node(uint32_t object_index, real_point3d *reference_position, int32_t node_index, real_matrix4x3 *nodes, real_point3d *own_position, uint32_t *success_bits);  // 0x557b80, EAX, EBX
extern uint32_t biped_ground_adjust_step(uint32_t object_index);  // 0x557a90, stack (0x55e883 pushes only the object)
extern void biped_movement_solve(biped_movement_solver_data *solve);  // 0x55efd0
extern void biped_trigger_on_velocity_threshold(uint32_t object_index);  // 0x55ec20, EAX
extern void biped_update_animation_frame_trigger(float threshold, uint8_t *timing_table, object *object_base);
extern void biped_update_idle_basis(uint32_t object_index, uint8_t *state_out);  // 0x55e840, ESI, EDI
extern void biped_update_target_lock_timer(datum_index target, uint32_t object_index);  // 0x55e0a0, blam-cc: EAX target, ECX object
extern void unit_accumulate_clamped_offset(uint32_t object_index, float new_value);  // 0x570400, units module, blam-cc: EAX, stack
extern void unit_add_initial_weapons(uint32_t object_index);  // 0x56cf10, blam-cc: ESI -> object_index
extern void unit_add_marker_relative_offset(uint32_t unit_index, uint32_t mode, float *world_point, uint32_t reference_direction, uint32_t offsets, real_point3d *accumulator);  // 0x569190, stack, EAX accumulator
extern int32_t unit_animation_change_priority_check(uint32_t unit_index, uint8_t follow_fallback, int16_t requested_priority, uint8_t allow_repeat, uint32_t *out_unknown_3f0, int16_t *dialogue_index, int32_t *chain_value);  // 0x560d00, EAX, DL, stack
extern uint8_t unit_animation_state_allows_parent_ik(uint8_t *animation_block);  // 0x565d60, blam-cc: ECX -> animation_block;
extern uint8_t unit_animation_state_allows_weapon_ik(uint8_t *animation_block);  // 0x565d00, blam-cc: ECX -> animation_block;
extern uint8_t unit_any_dying_or_seat_transition(void);  // 0x56c070, units module, not in this batch; UNSURE purpose,
extern void unit_apply_damage_effects(datum_index unit_index, damage_data *dd, uint32_t flags, float shield_damage, float body_damage, int32_t region_index, uint8_t is_local);  // 0x5674a0, stack
extern void unit_apply_fall_damage(uint32_t object_index, float fall_speed);  // 0x55e4f0
extern void unit_apply_impulse(uint32_t object_index, real_vector3d *impulse);  // 0x559fa0, EAX, EDI
extern void unit_apply_impulse_to_seat(uint32_t unit_index, real_vector3d *impulse);  // 0x571cb0, ECX, EAX
extern int16_t unit_base_animation_state_from_name(const char *name);  // 0x56eb90, blam-cc: EDI name
extern void unit_broadcast_state_change_event(unit_state_change_record record);  // 0x566c00, the record by value
extern int32_t unit_build_network_update(uint32_t object_index, int32_t buffer, int32_t bit_budget);  // 0x55aed0
extern void unit_calculate_luminosity(uint32_t object_index);  // 0x56ec60, EDI
extern void unit_cause_melee_damage(uint32_t unit_index, uint8_t suppress_effect, uint32_t target_object_index, int16_t damage_param4, int16_t damage_param5, int16_t damage_param6, uint32_t damage_param7);  // 0x56f2d0
extern void unit_check_fell_off_level(uint32_t object_index);  // 0x55e4a0, ECX
extern uint8_t unit_clamp_direction_to_aim_or_look_bounds(uint32_t unit_index, real_vector3d *world_direction, uint8_t use_aiming_bounds);  // 0x5697a0; EDI unit, stack (direction, flag)
extern void unit_clear_ground_adjust_dirty(uint32_t object_index);  // 0x55ad70, this batch: clears ground-adjust dirty flags
extern void unit_compute_marker_offset_position(uint32_t object_index, real_vector3d *reference_direction, int16_t mode, real_point3d *out_position, float *base_position, float *offsets);  // 0x55a170, ECX, EDX, BX, ESI, stack
extern void unit_detach_and_enter_named_seat(uint32_t unit_index, uint32_t target_parent_index, char *seat_marker_name);
extern int16_t unit_detach_child_at_named_seat(uint32_t unit_index, char *seat_marker_name);  // 0x56ab50, cdecl
extern void unit_dialogue_determine_variant(uint32_t object_index);  // 0x5618e0, blam-cc: EAX -> object_index
extern uint8_t unit_drop_current_weapon(uint32_t unit_index, uint8_t force);  // 0x56dec0
extern void unit_drop_grenades(uint32_t unit_index);  // 0x56ef60
extern void unit_drop_inventory_weapons(uint32_t unit_index);  // 0x56f060
extern void unit_drop_object_from_hand(uint32_t unit_index, uint32_t dropped_object_index);  // 0x56ed00
extern void unit_enter_stunned_state(uint32_t unit_index, uint32_t responsible_object);  // 0x5705a0, EDI, stack
extern uint32_t unit_enter_vehicle_seat(uint32_t vehicle_index, int16_t seat_index, uint32_t unit_index);  // 0x566970, EAX unit, stack
extern void unit_evaluate_flee_reaction(uint32_t object_index);  // 0x55e2d0, EDI
extern uint32_t unit_find_placement_position(uint32_t anchor_object, uint32_t orientation_object, real_point3d *out_position, float radius, char grid_mode, char skip_reposition, char scale_radius, uint32_t object_index_a, real_vector3d *reference_direction);  // 0x55a500, stack x7, EDX
extern int16_t unit_find_seats_matching_name_and_flags(uint32_t unit_index, char *name_filter, uint16_t flag_selector, int16_t *out_indices, int16_t max_indices);  // 0x56a310
extern uint16_t unit_find_weapon_index_with_fixed_flag(uint32_t unit_index);  // 0x570460, units
extern uint8_t unit_find_weapon_marker_transform(uint32_t unit_index, uint32_t vehicle_index, int16_t seat_index, real_point3d *out_entry, real_point3d *out_seat, real_point3d *out_hint);  // 0x5640a0, EAX unit, stack
extern void unit_fire_animation_sound_trigger(uint32_t unit_index, uint32_t trigger_kind, int16_t contact_point_index);  // 0x560590, next batch: fires a numbered unit trigger event
extern uint32_t unit_get_biped_specific_value(uint32_t object_index);  // 0x570ad0, EAX (AL used)
extern int32_t unit_get_custom_animation_time_remaining(uint32_t object_index);  // 0x5701b0, blam-cc: EAX
extern void unit_get_look_origin_and_direction(uint32_t object_index, uint32_t *out_status, real_vector3d *out_direction, real_point3d *out_origin);  // 0x55a390, units module
extern uint8_t unit_get_recently_updated_flag(uint32_t object_index);  // 0x570c80, EAX
extern uint8_t unit_has_child_of_type5(uint32_t unit_index);  // 0x570d70, ECX
extern void unit_initialize_random_turn_angle(uint32_t object_index);  // 0x570650, EAX
extern uint8_t unit_is_area_clear_of_fast_objects(void);  // UNSURE module: "vehicle_moving_near_any_player"
extern uint8_t unit_local_player_weapon_flag_check(void);  // 0x565b00
extern void unit_melee_attack_scan(uint32_t unit_index);  // 0x56f550
extern void unit_melee_lunge_damage_tick(uint32_t unit_index);  // 0x56fc80
extern uint8_t unit_named_seat_occupant_in_zone(uint32_t unit_index, char *seat_label, uint32_t zone_list_index);  // 0x56b380, cdecl
extern uint32_t unit_noop_569670(uint32_t object_index);  // 0x569670, EAX object (its result is kept as the excluded object)
extern uint8_t unit_point_in_front_and_asleep(real_point3d *world_point, uint32_t unit_index);  // 0x56bc80, EAX, EDI
extern int32_t unit_predict_aim_target_position(uint32_t unit_index, real_point3d *out_position);  // 0x571de0, ESI unit, EBX out
extern uint32_t unit_predict_movement_delta(real_vector3d *out_position_delta, real_vector3d *out_forward_delta, real_vector3d *out_up_delta, float time_fraction);
extern void unit_process_melee_special_interaction(uint32_t attacker_index, uint32_t target_index, uint32_t node_pair, uint32_t region_pair, uint32_t material, real_point3d *contact_point, real_plane3d *contact_plane, bsp_leaf_reference *contact_leaf);  // 0x56ff40, EAX, stack
extern void unit_ready_desired_weapon(uint32_t unit_index, uint8_t force);  // 0x56d6e0
extern void unit_recalculate_position(uint32_t object_index);  // 0x558eb0, EAX
extern void unit_release_thrown_grenade(uint32_t object_index, uint8_t apply_throw_fraction);  // 0x56e440
extern void unit_release_transient_state(uint32_t unit_index, uint8_t is_light_reset);  // 0x568610
extern void unit_reset_ground_adjust_state(uint32_t object_index);  // 0x55ad00, EAX
extern void unit_reset_orientation_and_find_position(uint32_t object_index, uint32_t vehicle_index);  // 0x55add0, stack, EDI
extern void unit_rotate_basis_about_axis(uint32_t object_index);  // 0x55e6b0, this batch
extern void unit_scripting_set_emotion_animation(uint32_t unit_index, const char *emotion_name);  // 0x569cf0, blam-cc: EAX, ECX
extern void unit_set_custom_animation(uint32_t object_index, datum_index graph, int16_t animation_index);  // 0x56ebd0, EAX, stack
extern uint8_t unit_set_custom_animation_frame(uint32_t unit_index, uint8_t warn_if_missing, datum_index graph_tag_id, const char *animation_name, int16_t frame);  // 0x570220, blam-cc: ECX, EAX, EDI, stack
extern void unit_set_facing_from_index_table(uint32_t object_index);  // 0x570de0
extern uint32_t unit_snap_to_min_ground_height(uint32_t object_index);  // 0x55ecf0
extern uint8_t unit_start_user_animation(uint32_t unit_index, datum_index graph_tag, const char *animation_name, uint8_t interpolate);  // 0x5702a0, stack unit, EDI graph, EAX name, stack interpolate
extern int32_t unit_test_placement_candidate(uint32_t unit_index, const real_vector3d *direction, real_vector3d *out_normal, float distance, real_point3d *out_position);  // 0x55aa20, ECX, ESI, EBX, stack
extern void unit_throw_grenade_move_to_hand(uint32_t unit_index);  // 0x56e280
extern void unit_track_target_lock_timeout(uint32_t object_index);  // 0x55ec90, UNSURE: register arg
extern void unit_trigger_material_hit_effect(int16_t material_index, datum_index unit_tag_id, datum_index object_index);  // 0x56f210, this batch
extern void unit_try_exit_controlled_seat(uint32_t unit_index);  // 0x56b5f0, blam-cc: EAX
extern uint8_t unit_try_select_equipment(uint32_t unit_index, uint32_t new_equipment_object_index, int16_t release_current);  // 0x56d1a0
extern uint8_t unit_try_start_scripted_action_animation(uint32_t unit_index, int16_t command, const real_vector2d *direction);  // 0x569530
extern uint8_t unit_try_start_seat_exit_animation(uint8_t force_flag, uint32_t unit_index);  // 0x56c470, AL, EDI
extern uint8_t unit_update(uint32_t unit_index);  // 0x5625b0, established (units module)
extern uint16_t unit_update_animation_state_machine(uint32_t unit_index, const int8_t *request);  // 0x565420, stack, ECX
extern void unit_update_animation_timers(uint32_t unit_index);  // 0x561620, EAX
extern void unit_update_autoaim_interaction(uint32_t unit_index);  // 0x570720
extern void unit_update_ground_contact_counter(uint32_t unit_index, uint8_t *contact_points);  // 0x575640
extern void unit_update_look_delta_controls(uint32_t object_index);  // 0x56e820, EAX
extern void unit_update_marker_skid_effects(uint32_t unit_index, uint8_t *contact_points);  // 0x575460
extern uint32_t unit_update_marker_traction_effects(uint32_t object_index);  // 0x575170
extern void unit_update_random_turn_angle(uint32_t object_index, real_vector3d *out_axis);  // 0x570840, EAX, EDI
extern void unit_update_recoil_decay(uint32_t object_index);  // 0x574780
extern void unit_update_stance_and_jump(uint32_t unit_index, uint8_t force_ready, uint8_t allow_death_reaction, uint8_t suppress_shield_check, uint8_t ignore_disoriented, uint8_t force_reaction, float turn_angle, int16_t weapon_class_index, const real_vector2d *throttle, uint8_t require_still);  // UNSURE: out of range, 0x566de0
extern void unit_update_steering_deviation_effects(uint32_t unit_index, real_vector3d *reference_direction, uint8_t *contact_points);  // 0x574f30
extern void unit_validate_and_clear_weapon_switch(uint32_t unit_index);  // 0x5659c0
extern void vehicle_calculate_ground_contact_lean(uint32_t unit_index, void *out_record, void *out_transform);  // 0x573f60, this batch
extern void vehicle_calculate_ground_contact_lean_alt(uint32_t unit_index, void *out_record, void *out_transform);  // 0x574460, this batch
extern void vehicle_calculate_ground_lean_controls(uint32_t unit_index, uint8_t *out_transform);  // 0x573100
extern void vehicle_calculate_lean_controls(uint32_t unit_index, void *mass_points, float *powered_states);  // 0x572df0, stack + ESI
extern void vehicle_calculate_mounted_controls_dispatch(uint32_t unit_index, void *out_transform, void *out_record);  // 0x573ee0, ESI, ECX, EDX
extern void vehicle_calculate_steering_wheel_controls(uint32_t unit_index, void *mass_points, float *powered_states);  // 0x572cd0, stack + EDI
extern void vehicle_calculate_turret_controls(uint32_t unit_index, void *mass_points, float *powered_states);  // 0x572b60, stack + EDI
extern void vehicle_calculate_wing_flex_controls(uint32_t unit_index, float angle, uint8_t *node_output, uint8_t *contact_points);  // 0x5734d0
extern void vehicle_create_hover_thruster_effects(uint32_t unit_index);  // 0x574900
extern void vehicle_create_hover_thruster_midpoint_effects(uint32_t unit_index);  // 0x574bc0, this batch
extern void vehicle_reset_state(uint32_t object_index);  // 0x570b00

#endif
