/**
 * @file include/halo/hs/api.hpp
 * Functions of the hs module that other modules and the data tables call (namespace halo::hs). The record types are
 * forward-declared, so the header is light enough for every caller and for the data tables.
 */
#pragma once

#include <stdint.h>



struct TagReflexive;
struct data_array;
struct effect;
struct hs_thread;
typedef uint32_t datum_index;
typedef datum_index object_list_iterator;
typedef int16_t hs_type_t;
typedef uint16_t hs_global_reference;

namespace halo::hs {

/**
 * The engine globals the hs module owns (their storage is defined by standalone/data under the original link names);
 * other modules reach them through globals().
 */
struct Globals {
    data_array *&thread_data;
    data_array *&globals_data;
    data_array *&syntax_data;
    uint8_t &runtime_active;
    uint8_t &syntax_data_is_local;
    int16_t &current_thread_index;
    int32_t &compile_error_offset;
    char *&compile_error;
    char *&compiled_source;
    int32_t &compiled_source_length;
    uint8_t &set_forbidden;
    uint8_t &reload_pending;
    uint8_t &preserve_token_case;
    uint8_t &postprocessing;
    uint8_t &blocking_forbidden;
    uint16_t &autocomplete_gametype_mask;
};

Globals &globals();

void game_variant_list_matching_substring_evaluate(int16_t function_index, datum_index thread, char first);
char hs_add_global(datum_index node_index);
char hs_add_script(datum_index node_index);
void hs_allocate_script_node_table(void);
void hs_autocomplete_add_command_list_names(void);
void hs_autocomplete_add_conversation_names(void);
void hs_autocomplete_add_cutscene_camera_point_names(void);
void hs_autocomplete_add_cutscene_flag_names(void);
void hs_autocomplete_add_cutscene_title_names(void);
void hs_autocomplete_add_encounter_names(void);
void hs_autocomplete_add_function_names(void);
void hs_autocomplete_add_global_names(void);
void hs_autocomplete_add_hud_message_names(void);
void hs_autocomplete_add_navpoint_names(void);
void hs_autocomplete_add_object_names(void);
void hs_autocomplete_add_recorded_animation_names(void);
void hs_autocomplete_add_script_names(void);
void hs_autocomplete_add_starting_profile_names(void);
void hs_autocomplete_add_startup(void);
void hs_autocomplete_add_trigger_volume_names(void);
void hs_autocomplete_add_type_names(void);
int16_t hs_autocomplete_gather(uint32_t category_mask, char **results, char *prefix, int16_t maximum_count, uint16_t gametype_mask);
void hs_autocomplete_scan_candidates(char **table, int16_t end, int16_t start);
void hs_autocomplete_scan_globals(TagReflexive *table, int16_t name_offset, int32_t stride);
void hs_autocomplete_test_candidate(char *candidate);
char hs_call_script_by_name(char *name);
int32_t hs_cast_enum_to_real(int32_t value);
int32_t hs_cast_identity(int32_t value);
int32_t hs_cast_long_to_boolean(int32_t value);
int32_t hs_cast_long_to_real(int32_t value);
datum_index hs_cast_object_name_to_object_list(int32_t name_index);
int32_t hs_cast_real_to_short(int32_t value);
int32_t hs_cast_short_to_boolean(int32_t value);
int32_t hs_cast_short_to_real(int32_t value);
int32_t hs_coerce_value(int32_t value, hs_type_t dest_type, hs_type_t source_type);
void hs_compile(int32_t source_length, char *source_text, char **error_message, int32_t *error_offset);
char hs_compile_and_evaluate(char *command);
datum_index hs_compile_expression(char *text, uint32_t length, char **error_message, char **error_offset);
char hs_compile_postprocess(char **error_message, int32_t *error_offset);
char hs_compile_source(void);
void hs_damage_apply_at_location(int16_t location_index, uint32_t damage_effect);
void hs_damage_apply_with_sound(datum_index object_index, uint32_t damage_effect);
void hs_dispose_dynamic_globals(void);
void hs_doc(void);
void hs_effect_spawn_at_location(int16_t location_index, uint32_t effect);
void hs_effect_spawn_on_marker(datum_index object_index, datum_index effect, char *marker_name);
void hs_enumerate_special_form_names(void);
void hs_evaluate_activate_nav_point_flag(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_activate_nav_point_object(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_activate_team_nav_point_flag(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_activate_team_nav_point_object(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_actors(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_allegiance(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_allegiance_broken(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_allegiance_remove(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_allow_charge(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_allow_dormant(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_attach(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_attach_free(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_attach_units(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_attack(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_automatic_migration_target(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_berserk(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_braindead(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_braindead_by_unit(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_command_list(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_command_list_advance(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_command_list_advance_by_unit(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_command_list_by_unit(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_command_list_status(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_conversation(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_conversation_advance(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_conversation_line(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_conversation_status(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_conversation_stop(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_defend(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_detach(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_detach_units(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_dialogue_triggers(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_disregard(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_erase(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_erase_all(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_exit_vehicle(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_follow_distance(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_follow_target_ai(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_follow_target_disable(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_follow_target_players(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_follow_target_unit(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_force_active(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_force_active_by_unit(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_free(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_free_units(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_go_to_vehicle(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_go_to_vehicle_override(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_going_to_vehicle(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_grenades(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_is_attacking(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_kill(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_kill_silent(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_link_activation(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_living_count(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_living_fraction(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_look_at_object(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_magically_see_encounter(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_magically_see_players(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_magically_see_unit(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_magically_see_units(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_maneuver_enable(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_migrate(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_migrate_and_speak(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_migrate_by_unit(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_nonswarm_count(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_place(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_playfight(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_prefer_target(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_renew(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_retreat(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_set_blind(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_set_current_state(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_set_deaf(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_set_respawn(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_set_return_state(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_set_team(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_spawn_actor(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_status(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_stop_looking(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_strength(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_swarm_count(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_teleport_to_starting_location(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_teleport_to_starting_location_if_unsupported(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_timer_expire(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_timer_start(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_try_to_fight(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_try_to_fight_nothing(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_try_to_fight_player(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_vehicle_encounter(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_vehicle_enterable_actor_type(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_vehicle_enterable_actors(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_vehicle_enterable_disable(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_vehicle_enterable_distance(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ai_vehicle_enterable_team(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_argument_list(uint32_t unused_param_1, uint32_t thread_index, int32_t value);
void hs_evaluate_arithmetic_reduce(int16_t opcode, uint32_t thread_index, char first);
void hs_evaluate_begin(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_bind(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_boolean_and_or(int16_t opcode, uint32_t thread_index, char first);
void hs_evaluate_breakable_surfaces_enable(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_breakable_surfaces_reset(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_camera_control(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_camera_set(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_camera_set_animation(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_camera_set_dead(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_camera_set_first_person(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_camera_set_relative(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_camera_time(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_change_team(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cheat_active_camouflage(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cheat_active_camouflage_local_player(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cheat_all_powerups(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cheat_all_vehicles(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cheat_all_weapons(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cheat_spawn_warthog(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cheat_teleport_to_camera(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_checkpoint_load(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_checkpoint_save(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_abort(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_screen_effect_set_convolution(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_screen_effect_set_filter(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_screen_effect_set_filter_desaturation_tint(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_screen_effect_set_video(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_screen_effect_start(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_screen_effect_stop(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_set_near_clip_distance(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_set_title(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_set_title_delayed(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_show_letterbox(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_skip_start_internal(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_skip_stop_internal(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_start(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_stop(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cinematic_suppress_bsp_object_creation(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_cls(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_comparison(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_connect(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_core_load(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_core_load_at_startup(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_core_save(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_crash(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_custom_animation(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_custom_animation_list(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_damage_new(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_damage_object(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_deactivate_nav_point_flag(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_deactivate_nav_point_object(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_deactivate_team_nav_point_flag(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_deactivate_team_nav_point_object(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_debug_camera_load(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_debug_camera_save(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_debug_sounds_enable(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_device_get_position(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_device_get_power(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_device_group_change_only_once_more_set(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_device_group_get(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_device_group_set(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_device_group_set_immediate(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_device_one_sided_set(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_device_operates_automatically_set(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_device_set_never_appears_locked(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_device_set_position(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_device_set_position_immediate(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_device_set_power(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_disconnect(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_display_scenario_help(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_effect_new(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_effect_new_on_object_marker(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_enable_hud_help_flash(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_equality(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_error_overflow_suppression(int16_t function_index, uint32_t thread_index, char first);
int32_t hs_evaluate_expression(datum_index node);
void hs_evaluate_fade_in(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_fade_out(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_fast_setup_network_server(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_all_quiet(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_difficulty_get(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_difficulty_get_real(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_difficulty_set(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_is_cooperative(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_lost(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_revert(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_reverted(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_safe_to_save(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_safe_to_speak(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_save(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_save_cancel(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_save_no_timeout(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_save_totally_unsafe(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_saving(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_skip_ticks(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_speed(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_time(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_variant(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_game_won(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_garbage_collect_now(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_digital_forward_throttle(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_digital_pitch_increment(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_digital_strafe_throttle(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_digital_yaw_increment(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_gamepad_forward_threshold(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_gamepad_strafe_threshold(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_gamepad_yaw_scale(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_mouse_forward_threshold(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_mouse_pitch_scale(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_mouse_strafe_threshold(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_mouse_yaw_scale(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_pitch_rate(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_get_yaw_rate(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_help(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_blink_health(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_blink_motion_sensor(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_blink_shield(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_clear_messages(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_get_timer_ticks(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_help_flash_restart(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_set_help_text(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_set_objective_text(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_set_timer_position(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_set_timer_time(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_set_timer_warning_time(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_show_crosshair(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_show_health(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_show_motion_sensor(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_hud_show_shield(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_if(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_ignore_arguments(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_input_activate_joy(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_input_deactivate_joy(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_input_find_default(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_input_find_joystick(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_input_get_joy_count(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_input_is_joy_active(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_input_show_joystick_info(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_inspect(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_list_count(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_list_get(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_magic_melee_attack(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_magic_seat_name(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_map_name(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_map_reset(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_message_metrics_dump(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_multiplayer_map_name(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_net_graph_clear(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_net_graph_show(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_not(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_nothing(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_numeric_countdown_timer_get(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_numeric_countdown_timer_restart(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_numeric_countdown_timer_set(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_numeric_countdown_timer_stop(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_beautify(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_can_take_damage(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_cannot_take_damage(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_cast(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_create(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_create_anew(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_create_anew_containing(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_create_containing(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_destroy(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_destroy_all(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_destroy_containing(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_pvs_clear(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_pvs_set_camera(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_pvs_set_object(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_set_collideable(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_set_facing(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_set_melee_attack_inhibited(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_set_permutation(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_set_ranged_attack_inhibited(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_set_scale(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_set_shield(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_teleport(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_object_type_predict(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_objects_attach(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_objects_can_see_flag(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_objects_can_see_object(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_objects_delete_by_definition(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_objects_detach(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_objects_dump_memory(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_objects_predict(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_pause_hud_timer(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_play_update_history(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_playback(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player0_joystick_set_is_normal(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player0_look_invert_pitch(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player0_look_pitch_is_inverted(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_accept(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_action(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_back(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_grenade_trigger(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_jump(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_look_relative_all_directions(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_look_relative_down(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_look_relative_left(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_look_relative_right(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_look_relative_up(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_move_relative_all_directions(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_primary_trigger(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_reset(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_action_test_zoom(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_add_equipment(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_camera_control(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_effect_set_max_rotation(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_effect_set_max_translation(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_effect_start(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_effect_stop(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_player_enable_input(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_players(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_players_unzoom_all(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_print(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_print_binds(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_profile_load(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_profile_unlock_solo_levels(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_quit(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_random(hs_thread *thread, uint32_t thread_index, char first);
void hs_evaluate_random_range(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_rasterizer_fixed_function_ambient(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_rasterizer_lights_reset_for_new_map(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_rasterizer_model_ambient_reflection_tint(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_rcon(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_real_random_range(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_recording_kill(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_recording_play(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_recording_play_and_delete(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_recording_play_and_hover(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_recording_time(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_remote_player_stats(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_render_lights(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_scenery_animation_start(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_scenery_animation_start_at_frame(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_scenery_get_animation_time(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_script_doc(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_script_recompile(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_script_screen_effect_set_value(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_digital_forward_throttle(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_digital_pitch_increment(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_digital_strafe_throttle(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_digital_yaw_increment(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_gamepad_forward_threshold(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_gamepad_strafe_threshold(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_gamma(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_mouse_forward_threshold(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_mouse_pitch_scale(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_mouse_strafe_threshold(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_mouse_yaw_scale(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_pitch_rate(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_set_yaw_rate(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_show_hud(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_show_hud_help_text(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_show_hud_timer(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sleep(uint32_t unused_param_1, uint32_t thread_index, char first);
void hs_evaluate_sleep_ticks(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_cache_dump_to_file(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_class_set_gain(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_eax_enabled(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_enable(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_enable_eax(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_enable_hardware(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_get_effects_gain(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_get_gain(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_get_master_gain(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_get_music_gain(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_get_supplementary_buffers(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_impulse_start(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_impulse_stop(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_impulse_time(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_looping_predict(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_looping_set_alternate(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_looping_set_scale(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_looping_start(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_looping_stop(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_set_effects_gain(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_set_env(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_set_factor(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_set_gain(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_set_master_gain(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_set_music_gain(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_set_rolloff(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sound_set_supplementary_buffers(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_structure_bsp_index(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_ban(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_banlist(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_end_game(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_get_player_action_queue_length(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_kick(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_map(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_map_next(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_map_reset(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_mapcycle(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_mapcycle_add(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_mapcycle_begin(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_mapcycle_del(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_parameters_dump(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_parameters_reload(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_players(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_status(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_sv_unban(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_switch_bsp(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_thread_sleep(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_track_remote_player_position_updates(int16_t function_index, uint32_t thread_index, char first);
int32_t * hs_evaluate_typed_arguments(uint32_t thread_index, int16_t parameter_count, int16_t *expected_types, char first);
void hs_evaluate_ui_widget_show_path(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unbind(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_aim_without_turning(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_can_blink(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_close(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_custom_animation_at_frame(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_doesnt_drop_items(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_enter_vehicle(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_exit_vehicle(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_get_current_flashlight_state(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_get_custom_animation_time(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_get_health(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_get_shield(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_get_total_grenade_count(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_has_weapon(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_has_weapon_readied(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_impervious(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_is_playing_custom_animation(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_kill_silent(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_open(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_set_current_vitality(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_set_desired_flashlight_state(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_set_emotion(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_set_emotion_animation(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_set_enterable_by_player(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_set_maximum_vitality(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_set_seat(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_solo_player_integrated_night_vision_is_active(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_stop_custom_animation(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_unit_suspended(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_units_set_current_vitality(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_units_set_desired_flashlight_state(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_units_set_maximum_vitality(int16_t function_index, uint32_t thread_index, char first);
char hs_evaluate_variadic_arguments(uint32_t thread_index, int32_t value, uint32_t *out_count, int32_t **out_values);
void hs_evaluate_vehicle_driver(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_vehicle_hover(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_vehicle_load_magic(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_vehicle_riders(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_vehicle_test_seat_list(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_vehicle_unload(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_version(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_volume_teleport_players_not_inside(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_volume_test_object(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_volume_test_objects(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_volume_test_objects_all(int16_t function_index, uint32_t thread_index, char first);
void hs_evaluate_wake(int16_t function_index, uint32_t thread_index, char first);
int16_t hs_find_function_by_name(char *name);
hs_global_reference hs_find_global_by_name(char *name);
void hs_format_function_signature(int16_t function_index, char *out);
char hs_gametype_flag_satisfied(uint8_t bit_index, uint8_t flags);
uint8_t hs_gametype_flags_applicable(uint8_t flags);
char hs_get_parameter_indices(char *function_name, int16_t required_count, datum_index node_index, datum_index *out_indices);
char * hs_global_get_name(hs_global_reference global);
hs_type_t hs_global_get_type(hs_global_reference global);
int32_t hs_global_get_value(hs_global_reference reference);
void hs_global_read_value(hs_global_reference reference);
void hs_global_write_value(hs_global_reference reference);
void hs_help_print_function(char *name);
void hs_inspect_boolean(int16_t type, int32_t value, char *buffer);
void hs_inspect_enum(int16_t type, int32_t value, char *buffer);
void hs_inspect_long(int16_t type, int32_t value, char *buffer);
void hs_inspect_real(int16_t type, int32_t value, char *buffer);
void hs_inspect_short(int16_t type, int32_t value, char *buffer);
void hs_inspect_string(int16_t type, int32_t value, char *buffer);
uint8_t hs_object_angle_predicate_helper(datum_index object_index, datum_index viewer_unit, float angle_degrees);
void hs_object_create_name_index_if_absent(int32_t name_index);
void hs_object_detach_and_place_at_location(int16_t location_index, datum_index object_index, char detach_from_parent, char reorient);
char hs_object_hierarchy_test(datum_index object_index);
uint32_t hs_object_list_any_angle_match(datum_index header_index, datum_index target_object, float angle_degrees);
uint32_t hs_object_list_any_angle_match_gated(datum_index header_index, int16_t gate, float angle_degrees);
datum_index hs_object_list_collect_player_units(void);
void hs_object_list_for_each(datum_index header_index);
datum_index hs_object_list_new_singleton(datum_index object_index);
char hs_object_list_test_trigger_volume(int32_t trigger_volume_index, datum_index header_index, char all_mode);
void hs_object_name_cache_validate(int16_t object_name_index);
void hs_object_name_destroy(int32_t object_name_index);
void hs_object_names_for_each(void (*callback)(int32_t index), uint32_t predicate_arg);
int32_t hs_object_orient(float x);
void hs_object_runtime_cleanup(void);
void hs_object_set_health_fraction(datum_index object_index, float fraction);
void hs_object_set_permutation_by_name(datum_index object_index, void *permutation_name, char *name);
void hs_objects_delete_by_type(uint32_t tag_id);
char hs_parse(datum_index node_index, hs_type_t expected_type);
char hs_parse_ai(datum_index node_index);
char hs_parse_ai_command_list(datum_index node_index);
char hs_parse_arithmetic(int16_t function_index, datum_index node_index);
char hs_parse_begin(int16_t function_index, datum_index node_index);
char hs_parse_boolean(datum_index node_index);
char hs_parse_cond(int16_t function_index, datum_index node_index);
datum_index hs_parse_cond_recursive(datum_index cond_node_index, datum_index pair_index);
char hs_parse_conversation(datum_index node_index);
char hs_parse_cutscene_camera_point(datum_index node_index);
char hs_parse_cutscene_flag(datum_index node_index);
char hs_parse_cutscene_recording(datum_index node_index);
char hs_parse_cutscene_title(datum_index node_index);
char hs_parse_device_group(datum_index node_index);
char hs_parse_function_arguments(int16_t function_index, datum_index node_index);
char hs_parse_hud_message(datum_index node_index);
char hs_parse_if(int16_t function_index, datum_index node_index);
char hs_parse_inspect(int16_t function_index, datum_index node_index);
char hs_parse_integer(datum_index node_index);
char hs_parse_logical(int16_t function_index, datum_index node_index);
char hs_parse_navpoint(datum_index node_index);
char hs_parse_nonprimitive(datum_index node_index);
char hs_parse_object(datum_index node_index);
char hs_parse_object_list(datum_index node_index);
char hs_parse_object_name(datum_index node_index);
char hs_parse_primitive(datum_index node_index);
char hs_parse_real(datum_index node_index);
char hs_parse_scenario_datum(datum_index node_index, int16_t name_offset, TagReflexive *array, int32_t stride);
char hs_parse_script(datum_index node_index);
char hs_parse_set(int16_t function_index, datum_index node_index);
char hs_parse_sleep(int16_t function_index, datum_index node_index);
char hs_parse_sleep_until(int16_t function_index, datum_index node_index);
char hs_parse_starting_profile(datum_index node_index);
char hs_parse_string(datum_index node_index);
char hs_parse_string_arguments(int16_t function_index, datum_index node_index);
char hs_parse_tag_reference(datum_index node_index);
char hs_parse_trigger_volume(datum_index node_index);
char hs_parse_two_numeric_arguments(int16_t function_index, datum_index node_index);
char hs_parse_two_object_arguments(int16_t function_index, datum_index node_index);
char hs_parse_unit(int16_t function_index, datum_index node_index);
char hs_parse_variable(datum_index node_index);
char hs_parse_wake(int16_t function_index, datum_index node_index);
char hs_rebuild_source(void);
char hs_report_expected_enum_values(datum_index node_index);
void hs_reposition_players_outside_trigger_volume(int32_t trigger_volume_index, int32_t location_index);
void hs_resolve_identifier_as_function_or_script(datum_index node_index);
void hs_runtime_initialize(void);
void hs_runtime_update(void);
void hs_scenario_scripts_initialize(void);
int16_t hs_script_find_by_name(char *name);
char hs_scripts_compile_and_link(char restore_previous);
void hs_scripts_free(void);
void hs_scripts_reload(void);
float * hs_sound_get_gain_reference(char *name);
char * hs_source_buffer_append(char *text, uint32_t length);
char hs_string_is_empty(char *s);
void hs_syntax_node_garbage_collect(void);
void hs_thread_evaluate_step(uint32_t thread_index);
datum_index hs_thread_find_by_script_index(int16_t script_index);
datum_index hs_thread_find_by_script_name(char *name);
datum_index hs_thread_new(int32_t script_index, uint8_t type);
void hs_thread_pop_frame(uint32_t thread_index);
void hs_thread_push(datum_index node, uint32_t thread_index, void *result_address);
void hs_thread_restart(uint32_t thread_index);
void hs_thread_return(int32_t value, uint32_t thread_index);
datum_index hs_tokenize(char **cursor);
void hs_tokenize_nonprimitive(datum_index node_index, char **cursor);
void hs_tokenize_primitive(char **cursor, datum_index node_index);
char hs_type_mask_is_subset(int16_t subtype_index, int16_t supertype_index);
char hs_types_are_compatible(hs_type_t dest_type, hs_type_t source_type);
char hs_verify_source_offset(int32_t offset);
void map_list_matching_substring_evaluate(int16_t function_index, datum_index thread, char first);
int32_t object_list_get_first(datum_index header_index, object_list_iterator *iterator_out);
int32_t object_list_nth_reference(datum_index header_index, int16_t n);
void object_list_reference_add(datum_index header_index, datum_index object_index);
void object_list_reference_chain_delete(data_array *reference_array, datum_index chain_head);
void object_lists_dispose_empty(void);
void object_lists_initialize(void);
void skip_whitespace(char **cursor);
void sv_ban_penalty_evaluate(int16_t function_index, datum_index thread, char first);
void sv_banlist_file_evaluate(int16_t function_index, datum_index thread, char first);
void sv_friendly_fire_evaluate(int16_t function_index, datum_index thread, char first);
void sv_maxplayers_evaluate(int16_t function_index, datum_index thread, char first);
void sv_name_evaluate(int16_t function_index, datum_index thread, char first);
void sv_password_evaluate(int16_t function_index, datum_index thread, char first);
void sv_rcon_password_evaluate(int16_t function_index, datum_index thread, char first);
void sv_single_flag_force_reset_evaluate(int16_t function_index, datum_index thread, char first);
void sv_timelimit_evaluate(int16_t function_index, datum_index thread, char first);
void sv_tk_cooldown_evaluate(int16_t function_index, datum_index thread, char first);
void sv_tk_grace_evaluate(int16_t function_index, datum_index thread, char first);

}
