/* Tables generated by tools/gen_standalone_link.py into build/standalone/standalone_tables.c */
#ifndef STANDALONE_TABLES_H
#define STANDALONE_TABLES_H

typedef struct standalone_piece {
    const char *name;
    unsigned long va;
    unsigned long blob_offset;
    unsigned long raw_size;
} standalone_piece;

typedef struct standalone_import {
    unsigned long slot;               /* IAT slot address in the mapped image */
    const char *dll;
    const char *name;                 /* NULL: import by ordinal */
    unsigned short ordinal;
    unsigned long module_handle_slot; /* delay-load: where the module handle is cached, else 0 */
} standalone_import;

typedef struct standalone_code_pointer {
    unsigned long slot;               /* dword in .rdata/.data that held an original function address */
    void *target;                     /* our C function */
} standalone_code_pointer;

extern const standalone_piece standalone_pieces[];
extern const int standalone_piece_count;
extern const standalone_import standalone_imports[];
extern const int standalone_import_count;
extern const standalone_code_pointer standalone_code_pointers[];
extern const int standalone_code_pointer_count;
extern const char standalone_halo_folder[];

#endif
