/* Tables generated by tools/gen_standalone_link.py into build/standalone/standalone_tables.c */
#ifndef STANDALONE_TABLES_H
#define STANDALONE_TABLES_H

typedef struct standalone_piece {
    const char *name;
    unsigned long va;                 /* original address */
    const void *source;               /* the piece in our exe (standalone/image/<name>.asm) */
    unsigned long size;
} standalone_piece;

typedef struct standalone_import {
    unsigned long slot;               /* IAT slot address in the mapped image */
    const char *dll;
    const char *name;                 /* NULL: import by ordinal */
    unsigned short ordinal;
    unsigned long module_handle_slot; /* delay-load: where the module handle is cached, else 0 */
} standalone_import;

extern const standalone_piece standalone_pieces[];
extern const int standalone_piece_count;
extern const standalone_import standalone_imports[];
extern const int standalone_import_count;
typedef struct standalone_code_entry {
    unsigned long address;            /* an original function start */
    void *target;                     /* our C function for it (0 when the link left it unresolved) */
} standalone_code_entry;              /* sorted by address */

extern const standalone_code_entry standalone_code_entries[];
extern const int standalone_code_entry_count;
extern const char standalone_halo_folder[];

#endif
