/* The loader's tables: the data image pieces (standalone/image/pieces.c), the original address -> C function table
   (standalone/generated/code_entries.asm), both generated by tools/gen_link_sources.py; the Halo folder (loader.c) */
#ifndef STANDALONE_TABLES_H
#define STANDALONE_TABLES_H

typedef struct standalone_piece {
    const char *name;
    unsigned long va;                 /* original address */
    const void *source;               /* the piece in our exe (standalone/image/<name>.asm) */
    unsigned long size;
} standalone_piece;

extern const standalone_piece standalone_pieces[];
extern const int standalone_piece_count;
typedef struct standalone_code_entry {
    unsigned long address;            /* an original function start */
    void *target;                     /* our C function for it (0 when the link left it unresolved) */
} standalone_code_entry;              /* sorted by address */

extern const standalone_code_entry standalone_code_entries[];
extern const int standalone_code_entry_count;
extern const char standalone_halo_folder[];

#endif
