/**
 * @file include/halo/ai/api.hpp
 * Functions of the ai module that other modules and the data tables call (namespace halo::ai). The record types are
 * forward-declared, so the header is light enough for every caller and for the data tables.
 */
#pragma once

#include <stdint.h>

struct Actor;
struct actor_command_aim;
struct actor_mode_obey_data;
struct actor_squad_action_state;
struct actor_mode_flee_data;
struct real_vector2d;
struct ActorVariant;
struct actor_firing_positions;
struct bsp_leaf_reference;
struct actor_burst_parameters;
struct actor_burst_scale;
struct ai_globals;
struct data_array;
struct encounter_platoon_state;

struct Projectile;
struct Scenario;
struct ScenarioEncounter;
struct ScenarioSquad;
struct ScenarioStructureBSP;
struct actor;
struct actor_combat_consideration;
struct actor_firing_position_candidate;
struct actor_firing_position_query;
struct actor_flee_source_reason;
struct actor_iterator_state;
struct actor_look_request;
struct actor_movement_context;
struct actor_order;
struct actor_placement_request;
struct actor_prop_iterator;
struct actor_recognition_scan_result;
struct actor_squad_order_header;
struct ai_communication_order;
struct ai_communication_record;
struct ai_communication_target_result;
struct ai_conversation_range_lookup;
struct ai_grenade_avoidance_entry;
struct ai_group_bucket_entry;
struct ai_object_attention_record;
struct ai_path_candidate_goal;
struct ai_platoon_condition;
struct ai_priority_target_list;
struct ai_priority_target_record;
struct ai_queued_order;
struct ai_reference_actor_iterator;
struct ai_reference_platoon_range;
struct ai_reference_squad_iterator;
struct ai_scored_candidate;
struct ai_search_context;
struct ai_target_candidate_list;
struct ai_release_state;
struct ai_search_edge_result;
struct ai_search_nearest_point_result;
struct ai_search_obstacle_list;
struct encounter_squad_state;
struct flag;
struct object_list_header;
struct path_find_adjacent_edge;
struct path_find_boundary_crossing;
struct path_find_boundary_trace_result;
struct path_find_context;
struct path_find_request;
struct path_find_waypoint;
struct prop;
struct real_point2d;
struct real_point3d;
struct real_vector2d;
struct real_vector3d;
struct team;
typedef uint32_t datum_index;
typedef float real;
typedef void (*actor_swarm_member_callback)(uint32_t actor_index, datum_index unit_index, uint16_t extra, actor_squad_action_state *action, actor_command_aim *aim, uint32_t callback_extra);
typedef actor_flee_source_reason actor_vocalization_context;

namespace halo::ai {

/**
 * The engine globals the ai module owns (their storage is defined by standalone/data under the original link names);
 * other modules reach them through globals().
 */
struct Globals {
    data_array *&actor_data;
    data_array *&prop_data;
    data_array *&encounter_data;
    data_array *&swarm_data;
    data_array *&swarm_component_data;
    data_array *&conversation_data;
    data_array *&pursuit_data;
    ai_globals *&state;
    encounter_squad_state *&squad_states;
    encounter_platoon_state *&platoon_states;
    int32_t &communication_quiet_until_tick;
};

Globals &globals();

uint8_t actor_action_has_queued_secondary(datum_index actor_index);
uint8_t actor_alert_from_damage(datum_index actor_index);
uint8_t actor_alert_from_disturbance(datum_index actor_index);
uint8_t actor_alert_from_flag_1b4(datum_index actor_index);
uint8_t actor_alert_from_projectile(datum_index actor_index);
uint8_t actor_alert_from_squad_attack(datum_index actor_index);
datum_index actor_allocate_paired_prop(datum_index actor_index, datum_index existing_prop);
datum_index actor_allocate_paired_prop_with_kind(datum_index actor_index, datum_index existing_prop, datum_index reference_prop);
uint8_t actor_apply_perception_scale(datum_index actor_index, const uint8_t *zone, float *in_out_value);
void actor_apply_queued_look_to_unit(datum_index actor_index);
void actor_apply_unit_definition_properties(datum_index actor_variant_tag, datum_index unit_index);
void actor_attach_to_unit(datum_index actor_index, datum_index unit_index);
void actor_attempt_grenade_throw(datum_index actor_index);
uint8_t actor_avoid_obstacle_and_project(datum_index actor_index, datum_index vehicle_index, real_point3d *entry, real_point3d *hint, uint8_t *in_out_near_line, real_point3d *out_point, int32_t *out_surface_index);
void actor_avoidance_build_direction_tables(void);
uint8_t actor_avoidance_interpolate_sample(const real_vector3d *direction, const real_vector3d *samples, int16_t count, const float *values, float *out_index, float *out_value);
uint8_t actor_begin_vocalization(datum_index actor_index, int16_t line, int16_t variant, actor_vocalization_context *context);
uint8_t actor_build_guard_mode_data(datum_index actor_index, uint8_t *out);
int32_t actor_build_order_default(uint32_t actor_index, int16_t order_code, actor_order *order, int16_t parameter);
uint32_t actor_build_order_face_seat_marker(uint32_t actor_index, int16_t firing_position_index, uint32_t *order);
uint32_t actor_build_order_face_seat_marker_committed(uint32_t actor_index, int16_t firing_position_index, uint8_t byte_a, uint32_t *order);
int32_t actor_build_order_flee(uint32_t actor_index, uint8_t byte_a, uint32_t *order);
int32_t actor_build_order_grenade_or_melee(uint32_t resolved_target, uint8_t use_alt_base, uint32_t actor_index, uint16_t order_code, uint8_t byte_a, uint8_t byte_b, uint16_t *order);
int32_t actor_build_order_guard(uint32_t actor_index, actor_order *order, int16_t guard_at_current_position);
uint8_t actor_build_order_investigate_encounter_point(uint32_t vehicle_index, uint32_t actor_index, int16_t seat_index, uint8_t *order);
int32_t actor_build_order_look(uint32_t actor_index, actor_order *order, actor_look_request *request);
int32_t actor_build_order_minimal_stop(uint32_t actor_index, uint32_t *order);
int32_t actor_build_order_random_wait(uint32_t actor_index, uint8_t byte_a, uint32_t *order);
int32_t actor_build_order_return_to_anchor(uint32_t actor_index, actor_order *order);
uint8_t actor_build_order_search_object(uint32_t vehicle_index, uint32_t actor_index, float radius_a, float radius_b, uint8_t *order);
int32_t actor_build_order_search_wait(uint32_t actor_index, actor_order *order);
int32_t actor_build_order_wait_byte(uint32_t actor_index, uint8_t byte_a, uint32_t *order);
void actor_build_path_find_request(datum_index actor_index, path_find_request *request);
uint8_t actor_can_throw_grenade_at_target(datum_index actor_index);
uint8_t actor_check_burst_length_exceeded(datum_index actor_index);
uint8_t actor_check_grenade_facing_and_commit(datum_index actor_index, uint8_t force_commit);
void actor_check_melee_target_reachable(uint32_t actor_index, actor_mode_flee_data *record);
uint8_t actor_check_pain_reaction(uint32_t resolved_target, uint8_t use_alt_base, uint16_t order_code, datum_index actor_index);
uint8_t actor_check_step_obstruction(datum_index actor_index, real_vector2d *direction, float step_distance, float step_up, uint8_t *out_flag, void *extra_param);
uint8_t actor_check_vehicle_mode_timeout(datum_index actor_index);
uint8_t actor_check_vehicle_target_available(datum_index vehicle_object_index, datum_index actor_index, uint8_t flag_pursue);
uint8_t actor_check_weapon_pickup_reachable(uint32_t actor_index, actor_mode_flee_data *record);
void actor_choose_best_target(datum_index actor_index);
void actor_choose_random_point_near(real_point3d *inout_point, float radius);
int16_t actor_claim_firing_position(datum_index actor_index, datum_index previous_owner, path_find_context *path_context, int16_t firing_position_index, uint8_t path_ok);
int32_t actor_classify_communication_object_type(datum_index actor_index);
void actor_clear_perceived_props(datum_index actor_index);
void actor_clear_recognition_history(datum_index actor_index, uint8_t keep_when_typed);
void actor_clear_target_state(datum_index actor_index);
void actor_clear_vocalization(datum_index actor_index);
uint8_t actor_combat_status_should_hold(datum_index actor_index, int16_t threshold_a, int16_t threshold_b);
uint8_t actor_command_list_permits_escalation(datum_index actor_index);
void actor_command_list_reset_record(uint32_t actor_index, datum_index unit_index, uint16_t extra, actor_squad_action_state *action, actor_command_aim *aim, uint32_t callback_extra);
uint32_t actor_commit_grenade_toss(datum_index actor_index, real_point3d *point, uint32_t object_handle, uint32_t exclude_object_index);
float actor_compute_accuracy_scale(datum_index actor_index);
uint32_t actor_compute_grenade_aim_direction(datum_index actor_index, real_point3d *target_point, real_vector3d *out_direction, float *out_698);
uint32_t actor_compute_grenade_throw_vector(datum_index actor_index, real_point3d *grenade_position, real_vector3d *out_vector);
void actor_compute_swarm_avoidance_offset(datum_index actor_index, datum_index unit_index, float radius, float *out_offset);
float actor_compute_target_priority_weight(datum_index prop_index, datum_index actor_index);
uint8_t actor_conditional_state_transition_check(datum_index actor_index);
uint8_t actor_consider_combat_mode(uint32_t actor_index, int16_t consideration_mode, actor_combat_consideration *out);
uint8_t actor_consider_grenade_throw(datum_index actor_index);
uint16_t actor_consider_target_candidate(datum_index actor_index, datum_index candidate_prop_index);
void actor_copy_prop_and_reset(datum_index dest_prop, datum_index src_prop);
datum_index actor_create_swarm(datum_index actor_index);
uint8_t actor_danger_register_point(datum_index actor_index, datum_index source_object_index, float radius, float distance, char accept_flag, uint8_t unknown_byte);
uint8_t actor_danger_register_stationary_object(const actor_firing_positions *reference, datum_index actor_index, datum_index object_index, uint8_t unknown_byte);
void actor_danger_update_reaction(datum_index actor_index);
void actor_delete(datum_index actor_index, uint32_t flag);
void actor_delete_or_release_unit(datum_index actor_index, uint8_t is_dead);
void actor_delete_swarm(datum_index actor_index);
int16_t actor_dispatch_look_handler_by_posture(int16_t posture, uint32_t actor_index, void *origin, void *target, uint8_t stance_a, uint8_t check_facing, uint16_t range_class);
void actor_dispatch_perception_reset(datum_index actor_index);
void actor_dispatch_squad_order(datum_index prop_index, const actor_squad_order_header *order, datum_index actor_index);
void actor_dispatch_type_vtable_0x10(datum_index actor_index);
void actor_dispatch_type_vtable_0x18(datum_index actor_index);
void actor_dispatch_type_vtable_0x1c(datum_index actor_index, uint32_t a, uint32_t b, uint32_t c);
uint8_t actor_escalate_apply(datum_index actor_index, int16_t threshold);
uint8_t actor_escalate_check_leader_flag(datum_index actor_index);
uint8_t actor_escalate_check_shield_damage(datum_index actor_index);
uint8_t actor_escalate_check_target_close(datum_index actor_index);
uint8_t actor_escalate_check_weapon_range(datum_index actor_index);
uint8_t actor_escalate_to_guard_or_combat(datum_index actor_index);
char actor_evaluate_combat_state_transition(uint32_t actor_index);
uint8_t actor_evaluate_custom_charge_trigger(datum_index actor_index);
int32_t actor_evaluate_engagement_reachability(int16_t self_cluster, int16_t target_cluster, real_point3d *target_position, real_point3d *self_position, int16_t movement_mode, uint8_t allow_wide_mask, datum_index exclude_object_index, uint8_t flying);
int16_t actor_evaluate_flank_offset(real_vector3d *cover_direction, real_vector3d *out_offset, real_point3d *threat_position, real_point3d *candidate_position);
uint8_t actor_evaluate_grenade_target_position(datum_index actor_index);
uint8_t actor_evaluate_search_node(datum_index actor_index, datum_index vehicle_index, int16_t seat_index, real_point3d *out_entry, real_vector3d *out_direction, real_point3d *out_hint, float *out_score, uint8_t *out_close, uint8_t *out_facing, uint8_t *out_in_front);
void actor_fill_unit_position_context(datum_index unit_index, actor_firing_positions *out_context);
uint32_t actor_find_best_firing_position(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *out_candidate, uint32_t *out_previous_owner, path_find_context *path_context, uint8_t *out_path_ok);
int16_t actor_find_best_search_node(datum_index actor_index, datum_index vehicle_index, real_point3d *out_entry, real_vector3d *out_direction, real_point3d *out_hint);
uint8_t actor_find_danger_escape(datum_index actor_index, int16_t *out_kind, float *out_step, real_vector3d *path_delta, uint8_t *in_danger);
uint8_t actor_find_grenade_landing_spot(datum_index actor_index, real_point3d *out_point, datum_index *out_target_handle, int32_t *out_relationship);
int32_t actor_find_nearest_grenade_ally(datum_index actor_index, uint8_t widen_search);
datum_index actor_find_or_allocate_prop(datum_index actor_index, uint32_t object_index, char kind);
datum_index actor_find_or_create_shared_prop(datum_index object_index, datum_index actor_index, char create_if_missing, uint32_t flag);
datum_index actor_find_prop_for_object(datum_index object_index, datum_index actor_index);
uint8_t actor_firing_position_compare(int32_t element, int32_t other);
uint8_t actor_firing_position_evaluate(actor_firing_position_candidate *candidate, actor_firing_position_query *query, datum_index actor_index);
uint8_t actor_firing_position_near_point(datum_index actor_index, real_point3d *point, int32_t start_surface_index, int16_t kind);
uint8_t actor_firing_position_probe_reject_rules(actor_firing_position_query *query, datum_index actor_index);
uint8_t actor_firing_position_run_reject_rules(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *candidate);
void actor_firing_position_run_score_rules(datum_index actor_index, uint16_t count, actor_firing_position_query *query, actor_firing_position_candidate *candidates);
uint32_t actor_flee_look_away(datum_index actor_index);
void actor_forward_target_object_reference(datum_index actor_index, uint32_t param);
uint8_t actor_gate_jump_traversal(uint32_t actor_index, int16_t threshold, char allow_broadcast, int16_t broadcast_threshold);
int16_t actor_gather_nearby_grenade_targets(datum_index source_actor_index, int16_t maximum_count, ai_grenade_avoidance_entry *out_entries);
void * actor_get_actor_definition(datum_index actor_index);
void actor_get_aim_from_position(datum_index actor_index, uint32_t out_position[3]);
void actor_get_body_axis_vector(uint32_t actor_index, uint32_t unit_index, actor_squad_action_state *request);
uint8_t actor_get_cached_wander_position(datum_index actor_index, real_vector3d *out_position);
float actor_get_consideration_wait_threshold(uint32_t actor_index, int16_t mode, actor_combat_consideration *consideration);
int16_t actor_get_current_mode_combat_grade(datum_index actor_index);
uint32_t actor_get_firing_position_group_mask(datum_index actor_index, int16_t kind, int16_t search_override);
void actor_get_firing_positions(datum_index actor_index, actor_firing_positions *out_block, real_point3d *query_point);
uint8_t actor_get_grenade_launch_velocity(int16_t grenade_type, real_vector3d *direction, void *origin, float range, real_point3d *point, int32_t max_time, float *speed, void *out_time_or_fraction, real_vector3d *out_velocity, float *out_gravity);
float * actor_get_idle_facing_range(datum_index actor_index);
uint8_t actor_get_ranged_attack_vector(datum_index target_prop_index, datum_index actor_index, real_vector3d *out_vector);
datum_index actor_get_relevant_squad_member_target(uint32_t unused_param, datum_index member_prop_index, char require_is_unit);
uint8_t actor_get_requested_velocity(uint8_t skip_clamp, datum_index actor_index, real_vector3d *out_velocity, uint32_t object_index, float speed_limit);
datum_index actor_get_squad_recent_attacker_target(datum_index actor_index, char require_is_unit);
datum_index actor_get_target_prop_object_index(datum_index actor_index);
void actor_get_target_state_flags(int16_t ax_mode, int16_t cx_mode, uint8_t shared_flag, uint32_t actor_index, int16_t mode_b, char force_c, char force_d, uint8_t *out_a, char *out_in_e, uint8_t *out_f, uint8_t *out_g, uint8_t *out_h, uint8_t *out_i);
void * actor_get_threat_weapon_definition(int32_t actor_index);
datum_index actor_get_threat_weapon_object_index(datum_index actor_index);
void actor_grenade_avoidance_entry_init(ai_grenade_avoidance_entry *entry, datum_index object_index, datum_index prop_index);
uint8_t actor_grenade_behavior_kind_allowed(datum_index actor_index, int16_t kind);
uint8_t actor_grenade_parabolic_path_clear(real_vector3d *initial_velocity, datum_index source_actor_index, real_point3d *start_position, real total_time, real vertical_acceleration, datum_index exclude_object_index, uint8_t wide_mask);
int32_t actor_grenade_trace_from_source(uint32_t actor_index, real_point3d *target_point);
uint8_t actor_grenade_trajectory_blocked(real_vector3d *trajectory_direction, datum_index source_actor_index, datum_index exclude_object_index, real_point3d *landing_position, int32_t *out_blocking_prop);
uint8_t actor_handle_death(datum_index actor_index, uint8_t param_2, uint8_t param_3);
uint8_t actor_has_unshielded_threat_weapon(datum_index actor_index);
void actor_init_prop_from_object(datum_index object_index, datum_index actor_index, datum_index prop_index);
int32_t actor_investigate_disturbance_update(uint32_t actor_index);
void actor_invoke_type_handler(uint32_t actor_index);
uint8_t actor_is_burst_pending(datum_index actor_index);
uint8_t actor_is_target_within_engagement_range(uint32_t actor_index);
uint8_t actor_is_within_alert_range(uint8_t always_in_range, float radius_a, float radius_b, uint8_t vitality_only, uint8_t use_radius_b, uint32_t actor_index, uint32_t object_index);
void actor_issue_multi_target_vocalization(int16_t line, datum_index actor_index, int16_t variant, datum_index vehicle_object_index);
void actor_issue_order_or_vocalize(datum_index prop_index, datum_index actor_index, datum_index vehicle_object_index, int16_t line, int16_t variant);
void actor_iterator_new(actor_iterator_state *out_iterator, uint8_t active_only);
actor * actor_iterator_next(actor_iterator_state *iterator);
uint8_t actor_link_to_unit_cluster(datum_index actor_index, datum_index unit_index);
int32_t actor_look_get_wait_ticks(datum_index actor_index, int16_t mode, uint32_t flags, float *deviation_table);
uint8_t actor_look_pick_random_point_in_cone(void *origin, float yaw_min, float yaw_max, float pitch_min, float pitch_max, real_vector3d *base_direction, uint8_t check_obstruction, real_point3d *out);
void actor_look_randomize_direction(datum_index actor_index, float *deviation_table, real_vector3d *base_direction);
int32_t actor_lookup_small_table_entry(int16_t index);
void actor_mark_prop_seen_with_delta(datum_index object_index, datum_index actor_index, float delta, const real_vector3d *direction);
void actor_mark_units_and_release(uint8_t use_alternate_flag, datum_index actor_index, uint8_t suppress_release);
void actor_mode_alert_movement_cancelled(datum_index actor_index);
uint8_t actor_mode_alert_process(uint32_t actor_index);
void actor_mode_alert_target_cleared(datum_index actor_index);
void actor_mode_alert_tick(uint32_t actor_index);
void actor_mode_alert_update(uint32_t actor_index);
void actor_mode_avoid_update(datum_index actor_index);
void actor_mode_charge_enter(datum_index actor_index);
uint8_t actor_mode_charge_process(datum_index actor_index);
void actor_mode_charge_tick(datum_index actor_index);
void actor_mode_charge_update(datum_index actor_index);
void actor_mode_converse_exit(datum_index actor_index);
uint8_t actor_mode_converse_process(datum_index actor_index);
void actor_mode_converse_replace_reference(datum_index actor_index, datum_index old_reference, datum_index new_reference);
void actor_mode_converse_update(datum_index actor_index);
void actor_mode_fight_tick(uint32_t actor_index);
void actor_mode_fight_update(uint32_t actor_index);
void actor_mode_flee_enter(datum_index actor_index);
void actor_mode_flee_exit(datum_index actor_index);
void actor_mode_flee_get_look_weights(datum_index actor_index, float *out_weights);
void actor_mode_flee_movement_cancelled(datum_index actor_index);
uint8_t actor_mode_flee_process(datum_index actor_index);
void actor_mode_flee_replace_reference(datum_index actor_index, datum_index old_reference, datum_index new_reference);
void actor_mode_flee_tick(datum_index actor_index);
void actor_mode_flee_update(datum_index actor_index);
void actor_mode_guard_enter(datum_index actor_index);
void actor_mode_guard_exit(datum_index actor_index);
void actor_mode_guard_get_look_weights(datum_index actor_index, float *out_weights);
void actor_mode_guard_movement_cancelled(datum_index actor_index);
void actor_mode_guard_replace_reference(datum_index actor_index, datum_index old_reference, datum_index new_reference);
void actor_mode_guard_target_cleared(datum_index actor_index);
void actor_mode_guard_tick(datum_index actor_index);
void actor_mode_guard_update(datum_index actor_index);
void actor_mode_obey_enter(uint32_t actor_index);
void actor_mode_obey_exit(uint32_t actor_index);
uint8_t actor_mode_obey_process(uint32_t actor_index);
void actor_mode_obey_tick_members(uint32_t actor_index);
void actor_mode_obey_update(uint32_t actor_index);
void actor_mode_search_enter(datum_index actor_index);
void actor_mode_search_movement_cancelled(datum_index actor_index);
uint8_t actor_mode_search_process(datum_index actor_index);
void actor_mode_search_tick(datum_index actor_index);
void actor_mode_search_update(datum_index actor_index);
void actor_mode_sleep_update(datum_index actor_index);
void actor_mode_uncover_enter(datum_index actor_index);
void actor_mode_uncover_get_look_weights(datum_index actor_index, float *out_weights);
void actor_mode_uncover_movement_cancelled(datum_index actor_index);
void actor_mode_uncover_tick(datum_index actor_index);
void actor_mode_uncover_update(datum_index actor_index);
void actor_mode_vehicle_enter(datum_index actor_index);
void actor_mode_vehicle_update(datum_index actor_index);
uint8_t actor_mode_wait_process(datum_index actor_index);
void actor_mode_wait_tick(datum_index actor_index);
void actor_mode_wait_update(datum_index actor_index);
void actor_movement_action_cancel(datum_index actor_index);
void actor_movement_action_complete(datum_index actor_index);
uint8_t actor_movement_action_in_progress(datum_index actor_index);
uint8_t actor_movement_action_is_complete(datum_index actor_index);
uint8_t actor_movement_action_resolve(datum_index actor_index, uint8_t record_distance, path_find_context *context);
void actor_movement_action_stop(datum_index actor_index);
void actor_movement_actions_cancel(datum_index actor_index);
void actor_movement_advance_waypoint(datum_index actor_index);
void actor_movement_apply_steering(int16_t cached_axis, uint8_t keep_z, datum_index actor_index, uint8_t want_avoid_check, float avoid_threshold, uint8_t order_failed, float steering_maximum, float oversteer_min, float oversteer_max, float avoidance_scale, float throttle_maximum, real_vector3d *desired_direction, real_vector3d *out_direction, int16_t *out_axis, real_vector3d *out_heading, uint8_t *out_flag_507, uint8_t *out_flag_506);
uint8_t actor_movement_check_arrival(datum_index actor_index);
void actor_movement_choose_avoidance_direction(uint32_t actor_index, real_vector3d *desired, real_vector3d *out_direction, float *out_scale);
void actor_movement_choose_strafe_axis(const real_vector3d *direction, uint8_t use_3d, const real_vector3d *facing, const real_vector3d *reference, real_vector3d *out_axis, int16_t *out_index);
void actor_movement_collect_obstacle_candidates(actor_movement_context *context);
uint8_t actor_movement_flying_needs_steering(datum_index actor_index, const real_point3d *destination, float *out_avoidance_distance);
void actor_movement_get_stopping_distances(datum_index actor_index, float *out_accelerate_stop_distance, float *out_stop_distance);
void actor_movement_project_into_frame(uint8_t use_3d, const real_vector3d *frame_axis, const real_vector3d *v, real_vector3d *out);
uint8_t actor_movement_set_destination_firing_position(datum_index actor_index, int16_t formation_slot, path_find_context *path_context);
uint8_t actor_movement_set_destination_move_position(datum_index actor_index, int16_t move_position_index);
uint8_t actor_movement_set_destination_near_target(datum_index target_prop_index, datum_index actor_index, float radius);
uint8_t actor_movement_set_destination_point(real_point3d *destination, datum_index actor_index, int32_t parameter, uint32_t extra);
int16_t actor_movement_test_obstacle_ray(real_vector3d *out_elevation, const float *sample, real_point3d *out_end_point, actor_movement_context *context, float *out_distance, uint8_t *out_clear_counter);
void actor_movement_update(datum_index actor_index);
datum_index actor_new(datum_index actor_variant_tag);
datum_index actor_new_and_attach_to_unit(char reuse_existing, datum_index unit_index, datum_index actor_variant_tag, uint32_t encounter_or_none, int16_t squad_index, char ignore_squad, datum_index exclude_actor, char start_active, uint16_t unknown_60, int16_t unknown_62, uint16_t unknown_90, uint8_t unknown_68);
void actor_notify_squad_and_flag_danger(datum_index actor_index, uint8_t alternate_event, uint8_t raise_danger_flag);
void actor_notify_squad_of_threat_direction(const real_point3d *point, datum_index actor_index, int16_t event_kind, int16_t grenade_type_code);
void actor_notify_target_engaged(datum_index target_prop_index, datum_index actor_index, uint8_t alternate_event);
void actor_notify_weapon_pickup_once(datum_index object_index);
void actor_obey_member_advance(uint32_t actor_index, datum_index unit_index, uint16_t command_list_index, actor_squad_action_state *action, actor_command_aim *aim, uint32_t callback_extra);
void actor_obey_member_enter(uint32_t actor_index, datum_index unit_index, uint16_t command_list_index, actor_squad_action_state *action, actor_command_aim *aim, uint32_t callback_extra);
void actor_obey_member_exit(uint32_t actor_index, datum_index unit_index, uint16_t command_list_index, actor_squad_action_state *action, actor_command_aim *aim, uint32_t callback_extra);
void actor_obey_member_tick(uint32_t actor_index, datum_index unit_index, uint16_t command_list_index, actor_squad_action_state *action, actor_command_aim *aim, uint32_t callback_extra);
int32_t actor_order_code_is_grenade_throw(int16_t order_code);
int32_t actor_pick_dialogue_variant_a(int16_t category);
int32_t actor_pick_dialogue_variant_b(int16_t category);
datum_index actor_place_new_unit(datum_index actor_variant_or_palette_tag, datum_index encounter_index, int16_t squad_index, uint8_t use_palette_entry, uint16_t unit_type_index, const actor_placement_request *placement_request);
uint8_t actor_play_first_valid_vocalization(int16_t *seat_list, datum_index vehicle_index, datum_index actor_index, char *seat_name, int16_t seat_flags, int16_t count);
uint8_t actor_point_in_directional_lane(real_point3d *to_point, real_point3d *forward, real_point3d *cone_axis, float min_cos_threshold, float side_thresholds[2]);
uint8_t actor_probe_step_direction(datum_index actor_index, float step_distance, real_vector2d *direction, uint16_t *variant, float step_up, uint8_t *out_flag, void *extra_param);
uint8_t actor_process_order_request(uint32_t actor_index, uint16_t order_code);
uint8_t actor_process_pending_command_list(datum_index actor_index);
uint8_t actor_process_vehicle_seat_exit(datum_index actor_index);
void actor_prop_iterator_init(datum_index actor_index, actor_prop_iterator *out_iterator);
prop * actor_prop_iterator_next(actor_prop_iterator *iterator);
void actor_propagate_unit_field(datum_index actor_index, int16_t value);
void actor_push_recognition_entry(datum_index actor_index, int16_t firing_position_index, uint8_t type);
void actor_queue_directional_reaction_event(const real_vector3d *direction, datum_index target_prop_index, datum_index actor_index);
void actor_queue_point_reaction_dialogue(const real_point3d *point, datum_index actor_index);
void actor_queue_recognized_target_dialogue(datum_index actor_index, datum_index target_prop_index);
void actor_queue_search_and_relay_perception(datum_index prop_index, datum_index actor_index);
void actor_queue_search_position(datum_index actor_index, real_point3d *position, int16_t priority, real_vector3d *velocity, uint32_t surface_index, uint32_t position_extra, uint32_t velocity_ticks, uint32_t prop_index, uint32_t prop_value, uint8_t prop_flag);
uint8_t actor_queue_secondary_action(datum_index actor_index, int16_t action, const real_vector2d *direction);
void actor_queue_sighted_target_dialogue(datum_index actor_index, datum_index target_prop_index, uint8_t already_noticed);
void actor_queue_velocity_search_from_prop(datum_index prop_index, datum_index actor_index);
void actor_raise_timer_5f6(datum_index actor_index, int32_t ticks);
float actor_rate_potential_target(datum_index actor_index, datum_index target_prop_index);
uint8_t actor_react_to_disturbance(datum_index actor_index, int16_t threshold);
void actor_react_to_flee_point(datum_index actor_index, int32_t flee_source_object, const real_point3d *point);
void actor_react_to_registered_danger(const real_point3d *point, datum_index actor_index, int32_t danger_object_index);
void actor_react_to_seen_target(datum_index actor_index, datum_index target_prop_index);
void actor_react_to_threat_event(datum_index self_object_index, datum_index other_object_index, int32_t event_kind, real magnitude, uint32_t extra_param, uint8_t suppress_vehicle_relay);
int32_t actor_reassign_vehicle_seat(datum_index vehicle_object_index, datum_index self_object_index, int32_t seat_selector);
void actor_recompute_grenade_eligibility(datum_index actor_index);
void actor_record_look_at_point(datum_index actor_index, const uint32_t *point, int16_t priority, uint32_t data);
void actor_record_perception_event(datum_index actor_index, int16_t event, int32_t data);
void actor_refresh_combat_context(datum_index actor_index);
uint8_t actor_reject_firing_position_by_perception(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *candidate);
uint8_t actor_reject_firing_position_by_pursuit(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *candidate);
uint8_t actor_reject_firing_position_by_request_result(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *candidate);
uint8_t actor_reject_firing_position_by_target_approach(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *candidate);
uint8_t actor_reject_firing_position_unreachable(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *candidate);
void actor_release_from_cluster_or_delete(datum_index actor_index, datum_index unit_index);
void actor_remove_from_unit_cluster(datum_index actor_index, datum_index unit_index);
void actor_replace_object_reference(datum_index actor_index, uint32_t new_reference, uint32_t old_reference);
int32_t actor_report_command_status(uint32_t actor_index);
void actor_report_firing_position_request(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *candidate);
uint8_t actor_request_move_and_face(datum_index actor_index);
uint8_t actor_request_path_with_grenade_arc(uint32_t actor_index);
void actor_reseed_movement_pause_timer(datum_index actor_index);
void actor_reset_perception_scratch(datum_index unit_index);
uint8_t actor_reset_queued_look_vector(datum_index actor_index);
void actor_reset_squad_link_for_type_change(datum_index actor_index, datum_index encounter_index, int16_t squad_index);
uint8_t actor_resolve_flee_source_point(actor_flee_source_reason *reason, real_vector3d *out, datum_index actor_index);
uint8_t actor_resolve_look_target(real_point3d *preferred_direction, datum_index actor_index, float *deviation_table, uint8_t require_trust, uint8_t use_aiming_deviation, uint8_t force_fallback);
uint8_t actor_resolve_wander_or_look_direction(datum_index actor_index, real_vector3d *out_direction);
void actor_run_mode_transition_loop(datum_index actor_index);
uint8_t actor_scale_value_by_ally_exposure(datum_index actor_index, float *value);
void actor_scan_allies_for_backup_request(datum_index actor_index);
void actor_scan_ally_death_panic_reaction(datum_index target_prop_index, datum_index actor_index);
void actor_scan_backup_and_panic_reaction(datum_index target_prop_index, datum_index actor_index);
void actor_schedule_grenade_throw(uint32_t actor_index);
uint8_t actor_score_blast_area_clear(datum_index actor_index, float blast_radius, float safety_radius, real_point3d *point, int16_t *out_count);
void actor_score_firing_positions_by_history(datum_index actor_index, actor_firing_position_query *query, uint16_t count, actor_firing_position_candidate *candidates);
void actor_score_firing_positions_by_range(datum_index actor_index, actor_firing_position_query *query, uint16_t count, actor_firing_position_candidate *candidates);
void actor_score_firing_positions_by_standoff(datum_index actor_index, actor_firing_position_query *query, uint16_t count, actor_firing_position_candidate *candidates);
void actor_score_firing_positions_by_threat(datum_index actor_index, actor_firing_position_query *query, uint16_t count, actor_firing_position_candidate *candidates);
void actor_score_firing_positions_close_range(datum_index actor_index, actor_firing_position_query *query, uint16_t count, actor_firing_position_candidate *candidates);
void actor_score_firing_positions_near_target(datum_index actor_index, actor_firing_position_query *query, uint16_t count, actor_firing_position_candidate *candidates);
uint8_t actor_seek_vehicle_to_board(datum_index actor_index);
uint8_t actor_select_facing_target_prop(datum_index actor_index, uint8_t require_trust, uint8_t skip_lane_test, actor_recognition_scan_result *out_result, uint8_t *out_in_front);
int16_t actor_select_firing_position(datum_index actor_index, actor_firing_position_query *query, actor_firing_position_candidate *out_candidate, uint32_t *out_previous_owner, path_find_context *path_context, uint8_t *out_path_ok);
int32_t actor_select_move_position(uint32_t actor_index, int16_t select_mode, int32_t position_index, uint8_t *direction_flag);
void actor_select_stance_offset_pair(datum_index actor_index, ActorVariant *base, actor_burst_parameters **out_a, actor_burst_scale **out_b);
void actor_set_combat_alert_flag(datum_index actor_index, uint8_t new_flag);
void actor_set_flag_bit1(datum_index actor_index);
void actor_set_mode(datum_index actor_index, int32_t mode, void *mode_data);
void actor_set_override_target(datum_index actor_index, uint8_t enable, datum_index override_target);
void actor_set_target_alert_stage1(datum_index target_prop_index, datum_index actor_index);
void actor_set_target_alert_stage2(datum_index target_prop_index, datum_index actor_index);
void actor_set_target_alert_stage3(datum_index target_prop_index, datum_index actor_index);
void actor_set_units_active(datum_index actor_index, uint8_t dormant);
uint8_t actor_should_hold_position(datum_index actor_index, const ActorVariant *definition);
uint8_t actor_should_throw_grenade(uint32_t actor_index, char force);
void actor_snapshot_orientation(datum_index actor_index);
uint32_t actor_solve_grenade_lob(datum_index actor_index, real_point3d *point);
int16_t actor_spawn_additional_units(datum_index actor_variant_tag, int16_t spawn_count, datum_index source_actor_index, float health_scale);
char actor_squad_action_execute(actor_command_aim *aim_state, uint32_t actor_index, uint32_t check_object_index, int16_t command_list_index, actor_squad_action_state *state);
uint8_t actor_squad_action_is_complete(actor_command_aim *aim_state, uint32_t actor_index, uint32_t check_object_index, int16_t command_list_index, actor_squad_action_state *state);
void actor_squad_action_list_process(uint32_t actor_index, uint32_t check_object_index, uint16_t command_list_index, actor_squad_action_state *state, actor_command_aim *aim_state, uint32_t callback_extra);
void actor_squad_action_reset_entry(uint32_t actor_index, uint32_t check_object_index, actor_squad_action_state *state, int16_t command_list_index, actor_command_aim *aim_state, uint8_t *next_action_index_out);
int32_t actor_squad_action_status_broadcast(uint32_t actor_index, int16_t command_list_index, actor_mode_obey_data *record);
void actor_squad_react_to_grenade(datum_index actor_index, datum_index target_prop_index, int16_t grenade_type);
void actor_squad_react_to_grenade_for_vehicle_occupants(datum_index vehicle_object_index, datum_index other_object_index);
void actor_start_search_timer(datum_index actor_index, datum_index prop_index);
void actor_swarm_for_each_component(uint32_t actor_index, char reset_first, actor_swarm_member_callback callback, uint32_t callback_extra, actor_mode_obey_data *obey);
void actor_swarm_for_each_component_thunk(uint32_t actor_index);
uint8_t actor_take_danger_escape(real_vector3d *path_delta, datum_index actor_index, uint16_t direction_kind, float step_distance, float distance);
uint8_t actor_target_data_acquire(datum_index actor_index, datum_index object_index, datum_index owner_reference, datum_index pair_reference);
void actor_target_data_refresh(uint32_t actor_index, uint32_t target_prop_index, actor_firing_positions *reference, char force, char allow_reassign);
uint32_t actor_target_data_release(datum_index target_prop_index, uint32_t actor_index, uint8_t *out_conflict_flag);
void actor_target_evaluate_squad_link(uint32_t actor_index, datum_index object_index, ai_target_candidate_list *candidates_a, ai_target_candidate_list *candidates_b);
uint8_t actor_target_get_backup_priority(datum_index target_prop_index);
uint16_t actor_target_get_priority_class(datum_index actor_index, datum_index target_prop_index);
void actor_target_get_relationship_object(datum_index target_prop_index);
uint8_t actor_target_has_conflicting_neighbor(datum_index actor_index, datum_index target_prop_index);
uint16_t actor_target_hearing_check(const bsp_leaf_reference *record, int16_t stance, datum_index actor_index, const actor_firing_positions *target_ref, int16_t gate, real_point3d *listener_position);
uint8_t actor_target_is_close_and_recognized(datum_index object_index, uint32_t param_2, datum_index actor_index);
uint8_t actor_target_is_visible_or_object_count_ok(datum_index actor_index, int16_t kind);
void actor_target_mark_engaged(datum_index target_prop_index, datum_index actor_index, uint8_t mark_engaged);
void actor_target_relationship_think(datum_index actor_index);
void actor_target_reset_combat_flags(datum_index target_prop_index, datum_index actor_index, uint32_t unused, uint8_t already_noticed);
void actor_target_reset_seen_flags(datum_index actor_index);
void actor_target_reset_shot_counters(datum_index actor_index);
void actor_target_scan_potential_targets(datum_index actor_index);
uint8_t actor_target_update_active_flag(datum_index actor_index, datum_index target_prop_index);
void actor_target_update_tracking_speed(uint32_t actor_index, datum_index target_prop_index, actor_firing_positions *scratch);
uint8_t actor_targets_share_descriptor(datum_index actor_a, datum_index actor_b);
uint8_t actor_toggle_active_state(uint8_t activate, datum_index actor_index);
uint8_t actor_try_grenade_evasion(datum_index actor_index, uint8_t allow_pain_reaction, uint8_t use_alt_base);
void actor_type_crew_update(uint32_t actor_index);
void actor_type_elite_update(datum_index actor_index);
void actor_type_engineer_update(datum_index actor_index);
void actor_type_flood_carrier_update(datum_index actor_index);
void actor_type_flood_update(datum_index actor_index);
void actor_type_grunt_update(datum_index actor_index);
void actor_type_hunter_update(datum_index actor_index);
void actor_type_infection_swarm_update(datum_index actor_index);
void actor_type_infection_update(datum_index actor_index);
void actor_type_jackal_update(datum_index actor_index);
void actor_type_marine_update(datum_index actor_index);
void actor_type_mounted_weapon_update(datum_index actor_index);
void actor_type_sentinel_update(datum_index actor_index);
void actor_unlink_prop(datum_index actor_index, datum_index prop_to_remove);
void actor_unlink_unit(datum_index actor_index);
void actor_update_activation_state(datum_index actor_index);
void actor_update_aim_wander(datum_index actor_index);
void actor_update_awareness_level(datum_index actor_index);
uint8_t actor_update_combat_behavior(datum_index actor_index, uint8_t param_1, uint8_t param_2);
void actor_update_crouch_state(datum_index actor_index);
uint8_t actor_update_danger_avoidance(datum_index actor_index);
void actor_update_facing_change_timer(datum_index actor_index);
void actor_update_firing_state(datum_index actor_index);
uint8_t actor_update_flee_response(datum_index actor_index);
char actor_update_grenade_and_morale_reactions(uint32_t actor_index);
void actor_update_grenade_eligibility_state(datum_index actor_index);
uint8_t actor_update_grenade_throw_decision(datum_index actor_index);
void actor_update_idle_stagger(datum_index actor_index);
void actor_update_look_target(datum_index actor_index);
uint8_t actor_update_melee_combat_action(datum_index actor_index);
uint8_t actor_update_movement_destination(uint32_t actor_index);
uint8_t actor_update_path_if_needed(datum_index actor_index);
uint8_t actor_update_special_mode(datum_index actor_index);
uint8_t actor_update_squad_link_state(datum_index actor_index);
void actor_update_swarm_component_position(datum_index component_index, datum_index unit_index);
void actor_update_target_combat_status(datum_index actor_index);
void actor_update_target_lead_position(datum_index actor_index);
uint8_t actor_validate_grenade_ally_candidate(datum_index candidate_actor, uint8_t caller_type_flag);
uint8_t actor_validate_grenade_impact_point(datum_index actor_index, real_point3d *candidate_point);
uint8_t actor_vehicle_not_recently_left(datum_index actor_index, datum_index vehicle_index);
uint8_t actor_wants_reload_or_swap(uint32_t actor_index);
void actors_initialize();
void ai_accumulate_repeated_event(int32_t event_type, real_point3d *position, int16_t event_id, int16_t window_ticks);
int32_t ai_actor_get_activity_stage(datum_index actor_index);
void ai_actor_link_to_unassigned_list(datum_index actor_index);
uint32_t ai_actor_type_get_morale_grade(int16_t command_list_index, const actor_squad_action_state *action);
void ai_actor_unlink_from_unassigned_list(datum_index actor_index);
void ai_alert_actors_in_grenade_radius(datum_index source_unit_index, int16_t stimulus, int16_t gate);
void ai_broadcast_communication_event(int16_t gate, real_point3d *point, int32_t source_object, int16_t event_type, int16_t unused);
void ai_build_priority_target_list(ai_priority_target_list *out_list);
void ai_category_matches_wildcard(int16_t category, int16_t other_category);
void ai_clear_object_references(datum_index object_index);
void ai_communication_broadcast(int32_t event_code, datum_index unit_index, datum_index object_a, int32_t reason, datum_index object_b, datum_index object_c, uint32_t *extra_data);
void ai_communication_gate_line_played(int16_t event_id, ai_communication_record *record, datum_index object_index);
void ai_communication_initialize();
int16_t ai_communication_line_fade_multiplier(uint32_t unit_index, int16_t priority, int16_t extra_delay, uint8_t follow_fallback, uint8_t apply_fade, float *volume, int32_t *chain_value, int16_t *dialogue_index, int16_t line_class);
void ai_communication_play_event_line(datum_index object_index, int16_t event_id, uint8_t force, datum_index explicit_speaker_actor_index, uint32_t *event_record);
float ai_communication_rate_player_proximity(uint8_t require_line_of_sight, datum_index *out_player_object_index, float *out_distance, datum_index object_index);
float ai_communication_rate_speaker(datum_index actor_index, datum_index object_b, real_point3d *position_b, float radius, int16_t allow_unreachable, uint32_t fade_limit, uint32_t line_class, uint32_t line_id, int16_t seat_filter, uint8_t flags, real_point3d *position_a, datum_index object_a);
void ai_communication_record_line_played(datum_index object_index, int16_t tier, int16_t communication_line_id, int16_t conversation_line_id);
void ai_communication_reset();
datum_index ai_communication_select_speaker_by_team(int16_t match_mode, datum_index object_a, datum_index object_b, float radius, int16_t allow_unreachable, uint32_t fade_limit, uint32_t line_class, uint32_t line_id, int16_t seat_filter, uint8_t flags, int16_t team);
datum_index ai_communication_select_speaker_in_reference(float radius, int16_t allow_unreachable, uint32_t fade_limit, uint32_t line_class, uint32_t line_id, int16_t seat_filter, uint8_t flags, uint32_t reference, datum_index object_a, datum_index object_b);
void ai_communication_target_result_reset(ai_communication_target_result *record);
uint8_t ai_conversation_activate(int16_t conversation_definition_index, uint8_t allow_eviction);
uint8_t ai_conversation_activate_next_participant(datum_index instance_handle);
void ai_conversation_clear_object_references(datum_index object_index, uint8_t force_full_scan);
void ai_conversation_clear_participant(datum_index actor_index);
uint8_t ai_conversation_current_line_is_ready(datum_index instance_handle);
int16_t ai_conversation_get_line_index(int16_t conversation_definition_index);
int32_t ai_conversation_get_run_to_player_range(ai_conversation_range_lookup *out, uint32_t conversation_index);
int32_t ai_conversation_get_status(int16_t conversation_definition_index);
void ai_conversation_mark_all(int16_t conversation_definition_index);
datum_index ai_conversation_new(int16_t conversation_definition_index, uint8_t allow_eviction);
int8_t ai_conversation_resolve_participant(int16_t participant_index, uint8_t *out_resolved, uint8_t *out_wants_alternate, uint8_t *out_blocked_by_player, float *inout_minimum_distance, datum_index conversation_index);
uint8_t ai_conversation_resolve_participants(datum_index conversation_index, uint8_t *out_keep_trying);
void ai_conversation_stop(datum_index instance_handle, uint8_t reason_a, uint8_t reason_b);
void ai_conversation_stop_all(int16_t conversation_definition_index);
void ai_conversation_update();
int16_t ai_count_actors_in_mode9_group(int32_t group_id);
uint8_t ai_dialogue_condition_42f4f0(datum_index object_index, uint32_t param_2, datum_index actor_index);
uint8_t ai_dialogue_condition_42f560(datum_index object_index, uint32_t param_2, datum_index actor_index);
uint8_t ai_dialogue_condition_42f5b0(datum_index object_index, uint32_t param_2, datum_index actor_index);
uint8_t ai_dialogue_condition_42f650(datum_index object_index, uint32_t param_2, datum_index actor_index);
uint8_t ai_dialogue_condition_42f690(datum_index object_index, uint32_t param_2, datum_index actor_index);
uint8_t ai_dialogue_condition_42f6f0(datum_index object_index, uint32_t param_2, datum_index actor_index);
uint8_t ai_dialogue_condition_42f7b0(datum_index object_index, uint32_t param_2, datum_index actor_index);
uint8_t ai_dialogue_condition_42f7f0(datum_index object_index, uint32_t param_2, datum_index actor_index);
void ai_dispatch_queued_order(ai_queued_order *order, datum_index prop_index, datum_index actor_index);
uint8_t ai_drift_zone_bias(datum_index encounter_index, int16_t squad_offset, float bias);
int32_t ai_encounter_record_recent_zone(datum_index encounter_index, int16_t zone_id);
void ai_encounter_stamp_team_from_unit(datum_index encounter_index, datum_index unit_index);
void ai_get_difficulty_request(int16_t request_code, uint8_t *out_flag_a, uint8_t *out_flag_b, float *out_value);
int16_t ai_group_bucket_find_or_add(ai_group_bucket_entry *buckets, int32_t key, int16_t *count, int16_t capacity);
void ai_initialize_for_new_map();
uint8_t ai_insert_scored_candidate_pair(ai_scored_candidate *list, datum_index handle, float score, datum_index payload, datum_index key);
void ai_mark_recognized_objects_for_reaction(int16_t team_a, int16_t team_b, uint8_t status);
uint8_t ai_navigate_around_obstacles(path_find_context *context, int16_t count, path_find_waypoint *waypoints, int16_t *out_count, path_find_waypoint *out_waypoints, uint8_t *out_valid);
void ai_notify_actors_of_encounter_state_change(int16_t zone_a, int16_t zone_b, uint8_t status, uint8_t force_update);
ai_object_attention_record * ai_object_attention_find_or_create(datum_index object_index);
void ai_object_attention_remove(datum_index object_index);
void ai_object_list_clear_orders_with_weapon(datum_index object_list_header_handle);
void ai_object_list_detach_actors_from_encounters(datum_index object_list_header_handle);
void ai_object_list_initialize_shield_stun_thresholds(datum_index object_list_header_handle, float override_max_body_vitality, float override_max_shield_vitality);
int16_t ai_object_list_max_flee_grade(datum_index object_list_header_handle);
void ai_object_list_remap_units_and_children(datum_index object_list_header, uint32_t packed_reference, char notify);
void ai_object_list_reset_or_wake_awareness(datum_index object_list_header_handle, char flag);
void ai_object_list_respawn_members(datum_index object_list_header_handle, uint32_t packed_reference);
void ai_object_list_set_unit_flag_400(datum_index object_list_header_handle, char flag);
void ai_object_list_set_unit_flag_800(datum_index object_list_header_handle, char flag);
void ai_object_list_set_unit_flag_800000(datum_index object_list_header_handle, char flag);
void ai_object_list_spawn_members(datum_index object_list_header_handle, uint32_t packed_reference);
uint8_t ai_object_list_start_user_animation_until_failure(datum_index object_list_header_handle, datum_index graph_tag_id, const char *animation_name, uint8_t interpolate);
void ai_object_list_update_vitality_fractions(datum_index object_list_header_handle, float body_delta, float shield_delta);
void ai_object_process_nearby_actors(uint32_t ai_reference, datum_index vehicle_index, char *seat_name, char allow_boarding_actors);
int16_t ai_pick_weighted_candidate(ai_scored_candidate *table, ai_scored_candidate *out_entry);
void ai_platoon_range_clear_defending(uint32_t packed_reference);
uint8_t ai_platoon_range_has_available(uint32_t packed_reference);
void ai_platoon_range_set_defending(uint32_t packed_reference);
void ai_platoon_range_set_maneuver_enabled(uint32_t packed_reference, char flag);
void ai_platoon_range_set_maneuvering(uint32_t packed_reference);
void ai_process_vehicle_entry_queue();
void ai_propagate_communication_reaction(datum_index object_index, ai_communication_order *order);
uint8_t ai_pursuit_check_object(datum_index object_index, datum_index encounter_index, int16_t type, int32_t min_last_tick, char create_if_missing, int16_t *out_count, uint32_t *out_last_tick);
uint8_t ai_pursuit_note_object(datum_index object_index, datum_index encounter_index, int16_t type, int32_t min_last_tick);
void ai_recompute_all_relationship_flags();
void ai_reference_activate_squads(uint32_t packed_reference);
void ai_reference_actor_iterator_init_cursor(int32_t encounter_index, datum_index *cursor);
void ai_reference_actor_iterator_new(uint32_t packed_reference, ai_reference_actor_iterator *out_iterator);
actor * ai_reference_actor_iterator_next(ai_reference_actor_iterator *iterator);
datum_index ai_reference_build_object_list(uint32_t packed_reference);
void ai_reference_clear_search_target(uint32_t packed_reference);
void ai_reference_detach_actors_from_encounters(uint32_t packed_reference);
void ai_reference_expand_to_platoon_range(uint32_t packed_reference, ai_reference_platoon_range *out_range);
void ai_reference_face_starting_location(uint32_t packed_reference, uint8_t idle_only);
void ai_reference_flee_if_ready(uint32_t packed_reference, uint32_t readiness_param);
void ai_reference_for_each_squad(uint32_t packed_reference);
uint32_t ai_reference_get_stat_pair(uint32_t packed_reference, int16_t stat_kind, int32_t *out_member_count, uint32_t *out_extra);
void ai_reference_invoke_squad_callback_406f80(uint32_t packed_reference);
int16_t ai_reference_max_activity_stage(uint32_t packed_reference);
void ai_reference_notify_actors(uint32_t packed_reference, uint8_t flag);
void ai_reference_notify_squad_index(uint32_t packed_reference);
uint8_t ai_reference_parse(char *reference_string, Scenario *scenario, uint32_t *out_packed_reference);
void ai_reference_refill_grenades(uint32_t packed_reference);
void ai_reference_reset_or_wake_awareness(uint32_t packed_reference, char flag);
int32_t ai_reference_resolve_squad_datum(uint32_t packed_reference);
void ai_reference_respawn_all_players(uint32_t packed_reference);
void ai_reference_respawn_member(uint32_t packed_reference, datum_index unit_index);
void ai_reference_respawn_placed_members(uint32_t packed_reference, uint32_t respawn_reference);
void ai_reference_set_charge_allowed(uint32_t packed_reference, char flag);
void ai_reference_set_combat_alert_flag(uint32_t packed_reference, uint8_t new_flag);
void ai_reference_set_search_target_area(uint32_t packed_reference);
void ai_reference_set_search_target_point(uint32_t packed_reference, uint32_t reference_value);
void ai_reference_set_squads_dormancy_allowed(uint32_t packed_reference, char flag);
void ai_reference_spawn_starting_location_object(datum_index unit_index, uint32_t packed_reference);
void ai_reference_squad_iterator_new(uint32_t packed_reference, ai_reference_squad_iterator *out_iterator);
encounter_squad_state * ai_reference_squad_iterator_next(ai_reference_squad_iterator *iterator);
void ai_reference_squad_set_automatic_migration(uint32_t packed_reference, uint8_t value);
void ai_reference_start_squad_timers(uint32_t packed_reference);
void ai_reference_units_exit_vehicles(uint32_t packed_reference);
void ai_refresh_unit_stimulus_and_alert(datum_index object_index, int16_t priority, int16_t stimulus_value);
void ai_release_actors_and_swarms();
void ai_release_actors_filtered(datum_index encounter_index, int32_t platoon_index, int32_t squad_index, uint8_t is_dead);
int32_t ai_release_inactive_encounters(char *buffer, uint8_t *has_more, ai_release_state *state);
int ai_release_inactive_swarms(char *buffer, uint8_t *has_more);
void ai_reset_all_actors_perception();
void ai_reset_fire_group_assignments();
void ai_reset_for_new_map();
int32_t ai_scan_for_recent_combat_activity(uint8_t hard_difficulty);
int16_t ai_search_add_node(ai_search_context *context, int16_t parent, real_point2d *position, int32_t surface_index, int16_t point_id, uint8_t side, float base_cost);
uint8_t ai_search_append_obstacle(ai_search_obstacle_list *list, uint16_t flags, uint32_t object_index, real_point2d *position, float radius);
uint8_t ai_search_choose_shorter_corner(real_point2d *p, real_point2d *corner_a, real_point2d *q, real_point2d *corner_b, real_point2d *r, real_point2d *out_point);
void ai_search_compute_point_tangents(ai_search_obstacle_list *list, int16_t point_index, real_point2d *position, real_vector2d *edge_neg, float radius, real_vector2d *out_a, real *out_b);
void ai_search_context_init(ai_search_context *context, uint8_t ignores_glass, uint32_t search_radius_bits, ai_search_obstacle_list *obstacles, real_point2d *origin, uint32_t structure_bsp, real_point2d *position, int32_t surface_index, uint32_t origin_surface_index, uint8_t final_leg, uint8_t ignore_flagged_obstacles);
uint8_t ai_search_evaluate_edge_cost(void *context, uint8_t ignore_permission, ai_search_obstacle_list *obstacle_list, int16_t exclude_index, real_point2d *point, int32_t start_surface_index, float distance, float base_cost, uint8_t skip_direct, uint8_t apply_offset, uint8_t require_unflagged, ai_search_edge_result *out_result, real_vector2d *direction);
void ai_search_expand_point_neighbors(ai_search_context *context, int16_t node_index, int16_t start_point_id);
void ai_search_find_circle_portal_crossing(real_point2d *center, real_point2d *portal, real_point2d *out_point, real_point2d *fallback_reference, float radius);
void ai_search_find_circle_tangent_point(real_point2d *center, real_point2d *target, real_point2d *out_point, float radius, uint8_t side);
int16_t ai_search_find_covering_point(ai_search_obstacle_list *list, real_point2d *position, int16_t exclude_index, float extra_radius);
uint8_t ai_search_find_nearest_visible_point(ai_search_obstacle_list *list, int16_t exclude_index, real_point2d *origin, real_vector2d *direction, float radius, float max_distance, uint8_t require_unflagged, ai_search_nearest_point_result *out_result);
void ai_search_flood_fill_group(ai_search_obstacle_list *list, float radius, uint32_t *out_bitmask, int16_t start_index);
void ai_search_gather_obstacles(ai_search_obstacle_list *list, real_point3d *center, float radius, real_vector3d *direction, uint32_t self_object_a, uint32_t self_object_b);
void ai_search_heap_sift_down(ai_search_context *context, int16_t index);
void ai_search_heap_sift_up(ai_search_context *context, int16_t index);
void ai_search_partition_into_groups(ai_search_obstacle_list *list, float radius);
uint8_t ai_search_run(ai_search_context *context, uint8_t ignores_glass, ai_search_obstacle_list *obstacles, uint32_t search_radius_bits, real_point2d *position, int32_t surface_index, real_point2d *origin, uint32_t origin_surface_index, uint8_t final_leg, uint8_t ignore_flagged_obstacles);
uint8_t ai_search_step(ai_search_context *context);
int32_t ai_select_communication_target(uint32_t param_a, uint32_t param_b, int16_t line_id, int16_t sub_id, float *out_weight);
int32_t ai_squad_find_best_matching_member(uint32_t packed_reference, int16_t requested_squad_index, const Actor *requested_actor_data, const ActorVariant *requested_actor_variant_data, char match_by_index);
int __cdecl ai_squad_priority_compare(const ai_priority_target_record *record_a, const ai_priority_target_record *record_b);
int16_t ai_squad_resolve_actor_type(ScenarioSquad *squad);
void ai_squads_merge(uint32_t source_reference, uint32_t target_encounter_index, char notify, char is_platoon_merge);
void ai_starting_location_derive_placement_flags(datum_index encounter_index, int16_t starting_location_index, uint8_t *out_a, int16_t *out_b, uint8_t *out_c, int16_t *out_d, int16_t *out_edx, int16_t *out_esi);
int ai_target_distance_qsort_compare(void *record_a, void *record_b);
void ai_tick_dispatcher();
void ai_unassigned_actors_attach_to_structure_bsp();
void ai_unit_clear_actor_vocalization(datum_index unit_index);
void ai_unit_create_actor(datum_index actor_variant_tag, datum_index unit_index);
void ai_unit_dispatch_actor_event_d(datum_index unit_index, int32_t unused);
void ai_unit_flee_if_ready(datum_index unit_index, uint32_t readiness_param);
void ai_unit_remap_actor_to_squad(datum_index unit_index, uint32_t packed_reference, char notify);
void ai_unit_set_actor_force_active(datum_index unit_index, uint8_t value);
void ai_unit_set_squad_reference(datum_index object_index, uint32_t packed_reference);
int32_t ai_weighted_random_index(int16_t weight_offset, void *base, int16_t stride, uint16_t count, uint32_t *exclude_mask);
uint8_t encounter_activate(datum_index encounter_index);
void encounter_add_actor(int16_t squad_index, datum_index actor_index, datum_index encounter_index, uint8_t keep_team);
void encounter_advance_grenade_timers(datum_index encounter_index);
void encounter_build_firing_position_claims(datum_index encounter_index, datum_index *out_claims);
void encounter_choose_vocalizations(datum_index encounter_index);
void encounter_deactivate(datum_index encounter_index);
void encounter_decay_squad_spawn_delays(datum_index encounter_index);
int32_t encounter_definition_find_platoon_index_by_name(ScenarioEncounter *encounter_definition, char *name);
int32_t encounter_definition_find_squad_index_by_name(ScenarioEncounter *encounter_definition, char *name);
uint8_t encounter_evaluate_platoon_condition(datum_index encounter_index, const ai_platoon_condition *condition);
void encounter_evaluate_support_needs(datum_index encounter_index, datum_index self_actor_index, int16_t mode, uint8_t phase, uint8_t *out_crowded, uint8_t *out_flanked, uint8_t *out_a, uint8_t *out_b, uint8_t *out_reachable_a, uint8_t *out_reachable_b, uint8_t *out_any);
void encounter_gather_occupied_clusters(datum_index encounter_index, uint32_t *out_clusters, uint8_t record_per_actor, uint32_t *other_clusters);
void encounter_new(int16_t *squad_cursor, ScenarioEncounter *definition, int16_t *platoon_cursor);
void encounter_process_squad_reinforcements(datum_index encounter_index);
void encounter_propagate_platoon_state_to_actors(datum_index encounter_index);
void encounter_recompute_morale(datum_index encounter_index);
void encounter_redistribute_squads_toward_targets(datum_index encounter_index);
void encounter_release_stale_props(datum_index encounter_index);
void encounter_remove_actor(datum_index actor_index, uint8_t skip_counters);
void encounter_set_team(datum_index encounter_index, int16_t team);
void encounter_spawn_squads(datum_index encounter_index, int16_t platoon_filter, int16_t squad_filter);
void encounter_squad_clear_spawn_delay(datum_index encounter_index, int16_t squad_index);
void encounter_squad_reset_starting_location_mask(datum_index encounter_index, int16_t squad_index);
uint8_t encounter_squad_spawn_actor(datum_index encounter_index, int16_t squad_index, uint32_t unit_type_index, uint32_t unused);
uint32_t encounter_squad_spawn_reinforcement(datum_index encounter_index, int16_t squad_index);
void encounter_update_platoon_defending_flag(datum_index encounter_index);
void encounters_initialize();
void encounters_note_hostile_object(datum_index object_index);
void encounters_recompute_dirty();
void encounters_reset();
void encounters_spawn_initial();
void encounters_update();
void encounters_update_activation();
datum_index object_find_nearest_squad_member(datum_index actor_index, const actor_firing_positions *reference, datum_index exclude_index, char stamp_group);
uint8_t path_find_compute_heuristic(path_find_context *context, uint32_t vertex_id, real_point3d *point, float *out_distance, float *out_secondary, real_vector3d *out_direction);
void path_find_context_init(path_find_context *context, const path_find_request *request, uint32_t second_param);
uint8_t path_find_find_unobstructed_ancestor(path_find_context *context, uint32_t vertex_id, real_point3d *point, uint8_t *out_used_start, real_point3d *out_position);
int16_t path_find_gather_adjacent_edges(void *context, int32_t vertex_id, path_find_adjacent_edge *out_edges);
int16_t path_find_hash_lookup_vertex(path_find_context *context, uint32_t vertex_id);
void path_find_heap_push(path_find_context *context, int16_t node, int16_t key);
void path_find_heap_sift_down(path_find_context *context, int16_t index);
void path_find_heap_sift_up(path_find_context *context, int16_t index);
uint8_t path_find_heights_are_close(ScenarioStructureBSP *structure_bsp, real_point2d *point, int32_t surface_a, int32_t surface_b);
uint8_t path_find_push_start_node(path_find_context *context);
uint8_t path_find_reconstruct_path(path_find_context *context, uint8_t *out_result);
uint8_t path_find_run(path_find_context *context);
float path_find_score_avoidance_penalty(path_find_context *context, const real_point3d *segment_start, const real_point3d *segment_end, float *out_distance);
void path_find_set_avoid_sphere(path_find_context *context, const real_point3d *position, float avoid_radius, datum_index avoid_object_index, float avoid_weight);
void path_find_set_goal(path_find_context *context, const real_point3d *position, uint32_t goal_vertex_id, float goal_cost);
void path_find_simplify_waypoints(path_find_context *context, int16_t count, path_find_waypoint *waypoints, int16_t *out_count, path_find_waypoint *out_waypoints, uint8_t *out_valid);
uint8_t path_find_test_direct_reachability(const real_point3d *point_a, const real_point3d *point_b, real_point3d *out_position, void *context, uint8_t *out_success);
uint8_t path_find_test_segment_unobstructed(void *map, real_point3d *point_a, uint8_t ignore_permission, int32_t surface_a, real_point3d *point_b, int32_t surface_b, float radius, uint8_t flags, path_find_boundary_crossing *out_result);
uint8_t path_find_trace_bsp_boundary(void *map, uint8_t ignore_permission, real_point3d *start, int32_t start_surface, real_point3d *end, int32_t target_surface, path_find_boundary_crossing *out_result);
uint8_t path_find_trace_cluster_boundary(void *map, int32_t edge_index, real_point2d *origin, float radius, uint8_t side, uint8_t ignore_permission, real_point2d *out_point);
uint8_t path_find_trace_cluster_boundary_from_vertex(void *context, uint8_t ignore_permission, real_point2d *point, int32_t start_index, real_vector2d *direction, float max_distance, path_find_boundary_trace_result *out);
uint8_t path_find_validate_and_record_goal(ai_path_candidate_goal *candidate, void *context, uint32_t point_b, uint32_t unused_c, const real_point3d *position);
float path_find_vertex_distance(ScenarioStructureBSP *structure_bsp, int32_t surface, real_point3d *point_a, real_point3d *out_point);
uint8_t projectile_get_aiming_vector(real_point3d *target, real *speed_in, Projectile *tag, real_point3d *origin, void *unused_param_3, real *max_time, real *max_speed_override, uint8_t use_high_arc, real_vector3d *out_direction, real *out_speed, real *out_time_or_fraction, real *out_range_or_length, uint8_t *out_used_straight_line);
uint8_t projectile_solve_ballistic_arc(real_point3d *target, real_point3d *origin, real speed_limit, real gravity_scale, real *max_time, uint8_t use_high_arc, real_vector3d *out_direction, real *max_speed_override, real *out_speed, real *out_time_of_flight, real *out_range, real *out_half_gravity_term, real *out_horizontal_speed);
uint8_t projectile_solve_straight_line(real_point3d *target, real_point3d *origin, real speed, real *out_time_of_flight, real_vector3d *out_direction, real *out_speed_echo, real *out_length);
int32_t scenario_find_encounter_index_by_name(Scenario *scenario, char *name);
void squad_members_assign_team_and_request_order(uint32_t packed_reference, int16_t value);
void squad_members_request_order(uint32_t packed_reference, int16_t order_code);
int16_t squad_pick_random_starting_location(datum_index encounter_index, int16_t squad_index);
datum_index squad_recent_object_get_or_create(datum_index encounter_index, int16_t type, int32_t min_last_tick, char create_if_missing);
void squad_recent_object_list_clear(datum_index encounter_index);
void swarm_add_component(datum_index component_index, uint32_t unit_index, datum_index swarm_index);
void unit_get_move_speed_for_range(datum_index actor_index, float param_a, float param_b, float param_dist, float *out_a, float *out_b);

}
