#pragma once

#include <stddef.h>

/** Compile-time checks that the named fields of the actor and prop records sit at the offsets the retail code uses. */
static_assert(offsetof(struct actor, identifier) == 0);
static_assert(offsetof(struct actor, unknown_02) == 2);
static_assert(offsetof(struct actor, type) == 4);
static_assert(offsetof(struct actor, swarm) == 6);
static_assert(offsetof(struct actor, unit_control_pending) == 7);
static_assert(offsetof(struct actor, active) == 8);
static_assert(offsetof(struct actor, encounterless) == 9);
static_assert(offsetof(struct actor, force_active) == 10);
static_assert(offsetof(struct actor, swarm_pending) == 11);
static_assert(offsetof(struct actor, deactivation_time) == 12);
static_assert(offsetof(struct actor, activation_delay) == 16);
static_assert(offsetof(struct actor, can_go_dormant) == 18);
static_assert(offsetof(struct actor, keep_unit_alive) == 19);
static_assert(offsetof(struct actor, unit_index) == 24);
static_assert(offsetof(struct actor, counts_toward_encounter) == 28);
static_assert(offsetof(struct actor, unknown_1d) == 29);
static_assert(offsetof(struct actor, cluster_count) == 30);
static_assert(offsetof(struct actor, total_cluster_count) == 32);
static_assert(offsetof(struct actor, pad_22) == 34);
static_assert(offsetof(struct actor, cluster_unit_index) == 36);
static_assert(offsetof(struct actor, swarm_index) == 40);
static_assert(offsetof(struct actor, next_in_encounter) == 44);
static_assert(offsetof(struct actor, original_encounter_index) == 48);
static_assert(offsetof(struct actor, encounter_index) == 52);
static_assert(offsetof(struct actor, original_squad_index) == 56);
static_assert(offsetof(struct actor, squad_index) == 58);
static_assert(offsetof(struct actor, platoon_index) == 60);
static_assert(offsetof(struct actor, team) == 62);
static_assert(offsetof(struct actor, idle_counter) == 74);
static_assert(offsetof(struct actor, needs_new_path) == 76);
static_assert(offsetof(struct actor, unknown_4d) == 77);
static_assert(offsetof(struct actor, target_reaction_threshold) == 78);
static_assert(offsetof(struct actor, first_prop) == 80);
static_assert(offsetof(struct actor, nearest_orphan_prop_index) == 84);
static_assert(offsetof(struct actor, actor_definition_tag) == 88);
static_assert(offsetof(struct actor, actor_variant_tag) == 92);
static_assert(offsetof(struct actor, pending_order_request) == 96);
static_assert(offsetof(struct actor, standing_order_request) == 98);
static_assert(offsetof(struct actor, last_order_request_time) == 100);
static_assert(offsetof(struct actor, sequence_id) == 104);
static_assert(offsetof(struct actor, unknown_69) == 105);
static_assert(offsetof(struct actor, awareness_level) == 106);
static_assert(offsetof(struct actor, mode) == 108);
static_assert(offsetof(struct actor, combat_status) == 110);
static_assert(offsetof(struct actor, mode_changed) == 112);
static_assert(offsetof(struct actor, unknown_71) == 113);
static_assert(offsetof(struct actor, minimum_combat_status) == 114);
static_assert(offsetof(struct actor, suspicion_status) == 116);
static_assert(offsetof(struct actor, unknown_76) == 118);
static_assert(offsetof(struct actor, suspicion_timer) == 120);
static_assert(offsetof(struct actor, ticks_in_combat) == 124);
static_assert(offsetof(struct actor, ticks_alerted) == 128);
static_assert(offsetof(struct actor, ticks_threatened) == 132);
static_assert(offsetof(struct actor, ticks_since_threatened) == 136);
static_assert(offsetof(struct actor, has_engaged) == 140);
static_assert(offsetof(struct actor, witnessed_death) == 141);
static_assert(offsetof(struct actor, command_list_run_immediately) == 142);
static_assert(offsetof(struct actor, pad_8f) == 143);
static_assert(offsetof(struct actor, pending_command_list) == 144);
static_assert(offsetof(struct actor, command_list_delay) == 146);
static_assert(offsetof(struct actor, command_list_finished_time) == 148);
static_assert(offsetof(struct actor, search_firing_positions) == 152);
static_assert(offsetof(struct actor, flying) == 153);
static_assert(offsetof(struct actor, pad_9a) == 154);
static_assert(offsetof(struct actor, mode_data) == 156);
static_assert(offsetof(struct actor, aim_origin) == 288);
static_assert(offsetof(struct actor, body_position) == 300);
static_assert(offsetof(struct actor, unknown_138) == 312);
static_assert(offsetof(struct actor, location) == 324);
static_assert(offsetof(struct actor, unknown_14c) == 332);
static_assert(offsetof(struct actor, active_unit_index) == 344);
static_assert(offsetof(struct actor, airborne) == 348);
static_assert(offsetof(struct actor, in_water) == 349);
static_assert(offsetof(struct actor, vehicle_driving_type) == 350);
static_assert(offsetof(struct actor, order_committed) == 352);
static_assert(offsetof(struct actor, vehicle_gunner) == 353);
static_assert(offsetof(struct actor, vehicle_gunner_bombards) == 354);
static_assert(offsetof(struct actor, pathfinding_surface_index) == 356);
static_assert(offsetof(struct actor, pathfinding_point) == 360);
static_assert(offsetof(struct actor, facing) == 372);
static_assert(offsetof(struct actor, unit_aiming_vector) == 384);
static_assert(offsetof(struct actor, unit_looking_vector) == 396);
static_assert(offsetof(struct actor, looking_left_vector) == 408);
static_assert(offsetof(struct actor, looking_up_vector) == 420);
static_assert(offsetof(struct actor, stuck_projectile_index) == 432);
static_assert(offsetof(struct actor, body_vitality) == 440);
static_assert(offsetof(struct actor, shield_vitality) == 444);
static_assert(offsetof(struct actor, recent_body_damage) == 448);
static_assert(offsetof(struct actor, recent_shield_damage) == 452);
static_assert(offsetof(struct actor, stood_down) == 456);
static_assert(offsetof(struct actor, platoon_defending) == 457);
static_assert(offsetof(struct actor, playfight) == 458);
static_assert(offsetof(struct actor, charge_disallowed) == 459);
static_assert(offsetof(struct actor, grenade_ally_phase_flag) == 460);
static_assert(offsetof(struct actor, pad_1cd) == 461);
static_assert(offsetof(struct actor, nearby_friend_prop_index) == 464);
static_assert(offsetof(struct actor, try_to_fight_type) == 468);
static_assert(offsetof(struct actor, pad_1d6) == 470);
static_assert(offsetof(struct actor, try_to_fight_reference) == 472);
static_assert(offsetof(struct actor, conversation_index) == 476);
static_assert(offsetof(struct actor, conversation_participant) == 480);
static_assert(offsetof(struct actor, post_combat_action) == 484);
static_assert(offsetof(struct actor, pad_1e6) == 486);
static_assert(offsetof(struct actor, post_combat_prop_index) == 488);
static_assert(offsetof(struct actor, tally) == 492);
static_assert(offsetof(struct actor, unknown_267) == 615);
static_assert(offsetof(struct actor, target_combat_status) == 616);
static_assert(offsetof(struct actor, pad_26a) == 618);
static_assert(offsetof(struct actor, target_last_seen_time) == 620);
static_assert(offsetof(struct actor, target_unit_index) == 624);
static_assert(offsetof(struct actor, ever_had_target) == 628);
static_assert(offsetof(struct actor, ticks_since_engaged) == 632);
static_assert(offsetof(struct actor, target_alive) == 636);
static_assert(offsetof(struct actor, pad_27d) == 637);
static_assert(offsetof(struct actor, danger_type) == 640);
static_assert(offsetof(struct actor, danger_owner_relation) == 642);
static_assert(offsetof(struct actor, danger_reaction_ticks) == 644);
static_assert(offsetof(struct actor, danger_reaction_delayed) == 646);
static_assert(offsetof(struct actor, danger_reacting) == 647);
static_assert(offsetof(struct actor, danger_dive) == 648);
static_assert(offsetof(struct actor, danger_is_own) == 650);
static_assert(offsetof(struct actor, pad_28b) == 651);
static_assert(offsetof(struct actor, danger_object_index) == 652);
static_assert(offsetof(struct actor, danger_owner_unit) == 656);
static_assert(offsetof(struct actor, danger_object_radius) == 660);
static_assert(offsetof(struct actor, danger_object_position) == 664);
static_assert(offsetof(struct actor, danger_object_velocity) == 676);
static_assert(offsetof(struct actor, flee_from_point) == 688);
static_assert(offsetof(struct actor, danger_velocity) == 700);
static_assert(offsetof(struct actor, danger_segment_end) == 712);
static_assert(offsetof(struct actor, danger_distance) == 724);
static_assert(offsetof(struct actor, danger_radius) == 728);
static_assert(offsetof(struct actor, danger_center) == 732);
static_assert(offsetof(struct actor, vehicle_eviction) == 749);
static_assert(offsetof(struct actor, look_at_priority) == 750);
static_assert(offsetof(struct actor, look_at_reference) == 756);
static_assert(offsetof(struct actor, look_at_has_point) == 760);
static_assert(offsetof(struct actor, pad_2f9) == 761);
static_assert(offsetof(struct actor, look_at_point) == 764);
static_assert(offsetof(struct actor, pending_panic_type) == 776);
static_assert(offsetof(struct actor, pad_30a) == 778);
static_assert(offsetof(struct actor, pending_panic_prop_index) == 780);
static_assert(offsetof(struct actor, escalation_level) == 784);
static_assert(offsetof(struct actor, search_priority) == 786);
static_assert(offsetof(struct actor, search_position_valid) == 788);
static_assert(offsetof(struct actor, pad_315) == 789);
static_assert(offsetof(struct actor, search_position) == 792);
static_assert(offsetof(struct actor, search_surface_index) == 804);
static_assert(offsetof(struct actor, search_position_extra) == 808);
static_assert(offsetof(struct actor, search_velocity_valid) == 812);
static_assert(offsetof(struct actor, pad_32d) == 813);
static_assert(offsetof(struct actor, search_velocity) == 816);
static_assert(offsetof(struct actor, search_velocity_ticks) == 828);
static_assert(offsetof(struct actor, search_prop_index) == 832);
static_assert(offsetof(struct actor, search_prop_value) == 836);
static_assert(offsetof(struct actor, search_prop_flag) == 840);
static_assert(offsetof(struct actor, unknown_349) == 841);
static_assert(offsetof(struct actor, perception_event) == 842);
static_assert(offsetof(struct actor, perception_event_data) == 844);
static_assert(offsetof(struct actor, threat_level) == 848);
static_assert(offsetof(struct actor, danger_meter) == 852);
static_assert(offsetof(struct actor, crouch_active) == 856);
static_assert(offsetof(struct actor, unknown_359) == 857);
static_assert(offsetof(struct actor, crouch_ticks) == 858);
static_assert(offsetof(struct actor, crouch_cover_flags) == 860);
static_assert(offsetof(struct actor, incoming_fire_ticks) == 864);
static_assert(offsetof(struct actor, charge_trigger_active) == 866);
static_assert(offsetof(struct actor, charge_trigger_decision) == 867);
static_assert(offsetof(struct actor, charge_trigger_ticks) == 868);
static_assert(offsetof(struct actor, charge_trigger_delay) == 870);
static_assert(offsetof(struct actor, evasion_delay_ticks) == 872);
static_assert(offsetof(struct actor, pad_36a) == 874);
static_assert(offsetof(struct actor, last_evasion_time) == 876);
static_assert(offsetof(struct actor, last_cover_attempt_time) == 880);
static_assert(offsetof(struct actor, defending) == 884);
static_assert(offsetof(struct actor, always_charge) == 885);
static_assert(offsetof(struct actor, ignores_glass) == 886);
static_assert(offsetof(struct actor, friendly_player_greeted) == 887);
static_assert(offsetof(struct actor, berserking) == 888);
static_assert(offsetof(struct actor, berserk_announced) == 889);
static_assert(offsetof(struct actor, pad_37a) == 890);
static_assert(offsetof(struct actor, search_wait_time) == 892);
static_assert(offsetof(struct actor, last_melee_time) == 896);
static_assert(offsetof(struct actor, last_vehicle_search_time) == 900);
static_assert(offsetof(struct actor, last_vehicle_charge_time) == 904);
static_assert(offsetof(struct actor, vehicle_exit_forced) == 908);
static_assert(offsetof(struct actor, pad_38d) == 909);
static_assert(offsetof(struct actor, exited_vehicle_index) == 912);
static_assert(offsetof(struct actor, exited_vehicle_reentry_time) == 916);
static_assert(offsetof(struct actor, last_flee_abort_time) == 920);
static_assert(offsetof(struct actor, panic_cooldown_time) == 924);
static_assert(offsetof(struct actor, found_body_time) == 928);
static_assert(offsetof(struct actor, retreat_end_time) == 932);
static_assert(offsetof(struct actor, retreat_timer) == 936);
static_assert(offsetof(struct actor, pad_3aa) == 938);
static_assert(offsetof(struct actor, retreat_prop_index) == 940);
static_assert(offsetof(struct actor, retreat_start_time) == 944);
static_assert(offsetof(struct actor, stood_down_body_vitality) == 948);
static_assert(offsetof(struct actor, firing_position_index) == 952);
static_assert(offsetof(struct actor, firing_position_without_path) == 954);
static_assert(offsetof(struct actor, grenade_evasion_active) == 955);
static_assert(offsetof(struct actor, target_lost) == 956);
static_assert(offsetof(struct actor, pursuit_target_prop_index) == 960);
static_assert(offsetof(struct actor, pursuit_position_count) == 964);
static_assert(offsetof(struct actor, recognition_cursor) == 966);
static_assert(offsetof(struct actor, recognition) == 968);
static_assert(offsetof(struct actor, recognition_valid) == 984);
static_assert(offsetof(struct actor, recognition_type) == 985);
static_assert(offsetof(struct actor, pad_3da) == 986);
static_assert(offsetof(struct actor, recognition_position) == 988);
static_assert(offsetof(struct actor, flee_reason) == 1000);
static_assert(offsetof(struct actor, pad_3ea) == 1002);
static_assert(offsetof(struct actor, flee_source) == 1004);
static_assert(offsetof(struct actor, look_posture) == 1020);
static_assert(offsetof(struct actor, pad_3fe) == 1022);
static_assert(offsetof(struct actor, queued_movement) == 1024);
static_assert(offsetof(struct actor, secondary_action) == 1048);
static_assert(offsetof(struct actor, pad_41a) == 1050);
static_assert(offsetof(struct actor, secondary_action_direction) == 1052);
static_assert(offsetof(struct actor, dive_into_cover) == 1060);
static_assert(offsetof(struct actor, crouch_decision) == 1062);
static_assert(offsetof(struct actor, crouch_hold) == 1064);
static_assert(offsetof(struct actor, cowering) == 1065);
static_assert(offsetof(struct actor, pad_42b) == 1067);
static_assert(offsetof(struct actor, movement_style_override) == 1068);
static_assert(offsetof(struct actor, strafe_axis_override) == 1070);
static_assert(offsetof(struct actor, move_in_direction) == 1072);
static_assert(offsetof(struct actor, pad_431) == 1073);
static_assert(offsetof(struct actor, move_direction) == 1076);
static_assert(offsetof(struct actor, jump_requested) == 1088);
static_assert(offsetof(struct actor, jump_is_leap) == 1089);
static_assert(offsetof(struct actor, jump_parameters_valid) == 1090);
static_assert(offsetof(struct actor, pad_443) == 1091);
static_assert(offsetof(struct actor, jump_facing) == 1092);
static_assert(offsetof(struct actor, jump_horizontal_velocity) == 1100);
static_assert(offsetof(struct actor, jump_vertical_velocity) == 1104);
static_assert(offsetof(struct actor, wants_to_fire) == 1108);
static_assert(offsetof(struct actor, bombard_target) == 1109);
static_assert(offsetof(struct actor, force_fire) == 1111);
static_assert(offsetof(struct actor, burst_duration_override) == 1112);
static_assert(offsetof(struct actor, throw_grenade) == 1116);
static_assert(offsetof(struct actor, forced_aim_valid) == 1117);
static_assert(offsetof(struct actor, pad_45e) == 1118);
static_assert(offsetof(struct actor, forced_aim_point) == 1120);
static_assert(offsetof(struct actor, active_movement) == 1132);
static_assert(offsetof(struct actor, movement_completed) == 1156);
static_assert(offsetof(struct actor, pad_485) == 1157);
static_assert(offsetof(struct actor, destination) == 1160);
static_assert(offsetof(struct actor, destination_surface_index) == 1172);
static_assert(offsetof(struct actor, destination_radius) == 1176);
static_assert(offsetof(struct actor, unknown_49c) == 1180);
static_assert(offsetof(struct actor, movement_timer) == 1184);
static_assert(offsetof(struct actor, path_resolved_this_tick) == 1188);
static_assert(offsetof(struct actor, pad_4a5) == 1189);
static_assert(offsetof(struct actor, movement_action_complete) == 1192);
static_assert(offsetof(struct actor, pad_4a9) == 1193);
static_assert(offsetof(struct actor, path_end_point) == 1196);
static_assert(offsetof(struct actor, unknown_4b8) == 1208);
static_assert(offsetof(struct actor, path_remaining_distance) == 1212);
static_assert(offsetof(struct actor, steps_finish_path) == 1216);
static_assert(offsetof(struct actor, waypoint_count) == 1217);
static_assert(offsetof(struct actor, waypoint_cursor) == 1218);
static_assert(offsetof(struct actor, unknown_4c3) == 1219);
static_assert(offsetof(struct actor, unknown_4cc) == 1228);
static_assert(offsetof(struct actor, unknown_4d0) == 1232);
static_assert(offsetof(struct actor, moving) == 1284);
static_assert(offsetof(struct actor, forced_aim) == 1285);
static_assert(offsetof(struct actor, waypoint_reached) == 1286);
static_assert(offsetof(struct actor, movement_thwarted) == 1287);
static_assert(offsetof(struct actor, crouching) == 1288);
static_assert(offsetof(struct actor, unknown_509) == 1289);
static_assert(offsetof(struct actor, moving_facing_direction) == 1290);
static_assert(offsetof(struct actor, current_waypoint) == 1292);
static_assert(offsetof(struct actor, desired_movement_vector) == 1304);
static_assert(offsetof(struct actor, forced_aim_direction) == 1316);
static_assert(offsetof(struct actor, jump_velocity_request) == 1328);
static_assert(offsetof(struct actor, vocalization_line) == 1348);
static_assert(offsetof(struct actor, vocalization_variant) == 1350);
static_assert(offsetof(struct actor, vocalization_state) == 1352);
static_assert(offsetof(struct actor, pad_54a) == 1354);
static_assert(offsetof(struct actor, vocalization_source) == 1356);
static_assert(offsetof(struct actor, idle_major_active) == 1372);
static_assert(offsetof(struct actor, idle_major_is_aiming) == 1373);
static_assert(offsetof(struct actor, idle_interesting_direction) == 1374);
static_assert(offsetof(struct actor, idle_minor_active) == 1375);
static_assert(offsetof(struct actor, idle_facing_timer) == 1376);
static_assert(offsetof(struct actor, idle_major_timer) == 1380);
static_assert(offsetof(struct actor, idle_minor_timer) == 1384);
static_assert(offsetof(struct actor, idle_major_direction_type) == 1388);
static_assert(offsetof(struct actor, pad_56e) == 1390);
static_assert(offsetof(struct actor, idle_major_point) == 1392);
static_assert(offsetof(struct actor, idle_major_prop_index) == 1392);
static_assert(offsetof(struct actor, idle_look_direction_type) == 1404);
static_assert(offsetof(struct actor, pad_57e) == 1406);
static_assert(offsetof(struct actor, idle_look_point) == 1408);
static_assert(offsetof(struct actor, idle_look_prop_index) == 1408);
static_assert(offsetof(struct actor, turn_required) == 1425);
static_assert(offsetof(struct actor, pad_592) == 1426);
static_assert(offsetof(struct actor, oversteer_angle) == 1428);
static_assert(offsetof(struct actor, desired_facing_vector) == 1444);
static_assert(offsetof(struct actor, desired_aiming_vector) == 1456);
static_assert(offsetof(struct actor, desired_looking_vector) == 1468);
static_assert(offsetof(struct actor, avoidance_ray_clear_ticks) == 1480);
static_assert(offsetof(struct actor, avoidance_last_direction) == 1496);
static_assert(offsetof(struct actor, pad_5da) == 1498);
static_assert(offsetof(struct actor, avoidance_direction) == 1500);
static_assert(offsetof(struct actor, avoidance_scale) == 1512);
static_assert(offsetof(struct actor, avoidance_emergency) == 1516);
static_assert(offsetof(struct actor, avoidance_turn_around_ticks) == 1520);
static_assert(offsetof(struct actor, firing_state) == 1522);
static_assert(offsetof(struct actor, firing_state_timer) == 1524);
static_assert(offsetof(struct actor, firing_delay_timer) == 1526);
static_assert(offsetof(struct actor, refire_timer) == 1528);
static_assert(offsetof(struct actor, line_of_fire_blocked_ticks) == 1530);
static_assert(offsetof(struct actor, special_fire_timer) == 1532);
static_assert(offsetof(struct actor, special_fire_strafe_cooldown) == 1534);
static_assert(offsetof(struct actor, new_target_firing_pattern) == 1536);
static_assert(offsetof(struct actor, moving_firing_pattern) == 1537);
static_assert(offsetof(struct actor, special_fire_overcharge) == 1538);
static_assert(offsetof(struct actor, special_fire_secondary) == 1539);
static_assert(offsetof(struct actor, special_fire_secondary_pending) == 1540);
static_assert(offsetof(struct actor, pad_605) == 1541);
static_assert(offsetof(struct actor, maximum_firing_distance) == 1544);
static_assert(offsetof(struct actor, firing_target_type) == 1548);
static_assert(offsetof(struct actor, pad_60e) == 1550);
static_assert(offsetof(struct actor, firing_target_prop_index) == 1552);
static_assert(offsetof(struct actor, firing_target_free_point) == 1552);
static_assert(offsetof(struct actor, firing_target_ticks) == 1564);
static_assert(offsetof(struct actor, target_in_firing_range) == 1576);
static_assert(offsetof(struct actor, pad_629) == 1577);
static_assert(offsetof(struct actor, firing_target_point) == 1580);
static_assert(offsetof(struct actor, firing_target_distance) == 1592);
static_assert(offsetof(struct actor, target_aim_vector) == 1596);
static_assert(offsetof(struct actor, target_aim_range) == 1608);
static_assert(offsetof(struct actor, aim_target_point) == 1612);
static_assert(offsetof(struct actor, firing_aim_point) == 1624);
static_assert(offsetof(struct actor, aim_wander_offset) == 1636);
static_assert(offsetof(struct actor, aim_recoil_per_tick) == 1648);
static_assert(offsetof(struct actor, grenade_aim_direction) == 1660);
static_assert(offsetof(struct actor, firing_vector_ballistic) == 1672);
static_assert(offsetof(struct actor, pad_689) == 1673);
static_assert(offsetof(struct actor, firing_vector) == 1676);
static_assert(offsetof(struct actor, projectile_error) == 1688);
static_assert(offsetof(struct actor, perception_scale) == 1692);
static_assert(offsetof(struct actor, grenade_throw_pending) == 1696);
static_assert(offsetof(struct actor, grenade_high_arc) == 1697);
static_assert(offsetof(struct actor, last_grenade_check_time) == 1700);
static_assert(offsetof(struct actor, grenade_impact_point) == 1704);
static_assert(offsetof(struct actor, grenade_target_prop_index) == 1716);
static_assert(offsetof(struct actor, grenade_exclude_object_index) == 1720);
static_assert(offsetof(struct actor, grenade_throw_direction) == 1724);
static_assert(offsetof(struct actor, grenade_throw_speed) == 1736);
static_assert(offsetof(struct actor, grenade_eligible) == 1740);
static_assert(offsetof(struct actor, unknown_6cd) == 1741);
static_assert(offsetof(struct actor, grenade_recheck_ticks) == 1742);
static_assert(offsetof(struct actor, control_flags) == 1744);
static_assert(offsetof(struct actor, persistent_control_ticks) == 1748);
static_assert(offsetof(struct actor, pad_6d6) == 1750);
static_assert(offsetof(struct actor, persistent_control_flags) == 1752);
static_assert(offsetof(struct actor, control_animation_mode) == 1756);
static_assert(offsetof(struct actor, pad_6de) == 1758);
static_assert(offsetof(struct actor, throttle) == 1760);
static_assert(offsetof(struct actor, control_animation_impulse) == 1772);
static_assert(offsetof(struct actor, control_animation_alignment) == 1776 && offsetof(struct actor, control_aiming_speed) == 1784);
static_assert(offsetof(struct actor, snapshot_facing) == 1788);
static_assert(offsetof(struct actor, aiming_vector_snapshot) == 1800);
static_assert(offsetof(struct actor, looking_vector_snapshot) == 1812);
static_assert(offsetof(struct actor, override_target) == 1824);
static_assert(offsetof(struct actor, inactive_ticks) == 20);
static_assert(offsetof(struct actor, pad_16) == 22);
static_assert(offsetof(struct actor, squad_link_saved) == 64);
static_assert(offsetof(struct actor, pad_41) == 65);
static_assert(offsetof(struct actor, saved_encounter_index) == 68);
static_assert(offsetof(struct actor, saved_squad_index) == 72);
static_assert(offsetof(struct actor, enemy_child_attached) == 436);
static_assert(offsetof(struct actor, on_fire) == 437);
static_assert(offsetof(struct actor, pad_1b6) == 438);
static_assert(offsetof(struct actor, danger_reported) == 649);
static_assert(offsetof(struct actor, danger_countdown) == 744);
static_assert(offsetof(struct actor, pad_2ea) == 746);
static_assert(offsetof(struct actor, attack_pending) == 748);
static_assert(offsetof(struct actor, surprise_pending) == 752);
static_assert(offsetof(struct actor, pad_2f1) == 753);
static_assert(offsetof(struct actor, target_lost_reported) == 957);
static_assert(offsetof(struct actor, pad_3be) == 958);
static_assert(offsetof(struct actor, force_turn) == 1066);
static_assert(offsetof(struct actor, look_claimed) == 1420);
static_assert(offsetof(struct actor, aim_unlocked) == 1421);
static_assert(offsetof(struct actor, look_unlocked) == 1422);
static_assert(offsetof(struct actor, stationary_facing_enabled) == 1423);
static_assert(offsetof(struct actor, stationary_facing_held) == 1424);
static_assert(offsetof(struct actor, firing_line_clear) == 1568);
static_assert(offsetof(struct actor, firing_target_in_water) == 1569);
static_assert(offsetof(struct actor, use_high_arc) == 1570);
static_assert(offsetof(struct actor, fire_blindly) == 1571);
static_assert(offsetof(struct actor, firing_target_hidden) == 1572);
static_assert(offsetof(struct actor, unknown_625) == 1573);
static_assert(offsetof(struct actor, firing_target_obstruction) == 1574);
static_assert(offsetof(struct prop, identifier) == 0);
static_assert(offsetof(struct prop, unknown_02) == 2);
static_assert(offsetof(struct prop, actor_index) == 4);
static_assert(offsetof(struct prop, next_in_actor) == 8);
static_assert(offsetof(struct prop, pair_index) == 12);
static_assert(offsetof(struct prop, actor_type) == 16);
static_assert(offsetof(struct prop, team) == 18);
static_assert(offsetof(struct prop, swarm_owned) == 20);
static_assert(offsetof(struct prop, unknown_15) == 21);
static_assert(offsetof(struct prop, unknown_16) == 22);
static_assert(offsetof(struct prop, object_index) == 24);
static_assert(offsetof(struct prop, owner_actor_index) == 28);
static_assert(offsetof(struct prop, danger_radius) == 32);
static_assert(offsetof(struct prop, state) == 36);
static_assert(offsetof(struct prop, reaction_timer) == 38);
static_assert(offsetof(struct prop, swarm_reassign_time) == 40);
static_assert(offsetof(struct prop, acknowledge_progress) == 44);
static_assert(offsetof(struct prop, perception_level) == 48);
static_assert(offsetof(struct prop, visual_perception) == 50);
static_assert(offsetof(struct prop, auditory_perception) == 52);
static_assert(offsetof(struct prop, ambient_perception) == 54);
static_assert(offsetof(struct prop, obstruction) == 56);
static_assert(offsetof(struct prop, orphan_timer) == 58);
static_assert(offsetof(struct prop, inspection_ticks) == 60);
static_assert(offsetof(struct prop, pad_3e) == 62);
static_assert(offsetof(struct prop, perceived_to_known_delta) == 64);
static_assert(offsetof(struct prop, lost_timer) == 76);
static_assert(offsetof(struct prop, dead_confirmed) == 78);
static_assert(offsetof(struct prop, pad_4f) == 79);
static_assert(offsetof(struct prop, desirability) == 80);
static_assert(offsetof(struct prop, interest) == 84);
static_assert(offsetof(struct prop, interest_satisfied) == 88);
static_assert(offsetof(struct prop, last_attention_time) == 92);
static_assert(offsetof(struct prop, enemy) == 96);
static_assert(offsetof(struct prop, allegiance) == 97);
static_assert(offsetof(struct prop, team_pair_status) == 98);
static_assert(offsetof(struct prop, in_use) == 99);
static_assert(offsetof(struct prop, combat_dirty) == 100);
static_assert(offsetof(struct prop, pad_65) == 101);
static_assert(offsetof(struct prop, stimulus_type) == 102);
static_assert(offsetof(struct prop, stimulus_timer) == 104);
static_assert(offsetof(struct prop, retain_timer) == 106);
static_assert(offsetof(struct prop, seen_state) == 108);
static_assert(offsetof(struct prop, pad_6e) == 110);
static_assert(offsetof(struct prop, damage_inflicted_on_me) == 112);
static_assert(offsetof(struct prop, seen) == 116);
static_assert(offsetof(struct prop, pad_75) == 117);
static_assert(offsetof(struct prop, dead_ticks) == 118);
static_assert(offsetof(struct prop, sighted_ticks) == 120);
static_assert(offsetof(struct prop, pad_7a) == 122);
static_assert(offsetof(struct prop, last_perceived_time) == 124);
static_assert(offsetof(struct prop, last_perceived_position) == 128);
static_assert(offsetof(struct prop, last_seen_time) == 140);
static_assert(offsetof(struct prop, last_seen_position) == 144);
static_assert(offsetof(struct prop, engaged_ticks) == 156);
static_assert(offsetof(struct prop, pad_9e) == 158);
static_assert(offsetof(struct prop, last_engaged_time) == 160);
static_assert(offsetof(struct prop, engaged) == 164);
static_assert(offsetof(struct prop, pad_a5) == 165);
static_assert(offsetof(struct prop, friends_killed) == 166);
static_assert(offsetof(struct prop, friends_killed_timer) == 168);
static_assert(offsetof(struct prop, shots_fired) == 170);
static_assert(offsetof(struct prop, shots_hit) == 172);
static_assert(offsetof(struct prop, danger_trigger_ticks) == 174);
static_assert(offsetof(struct prop, information_age) == 176);
static_assert(offsetof(struct prop, pad_b2) == 178);
static_assert(offsetof(struct prop, information_source_actor) == 180);
static_assert(offsetof(struct prop, has_current_information) == 184);
static_assert(offsetof(struct prop, noticed_a) == 185);
static_assert(offsetof(struct prop, noticed_b) == 186);
static_assert(offsetof(struct prop, noticed_c) == 187);
static_assert(offsetof(struct prop, last_known_position) == 188);
static_assert(offsetof(struct prop, center_of_mass) == 200);
static_assert(offsetof(struct prop, velocity) == 212);
static_assert(offsetof(struct prop, direction) == 224);
static_assert(offsetof(struct prop, pathfinding_surface_index) == 236);
static_assert(offsetof(struct prop, pathfinding_point) == 240);
static_assert(offsetof(struct prop, location) == 252);
static_assert(offsetof(struct prop, head_position) == 260);
static_assert(offsetof(struct prop, relationship_object_index) == 272);
static_assert(offsetof(struct prop, parent_object_index) == 276);
static_assert(offsetof(struct prop, in_water) == 280);
static_assert(offsetof(struct prop, pad_119) == 281);
static_assert(offsetof(struct prop, distance) == 284);
static_assert(offsetof(struct prop, perception_range_class) == 288);
static_assert(offsetof(struct prop, distance_class) == 289);
static_assert(offsetof(struct prop, aiming_at_actor_class) == 290);
static_assert(offsetof(struct prop, speed_class) == 291);
static_assert(offsetof(struct prop, closing_speed_class) == 292);
static_assert(offsetof(struct prop, child_unit_count) == 293);
static_assert(offsetof(struct prop, just_created) == 294);
static_assert(offsetof(struct prop, dead) == 295);
static_assert(offsetof(struct prop, dead_not_feigning) == 296);
static_assert(offsetof(struct prop, just_died) == 297);
static_assert(offsetof(struct prop, just_sighted) == 298);
static_assert(offsetof(struct prop, owner_not_in_combat) == 299);
static_assert(offsetof(struct prop, owner_stalled) == 300);
static_assert(offsetof(struct prop, owner_burst_length_exceeded) == 301);
static_assert(offsetof(struct prop, is_parented) == 302);
static_assert(offsetof(struct prop, shooting) == 303);
static_assert(offsetof(struct prop, flying) == 304);
static_assert(offsetof(struct prop, camouflaged) == 305);
static_assert(offsetof(struct prop, flashlight_on) == 306);
static_assert(offsetof(struct prop, disregarded) == 307);
static_assert(offsetof(struct prop, preferred_target) == 308);
static_assert(offsetof(struct prop, is_vehicle_gunner) == 309);
static_assert(offsetof(struct prop, is_vehicle_driver) == 310);
static_assert(offsetof(struct prop, pad_137) == 311);
static_assert(offsetof(struct ai_conversation, identifier) == 0);
static_assert(offsetof(struct ai_conversation, definition_index) == 2);
static_assert(offsetof(struct ai_conversation, priority) == 4);
static_assert(offsetof(struct ai_conversation, started) == 5);
static_assert(offsetof(struct ai_conversation, active) == 6);
static_assert(offsetof(struct ai_conversation, finished) == 7);
static_assert(offsetof(struct ai_conversation, waiting_for_advance) == 8);
static_assert(offsetof(struct ai_conversation, advance) == 9);
static_assert(offsetof(struct ai_conversation, pad_0a) == 10);
static_assert(offsetof(struct ai_conversation, start_tick) == 12);
static_assert(offsetof(struct ai_conversation, player_unit_index) == 16);
static_assert(offsetof(struct ai_conversation, participant_mask) == 20);
static_assert(offsetof(struct ai_conversation, participant_actor) == 40);
static_assert(offsetof(struct ai_conversation, line_index) == 72);
static_assert(offsetof(struct ai_conversation, speaker_participant_index) == 74);
static_assert(offsetof(struct ai_conversation, line_delay_ticks) == 76);
static_assert(offsetof(struct ai_conversation, line_flags) == 78);
static_assert(offsetof(struct ai_conversation, speaker_actor_index) == 80);
static_assert(offsetof(struct ai_conversation, speaker_unit_index) == 84);
static_assert(offsetof(struct ai_conversation, addressee_unit_index) == 88);
static_assert(offsetof(struct ai_conversation, sound_index) == 92);
static_assert(offsetof(struct ai_conversation, speaker_disembodied) == 96);
static_assert(offsetof(struct ai_conversation, line_started) == 97);
static_assert(offsetof(struct ai_conversation, line_spoken) == 98);
static_assert(offsetof(struct ai_conversation, line_finished) == 99);
static_assert(offsetof(struct encounter, identifier) == 0);
static_assert(offsetof(struct encounter, team) == 2);
static_assert(offsetof(struct encounter, first_squad) == 4);
static_assert(offsetof(struct encounter, squad_count) == 6);
static_assert(offsetof(struct encounter, first_platoon) == 8);
static_assert(offsetof(struct encounter, platoon_count) == 10);
static_assert(offsetof(struct encounter, force_active) == 12);
static_assert(offsetof(struct encounter, units_active) == 13);
static_assert(offsetof(struct encounter, activation_delay) == 14);
static_assert(offsetof(struct encounter, activation_tick) == 16);
static_assert(offsetof(struct encounter, first_actor) == 20);
static_assert(offsetof(struct encounter, member_count) == 24);
static_assert(offsetof(struct encounter, pre_combat_living_count) == 26);
static_assert(offsetof(struct encounter, live_count) == 28);
static_assert(offsetof(struct encounter, squads_carried_over) == 30);
static_assert(offsetof(struct encounter, pad_1f) == 31);
static_assert(offsetof(struct encounter, activation_link_count) == 32);
static_assert(offsetof(struct encounter, activation_link) == 34);
static_assert(offsetof(struct encounter, dirty) == 40);
static_assert(offsetof(struct encounter, living_count) == 42);
static_assert(offsetof(struct encounter, swarm_count) == 44);
static_assert(offsetof(struct encounter, combat_count) == 46);
static_assert(offsetof(struct encounter, engaged_count) == 48);
static_assert(offsetof(struct encounter, average_vitality) == 52);
static_assert(offsetof(struct encounter, first_pursuit) == 56);
static_assert(offsetof(struct encounter, respawn_enabled) == 60);
static_assert(offsetof(struct encounter, respawn_delay_ticks) == 62);
static_assert(offsetof(struct encounter, blind) == 64);
static_assert(offsetof(struct encounter, deaf) == 65);
static_assert(offsetof(struct encounter, stood_down) == 66);
static_assert(offsetof(struct encounter, ever_had_target) == 67);
static_assert(offsetof(struct encounter, has_live_target) == 68);
static_assert(offsetof(struct encounter, engaged) == 69);
static_assert(offsetof(struct encounter, post_combat) == 71);
static_assert(offsetof(struct encounter, post_combat_quiet) == 72);
static_assert(offsetof(struct encounter, post_combat_timer) == 74);
static_assert(offsetof(struct encounter, enemy_death_count) == 76);
static_assert(offsetof(struct encounter, ticks_since_engaged) == 80);
static_assert(offsetof(struct encounter, ticks_since_live_target) == 84);
static_assert(offsetof(struct encounter, last_idle_time) == 88);
static_assert(offsetof(struct encounter, last_grenade_time) == 92);
static_assert(offsetof(struct encounter, playfight) == 96);
static_assert(offsetof(struct encounter, follow_target_type) == 98);
static_assert(offsetof(struct encounter, follow_target) == 100);
static_assert(offsetof(struct encounter, follow_distance) == 104);
static_assert(offsetof(struct swarm, identifier) == 0);
static_assert(offsetof(struct swarm, component_count) == 2);
static_assert(offsetof(struct swarm, actor_index) == 4);
static_assert(offsetof(struct swarm, component_pick_delay) == 8);
static_assert(offsetof(struct swarm, unknown_0a) == 10);
static_assert(offsetof(struct swarm, aggregate_position) == 12);
static_assert(offsetof(struct swarm, unit_index) == 24);
static_assert(offsetof(struct swarm, component_index) == 88);
static_assert(offsetof(struct encounter, unknown_29) == 41);
static_assert(offsetof(struct encounter, unknown_32) == 50);
static_assert(offsetof(struct encounter, unknown_3d) == 61);
static_assert(offsetof(struct encounter, unknown_46) == 70);
static_assert(offsetof(struct encounter, unknown_49) == 73);
static_assert(offsetof(struct encounter, pad_4e) == 78);
static_assert(offsetof(struct encounter, unknown_61) == 97);
static_assert(offsetof(actor_mode_wait_data, finished) == 0);
static_assert(offsetof(actor_mode_wait_data, unknown_01) == 1);
static_assert(offsetof(actor_mode_wait_data, unknown_02) == 2);
static_assert(offsetof(actor_mode_wait_data, following_friend) == 3);
static_assert(offsetof(actor_mode_wait_data, unknown_04) == 4);
static_assert(offsetof(actor_mode_wait_data, unknown_05) == 5);
static_assert(offsetof(actor_mode_wait_data, start_game_time) == 8);
static_assert(offsetof(actor_mode_wait_data, countdown_0c) == 12);
static_assert(offsetof(actor_mode_wait_data, countdown_150) == 14);
static_assert(offsetof(actor_mode_wait_data, random_countdown) == 16);
static_assert(offsetof(actor_mode_wait_data, unknown_12) == 18);
static_assert(offsetof(actor_mode_flee_data, countdown_180) == 0);
static_assert(offsetof(actor_mode_flee_data, countdown_02) == 2);
static_assert(offsetof(actor_mode_flee_data, use_last_seen_position) == 4);
static_assert(offsetof(actor_mode_flee_data, cover_flag) == 5);
static_assert(offsetof(actor_mode_flee_data, movement_cancelled) == 6);
static_assert(offsetof(actor_mode_flee_data, unknown_07) == 7);
static_assert(offsetof(actor_mode_flee_data, destination) == 8);
static_assert(offsetof(actor_mode_flee_data, destination_without_path) == 10);
static_assert(offsetof(actor_mode_flee_data, unknown_0b) == 11);
static_assert(offsetof(actor_mode_flee_data, panic) == 12);
static_assert(offsetof(actor_mode_flee_data, engage) == 14);
static_assert(offsetof(actor_mode_flee_data, finished) == 15);
static_assert(offsetof(actor_mode_flee_data, announced) == 16);
static_assert(offsetof(actor_mode_flee_data, pad_11) == 17);
static_assert(offsetof(actor_mode_flee_data, announce_time) == 20);
static_assert(offsetof(actor_mode_flee_data, ticks_in_mode) == 24);
static_assert(offsetof(actor_mode_flee_data, reference) == 28);
static_assert(offsetof(actor_mode_flee_data, target_reachable) == 32);
static_assert(offsetof(actor_mode_flee_data, pad_21) == 33);
static_assert(offsetof(actor_mode_flee_data, target_position) == 36);
static_assert(offsetof(actor_mode_converse_data, conversation) == 0);
static_assert(offsetof(actor_mode_converse_data, finished) == 4);
static_assert(offsetof(actor_mode_converse_data, arrived) == 5);
static_assert(offsetof(actor_mode_converse_data, unknown_06) == 6);
static_assert(offsetof(actor_mode_converse_data, approach_distance) == 8);
static_assert(offsetof(actor_mode_converse_data, partner_unit) == 12);
static_assert(offsetof(actor_mode_converse_data, partner_prop) == 16);
static_assert(offsetof(actor_mode_uncover_data, crouch) == 0);
static_assert(offsetof(actor_mode_uncover_data, done) == 1);
static_assert(offsetof(actor_mode_uncover_data, no_progress) == 2);
static_assert(offsetof(actor_mode_uncover_data, unknown_03) == 3);
static_assert(offsetof(actor_mode_uncover_data, use_last_seen_position) == 4);
static_assert(offsetof(actor_mode_uncover_data, unknown_05) == 5);
static_assert(offsetof(actor_mode_uncover_data, stage) == 8);
static_assert(offsetof(actor_mode_uncover_data, firing_position) == 10);
static_assert(offsetof(actor_mode_uncover_data, target_cluster) == 12);
static_assert(offsetof(actor_mode_uncover_data, unknown_0e) == 14);
static_assert(offsetof(actor_mode_uncover_data, target_object) == 16);
static_assert(offsetof(actor_mode_uncover_data, position) == 20);
static_assert(offsetof(actor_mode_uncover_data, target_reached) == 32);
static_assert(offsetof(actor_mode_uncover_data, pad_21) == 33);
static_assert(offsetof(actor_mode_uncover_data, stage_ticks) == 36);
static_assert(offsetof(actor_mode_uncover_data, duration_ticks) == 40);
static_assert(offsetof(actor_mode_uncover_data, remaining_ticks) == 44);
static_assert(offsetof(actor_mode_uncover_data, total_ticks) == 48);
static_assert(offsetof(actor_mode_search_data, finished) == 0);
static_assert(offsetof(actor_mode_search_data, unknown_01) == 1);
static_assert(offsetof(actor_mode_search_data, reachable) == 2);
static_assert(offsetof(actor_mode_search_data, unknown_03) == 3);
static_assert(offsetof(actor_mode_search_data, unknown_04) == 4);
static_assert(offsetof(actor_mode_search_data, unknown_05) == 5);
static_assert(offsetof(actor_mode_search_data, unknown_06) == 6);
static_assert(offsetof(actor_mode_search_data, stage) == 8);
static_assert(offsetof(actor_mode_search_data, firing_position) == 10);
static_assert(offsetof(actor_mode_search_data, target_cluster) == 12);
static_assert(offsetof(actor_mode_search_data, unknown_0e) == 14);
static_assert(offsetof(actor_mode_search_data, position) == 20);
static_assert(offsetof(actor_mode_search_data, duration_ticks) == 32);
static_assert(offsetof(actor_mode_search_data, remaining_ticks) == 36);
static_assert(offsetof(actor_mode_search_data, elapsed_ticks) == 40);
static_assert(offsetof(actor_mode_charge_data, charge_start_time) == 0);
static_assert(offsetof(actor_mode_charge_data, stage) == 4);
static_assert(offsetof(actor_mode_charge_data, strike_started) == 6);
static_assert(offsetof(actor_mode_charge_data, strike_finished) == 7);
static_assert(offsetof(actor_mode_charge_data, done) == 8);
static_assert(offsetof(actor_mode_charge_data, turning_to_face) == 9);
static_assert(offsetof(actor_mode_charge_data, leap_allowed) == 10);
static_assert(offsetof(actor_mode_charge_data, jump_started) == 11);
static_assert(offsetof(actor_mode_charge_data, jump_solved) == 12);
static_assert(offsetof(actor_mode_charge_data, unknown_0d) == 13);
static_assert(offsetof(actor_mode_charge_data, stage_ticks) == 14);
static_assert(offsetof(actor_mode_charge_data, stage_start_time) == 16);
static_assert(offsetof(actor_mode_charge_data, jump_direction) == 20);
static_assert(offsetof(actor_mode_charge_data, jump_horizontal_speed) == 28);
static_assert(offsetof(actor_mode_charge_data, jump_vertical_speed) == 32);
static_assert(offsetof(actor_mode_charge_data, target_weak) == 36);
static_assert(offsetof(actor_mode_charge_data, stand) == 37);
static_assert(offsetof(actor_mode_charge_data, weak_target_ticks) == 38);
static_assert(offsetof(actor_mode_charge_data, close_in) == 40);
static_assert(offsetof(actor_mode_charge_data, approach_failed) == 41);
static_assert(offsetof(actor_mode_charge_data, unknown_2a) == 42);
static_assert(offsetof(actor_mode_charge_data, wait_threshold) == 44);
static_assert(offsetof(actor_mode_charge_data, suicide_charge) == 48);
static_assert(offsetof(actor_mode_charge_data, unknown_31) == 49);
static_assert(offsetof(actor_mode_charge_data, lead_ticks) == 50);
static_assert(offsetof(actor_mode_charge_data, strike_range_extra) == 52);
static_assert(offsetof(actor_mode_guard_data, countdown_00) == 0);
static_assert(offsetof(actor_mode_guard_data, countdown_02) == 2);
static_assert(offsetof(actor_mode_guard_data, settled) == 4);
static_assert(offsetof(actor_mode_guard_data, command_pending) == 5);
static_assert(offsetof(actor_mode_guard_data, unknown_06) == 6);
static_assert(offsetof(actor_mode_guard_data, attack_point) == 7);
static_assert(offsetof(actor_mode_guard_data, ambush_active) == 8);
static_assert(offsetof(actor_mode_guard_data, ambush_triggered) == 9);
static_assert(offsetof(actor_mode_guard_data, ambush_retreat) == 10);
static_assert(offsetof(actor_mode_guard_data, unknown_0b) == 11);
static_assert(offsetof(actor_mode_guard_data, countdown_0c) == 12);
static_assert(offsetof(actor_mode_guard_data, reselect) == 14);
static_assert(offsetof(actor_mode_guard_data, watch_pending) == 15);
static_assert(offsetof(actor_mode_guard_data, hold_reference) == 16);
static_assert(offsetof(actor_mode_guard_data, look_point_valid) == 20);
static_assert(offsetof(actor_mode_guard_data, look_point_hostile) == 21);
static_assert(offsetof(actor_mode_guard_data, pad_16) == 22);
static_assert(offsetof(actor_mode_guard_data, look_point) == 24);
static_assert(offsetof(actor_mode_guard_data, stage) == 36);
static_assert(offsetof(actor_mode_guard_data, pad_26) == 38);
static_assert(offsetof(actor_mode_guard_data, firing_position) == 40);
static_assert(offsetof(actor_mode_guard_data, guard_point) == 40);
static_assert(offsetof(actor_mode_guard_data, guard_point_surface) == 52);
static_assert(offsetof(actor_mode_guard_data, guard_radius) == 56);
static_assert(offsetof(actor_mode_guard_data, guard_target) == 60);
static_assert(offsetof(actor_mode_guard_data, follow_movement) == 64);
static_assert(offsetof(actor_mode_guard_data, pad_41) == 65);
static_assert(offsetof(actor_mode_alert_data, position_count) == 0);
static_assert(offsetof(actor_mode_alert_data, wait_ticks) == 2);
static_assert(offsetof(actor_mode_alert_data, direction_flag) == 4);
static_assert(offsetof(actor_mode_alert_data, unknown_05) == 5);
static_assert(offsetof(actor_mode_alert_data, current_position) == 6);
static_assert(offsetof(actor_mode_alert_data, next_position) == 8);
static_assert(offsetof(actor_mode_alert_data, position_reached) == 10);
static_assert(offsetof(actor_mode_alert_data, unknown_0b) == 11);
static_assert(offsetof(actor_mode_alert_data, position) == 12);
static_assert(offsetof(actor_mode_alert_data, facing) == 24);
static_assert(offsetof(actor_mode_alert_data, weight) == 28);
static_assert(offsetof(actor_mode_alert_data, time) == 32);
static_assert(offsetof(actor_mode_alert_data, animation_index) == 40);
static_assert(offsetof(actor_mode_alert_data, sequence_id) == 42);
static_assert(offsetof(actor_mode_alert_data, pad_2b) == 43);
static_assert(offsetof(actor_mode_alert_data, unknown_2c) == 44);
static_assert(offsetof(actor_mode_alert_data, cluster_index) == 52);
static_assert(offsetof(actor_mode_alert_data, unknown_36) == 54);
static_assert(offsetof(actor_mode_alert_data, surface_index) == 88);
static_assert(offsetof(actor_mode_vehicle_data, vehicle_index) == 0);
static_assert(offsetof(actor_mode_vehicle_data, seat_index) == 4);
static_assert(offsetof(actor_mode_vehicle_data, unknown_06) == 6);
static_assert(offsetof(actor_mode_vehicle_data, near_line) == 7);
static_assert(offsetof(actor_mode_vehicle_data, seated) == 8);
static_assert(offsetof(actor_mode_vehicle_data, unit_replaced) == 9);
static_assert(offsetof(actor_mode_vehicle_data, failed) == 10);
static_assert(offsetof(actor_mode_vehicle_data, unknown_0b) == 11);
static_assert(offsetof(actor_mode_vehicle_data, path_failures) == 12);
static_assert(offsetof(actor_mode_vehicle_data, stuck_count) == 14);
static_assert(offsetof(actor_mode_vehicle_data, last_progress_time) == 16);
static_assert(offsetof(actor_mode_vehicle_data, last_progress_position) == 20);
static_assert(offsetof(actor_mode_vehicle_data, alert_range_min) == 32);
static_assert(offsetof(actor_mode_vehicle_data, alert_range_max) == 36);
static_assert(offsetof(actor_mode_vehicle_data, close) == 40);
static_assert(offsetof(actor_mode_vehicle_data, facing) == 41);
static_assert(offsetof(actor_mode_vehicle_data, in_front_ticks) == 42);
static_assert(offsetof(actor_mode_vehicle_data, entry_reached) == 44);
static_assert(offsetof(actor_mode_vehicle_data, pad_2d) == 45);
static_assert(offsetof(actor_mode_vehicle_data, path_destination) == 48);
static_assert(offsetof(actor_mode_vehicle_data, entry_direction) == 60);
static_assert(offsetof(actor_mode_vehicle_data, path_surface) == 72);
static_assert(offsetof(actor_mode_obey_data, command_list_index) == 0);
static_assert(offsetof(actor_mode_obey_data, allow_initiative) == 2);
static_assert(offsetof(actor_mode_obey_data, allow_look) == 3);
static_assert(offsetof(actor_mode_obey_data, allow_communication) == 4);
static_assert(offsetof(actor_mode_obey_data, finished) == 5);
static_assert(offsetof(actor_mode_obey_data, unknown_06) == 6);
static_assert(offsetof(actor_mode_obey_data, action) == 8);
static_assert(offsetof(actor_mode_obey_data, aim) == 44);
static_assert(offsetof(actor_mode_fight_data, position_hold_countdown) == 0);

static_assert(offsetof(swarm_component, identifier) == 0);
static_assert(offsetof(swarm_component, flags) == 2);
static_assert(offsetof(swarm_component, position) == 4);
static_assert(offsetof(swarm_component, marker_index) == 16);
static_assert(offsetof(swarm_component, leap_target_index) == 20);
static_assert(offsetof(swarm_component, infection) == 24);
static_assert(offsetof(swarm_component, unknown_18) == 24);
static_assert(offsetof(swarm_component, action) == 28);