/**
 * @file include/halo/objects/api.hpp
 * Functions of the objects module that other modules and the data tables call (namespace halo::objects). The record types are
 * forward-declared, so the header is light enough for every caller and for the data tables.
 */
#pragma once

#include <stdint.h>

struct memory_pool;
struct object_globals;

struct Antenna;
struct DamageEffect;
struct LightVolume;
struct LightVolumeFrame;
struct ModelCollisionGeometry;
struct ModelCollisionGeometryMaterial;
struct ColorRGB;
struct Flag;
struct GBXModel;
struct ModelRegion;
struct TagReflexive;
struct antenna;
struct bsp_leaf_reference;
struct damage_data;
struct data_array;
struct flag;
struct glow;
struct glow_particle;
struct hash_table;
struct object;
struct object_iterator;
struct object_marker;
struct object_memory_dump_record;
struct object_placement_cursor;
struct object_placement_data;
struct object_shield_impulse_result;
struct object_statistics;
struct particle;
struct real_matrix4x3;
struct real_point3d;
struct real_vector3d;
struct render_lighting;
typedef uint32_t datum_index;
typedef float real;

namespace halo::objects {

/**
 * The engine globals the objects module owns (their storage is defined by standalone/data under the original link names);
 * other modules reach them through globals().
 */
struct Globals {
    data_array *&object_data;
    object_globals *&object_globals;
    data_array *&object_list_header_data;
    data_array *&object_list_reference_data;
    datum_index *&object_name_list;
    memory_pool *&object_memory_pool;
    datum_index *&noncollideable_cluster_first;
    data_array *&noncollideable_object_references;
};

Globals &globals();

void object_get_center_of_mass_and_scale(real_point3d *out_center, uint32_t object_index, float *out_radius);
void object_apply_impulse_and_spin(uint32_t object_index, real_vector3d *delta_velocity);
void object_initialize_shield_stun_thresholds(uint32_t object_index, float *override_max_body_vitality, float *override_max_shield_vitality);
void object_update_vitality_and_regeneration(uint32_t object_index);
void damage_data_initialize(damage_data *dd, datum_index damage_effect_tag);
uint8_t object_restore_full_body_vitality(uint32_t object_index);
void object_set_health_frozen_flag(uint32_t object_index);
void object_set_shield_depleted_flag(uint32_t object_index);
uint8_t object_shield_recharge_start(uint32_t object_index);
void object_children_recurse_prune(uint32_t object_index);
void object_delete_teardown(uint32_t object_index);
void damage_apply_area_effect(damage_data *dd);
void object_damage_apply_line_of_sight(damage_data *dd, datum_index target_index, int8_t continue_flag);
int32_t object_get_controlling_player_index(datum_index object_index);
void object_throttled_multiplayer_sound_event();
void object_notify_pickup_or_refresh_probe(uint32_t object_index, datum_index player_index);
void object_apply_shield_charge_and_notify(void **message);
void object_apply_damage(damage_data *dd, uint32_t target_object_index, int16_t hit_node_index, int16_t hit_region_index, int16_t hit_material_index, uint32_t hit_plane);
void object_hash_clear_flag_bit3(uint32_t key);
void object_hash_set_flag_bit3(uint32_t key);
void object_apply_body_damage(uint32_t target_index, int32_t region_index, int32_t node_index, void *plane, ModelCollisionGeometry *geometry, ModelCollisionGeometryMaterial *material, DamageEffect *effect_block, damage_data *dd, uint32_t *notify_flags, float *body_damage_out, float *material_multiplier_out, float damage, uint8_t is_local);
void object_apply_shield_damage(uint32_t target_index, ModelCollisionGeometry *geometry, ModelCollisionGeometryMaterial *material, DamageEffect *effect_block, uint32_t *notify_flags, float *shield_damage_out, float *remaining_damage, uint8_t is_local, uint8_t apply_state, object_shield_impulse_result *record);
void object_queue_pickup_denied_event(void *param_1, int32_t key, uint32_t *source);
void object_apply_linked_impulse(void **message);
void object_damage_notify_and_impulse(uint32_t target_index, damage_data *dd, uint32_t notify_flags, float shield_damage, float body_damage, uint32_t unused_6, int32_t region_index, uint32_t is_local);
void object_dispatch_effect_notify(uint32_t forwarded_eax, uint32_t forwarded_ecx);
void damage_effect_new_at_location(datum_index effect_tag, int16_t node_index, real_vector3d *normal, real_vector3d *incident, real_point3d *impact_position, uint32_t object_index);
void object_destroy_region(uint32_t object_index, int32_t region_index);
void object_regions_reset_permutation_lock(uint32_t object_index, int8_t unlock);
void hash_table_initialize(hash_table *table, int32_t bucket_count);
void hash_table_dispose(hash_table *table);
void hash_table_set_or_remove(hash_table *table, int32_t key, int32_t value);
int32_t hash_table_get(hash_table *table, int32_t key);
void hash_table_grow_freelist(hash_table *table);
void lights_initialize();
void lights_dispose_all();
datum_index light_new_attached(datum_index light_tag, datum_index owner_object, int16_t marker_index, int16_t marker_index_secondary, int16_t change_color_index);
void light_delete(datum_index light_handle);
datum_index light_new_positioned(datum_index light_tag, int32_t marker_index, int16_t marker_sub_index, real_point3d *position, uint32_t param_5, real_vector3d *direction);
void object_lights_update_all();
void light_transient_add(datum_index light_tag, real_vector3d *color, real_point3d *position, uint32_t direction, uint32_t param_3, float intensity);
int16_t light_collect_object_references(uint32_t light_handle, int16_t max_count, int16_t *out_buffer);
void lights_apply_spot_falloff();
void lights_apply_spot_falloff_specular();
real object_sum_attached_light_luminance(uint32_t object_index);
void object_sample_total_lighting_at_point(real_point3d *point, bsp_leaf_reference *location, real_vector3d *color);
void object_sample_ambient_lightmap_point(real_point3d *point, real_vector3d *lightmap_color, real_vector3d *base_map_color, uint8_t wait_for_textures);
void object_sample_ambient_lighting(uint32_t object_index, float *sample);
void object_gather_light_list(datum_index object_index, uint8_t *out);
void object_light_clear_dirty_flag(uint32_t light_index);
void object_light_recompute_transform(uint32_t light_index);
void object_lights_detach_from_structure_bsp();
void object_lights_refresh_transforms();
void object_lights_gather_nearest(int16_t cluster_index, uint32_t self_object_index, real_point3d *probe_point, float search_margin, uint32_t *out_indices, float *out_intensities, uint32_t out_falloffs, int16_t *count, int16_t max_count);
void object_build_effect_parameter_block(uint8_t flags, real_vector3d *shading_normal, float intensity, ColorRGB *lightmap_color, real_vector3d *lightmap_normal, ColorRGB *base_map_color, render_lighting *lighting);
void object_color_clamp_to_intensity(float intensity, ColorRGB *color);
datum_index light_cluster_iterate_begin(datum_index *cursor, int16_t cluster_index);
datum_index light_cluster_iterate_next(datum_index *cursor);
void light_get_render_bounds(datum_index handle, real_point3d *center_out, float *radius_out);
uint8_t light_not_marked_this_frame(datum_index handle);
uint8_t light_mark_this_frame(datum_index handle);
void scenario_objects_place(uint8_t *scenario);
void object_type_definition_chain_build();
void object_type_definitions_notify_0x24(uint32_t object_index, uint32_t argument);
uint8_t object_type_definitions_query_0x28(uint32_t object_index);
void object_type_definitions_notify_two_args_0x2c(uint32_t object_index, uint32_t event_argument);
void object_type_definitions_notify_0x30(uint32_t object_index);
uint8_t object_type_definitions_query_0x34(uint32_t object_index);
void object_type_definitions_notify_0x38(uint32_t object_index);
void object_type_definitions_notify_0x3c(uint32_t object_index, uint32_t argument);
void object_type_definitions_notify_region_damage(uint32_t object_index, uint32_t argument_1, uint32_t argument_2);
uint8_t object_type_definitions_query_0x44(uint32_t object_index);
void object_type_definitions_notify_two_args_0x48(uint32_t object_index, uint32_t event_argument);
void object_type_definitions_notify_0x4c(uint32_t object_index, uint32_t argument);
void object_type_definitions_notify_0x50(uint32_t object_index);
void object_type_definitions_notify_0x54(uint32_t object_index);
void object_type_definitions_notify_0x5c(uint32_t object_index);
void object_type_definitions_notify_0x58(uint32_t object_index, uint32_t argument_1, uint32_t argument_2);
int object_type_override_get_0x64(uint32_t object_index, void *buffer, int32_t buffer_size);
void object_type_override_call_0x68(uint32_t object_index);
int object_type_override_call_0x6c(uint32_t object_index, void *buffer, int32_t bit_budget, int32_t full_update);
void object_type_override_call_0x70(uint32_t object_index, uint32_t edi_argument, uint32_t stack_argument);
void object_type_override_call_0x70_release_node(int32_t *record, uint32_t client);
uint8_t object_datum_consume_pending_flag(uint32_t object_index);
uint8_t object_type_override_call_0x74(uint32_t object_index);
void object_type_override_call_0x7c(uint32_t object_index);
void objects_delete_unparented_of_type_mask();
void scenario_objects_place_for_structure_bsp_on_activate();
void scenario_objects_place_for_structure_bsp(uint8_t place);
void objects_initialize();
void objects_reset();
void objects_flush_dirty_state();
void objects_dispose();
void objects_update();
void object_mark_pending_delete(uint32_t object_index);
void object_clear_pending_delete_flag(uint32_t object_index);
void object_reset_velocity_and_wake(uint32_t object_index);
void object_set_position_and_orientation(uint32_t object_index, real_vector3d *forward, real_vector3d *up, real_point3d *position);
void object_set_position_and_recalculate(real_point3d *position, uint32_t object_index);
void object_set_position_and_relink(real_point3d *position, uint32_t object_index, bsp_leaf_reference *location);
void object_placement_data_initialize(object_placement_data *placement, datum_index definition_tag, datum_index role);
datum_index object_new(object_placement_data *placement);
datum_index object_new_with_datum_role_control(object_placement_data *placement, uint32_t role);
void object_delete_recursive(uint32_t object_index, uint8_t recurse_siblings);
void object_delete_unparented(uint32_t object_index);
void object_delete_by_pooled_node_id(int32_t **record);
void object_delete(uint32_t object_index);
uint8_t object_is_delete_pending(uint32_t object_index);
void object_set_cluster_and_parent(uint32_t object_index, bsp_leaf_reference *location);
void object_unlink_cluster_or_notify_parent(uint32_t object_index);
datum_index object_cluster_noncollideable_iterate_begin(datum_index *cursor, int16_t cluster_index);
datum_index object_cluster_noncollideable_iterate_next(datum_index *cursor);
datum_index object_resolve_collideable_reference(datum_index *next_reference, int16_t cluster_index);
datum_index object_cluster_collideable_iterate_next(datum_index *cursor);
int16_t object_get_root_parent_placement(uint32_t object_index, object_placement_cursor *out_cursor);
real_matrix4x3 * object_get_node_marker_address(uint32_t object_index, int16_t node_index);
char * object_get_attachment_marker_name(uint32_t object_index, int16_t attachment_index);
int32_t object_get_node_local_transform(uint32_t object_index, char *marker_name, object_marker *marker, uint32_t maximum_markers);
void object_reorient_relative_to_marker(uint32_t parent_index, char *parent_marker_name, uint32_t object_index, char *object_marker_name);
void object_recompute_basis_from_marker_delta(object *obj, object_marker *marker, real_matrix4x3 *output_matrix);
void object_attach_to_object(uint32_t parent_index, uint32_t child_index, int16_t marker_index);
void object_snap_to_parent_marker_and_detach(uint32_t object_index);
void object_set_in_pvs_pass_flag(uint32_t object_index, uint8_t in_pvs);
void object_set_collision_enabled(uint32_t object_index, uint8_t enable);
void object_get_position(real_point3d *out, uint32_t object_index);
void object_get_orientation(real_vector3d *out_forward, uint32_t object_index, real_vector3d *out_up);
real_matrix4x3 * object_get_world_matrix(uint32_t object_index, real_matrix4x3 *out);
void object_get_root_object_velocities(uint32_t object_index, real_vector3d *out_velocity, real_vector3d *out_angular_velocity);
void object_get_root_location(int32_t *out, uint32_t object_index);
void object_copy_default_node_transforms(uint32_t object_index, int16_t requested_count);
void object_offset_node_translation(uint32_t object_index, real_vector3d *delta);
void object_set_permutation_by_name(uint32_t object_index, char *name, int16_t region_filter, char use_matched_index);
void object_solve_two_bone_ik_to_marker(uint32_t object_index, char *marker_a_name, uint32_t marker_b_object_index, char *marker_b_name, uint8_t *node_base);
uint8_t object_function_get_value(uint32_t object_index, int16_t selector, float *out_value);
object * object_try_and_get(datum_index object_index, uint32_t type_mask);
object * object_iterator_next(object_iterator *iterator);
uint32_t object_get_root_object_index(uint32_t object_index);
int16_t object_find_in_sphere(uint32_t search_mask, uint32_t type_mask, void *location, real_point3d *center, float radius, datum_index *out_objects, int16_t max_output);
int16_t object_collect_in_clusters(uint32_t search_mask, int16_t cluster_count, int16_t *cluster_indices, int16_t max_output, datum_index *out_objects);
datum_index object_new_from_scenario_name(int16_t name_index);
datum_index object_lookup_table_get(int16_t name_index);
void object_clear_references_to_object(uint32_t dying_object_index);
void object_list_membership_set(uint32_t object_index, char add);
void object_sweep_refresh_cluster_membership();
void objects_recompute_cluster_membership();
uint8_t object_test_in_atmosphere_zone(uint32_t object_index);
void objects_get_statistics(object_statistics *out);
void objects_set_ambient_cluster_override(int16_t local_player_index);
int16_t objects_get_ambient_cluster();
void object_notify_predicted_resources_if_valid(datum_index definition_tag);
void object_notify_children_recursive(uint32_t object_index);
uint8_t object_reposition_to_spawn_location(uint32_t object_index, real_point3d *target_position, uint32_t ignore_object_index);
uint8_t object_nudge_position_by_velocity(uint32_t object_index, real_point3d *out);
datum_index object_block_data_new(int32_t specific_index, data_array *array, int16_t size);
void object_block_data_free(data_array *array, datum_index handle);
uint8_t object_block_data_grow(uint32_t object_index, int16_t field_offset, int16_t extra_size);
uint8_t object_update(uint32_t object_index);
void object_update_export_functions(datum_index object_index);
void object_recalculate_bounding_radius_recursive(uint32_t object_index);
void object_recalculate_bounding_radius(uint32_t object_index);
void object_notify_node_array_if_animated(uint32_t object_index);
void object_initialize_change_colors(uint32_t object_index, ColorRGB *colors);
int16_t object_permutation_find_matching_group(ModelRegion *region, int16_t group, int16_t *out);
uint8_t object_regions_initialize_permutations(uint32_t object_index, int16_t group, GBXModel *model);
int16_t object_get_first_region_probability_group(uint32_t object_index, GBXModel *model);
void object_refresh_region_permutations(uint32_t object_index);
void object_remove_from_sibling_list(datum_index *slot, uint32_t target_object_index);
void object_delete_4f9030(uint32_t object_index, char recurse_siblings);
void object_update_change_colors(uint32_t object_index);
void object_update_functions(uint32_t object_index);
void object_set_scale_and_refresh_nodes(uint32_t object_index, float scale, int16_t ticks);
uint8_t object_disconnect_from_map(uint32_t object_index);
uint8_t object_cluster_stamp_mark_visited(datum_index object_index);
void object_create_attachments(uint32_t object_index);
void object_delete_attachments(uint32_t object_index);
void object_for_each_light_attachment(uint32_t object_index, int32_t register_in_table, int32_t invoke_callback);
void object_reserve_render_cache_slot(uint32_t object_index, int16_t slot);
void object_release_render_cache_slot(uint32_t object_index);
datum_index object_new_from_scenario_placement(uint8_t *placement, TagReflexive *palette);
void objects_garbage_collection();
int32_t object_tree_collect_matching(uint32_t object_index, uint8_t (*filter)(uint32_t, void *), void *filter_context, int32_t count, int32_t max_count, datum_index *out);
int32_t object_collect_local_player_relevant_objects(real_point3d *point, uint8_t (*filter)(uint32_t, void *), void *filter_context, int32_t max_count, datum_index *out);
int32_t object_type_definitions_collect_by_flag_bits(int32_t bit_index, int32_t remaining_bits, int16_t range_index, int16_t range_count, int32_t *bit_array, int32_t cluster_stamp_snapshot, uint8_t (*filter)(uint32_t, void *), void *filter_context, int32_t count, int32_t max_count, datum_index *out);
int object_dump_compare_by_total_size(const object_memory_dump_record *a, const object_memory_dump_record *b);
void object_dump_accumulate_stats(uint32_t object_index, object_memory_dump_record *record);
void object_dump_write(object_memory_dump_record *record, void *file);
void objects_dump_memory();
uint8_t scenery_new(datum_index object_index);
uint8_t scenery_update(datum_index object_index);
void object_start_animation(uint32_t object_index, datum_index graph_tag, char *name, int16_t requested_frame);
uint32_t object_animation_get_frames_remaining(uint32_t object_index);
void antennas_initialize();
void antennas_dispose();
void antennas_clear_disposing_flag();
void antennas_reset_data_pointer();
datum_index antenna_new(datum_index antenna_tag);
void antenna_delete(datum_index antenna_index);
void antenna_render_callback(datum_index object_index, datum_index antenna_index);
void antennas_update(float dt);
void antenna_update_physics(antenna *ant, Antenna *antenna_tag, float dt);
void antenna_apply_marker_delta(real_vector3d *out_forward, real_point3d *out_position, antenna *ant, Antenna *antenna_tag, bsp_leaf_reference *node_ref);
void antenna_render_geometry(Antenna *antenna_tag, antenna *ant);
void flags_initialize();
void flags_dispose();
void flags_clear_disposing_flag();
void flags_reset_data_pointer();
datum_index flag_new(datum_index flag_tag);
void flag_cloth_mark_border_cells(flag *entry, Flag *tag);
void flag_cloth_init_shape_constraints(flag *entry, Flag *tag);
void flag_cloth_stamp_region_split_flags(int16_t outer_start, Flag *tag, flag *entry, int16_t inner_start, int16_t size, uint16_t split_code);
void flag_delete(datum_index flag_index);
void flag_render_callback(datum_index object_index, datum_index flag_index, uint32_t arg3, uint32_t arg4);
void flags_update(float dt);
void flag_cloth_update(flag *entry, Flag *tag, float dt);
void flag_pole_get_marker_positions(flag *entry, bsp_leaf_reference *node_ref, real_point3d *marker_positions, uint8_t *row_table, int16_t *row_start_scratch, int16_t *column_marker_index, Flag *tag);
void flag_render(uint32_t *entry, uint32_t *submission_block, Flag *tag, uint8_t *second_geometry);
void glow_initialize();
void glow_dispose();
void glow_clear_disposing_flag();
datum_index glow_new(datum_index glow_tag);
void glow_delete(datum_index glow_index);
void glow_render_dispatch(uint32_t object_index, datum_index glow_handle);
void glow_update(uint32_t object_index, glow *entry);
void glow_particle_compute_fade(glow *entry, glow_particle *particle);
void glow_particle_compute_color(glow *entry, glow_particle *particle);
void glow_particle_compute_position(uint32_t object_index, glow *entry, glow_particle *particle);
void glow_particle_advance_time(uint32_t object_index, glow *entry, glow_particle *particle, float rate);
void glow_chain_build(glow *entry);
glow_particle * glow_particle_new(glow *entry, int16_t index, int16_t count);
glow_particle * glow_particle_spawn(glow *entry);
glow_particle * glow_particle_datum_new();
void glow_particle_reposition(glow *entry, glow_particle *particle, float phase_rate);
void glow_render(datum_index glow_handle);
void light_volumes_initialize();
void light_volumes_dispose();
void light_volumes_clear_disposing_flag();
datum_index light_volume_new(datum_index definition_tag);
void light_volume_delete(datum_index light_volume_index);
LightVolumeFrame *object_attachment_get_blended_marker(uint32_t object_index, const LightVolume *tag);
void light_volume_render(uint32_t object_index, datum_index light_volume_handle, uint32_t unused, uint8_t *function_context);
float curve_apply_exponent(float value, float exponent);
void light_volume_render_procedure(uint32_t object_index, datum_index light_volume_handle);
void lightnings_initialize();
void lightnings_dispose();
void lightnings_clear_disposing_flag();
datum_index lightning_new(datum_index definition_tag);
void lightning_delete(datum_index lightning_index);
void antenna_tip_jitter(real_vector3d *amplitude, real_point3d *position, real_matrix4x3 *m);
void lightning_render(uint32_t object_index, datum_index lightning_handle, uint32_t unused, int32_t *function_context);
void widgets_initialize();
void widgets_dispose();
void widgets_dispose_clear_flag();
void widget_new(uint32_t object_index);
void widget_delete_all(uint32_t object_index);
int8_t widget_list_has_flag(datum_index first_widget);
void widget_list_notify(uint32_t object_index, uint32_t render_arg, void *render_context);
void widgets_update_all(float dt);
void breakable_surfaces_reset();
int8_t breakable_surface_is_intact(int16_t bit_index);

}
