/**
 * @file include/halo/shell/vars.hpp
 * Addresses of the engine variables the shell module owns, by name. Other files bind a typed reference to the entry they use
 * (halo::link::ref<T>); the link names themselves appear only in standalone/data/link/shell_vars.hpp.
 */
#pragma once

namespace halo::shell {

/** Address table of the engine variables owned by the shell module. */
struct Vars {
    void *clsid_dxdiag_provider;
    void *config_decal_slope_z_bias;
    void *config_decal_z_bias;
    void *config_disable_alpha_render_targets;
    void *config_disable_buffering;
    void *config_disable_driver_management;
    void *config_disable_render_targets;
    void *config_disable_specular;
    void *config_enable_stop_start;
    void *config_error_text;
    void *config_force_shader;
    void *config_head_relative_speech;
    void *config_invalid_driver;
    void *config_invalid_sound_driver;
    void *config_linear_texture_addressing;
    void *config_linear_texture_addressing_sun;
    void *config_linear_texture_addressing_zoom;
    void *config_maximum_resolution;
    void *config_min_max_blend_op_is_broken;
    void *config_old_driver;
    void *config_old_sound_driver;
    void *config_properties;
    void *config_prototype_card;
    void *config_safe_mode;
    void *config_transparent_decal_slope_z_bias;
    void *config_transparent_decal_z_bias;
    void *config_unknown_property_text;
    void *config_unsupported_card;
    void *config_use_alternate_convolve_mask;
    void *config_use_anisotropic_filter;
    void *config_use_fixed_function;
    void *connect_address;
    void *console_debug_flag_4;
    void *cpu_brand_string;
    void *cpu_extended_features;
    void *cpu_features;
    void *cpu_identification_state;
    void *cpu_l1_code_cache;
    void *cpu_l1_data_cache;
    void *cpu_l1_tlb_4k;
    void *cpu_l1_tlb_large;
    void *cpu_l2_cache;
    void *cpu_l2_tlb_4k;
    void *cpu_l2_tlb_large;
    void *cpu_l2_unknown;
    void *cpu_signature;
    void *cpu_speed;
    void *cpu_vendor_string;
    void *crash_in_progress;
    void *crypt_provider;
    void *d3d9_module;
    void *default_locale_name;
    void *dinput8_module;
    void *direct3d_create9;
    void *direct_input8_create;
    void *direct_sound_create8;
    void *display_adapter_count;
    void *display_adapters;
    void *dsdevid_default_playback;
    void *dsound_module;
    void *dxdiag_sound_device_child_name;
    void *error_file_enabled;
    void *eula_file_name;
    void *exception_gathering_text;
    void *exception_title;
    void *external_00686b4c;
    void *external_00686b50;
    void *external_00686b54;
    void *external_00686b58;
    void *external_00686b5c;
    void *fatal_error_help_file;
    void *fatal_error_is_fatal;
    void *fatal_error_remember_choice;
    void *fatal_error_text;
    void *fatal_error_title;
    void *global_scenario_game_globals;
    void *graphics_device_id;
    void *graphics_device_name;
    void *graphics_vendor_name;
    void *hardware_requirements;
    void *hwreq_cannot_find_format;
    void *hwreq_config_file_suffix;
    void *hwreq_open_error_text;
    void *hwreq_parser_vtable_instance;
    void *hwreq_quoted_string;
    void *hwreq_version_root_block;
    void *iid_direct_draw7;
    void *iid_dxdiag_provider;
    void *keystone_create;
    void *keystone_create_window;
    void *keystone_dispatch_message;
    void *keystone_module;
    void *keystone_release;
    void *keystone_set_focus_window;
    void *keystone_translate_accelerator;
    void *keystone_update;
    void *keystone_window_add_dirty_control;
    void *length_error_throw_info;
    void *length_error_vtable;
    void *locale_codepage_format;
    void *logic_error_vtable;
    void *nojoystick;
    void *nowindowskey;
    void *os_platform_value;
    void *out_of_range_throw_info;
    void *out_of_range_vtable;
    void *physical_memory;
    void *product_id_string;
    void *report_fault;
    void *required_cpu_speed;
    void *required_directx_build;
    void *required_disk_space;
    void *required_memory;
    void *safe_mode;
    void *security_write_access_state;
    void *selected_sound_device;
    void *sh_get_folder_path;
    void *shell_argc;
    void *shell_argv;
    void *shell_arrow_cursor;
    void *shell_command_line;
    void *shell_instance;
    void *shell_instance_index;
    void *shell_instance_mode_value;
    void *shell_instance_mutex;
    void *shell_instance_mutex_names;
    void *shell_language_id;
    void *shell_module_handle;
    void *shell_module_path;
    void *shell_nosound;
    void *shell_show_command;
    void *shell_stack_guard_old_protect;
    void *shell_stack_guard_page;
    void *shell_window;
    void *shell_window_maximized;
    void *shell_window_minimized;
    void *shell_window_proc_bypass;
    void *shfolder_module;
    void *sound_cache_size_megabytes;
    void *sound_cache_unknown_c8;
    void *sound_device_count;
    void *sound_devices;
    void *sound_paused;
    void *std_exception_vtable;
    void *string_invalid_string_position;
    void *string_invalid_vector_subscript;
    void *string_string_too_long;
    void *string_vector_too_long;
    void *strings_dll_invalid_text;
};

/** The singleton address table; its storage is constant-initialised. */
const Vars &vars();

}  // namespace halo::shell
