/**
 * @file src/ai/vars.cpp
 * Binds halo::ai::Vars to the engine variables the data image defines under their original link names.
 */

#include "halo/ai/vars.hpp"
#include "link/ai_vars.hpp"

namespace halo::ai {

const Vars &vars()
{
    static const Vars table{
        DAT_00655ab4,
        DAT_00656b24,
        actor_avoidance_a_bearing,
        actor_avoidance_a_elevation,
        actor_avoidance_a_radius,
        actor_avoidance_b_bearing,
        actor_avoidance_b_elevation,
        actor_avoidance_b_radius,
        actor_avoidance_circle,
        actor_avoidance_near_weights,
        actor_avoidance_ray_weights,
        actor_avoidance_samples_a,
        actor_avoidance_samples_b,
        actor_combat_status_min_grade,
        actor_control_animation_state_table,
        actor_data,
        actor_dialogue_variant_offset_1a,
        actor_dialogue_variant_offset_2a,
        actor_dialogue_variant_offset_3a,
        actor_dialogue_variant_scale_1b,
        actor_dialogue_variant_scale_23b,
        actor_dialogue_variant_scale_2a,
        actor_dialogue_variant_table_a,
        actor_dialogue_variant_table_b,
        actor_dialogue_variant_table_c,
        actor_dialogue_variant_table_d,
        actor_dialogue_variant_table_e,
        actor_dialogue_variant_table_f,
        actor_dialogue_variant_table_g,
        actor_dodge_table,
        actor_firing_position_reject_rules,
        actor_firing_position_score_rules,
        actor_lookup_table_006555a8,
        actor_mode_definitions,
        actor_mode_guard_look_weights_a5,
        actor_mode_guard_look_weights_a6,
        actor_mode_guard_look_weights_ambush,
        actor_mode_guard_look_weights_idle,
        actor_mode_uncover_look_weights_active,
        actor_type_procs,
        actor_vocalization_duration,
        actor_vocalization_variant,
        ai_actor_mode_dispatch_table,
        ai_communication_class_follow_up,
        ai_communication_class_look_marker,
        ai_communication_class_no_actor_class,
        ai_communication_class_priority,
        ai_communication_class_repeat_delay,
        ai_communication_class_tail_seconds,
        ai_communication_direction_table,
        ai_communication_event_definitions,
        ai_communication_lines,
        ai_communication_quiet_until_tick,
        ai_communication_selector_delay_seconds,
        ai_conversation_data,
        ai_default_2d_direction,
        ai_globals_ptr,
        ai_marker_name_b,
        ai_pursuit_data,
        ai_vocalization_line_table,
        communication_line_base,
        communication_line_count,
        conversation_index_lookup,
        conversation_line_base,
        conversation_line_count,
        encounter_data,
        encounter_platoon_states,
        encounter_squad_states,
        game_time,
        global_down3d_pointer,
        global_forward2d_pointer,
        global_origin3d_pointer,
        global_structure_bsp,
        k_random_scale_65536,
        k_real_one,
        k_real_point_six,
        k_real_zero,
        order_code_mode_data_expect,
        prop_array_name,
        prop_data,
        qsort_candidate_base,
        qsort_candidate_count,
        swarm_component_data,
        swarm_data,
        team_pair_data,
        ticks_per_second,
    };
    return table;
}

}  // namespace halo::ai
