/**
 * @file include/halo/interface/api.hpp
 * Functions of the interface module that other modules and the data tables call (namespace halo::interface). The record types are
 * forward-declared, so the header is light enough for every caller and for the data tables.
 */
#pragma once

#include <stdint.h>

struct HUDGlobals;
struct first_person_weapon_interface;
struct heap;
struct hud_messaging_globals;
struct hud_unit_meter_globals;
struct map_list_entry;
struct saved_player_profile;
struct virtual_keyboard_globals;

#ifdef interface
#undef interface
#endif

struct BitmapData;
struct ColorARGB;
struct ColorRGB;
struct EventHandlerReference;
struct HUDGlobalsButtonIcon;
struct HUDInterfaceMultitextureOverlay;
struct Point2DInt;
struct Rectangle2D;
struct TagReflexive;
struct UIWidgetDefinition;
struct Weapon;
struct controls_gamepad_record;
struct flag;
struct hud_element_placement;
struct hud_flash_parameters;
struct hud_message_slot;
struct hud_messaging_information;
struct hud_meter_placement;
struct hud_number_placement;
struct hud_overlay_list;
struct hud_player_messaging_state;
struct hud_static_element_placement;
struct motion_sensor_blip;
struct motion_sensor_frame;
struct object_marker;
struct player;
struct real_point3d;
struct real_vector3d;
struct team;
struct terminal_console;
struct text_edit_state;
struct ui_key_event;
struct video_resolution;
struct weapon_hud_ammo_state;
struct widget;
struct widget_history_node;
struct widget_instance;
typedef uint32_t datum_index;
typedef uint8_t (*ui_list_item_format_function)(void *item_buffer, int32_t item_index, void *list_items);

namespace halo::interface {

/**
 * The engine globals the interface module owns (their storage is defined by standalone/data under the original link names);
 * other modules reach them through globals().
 */
struct Globals {
    uint8_t &chat_dialog_open;
    int32_t &controls_capture_row;
    uint8_t &controls_input_capture_flags;
    int16_t &current_local_player_index;
    map_list_entry *&map_list;
    int32_t &map_list_count;
    uint8_t &quit_confirm_error_is_error;
    uint8_t &quit_confirm_error_modal;
    int16_t &quit_confirm_error_string_index;
    int16_t &quit_confirm_error_unknown_ae;
    int32_t &selected_saved_item;
    uint8_t &split_screen_quit_prompt_armed;
    heap *&widget_memory_pool;
    uint8_t &widget_memory_pool_valid;
    virtual_keyboard_globals &virtual_keyboard;
    HUDGlobals *&hud_globals_tag_data;
    hud_messaging_globals *&hud_messaging;
    hud_unit_meter_globals *&hud_unit_meters;
    first_person_weapon_interface *&first_person_weapon_interfaces;
};

Globals &globals();

uint32_t audio_options_apply_from_profile(widget_instance *widget);
void autopatch_status_widget_update(widget_instance *record);
int32_t bitmap_group_sequence_get_bitmap_offset(datum_index bitmap_tag, int16_t sequence_index, int16_t frame_index);
uint8_t blip_type_get(int16_t local_player_index, datum_index object_index);
void chat_close(void);
int32_t chat_default_team_channel(void);
void chat_dispatch_incoming(void *event);
uint8_t chat_poll_hotkeys(void);
void chat_queue_team_message(int32_t team_index);
void chat_server_relay_incoming_message(void **context, void *machine);
void chat_submit_input(void);
uint8_t checkpoint_list_add_row(int32_t index, const char *name, int32_t level_index, int32_t difficulty, int32_t game_time, const void *time, void *user_data);
void chimera__chat_open(int32_t chat_scope);
void chimera__chat_out(uint8_t channel);
void chimera__console_out(ColorARGB *color, char *format, ...);
void chimera__console_out_copy(char *text);
void chimera__do_show_loading_screen(void);
void chimera__hud_message(int16_t local_player_index, const wchar_t *text);
void chimera__load_main_menu(void);
widget_instance * chimera__load_ui_widget(const char *tag_path, datum_index tag_index, widget_instance *parent, uint16_t controller_index, datum_index history_definition, datum_index history_list_definition, int16_t history_selection);
void chimera__main_menu_music(uint8_t finalize_render_frame);
void chimera__motion_sensor_update(void);
void chimera__multiplayer_message(const wchar_t *text);
uint32_t color_argb_scale_alpha(uint32_t packed_color, float scale);
uint32_t color_pack_argb_from_real(ColorARGB *color);
uint32_t color_rgb_float_to_int(const float *rgb);
void console_clear_bottom_line(uint8_t clear_text);
void console_clear_screen(void);
void console_close(terminal_console *console);
void console_draw_input_line(void);
void console_draw_overlay(void);
void console_message_delete(datum_index message);
void console_message_expire_old(void);
datum_index console_message_new(void);
uint8_t console_open(terminal_console *console);
void console_position_cursor(void);
void console_printf_verbose(ColorARGB *color, char *format, ...);
void console_process_input_events(void);
uint8_t console_process_queued_input(void);
void console_restore_cursor(void);
void console_update_display(void);
uint8_t controls_action_column_is_bindable(int32_t slot, int32_t action_index);
uint16_t * controls_action_display_name(int32_t device, const char *action_name);
uint8_t controls_apply_preset(widget_instance *widget);
uint8_t controls_binding_clear(int32_t action_index, int32_t device);
int32_t controls_binding_list_refresh_rows(widget_instance *widget, int32_t page);
uint8_t controls_binding_row_handle_input(widget_instance *screen);
void controls_binding_row_widget_update(int32_t action_index, widget_instance *row, int32_t device);
void controls_binding_rows_toggle_device_mode(widget_instance *widget, uint8_t mode);
void __cdecl controls_build_device_label_table(void);
void controls_device_label_add(const uint16_t *name, int32_t device_type);
uint8_t controls_enumerate_next_assignable_action(int32_t device, int16_t *record, const char *action_name, uint8_t accept_reserved_on_retry);
uint8_t controls_gamepad_bindings_restore(void);
uint8_t controls_gamepad_list_add(const controls_gamepad_record *entry, controls_gamepad_record *list);
int32_t controls_gamepad_list_find(const controls_gamepad_record *entry, controls_gamepad_record *list);
uint8_t controls_gamepad_list_remove(const controls_gamepad_record *entry, controls_gamepad_record *list);
uint8_t controls_gamepad_lists_load(widget_instance *screen);
void controls_gamepad_lists_refresh(widget_instance *screen);
uint8_t controls_gamepad_toggle_assignment(widget_instance *row);
void controls_gamepad_widget_nodes_collect(widget_instance **out, widget_instance *screen);
uint8_t controls_key_is_bindable(int32_t action);
void debug_fp_clip_note(const float *world, int32_t effect_type);
void debug_fp_dispatch_note(int32_t toggle, int32_t mode, int32_t shader_type, int32_t primitives, void *draw, void *draw_simple, void *overlay);
void debug_fp_draw_state_note(const char *site, int32_t hresult, uint32_t primitive_type, uint32_t vertex_count, uint32_t primitive_count);
void debug_fp_pre_draw(void);
void debug_fp_render_model_note(uint32_t model_tag, float pixels, int32_t lod, const float *node0, const float *center, int32_t early_out);
void debug_fp_state_arm(int32_t armed);
void debug_play_diagnostics(void);
void display_error(int16_t error_string_index, int32_t player_index, uint8_t modal, uint8_t is_error);
void first_person_weapon_center_flashlight(datum_index unit_index, real_point3d *out_origin, real_vector3d *out_extents, real_vector3d *out_direction);
uint32_t first_person_weapon_get_marker_data(datum_index weapon_index, const char *marker_name, object_marker *out, uint32_t maximum);
void first_person_weapon_interface_initialize(int16_t local_player_index);
void first_person_weapon_interface_tick(void);
void first_person_weapon_interface_tick_reset(int16_t local_player_index);
void first_person_weapon_process_action(int16_t local_player_index, int16_t action_code);
void first_person_weapon_set_attached(int16_t local_player_index, uint8_t attached);
void first_person_weapon_set_state(int16_t local_player_index, uint8_t force_pose_snapshot, int16_t new_state);
void first_person_weapon_snapshot_pose(int16_t local_player_index, int16_t blend_gap);
void first_person_weapon_update(int16_t local_player_index);
void first_person_weapon_update_active_state(void);
void first_person_weapon_update_animation_controls(int16_t local_player_index);
void first_person_weapon_update_lighting(void);
void first_person_weapon_update_screen_effects(void);
void first_person_weapon_update_state(int16_t local_player_index);
void first_person_weapon_update_zoom_static_tint(uint8_t enabled);
void globals_color_table_get_cyclic_color(int16_t table_index, int16_t color_index, ColorARGB *out);
void hud_add_item_message(int16_t local_player_index, int32_t source, uint8_t source_kind, int16_t count);
void hud_anchor_offset_to_screen_position(const void *anchor, uint8_t has_scale, float scale, const int16_t *offset, int16_t *out, int32_t selector);
void hud_bitmap_anchor_extents(uint8_t pixel_uvs, const BitmapData *bitmap, const float *uv, float *out_extents, int16_t anchor);
void hud_chat_listbox_clear(void);
uint32_t hud_chat_listbox_remove_oldest(void);
void hud_chat_listbox_update(void);
void hud_display_checkpoint_message(uint8_t is_begin);
void hud_display_loading_message(uint8_t is_begin);
void hud_draw_bitmap_at(const float *uv, BitmapData *bitmap, uint8_t pixel_uvs, int16_t anchor, const Point2DInt *screen_position, float scale, float rotation, uint32_t color);
void hud_draw_bitmap_element(const float *uv, const hud_element_placement *placement, uint8_t pixel_uvs, void *meter_parameters, BitmapData *bitmap, const void *anchor, float scale, float rotation, uint32_t color, uint8_t split_screen);
void hud_draw_damage_indicators(int16_t local_player_index);
void hud_draw_grenade_interface(int16_t local_player_index, datum_index unit_index);
void hud_draw_message_icon(const hud_messaging_information *information, Rectangle2D *cursor, uint32_t color);
void hud_draw_message_text_span(Rectangle2D *cursor, Rectangle2D *origin, const uint16_t *text, uint8_t allow_button_prompts);
void hud_draw_multitexture_overlay(const float *scale, const HUDInterfaceMultitextureOverlay *overlay, int16_t local_player_index, const Point2DInt *screen_position, const float *uv, const float *extents, float rotation, uint32_t color);
void hud_draw_number(void *unused, const void *anchor, const hud_number_placement *placement, int16_t value, int16_t fraction, uint32_t flags, int32_t flash_start_time, float scale);
void hud_draw_overlays(const void *anchor, const hud_overlay_list *list, uint32_t type_mask, int32_t flash_start_time, uint32_t draw_flags, uint8_t split_screen);
void hud_draw_rotated_bitmap_quad(const Point2DInt *screen_position, const float *scale, void *meter_parameters, BitmapData *bitmap, const float *uv, const float *extents, float rotation, uint32_t color);
void hud_draw_static_element(int16_t local_player_index, const void *anchor, const hud_static_element_placement *element, uint32_t draw_flags, int32_t flash_start_time);
void hud_draw_weapon_interface(player *p);
uint16_t * hud_get_message_string(int32_t message_index);
void hud_message_broadcast_to_local_players(const uint16_t *text);
int32_t hud_message_compare(const void *a, const void *b);
hud_message_slot * hud_message_find_slot(int32_t source, hud_player_messaging_state *record, uint8_t source_kind);
void hud_messaging_clear_after_load(void);
void hud_messaging_update(int16_t local_player_index);
void hud_meter_draw_fill(void *dest, uint8_t value_a, uint8_t value_b, uint32_t flags, float fraction, float fraction_2, const hud_meter_placement *meter);
uint8_t hud_meter_find_matching_elements(uint32_t source_tag_ref, uint32_t target_tag_ref, int16_t *out);
uint32_t hud_meter_flash_color_blend(const hud_flash_parameters *flash, int32_t start_time);
void hud_meter_permute_node_records(uint8_t *dest, uint8_t *source, uint32_t target_tag_ref, int16_t *lookup);
void hud_meter_resolve_bitmap_frame(datum_index bitmap_tag, int16_t sequence_index, uint16_t frame_index, void **out_data, int32_t *out_offset);
void hud_pause_timer(uint8_t paused);
void hud_play_pickup_notification(uint32_t object_or_slot_index, int16_t item_type_code);
uint8_t hud_player_weapon_ammo_state(const player *p, weapon_hud_ammo_state *out);
void hud_post_item_message(int16_t count, int32_t source, uint8_t kind, int16_t local_player_index, int8_t machine_id);
void hud_receive_item_message(void **message);
void hud_render_unit_interface(player *p);
void hud_set_action_text_shown(int16_t local_player_index, uint8_t shown);
void hud_set_help_text(int16_t message_index);
void hud_set_message_icon_argument(int16_t local_player_index, int16_t slot, const hud_messaging_information *information);
void hud_set_message_string_argument(int16_t local_player_index, int16_t slot, int16_t string_index, uint8_t from_scenario_names);
void hud_set_objective_text(int16_t message_index);
void hud_set_player_message(int16_t message_index, int16_t local_player_index);
void hud_set_timer_time(int32_t minutes, int32_t seconds);
void hud_state_allocate(void);
void hud_state_reset(void);
void hud_text_draw_configure(int16_t font_table_index, uint16_t color_or_flags, int16_t column, uint32_t unknown_4730, int16_t color_table_index, int16_t color_index);
int32_t hud_text_message_queue_add(uint16_t *text, int32_t start_time, int32_t tag);
uint32_t hud_text_message_queue_init(void);
uint32_t hud_text_message_queue_update_and_draw(widget_instance *widget);
void hud_timer_draw(void);
void hud_unit_meter_apply_predictive_damage(datum_index player_index, float damage);
void hud_unit_meters_update(void);
void hud_unit_meters_update_for_player(int16_t local_player_index);
void hud_unit_sounds_play(uint32_t active_mask, const TagReflexive *sounds, int32_t *handles, uint16_t *playing);
void hud_unit_sounds_update(player *p, uint8_t hud_enabled);
void hud_update_dispatch(void);
void hud_update_interaction_prompt(datum_index player_index);
void hud_update_player(void);
void hud_waypoint_activate_for_player(datum_index player_index, datum_index target, int16_t kind, int16_t arrow_index, float vertical_offset);
void hud_waypoint_activate_for_team(datum_index target, int16_t arrow_index, int16_t team, int16_t kind, float vertical_offset);
int16_t hud_waypoint_arrow_find(const char *name);
void hud_waypoint_deactivate_for_player(datum_index player_index, datum_index target, int16_t kind);
void hud_waypoint_deactivate_for_team(int16_t kind, int16_t team, datum_index target);
void hud_waypoint_draw(const real_point3d *position, int16_t local_player_index, int16_t arrow_index, int16_t visibility, uint8_t show_distance);
void hud_waypoint_draw_all_for_player(void);
void hud_waypoint_draw_one(datum_index player_index);
int16_t hud_waypoint_visibility(int16_t local_player_index, const real_point3d *eye, const real_point3d *target, datum_index ignore_object);
void hud_waypoints_draw_for_player(int16_t local_player_index);
void hud_waypoints_update(void);
void hud_waypoints_update_for_player(int16_t local_player_index);
void hud_weapon_crosshairs_draw(datum_index hud_tag, const player *p, const weapon_hud_ammo_state *ammo);
void hud_weapon_interface_draw_elements(datum_index hud_tag, int16_t local_player_index, const Weapon *weapon_tag, const weapon_hud_ammo_state *ammo, const uint16_t *parent_state_flags, const uint16_t *parent_overlay_types, const int16_t *parent_numbers);
void hud_weapon_interface_meters_evaluate(datum_index hud_interface_tag_id, int16_t local_player_index, int32_t weapon_or_vehicle_index, const weapon_hud_ammo_state *state_ptr);
void hud_weapon_interface_state_update(void);
void interface_draw_cursor(void);
void interface_globals_allocate(void);
void interface_handle_quit_request(void);
void interface_loading_screen_reset(void);
void interface_loading_screen_set_text(const char *text);
void interface_local_player_state_reset(void);
void interface_tick(void);
void interface_update_for_resolution_change(int32_t new_cursor_x, int32_t new_cursor_y);
int16_t item_type_to_animation_stage(int16_t message_stage);
int16_t item_type_to_message_stage(int16_t item_type_code);
void list_node_pop(widget_history_node *out, widget_history_node **head);
void list_node_prepend(widget_history_node *template_record, widget_history_node **head);
int32_t local_player_get_weapon_hud_interface(float *out_intensity);
int32_t local_player_index_for_object(datum_index object_index);
int32_t local_player_index_for_unit(datum_index unit_index);
int32_t local_player_index_for_weapon(datum_index weapon_index);
void main_menu_on_shown(int32_t fade_milliseconds);
void main_menu_play_title_music(void);
void map_list_add_entry(char *path, int32_t map_id);
int32_t map_list_find_known_map_index(char *map_path);
void map_list_free_all(void);
void map_list_get_friendly_level_name(wchar_t *destination, char *map_path, int32_t destination_capacity);
void motion_sensor_blip_fill(int16_t local_player_index, datum_index object_index, motion_sensor_blip *blip);
uint8_t motion_sensor_object_is_detected(datum_index unit_index);
void motion_sensor_plot_blip(const float *position, uint8_t type, const motion_sensor_frame *frame, int8_t subtype, float pixels_per_unit, float alpha, float size_factor);
void motion_sensor_render(uint8_t splitscreen, const int16_t *screen_center, int16_t local_player_index);
void __cdecl motion_sensor_reset(void);
void motion_sensor_update_for_player(int16_t local_player_index);
uint8_t multiplayer_host_session_start(void);
void multiplayer_settings_select_list_refresh_3wide(widget_instance *widget);
void multiplayer_settings_select_list_update_item(widget_instance *widget, const uint16_t *record);
uint8_t network_autojoin_from_command_line(void);
void network_clear_player_ready_flags(void);
void network_game_host_start(char *map_name, char *variant_name, uint8_t disconnect_timeout_flag);
void network_game_setup_teardown(void);
uint32_t network_server_reset_game_stats(void);
int16_t object_get_hud_text_message_index(datum_index object_index);
datum_index player_get_vehicle(datum_index player_index);
void player_help_screen_select_by_name(int16_t value);
void player_profile_1wide_list_update(widget_instance *widget);
void player_profile_apply_audio_options(saved_player_profile *profile);
uint8_t player_profile_apply_video_options(saved_player_profile *profile);
void player_profile_auto_select(void);
int32_t player_profile_check_storage_and_defaults(void);
void player_profile_details_widget_refresh(widget_instance *widget, const uint8_t *profile_record);
int16_t player_profile_find_index_by_id(int16_t id);
uint8_t player_profile_get_flag_by_id(int16_t id);
void player_profile_load(int16_t player_index, void *source_profile, int32_t profile_id);
void player_profile_refresh_settings_cache(int16_t player_index);
uint8_t player_profile_save(void);
void player_profile_save_495fb0(uint8_t flag);
void player_profile_select_list_widget_build(widget_instance *widget);
void player_profile_select_list_widget_build_thunk(widget_instance *widget);
void player_profile_subsystem_initialize(void);
void * registry_get_product_id(void);
uint32_t restart_map_dialog_choice_handler(widget_instance *widget);
uint8_t saved_item_has_unsaved_changes(void);
int32_t saved_item_name_changed(void);
uint8_t saved_item_name_edit_begin(void);
uint8_t saved_item_name_matches(wchar_t *name);
void saved_item_select(int32_t item);
uint8_t server_browser_back_event(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t server_browser_button_event(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t server_browser_closed_event(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t server_browser_filter_panel_apply_event(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t server_browser_filter_panel_cancel_event(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t server_browser_hide_widget_event(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t server_browser_list_row_event(widget_instance *widget, int16_t *event, uint8_t *out_handled);
void server_list_menu_update(widget_instance *widget);
void set_profile_name(widget_instance *widget, const uint16_t *name_source);
void string_replace_all_in_place(char *buffer, char *search, char *replacement);
void terminal_initialize(void);
void ui_audio_options_apply_volume_sliders(widget_instance *widget);
uint32_t ui_build_level_select_list(widget_instance *widget, void *param_2, void *param_3);
void ui_build_level_select_list_coop(widget_instance *widget, void *param_2, void *param_3);
uint32_t ui_build_profile_list(widget_instance *widget);
void ui_button_prompt_draw_icon(HUDGlobalsButtonIcon *icon);
int16_t ui_button_prompt_index_from_string(uint16_t *text);
int32_t ui_carousel_slot_compare_valid_first(const int32_t *a, const int32_t *b);
void ui_chat_window_reset_position(void);
uint32_t ui_check_for_pause_game(void);
void ui_controls_4wide_selector_refresh(widget_instance *widget);
uint32_t ui_controls_options_free_list(widget_instance *widget);
uint32_t ui_controls_options_populate_from_profile(widget_instance *widget);
uint8_t ui_controls_options_reload_profile(void);
void ui_controls_populate_bind_rows(widget_instance *widget, uint32_t packed);
void ui_controls_populate_input_row(widget_instance *widget, const saved_player_profile *profile_record);
void ui_controls_populate_sensitivity_row(widget_instance *widget, const saved_player_profile *profile_record);
uint32_t ui_controls_sensitivity_row_refresh(widget_instance *widget, const saved_player_profile *profile_record);
void ui_cursor_update(void);
void ui_draw_filled_rectangle(uint32_t packed_color, Rectangle2D *rect);
void ui_draw_rotated_screen_quad(int16_t *origin, int32_t source_record, float *corner_uvs, float scale, float rotation_radians, float alpha_fraction);
void ui_draw_screen_quad(int16_t *source_rect, int16_t *dest_rect, int32_t bitmap_data, int16_t *clip_rect, uint32_t vertex_color);
void ui_draw_trouble_brewing_indicator(void);
void ui_error_modal_update(void);
uint8_t ui_event_49cdd0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49cfa0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d0d0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d100(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d120(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d140(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d160(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d1a0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d1b0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d440(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d450(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d480(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d520(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d540(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d5b0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d5d0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d5f0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d7a0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49d8b0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49dab0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49dbc0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49dca0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49e170(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49e210(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49e220(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49e2c0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49e300(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49e5d0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49e7e0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49ea50(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49edc0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49f030(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49f300(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49f470(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49f560(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49f610(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49f680(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49f8f0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49fad0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_49fd30(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a02a0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a0590(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a0700(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a07e0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a0860(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a0a80(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a0ae0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a0bc0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a0c00(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a0c60(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a0d60(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a0e90(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a0fb0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a10f0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1180(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a11e0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1280(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a12c0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a12f0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1310(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1480(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1570(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a15e0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1650(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a16a0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a16c0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a16d0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a16e0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1700(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1740(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1790(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1900(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1b00(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1b60(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1bf0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1c80(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1ca0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1cd0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1d00(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1d30(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1d60(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1d90(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a1dc0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a2190(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a21c0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a2490(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a24c0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a2950(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a2a00(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a2c50(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a2c80(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a2f10(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a3000(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a3050(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a3150(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a33a0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a3510(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a3540(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a3790(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a3870(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a39c0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a39e0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a3a70(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a3d40(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a4110(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a4190(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a41a0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a4270(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a44f0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a4570(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a4580(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a45d0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a45f0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a47b0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a4870(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4a4af0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4b4980(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4b4af0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4b4c40(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4b52f0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4b5350(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4b54a0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4b54c0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4bb290(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4bb300(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4bb360(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4bb7e0(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4bb970(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_event_4bba80(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint32_t ui_free_profile_list(widget_instance *widget);
void ui_game_data_input_4a3b70(widget_instance *widget);
void ui_game_data_input_4a4c70(widget_instance *widget);
void ui_game_data_input_4a5740(widget_instance *widget);
void ui_game_data_input_4a6880(widget_instance *widget);
void ui_game_data_input_4a6a60(widget_instance *widget);
void ui_game_data_input_4a6ab0(widget_instance *widget);
void ui_game_data_input_4a6b70(widget_instance *widget);
void ui_game_data_input_4a6d50(widget_instance *widget);
void ui_game_data_input_4a6e50(widget_instance *widget);
void ui_game_data_input_4a6e90(widget_instance *widget);
void ui_game_data_input_4a6f00(widget_instance *widget);
void ui_game_data_input_4a6fa0(widget_instance *widget);
void ui_game_data_input_4a7180(widget_instance *widget);
void ui_game_data_input_4a7210(widget_instance *widget);
void ui_game_data_input_4a7280(widget_instance *widget);
void ui_game_data_input_4a7300(widget_instance *widget);
void ui_game_data_input_4a7340(widget_instance *widget);
void ui_game_data_input_4a7350(widget_instance *widget);
void ui_game_data_input_4a73d0(widget_instance *widget);
void ui_game_data_input_4a7660(widget_instance *widget);
void ui_game_data_input_4a7880(widget_instance *widget);
void ui_game_data_input_4b5ce0(widget_instance *widget);
void ui_game_variant_flag_list_widget_build(widget_instance *widget);
void ui_game_variant_list_widget_build(widget_instance *widget);
ColorRGB * ui_get_saved_color(ColorRGB *out);
ColorARGB * ui_get_saved_pulse_color(ColorARGB *out);
void ui_handler_4a68f0(uint8_t *widget);
void ui_level_carousel_refresh(widget_instance *widget);
void ui_level_carousel_row_refresh(widget_instance *widget, int32_t level_index);
uint8_t ui_level_select_confirm_choice(widget_instance *widget);
void ui_list_add_entry(int32_t group_index, const uint16_t *name, int32_t id, const void *data_blob, uint32_t data_size, uint8_t is_default);
uint8_t ui_list_default_item_format(void *item_buffer, int32_t item_index, void *list_items);
int32_t ui_list_find_default(int32_t group_index);
void ui_list_free_all(void);
void * ui_list_get_data(int32_t index);
int32_t ui_list_get_id(int32_t index);
uint8_t ui_list_item_format_name_and_cache_flag(uint16_t *out_name, int32_t item_index);
int32_t ui_list_widget_compute_scroll_start(widget_instance *widget);
void ui_list_widget_rebuild_rows(widget_instance *widget, ui_list_item_format_function format_item);
void ui_map_list_carousel_refresh_window(widget_instance *widget);
uint8_t ui_map_select_confirm_choice(widget_instance *widget);
void ui_network_adapter_details_refresh(widget_instance *widget);
void ui_network_adapter_list_widget_build(widget_instance *widget);
uint8_t ui_network_client_connect_and_save(void);
uint8_t ui_network_game_options_populate(widget_instance *widget, const saved_player_profile *options_record);
void ui_network_game_options_refresh(widget_instance *widget, const saved_player_profile *options_record);
uint8_t ui_network_host_setup_defaults_init(widget_instance *widget);
void ui_network_host_setup_refresh(widget_instance *widget);
void ui_network_name_fields_refresh(widget_instance *widget);
uint32_t ui_network_name_fields_reset(void);
void ui_network_wait_timeout_check(void);
void ui_network_wait_timeout_start(void);
uint32_t ui_new_profile_name_entry_commit(void);
uint8_t ui_new_profile_name_entry_open(void *widget, int16_t *event, uint8_t *out_handled);
void ui_profile_carousel_fetch_name(widget_instance *widget);
void ui_profile_carousel_fetch_sensitivity(widget_instance *widget);
void ui_profile_carousel_slot_cache_populate(int32_t count, const int32_t *candidate_ids);
void ui_profile_details_list_widget_build(widget_instance *widget);
uint8_t ui_profile_list_apply_selection(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint32_t ui_profile_list_apply_selection_for_player(widget_instance *widget, int16_t *context);
uint8_t ui_profile_require_existing(void *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_profile_select_or_create(void *widget, int16_t *event, uint8_t *out_handled);
int32_t ui_real_to_int_truncate(float value);
void * ui_replace_empty(widget_instance *widget);
void * ui_replace_player_number(widget_instance *widget);
void * ui_replace_product_id(widget_instance *widget);
void * ui_replace_version(widget_instance *widget);
uint32_t ui_restart_saved_game(void);
const uint16_t * ui_search_replace_function_call(int16_t index, widget_instance *widget);
void ui_selection_list_mirror_value_build(widget_instance *widget);
uint8_t ui_server_list_connect_selected(widget_instance *widget, int16_t *event, uint8_t *out_handled);
uint8_t ui_server_type_option_selected(widget_instance *widget);
uint32_t ui_start_campaign_from_level_one(void *widget, int16_t *event);
uint8_t ui_string_has_button_prompt_token(uint16_t *text);
int32_t ui_string_replace_all(wchar_t *search, uint16_t *replacement, wchar_t **buffer);
void ui_tab_group_sync_5wide(widget_instance *widget);
void ui_tab_group_sync_7wide(widget_instance *widget);
void ui_tab_group_sync_9wide(widget_instance *widget);
void ui_tab_group_sync_grouped(widget_instance *widget);
void ui_variant_carousel_slot_cache_populate(int32_t *candidate_ids, int32_t count);
uint8_t ui_variant_name_is_available(const uint16_t *name);
uint8_t ui_wide_string_has_non_whitespace(const uint16_t *text);
void ui_widget_draw_formatted_prompt_string(Rectangle2D *bounds, uint8_t use_text_color, const uint16_t *text);
void ui_widget_draw_prompt_span(const uint16_t *text, Rectangle2D *cursor, Rectangle2D *origin);
void ui_widget_list_item_activate(widget_instance *widget, UIWidgetDefinition *tag, int16_t *event, EventHandlerReference *handler, uint8_t *out_handled);
void ui_widget_sync_profile_status_flag(widget_instance *widget);
void ui_widget_text_ensure_and_refresh(widget_instance *widget);
void ui_widget_text_from_hud_objective(widget_instance *widget);
uint8_t unit_get_first_person_marker_transform(datum_index object_index, const char *marker_name, real_point3d *out_position, real_vector3d *out_extents, real_vector3d *out_direction);
void video_display_modes_enumerate(uint32_t format);
void video_options_menu_populate(widget_instance *screen, const saved_player_profile *profile);
uint8_t video_options_menu_update(widget_instance *screen);
uint8_t video_options_reset_to_defaults(widget_instance *button);
uint32_t __cdecl video_refresh_rate_compare(const uint32_t *a, const uint32_t *b);
uint32_t video_refresh_rate_find_index(int32_t resolution_index, int32_t refresh_rate);
void video_resolution_add(int32_t height, int32_t width, int32_t refresh_rate);
int __cdecl video_resolution_compare(const video_resolution *a, const video_resolution *b);
void __cdecl video_resolution_list_build(void);
void virtual_keyboard_backspace(void);
uint8_t virtual_keyboard_character_is_legal(int32_t validation_mode, uint8_t character);
uint8_t virtual_keyboard_close(void);
void virtual_keyboard_draw_text(Rectangle2D *bounds);
int32_t virtual_keyboard_initialize(void);
uint8_t virtual_keyboard_open(uint16_t *destination, uint16_t maximum_length, int16_t field_kind);
void virtual_keyboard_process_input(void);
void virtual_keyboard_render(void);
void weapon_action_notify_for_unit(datum_index unit_index, int32_t action_code);
void weapon_action_notify_for_weapon(datum_index weapon_index, int32_t action_code);
uint8_t weapon_hud_ammo_state_is_empty(const weapon_hud_ammo_state *state);
void widget_close(widget_instance *widget);
void widget_close_all(void);
void widget_column_list_sync_selected(widget_instance *widget);
uint8_t widget_create_children_from_tag(widget_instance *widget, UIWidgetDefinition *tag);
int32_t widget_cursor_side_of_midpoint(widget_instance *widget);
uint32_t widget_cyclable_list_nudge(widget_instance *widget);
void widget_draw_fullscreen_region(int16_t controller_index);
void widget_draw_split_screen_region(Rectangle2D *viewport, int16_t controller_index);
void widget_extended_description_sync_selection(widget_instance *widget);
widget_instance * widget_find_by_tag_id(widget_instance *widget, datum_index tag_id);
void widget_focus_next_child(widget_instance *widget);
void widget_focus_previous_child(widget_instance *widget);
int32_t widget_get_sibling_index(widget_instance *widget);
void widget_initialize_from_tag(widget_instance *widget, datum_index tag_index, widget_instance *parent, uint16_t controller_index, UIWidgetDefinition *tag);
void widget_instance_close_and_restore_previous(widget_instance *widget);
widget_instance * widget_instance_find_at_point(widget_instance *widget, int32_t cursor_x, int32_t cursor_y, int32_t offset_xy);
widget_instance * widget_instance_find_root(widget_instance *widget);
float widget_instance_get_cumulative_scale(widget_instance *widget);
void widget_instance_handle_input_event(widget_instance *widget, UIWidgetDefinition *tag, int16_t *event, uint8_t *out_handled);
uint8_t widget_instance_is_input_eligible(widget_instance *widget);
uint8_t widget_instance_is_top_of_stack(widget_instance *widget);
uint8_t widget_instance_point_in_bounds(widget_instance *widget);
void widget_instance_relink_focus(widget_instance *widget, widget_instance *child);
void widget_instance_render(widget_instance *widget, Rectangle2D *dest, int32_t offset_xy, uint32_t flag1, int32_t flag2);
void widget_instance_render_column_list_items(widget_instance *widget, UIWidgetDefinition *tag, Rectangle2D *dest, int32_t offset_xy, uint32_t flags);
void widget_instance_render_list_head(widget_instance *widget, UIWidgetDefinition *tag, Rectangle2D *dest, int32_t offset_xy, uint8_t is_top_of_stack);
void widget_instance_render_text_box(widget_instance *widget, UIWidgetDefinition *tag, Rectangle2D *dest, int32_t offset_xy, uint8_t is_top_of_stack);
void widget_instance_select_list_index(widget_instance *widget, datum_index list_definition, int32_t selection);
void widget_instance_set_state_recursive(widget_instance *widget, uint8_t state);
uint8_t widget_instance_verify_stack_chain(widget_instance *node);
void widget_list_adjust_rect_for_scroll_arrows(widget_instance *widget, Rectangle2D *rect);
widget_instance * widget_list_get_child_by_index(widget_instance *list, int32_t index);
void widget_list_scroll_window(int32_t out[3], widget_instance *widget);
uint8_t widget_list_select_next(widget_instance *widget);
uint8_t widget_list_select_previous(widget_instance *widget);
void widget_memory_pool_initialize(void);
void widget_play_sound_effect(int16_t effect_id);
void widget_play_sound_effect_tag(datum_index sound_tag);
void widget_pool_list_free_all(widget_history_node **head);
void widget_relink_focus_by_tag_id(widget_instance *widget, datum_index child_definition);
widget_instance * widget_reopen_as_root_with_history(widget_instance *widget, datum_index open_tag);
void widget_spinner_list_sync_selected(widget_instance *widget, UIWidgetDefinition *tag);
void widget_text_edit_clamp_selection(text_edit_state *state);
uint32_t widget_text_edit_get_selection(text_edit_state *state, int16_t *out_start, int16_t *out_end);
void widget_text_edit_insert_string(text_edit_state *state, char *insert_str);
void widget_text_edit_process_key(text_edit_state *state, ui_key_event *event);
void widget_text_edit_reset_length(text_edit_state *state);

}
