#pragma once

/**
 * @file src/rasterizer/internal/state.hpp
 * Shared declarations for the rasterizer implementation files: the engine globals and external functions
 * (C linkage) and the prototypes of the halo::rasterizer implementation functions.
 */

#include "win32.h"
#include "tags.h"
#include "memory.h"
#include "math.h"
#include "rasterizer.h"
#include "render.h"
#include "interface.h"
#include <string.h>
#include "cache.h"
#include "objects.h"
#include "units.h"
#include <stdint.h>
#include "effects.h"
#include "crt.h"
#include <wchar.h>
#include <stdlib.h>
#include "game.h"
#include <stdio.h>
#include "bitmaps.h"
#include "halo/rasterizer/render_device.hpp"
#include "halo/memory/api.hpp"
#include "halo/cache/api.hpp"

extern "C" {

extern int8_t bitmap_format_bits_per_pixel[];
extern cinematic_screen_effect_globals *cinematic_screen_effect_state;
extern float rasterizer_default_z_near;
extern rasterizer_frame_time rasterizer_time;
extern d3d_caps9 rasterizer_caps;
extern uint8_t unknown_0071d275;
extern uint8_t unknown_0071d276;
extern uint8_t decals_for_all_responses;
extern uint8_t *rasterizer_decal_vertex_cache_handle;
extern uint8_t text_rendering_enabled;
extern rasterizer_window_parameters rasterizer_window;
extern font_glyph_cache g_font_glyph_cache;
extern int32_t rasterizer_frame_index;
extern int16_t render_viewport_top[2];
extern int16_t render_viewport_bottom[2];
extern int16_t screen_safe_area_right[2];
extern int16_t screen_safe_area_bottom[2];
extern uint8_t rasterizer_gamma_disabled;
extern int32_t rasterizer_gamma_captured;
extern int32_t rasterizer_gamma_exponent;
extern d3d_gamma_ramp rasterizer_game_gamma_ramp;
extern uint8_t rasterizer_gamma_high_bit_17;
extern uint8_t rasterizer_fullscreen;
extern void *rasterizer_device;
extern HWND rasterizer_window_handle;
extern void *rasterizer_misc_vertex_buffer;
extern transparent_geometry_group *transparent_geometry_groups;
extern transparent_geometry_group *transparent_geometry_groups_secondary;
extern int16_t *transparent_geometry_group_sorted_indices;
extern int32_t transparent_geometry_group_count;
extern int32_t transparent_geometry_group_secondary_count;
extern uint8_t rasterizer_software_vertex_processing;
extern rasterizer_vertex_declaration rasterizer_vertex_declarations[k_rasterizer_vertex_type_count];
extern int16_t rasterizer_vertex_sizes[k_rasterizer_vertex_type_count];
extern rasterizer_dynamic_index_slot rasterizer_dynamic_index_slots[k_rasterizer_dynamic_vertex_slots];
extern void *rasterizer_dynamic_index_buffer;
extern void *rasterizer_scratch_memory;
extern uint32_t rasterizer_scratch_memory_used;
extern uint32_t rasterizer_blend_src_table[16];
extern uint32_t rasterizer_blend_dest_table[16];
extern uint32_t rasterizer_blend_op_table[16];
extern float g_007c1228;
extern float g_007c122c;
extern float g_007c1230;
extern float g_007c1234;
extern float g_007c1238;
extern float g_007c123c;
extern float g_007c1290;
extern float g_007c1294;
extern float g_007c1298;
extern float g_007c129c;
extern float g_007c12a0;
extern float g_007c12a4;
extern float g_007c12a8;
extern float g_007c12ac;
extern float g_007c12b0;
extern float g_007c12b4;
extern float g_007c12b8;
extern float g_007c12bc;
extern float g_007c12c4;
extern float g_007c12c8;
extern float g_007c12cc;
extern float g_007c12d0;
extern float g_007c12d4;
extern float g_007c12d8;
extern float g_007c13c0[16];
extern float g_007c13d0;
extern float g_007c13d4;
extern float g_007c13e0;
extern float g_007c13e4;
extern float g_007c13f0;
extern int16_t rasterizer_maximum_skinning_nodes;
extern rasterizer_skinning_matrix rasterizer_skinning_palette[63];
extern GlobalsRasterizerData *rasterizer_globals_data;
extern uint8_t console_debug_toggle_689409;
extern int16_t rasterizer_bound_bitmap_size_a[2];
extern uint8_t *rasterizer_node_part_indices;
extern int32_t rasterizer_node_part_count;
extern d3d_gamma_ramp rasterizer_desktop_gamma_ramp;
extern int32_t shell_argc;
extern char **shell_argv;
extern int32_t safe_mode;
extern float rasterizer_ui_text_constants[20];
extern Globals *global_globals;
extern lens_flare_object_visibility lens_flare_object_visibility_table[k_lens_flare_object_visibility_slots];
extern uint8_t lens_flare_marker_visibility[0x10008];
extern int32_t lens_flare_instance_count;
extern float *rasterizer_model_ambient_reflection_tint;
extern data_array *decal_data;
extern datum_index decal_vertex_cache_last_queried;
extern d3d_display_mode rasterizer_desktop_display_mode;
extern d3d_present_parameters rasterizer_present_parameters;
extern int32_t os_platform;
extern uint8_t unknown_006893ff;
extern int16_t unknown_00719aac;
extern int16_t screenshot_scale;
extern lens_flare_instance lens_flare_instances[0x400];
extern uint8_t lens_flare_instance_overflow;
extern uint8_t lens_flare_occlusion_queries_supported;
extern void *rasterizer_effect_pool_scratch;
extern int16_t unknown_00746fbc;
extern uint8_t rasterizer_caps_flag_68a;
extern uint8_t unknown_00689426;
extern rasterizer_dynamic_vertex_cache rasterizer_dynamic_vertex_caches[k_rasterizer_vertex_type_count];
extern int32_t rasterizer_dynamic_vertex_slot_count;
extern int32_t rasterizer_dynamic_index_count;
extern int32_t rasterizer_dynamic_index_slot_count;
extern uint32_t unknown_0071d160;
extern uint32_t transparent_geometry_group_drawn_bits[12];
extern int32_t rasterizer_light_count;
extern uint16_t unknown_0071d1b4;
extern uint8_t rasterizer_render_target_capture_done;
extern uint8_t rasterizer_render_target_capture_requested;
extern uint8_t console_debug_toggle_6893e4;
extern uint8_t console_debug_toggle_6893e6;
extern int8_t renderer_texture_quality;
extern int32_t rasterizer_bitmap_format_to_d3dformat[];
extern int16_t rasterizer_cube_face_to_d3d_face[6];
extern uint8_t unknown_0071d18d;
extern uint32_t screenshots;
extern void *shell_window;
extern uint8_t video_force_mode_flag;
extern uint32_t game_time_force_single_tick;
extern uint8_t rasterizer_device_lost;
extern uint8_t rasterizer_pending_clear;
extern uint32_t game_window_top_left;
extern uint32_t game_window_bottom_right;
extern int32_t rasterizer_present_counter_low;
extern int32_t rasterizer_present_counter_high;
extern void *shell_window_proc;
extern uint32_t rasterizer_window_style;
extern void *shell_instance;
extern char shell_window_class_name[];
extern char shell_window_title[];
extern void *rasterizer_window_icon_bitmap;
extern void *rasterizer_window_icon_dc;
extern int16_t rasterizer_decal_layer;
extern int16_t rasterizer_decal_blend_mode;
extern int16_t rasterizer_decal_bitmap_frame;
extern uint32_t rasterizer_decal_bitmap_tag;
extern uint8_t unknown_0071d1c4;
extern uint8_t console_debug_toggle_689441;
extern void *rasterizer_decal_vertex_cache;
extern int16_t rasterizer_vertex_buffer_lock_state;
extern uint32_t *decal_grid_block;
extern rasterizer_vertex_shader rasterizer_vertex_shaders[k_rasterizer_vertex_shaders];
extern uint8_t *game_state_base;
extern int32_t game_state_cursor;
extern uint32_t game_state_crc;
extern void *rasterizer_detail_object_vertex_buffer;
extern uint8_t console_debug_toggle_689404;
extern float console_debug_value_689430;
extern Scenario *global_scenario;
extern ScenarioStructureBSP *global_structure_bsp;
extern int32_t rasterizer_vertex_buffer_slot_high_water;
extern rasterizer_vertex_buffer_slot rasterizer_vertex_buffer_slots[k_rasterizer_vertex_buffer_slots];
extern void *lens_flare_occlusion_queries[k_lens_flare_occlusion_queries];
extern void *rasterizer_effect_pool;
extern d3dx_macro rasterizer_effect_defines[2];
extern rasterizer_effect_slot rasterizer_effects[k_rasterizer_pixel_shader_effects];
extern const char *rasterizer_shader_file_name;
extern int32_t config_force_shader;
extern const d3d_vertex_element9 vertex_elements_environment_uncompressed[];
extern const d3d_vertex_element9 vertex_elements_environment_lightmap[];
extern const d3d_vertex_element9 vertex_elements_model[];
extern const d3d_vertex_element9 vertex_elements_dynamic[];
extern const d3d_vertex_element9 vertex_elements_dynamic_screen[];
extern const d3d_vertex_element9 vertex_elements_debug[];
extern const d3d_vertex_element9 vertex_elements_decal[];
extern const d3d_vertex_element9 vertex_elements_detail_object[];
extern const d3d_vertex_element9 vertex_elements_environment_uncompressed_ff[];
extern const d3d_vertex_element9 vertex_elements_environment_lightmap_ff[];
extern const d3d_vertex_element9 vertex_elements_model_ff[];
extern const d3d_vertex_element9 vertex_elements_model_processed[];
extern const d3d_vertex_element9 vertex_elements_unlit_zsprite[];
extern const d3d_vertex_element9 vertex_elements_screen_transformed_lit[];
extern const d3d_vertex_element9 vertex_elements_screen_transformed_lit_specular[];
extern const d3d_vertex_element9 vertex_elements_environment_single_stream_ff[];
extern uint32_t rasterizer_triangle_buffer_primitive_types[2];
extern int32_t rasterizer_vertex_buffer_slot_count;
extern rasterizer_dynamic_vertex_slot rasterizer_dynamic_vertex_slots[k_rasterizer_dynamic_vertex_slots];
extern uint8_t rasterizer_dynamic_index_overflow;
extern uint8_t console_debug_toggle_6893f7;
extern int16_t render_force_flag;
extern uint8_t rasterizer_dynamic_vertex_overflow;
extern void *chat_gui_root_handle;
extern void *(*unknown_00721ea0)(void *hwnd, void *device, uint32_t a, uint32_t b, uint32_t c, uint32_t d, uint32_t e);
extern uint32_t keystone_current_directory;
extern void *chat_gui_find_object_arg;
extern void *chat_listbox_gui_find_object_arg;
extern int32_t (*unknown_00721eb4)(void *engine, void *path, void *key, uint32_t flags, void *rect, uint32_t a, uint32_t b, uint32_t c, uint32_t d, uint32_t e, uint32_t f);
extern int32_t (*unknown_00721eb8)(void *engine, void *key);
extern void (*unknown_00721edc)(int32_t document, uint32_t a);
extern void (*unknown_00721ec8)(int32_t document);
extern rasterizer_render_target rasterizer_render_targets[k_rasterizer_render_targets];
extern int16_t rasterizer_active_render_target;
extern void *rasterizer_render_target_vertex_buffer;
extern void *rasterizer_render_target_index_buffer;
extern uint8_t rasterizer_frame_started;
extern uint8_t rasterizer_in_scene;
extern uint8_t chat_dialog_open;
extern int32_t (*unknown_00721ebc)(void *engine);
extern int32_t rasterizer_ui_render_failed;
extern uint8_t console_debug_toggle_6893f4;
extern uint8_t console_debug_toggle_68941d;
extern uint8_t rasterizer_fog_enabled;
extern int32_t video_gamma_current;
extern uint32_t rasterizer_frustum_z_values[2];
extern real_matrix4x3 *k_render_identity_matrix_ptr;
extern uint32_t rasterizer_depth_prepass_vertex_shader;
extern void *rasterizer_capture_surfaces[4];
extern void *rasterizer_glass_draw_procedures[3];
extern int16_t rasterizer_bound_bitmap_size_b[2];
extern void *rasterizer_direct3d;
extern uint8_t rasterizer_caps_flag_688;
extern uint8_t rasterizer_caps_flag_689;
extern uint32_t rasterizer_device_type;
extern int16_t rasterizer_texture_stage_count;
extern uint32_t d3d_adapter;
extern uint8_t rasterizer_use_fx_file;
extern void *shell_direct3d;
extern void *(__stdcall *direct3d_create9_procedure)(uint32_t sdk_version);
extern int32_t rasterizer_window_requested;
extern int32_t windowed;
extern int32_t checkfpu;
extern int32_t width640;
extern uint32_t physical_memory;
extern uint32_t cpu_speed;
extern uint32_t graphics_device_id;
extern uint32_t graphics_vendor_id;
extern uint32_t video_memory;
extern uint32_t required_video_memory;
extern void (*unknown_00721eac)(void *engine);
extern lens_flare_batch_key lens_flare_applied_key;
extern lens_flare_batch lens_flare_batches[k_lens_flare_batch_slots];
extern lens_flare_batch_key lens_flare_current_key;
extern uint32_t lens_flare_batch_clock;
extern uint8_t console_debug_toggle_689425;
extern void *unknown_0069da10;
extern uint32_t lens_flare_vertex_specular;
extern uint8_t console_debug_toggle_689424;
extern uint8_t transparent_geometry_group_overflow_d;
extern uint8_t console_debug_toggle_6893f3;
extern rasterizer_light rasterizer_lights[k_rasterizer_maximum_lights];
extern uint8_t rasterizer_default_material[0x44];
extern int32_t rasterizer_fixed_function_light_count;
extern uint32_t unknown_006e1b58;
extern uint8_t console_debug_toggle_6893ec;
extern uint8_t console_debug_toggle_689421;
extern rasterizer_model_draw_context *rasterizer_active_model_context;
extern uint8_t rasterizer_model_scratch_valid;
extern uint8_t unknown_0071d1fb;
extern uint8_t unknown_0071d1fc;
extern uint8_t unknown_0071d1fd;
extern int16_t rasterizer_active_model_mode;
extern float unknown_007c047c;
extern uint8_t console_debug_toggle_689403;
extern uint8_t rasterizer_motion_sensor_ready;
extern player_globals *local_player_globals;
extern const float rasterizer_identity_vertex_constants[5][4];
extern uint8_t console_debug_toggle_6893f2;
extern uint8_t console_debug_toggle_68941f;
extern ColorRGB rasterizer_object_shadow_color;
extern float rasterizer_object_shadow_radius;
extern real_matrix4x3 rasterizer_object_shadow_projection;
extern rasterizer_model_draw_context *rasterizer_object_shadow_model_context;
extern uint8_t rasterizer_object_shadow_prepared;
extern uint8_t rasterizer_object_shadow_model_active;
extern uint8_t rasterizer_object_shadow_window_restored;
extern uint8_t console_debug_toggle_68941e;
extern rasterizer_dynamic_screen_vertex rasterizer_object_shadow_blur_quad[4];
extern rasterizer_screen_vertex rasterizer_object_shadow_border_lines[8];
extern uint8_t unknown_0071d1b0;
extern uint8_t rasterizer_needs_reset;
extern float unknown_00689418;
extern uint32_t renderer_unknown_69c684;
extern ColorRGB zoom_static_tint_r;
extern uint8_t console_debug_toggle_6893f6;
extern int16_t rasterizer_projected_light_shader_variant;
extern float rasterizer_projected_light_luminance;
extern rasterizer_projected_light_constants rasterizer_projected_light;
extern uint8_t rasterizer_projected_light_has_cube_map;
extern uint32_t rasterizer_projected_light_cube_map;
extern uint8_t console_debug_toggle_689422;
extern float rasterizer_screen_quad_vertices[4][6];
extern uint8_t unknown_006893f6;
extern uint8_t unknown_006893f7;
extern uint8_t unknown_006893f8;
extern uint8_t console_debug_toggle_6893f9;
extern uint8_t unknown_006893fd;
extern uint8_t unknown_0068941d;
extern int16_t unknown_0069c640;
extern int16_t unknown_0069c642;
extern int16_t unknown_0069c63e;
extern int16_t game_screen_rect;
extern int16_t rasterizer_bound_bitmap_size_c[2];
extern uint32_t screen_effect_techniques[k_rasterizer_screen_effect_techniques];
extern uint8_t console_debug_toggle_689428;
extern rasterizer_dynamic_screen_vertex rasterizer_screen_effect_quad[4];
extern void *screen_flash_techniques[6];
extern void *rasterizer_screen_flash_effect;
extern uint8_t console_debug_toggle_689427;
extern void *unknown_007c048c;
extern void *unknown_007c0490;
extern void *unknown_007c0494;
extern void *rasterizer_water_draw_procedure;
extern uint8_t console_debug_toggle_689407;
extern uint8_t console_debug_toggle_689408;
extern uint8_t console_debug_toggle_6893fc;
extern const ColorRGB *global_white_color;
extern uint8_t unknown_006893ef;
extern int16_t rasterizer_shader_stage_config;
extern uint8_t console_debug_toggle_6893fa;
extern int32_t environment_techniques_multipurpose[24];
extern int32_t environment_techniques_no[12];
extern int32_t environment_techniques_self_illumination[24];
extern int32_t environment_techniques_plain[12];
extern int32_t environment_techniques_reflection[24];
extern int32_t environment_techniques_change_color[24];
extern const char rasterizer_shader_technique_name_suffixes[][0x80];
extern void *shader_environment_draw_simple;
extern void *shader_environment_draw;
extern uint32_t rasterizer_device_version;
extern float rasterizer_camera_position[3];
extern float rasterizer_camera_forward[3];
extern uint8_t rasterizer_fog_flags;
extern ColorRGB rasterizer_fog_atmospheric_color;
extern float rasterizer_fog_atmospheric_max_density;
extern float rasterizer_fog_atmospheric_min_distance;
extern float rasterizer_fog_atmospheric_max_distance;
extern float rasterizer_fog_plane[4];
extern ColorRGB rasterizer_fog_planar_color;
extern rasterizer_effect_slot environment_effect_slot;
extern uint32_t environment_techniques_ps14[];
extern uint32_t rasterizer_model_vertex_declaration;
extern uint8_t rasterizer_lightmap_bitmap_missing;
extern BitmapData *rasterizer_lightmap_bitmap;
extern uint8_t unknown_006e0a04;
extern BitmapData *rasterizer_environment_lightmap;
extern uint8_t console_debug_toggle_6893f1;
extern uint8_t console_debug_toggle_68941c;
extern uint8_t console_debug_toggle_6893f8;
extern rasterizer_effect_slot *rasterizer_active_environment_effect;
extern uint8_t rasterizer_environment_lightmap_missing;
extern uint8_t rasterizer_camouflage_fade_active;
extern float rasterizer_camouflage_fade;
extern float rasterizer_model_effect_vector[4];
extern int16_t rasterizer_transparent_vertex_shader_table[];
extern const int16_t rasterizer_first_map_bitmap_types[4];
extern const uint32_t rasterizer_first_map_address_modes[4];
extern int16_t rasterizer_transparent_extended_vertex_shader_table[];
extern const int16_t rasterizer_extended_first_map_bitmap_types[4];
extern const uint32_t rasterizer_extended_first_map_address_modes[4];
extern uint32_t rasterizer_chicago_color_function_stage_states[][3];
extern uint8_t console_debug_toggle_689423;
extern rasterizer_dynamic_screen_vertex rasterizer_shadow_screen_quad[4];
extern const float rasterizer_sun_glow_blur_offsets[8][4];
extern uint8_t console_debug_toggle_6893ed;
extern transparent_geometry_group transparent_geometry_group_environment_immediate;
extern uint8_t transparent_geometry_group_overflow_c;
extern uint8_t model_render_first_person;
extern int32_t transparent_geometry_group_last_drawn_key;
extern uint8_t rasterizer_secondary_groups_drawn;
extern uint8_t rasterizer_render_states_dirty;
extern void *rasterizer_model_scratch_node_matrices;
extern int16_t rasterizer_model_scratch_node_count;
extern void *rasterizer_model_scratch_lighting;
extern void *rasterizer_model_scratch_function_source;
extern uint8_t console_debug_toggle_6893eb;
extern int16_t debug_print_enabled_flag;
extern float console_debug_meter_period;
extern float console_debug_meter_values[4];
extern uint8_t rasterizer_widescreen_camouflage_scale;
extern uint8_t unknown_0071d1fa;
extern uint8_t console_debug_toggle_6893fb;
extern transparent_geometry_group transparent_geometry_group_immediate;
extern uint8_t transparent_geometry_group_overflow_b;
extern uint8_t transparent_geometry_group_overflow_a;
extern uint8_t console_debug_toggle_689400;
extern float renderer_unknown_68940c;
extern float rasterizer_underwater_tint_jitter_r;
extern float rasterizer_underwater_tint_jitter_g;
extern float rasterizer_underwater_tint_jitter_b;
extern uint8_t rasterizer_underwater_material[0x44];
extern uint8_t rasterizer_water_enabled;
extern float water_fade_plane_distance;
extern float water_fade_factor_a;
extern float water_fade_factor_b;
extern uint32_t renderer_unknown_6e1af8;
extern float rasterizer_water_ripple_quad[4][6];
extern int16_t render_window_index;
extern uint32_t text_shadow_color_argb;
extern uint8_t font_glyph_cache_slots[];
extern int16_t transparent_geometry_group_draw_cursor;

}  // extern "C"

#include "halo/rasterizer/api.hpp"
