"""Maintenance tool (never part of a build): regenerates the committed build inputs under standalone/frozen/ from the
retail binary bin/halo.exe and the Ghidra export out/functions.json.

The standalone build reads only those committed files (see tools/retail_guard.py); run this only when a change to
src/ needs something new from the retail image:
  - a new C function that retail DATA tables point at (code_pointer_slots.json only lists slots whose target was known
    when it was last frozen),
  - a new code_address_<fn> thunk (its ret byte count, code_address_ret.json),
or to rebuild build/standalone/halo_image.bin, the retail image tools/verify_image_source.py compares the linked data
image with. The data image itself (standalone/image/*.asm) is regenerated by tools/gen_image_source.py.
Usage: python tools/freeze_retail_inputs.py"""
import bisect, glob, json, os, re, struct, subprocess, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "harness"))
import retail_guard as rg
from gen_standalone import rewritten_functions

ROOT = rg.ROOT
OUT = os.path.join(ROOT, "build", "standalone")
EXE = os.path.join(ROOT, "bin", "halo.exe")


def pe_layout(exe):
    pe = struct.unpack_from("<I", exe, 0x3c)[0]
    nsec = struct.unpack_from("<H", exe, pe + 6)[0]
    opt = pe + 24
    optsize = struct.unpack_from("<H", exe, pe + 20)[0]
    base = struct.unpack_from("<I", exe, opt + 28)[0]
    dirs = [struct.unpack_from("<II", exe, opt + 96 + 8 * i) for i in range(16)]
    sections = []
    for i in range(nsec):
        o = opt + optsize + 40 * i
        name = exe[o:o + 8].rstrip(b"\0").decode()
        vsize, va, rsize, raw = struct.unpack_from("<IIII", exe, o + 8)
        sections.append({"name": name, "va": base + va, "vsize": vsize, "raw": raw, "rsize": rsize})
    return base, dirs, sections


def reader(exe, base, sections):
    def off(va):
        for s in sections:
            if s["va"] <= va < s["va"] + max(s["vsize"], s["rsize"]):
                d = va - s["va"]
                return s["raw"] + d if d < s["rsize"] else None
        return None
    def u32(va):
        o = off(va)
        return None if o is None else struct.unpack_from("<I", exe, o)[0]
    def cstr(va):
        o = off(va)
        return exe[o:exe.index(b"\0", o)].decode("latin-1")
    return off, u32, cstr


def imports(exe, base, dirs, u32, cstr):
    slots = []
    va, size = dirs[1]
    d = base + va
    while True:
        oft, _, _, name, ft = [u32(d + 4 * k) for k in range(5)]
        if not name:
            break
        dll = cstr(base + name)
        lookup, iat = base + (oft or ft), base + ft
        k = 0
        while True:
            e = u32(lookup + 4 * k)
            if not e:
                break
            sym = ("#%d" % (e & 0xffff)) if e & 0x80000000 else cstr(base + e + 2)
            slots.append({"slot": iat + 4 * k, "dll": dll, "name": sym, "delay": False})
            k += 1
        d += 20
    va, size = dirs[13]                         # delay-load directory (VC7 layout: attributes bit 0 = RVAs)
    d = base + va
    while True:
        attrs, name, hmod, iat, int_, bound, unload, stamp = [u32(d + 4 * k) for k in range(8)]
        if not name:
            break
        rel = base if attrs & 1 else 0
        dll = cstr(rel + name)
        k = 0
        while True:
            e = u32(rel + int_ + 4 * k)
            if not e:
                break
            sym = ("#%d" % (e & 0xffff)) if e & 0x80000000 else cstr(rel + e + 2)
            slots.append({"slot": rel + iat + 4 * k, "dll": dll, "name": sym, "delay": True,
                          "module_handle_slot": rel + hmod})
            k += 1
        d += 32
    return slots


def extract_retail():
    """reads bin/halo.exe and out/functions.json: writes halo_image.bin and refreshes the frozen build inputs"""
    exe = open(EXE, "rb").read()
    base, dirs, sections = pe_layout(exe)
    off, u32, cstr = reader(exe, base, sections)
    sec = {s["name"]: s for s in sections}

    # ---- data image: .rdata then .data (initialised part); .bss is the zero tail of .data's virtual size
    rdata, data = sec[".rdata"], sec[".data"]
    blob = b""
    pieces = []
    # .text goes in too, but only as data: the loader maps it without execute permission, so tables the compiler put in
    # the code section (jump tables, handler arrays) read correctly and any jump into original code faults (DEP) at an
    # address that names the original function
    for name in (".text", ".rdata", ".data", ".tls", ".rsrc"):
        if name not in sec:
            continue
        s = sec[name]
        pieces.append({"name": name, "va": s["va"], "blob_offset": len(blob), "raw": s["rsize"], "virtual": s["vsize"]})
        blob += exe[s["raw"]:s["raw"] + s["rsize"]]
    open(os.path.join(OUT, "halo_image.bin"), "wb").write(blob)
    layout = {"image_base": base, "entry": base + struct.unpack_from("<I", exe, struct.unpack_from("<I", exe, 0x3c)[0] + 40)[0],
              "pieces": pieces,
              "tls_directory": base + dirs[9][0] if dirs[9][1] else None,
              "tls_section": {"va": sec[".tls"]["va"], "virtual": sec[".tls"]["vsize"]} if ".tls" in sec else None,
              "resources": {"va": sec[".rsrc"]["va"], "size": sec[".rsrc"]["vsize"]} if ".rsrc" in sec else None,
              "reserve": {"from": rdata["va"], "to": max(s["va"] + s["vsize"] for s in sections)}}

    # ---- import slots the loader fills
    slots = imports(exe, base, dirs, u32, cstr)
    slot_set = {s["slot"] for s in slots}

    # ---- code pointers stored in data
    # data ranges whose dwords only coincidentally equal a function start: never patched (a patch would corrupt them)
    NOT_CODE_POINTER_RANGES = [
        # int16 LR parser tables read by library code at 0x5a6600..0x5a7420 (0x679600, 0x679848, 0x679a90,
        # 0x679e50, 0x679f38, 0x67a6b8, 0x67a7a0, 0x67c1e8 ...); the shorts 0x0000 0x0057 at 0x679d54 equal the
        # entry 0x570000 (2026-09-28)
        (0x679600, 0x67d000),
        # DIDATAFORMAT at 0x0064dfdc (pushed at 0x491930 for SetDataFormat): its rgodf field 0x64dff0 points at the
        # DIOBJECTDATAFORMAT array the linker placed in .text at 0x613400 -- data, which the loader maps with .text
        # (2026-09-28)
        (0x64dff0, 0x64dff4),
    ]
    # Code pointers that are real but can never be followed in the standalone. catch(...) handler addresses in the
    # __CxxFrameHandler HandlerType arrays of the retail hwreq C++ functions (std::map / std::vector helpers at
    # 0x57bf00..0x57cf00): the CRT only reaches them while unwinding through those retail frames, and their C versions
    # register no EH frames. They are EBP-based funclets of the parent frame (e.g. 0x57c743 reads [ebp+0x8]), so they
    # cannot have C of their own. (2026-09-28)
    DEAD_CODE_POINTER_SLOTS = {
        0x673648: 0x57c7e2, 0x673658: 0x57c743, 0x6736e8: 0x57ccc4, 0x6737d0: 0x57ced1,
        0x673990: 0x57bfec, 0x6739a0: 0x57c0a8,
    }
    funcs = {int(f["addr"], 16): f for f in json.load(open(os.path.join(ROOT, "out", "functions.json")))}
    library_ranges = sorted((int(f["addr"], 16), int(f["addr"], 16) + (f.get("size") or 0))
                            for f in funcs.values() if f.get("lib") or f.get("fid"))

    function_starts = sorted(funcs)

    def inside_library_function(v):
        i = bisect.bisect_right(library_ranges, (v, 0xffffffff)) - 1
        return i >= 0 and library_ranges[i][0] < v < library_ranges[i][1]
    mods = json.load(open(os.path.join(ROOT, "modules.json")))
    rewritten = rewritten_functions()
    text = sec[".text"]
    pointer_slots = []
    for s in (rdata, data):
        for o in range(0, s["rsize"] - 3, 4):
            va = s["va"] + o
            if va in slot_set:
                continue
            if any(lo <= va < hi for lo, hi in NOT_CODE_POINTER_RANGES):
                continue
            if va in DEAD_CODE_POINTER_SLOTS:
                assert struct.unpack_from("<I", exe, s["raw"] + o)[0] == DEAD_CODE_POINTER_SLOTS[va]
                continue
            v = struct.unpack_from("<I", exe, s["raw"] + o)[0]
            if not (text["va"] <= v < text["va"] + text["vsize"]):
                continue
            f = funcs.get(v)
            r = rewritten.get(v)
            if not f and not r:
                # a function entry Ghidra never created (reachable only through this table): 16-byte aligned and
                # preceded by padding (int3 / nop), a ret, or an unconditional jmp that ends exactly there (a tail-
                # jumping thunk right before it, e.g. 0x558d4b jmp -> 0x558d50 in the biped type definition).
                # It becomes a named trap until it has C.
                o = off(v)
                if v % 16 or o is None:
                    continue
                previous_dword = struct.unpack_from("<I", exe, o - 4)[0]
                after_jump_table = text["va"] <= previous_dword < text["va"] + text["vsize"]
                if exe[o - 1] not in (0xcc, 0x90, 0xc3) and not after_jump_table:
                    # (a switch jump table stored in .text right before the entry also ends a function:
                    # 0x5718e0, the vehicle notify slot, follows vehicle_update's table)
                    # after a jmp only outside library code: CRT scope tables point at handler labels that
                    # also follow a jmp (0x6293e0, 0x62d560, 0x62ef30)
                    if not (exe[o - 5] == 0xe9 or exe[o - 2] == 0xeb) or inside_library_function(v):
                        continue
                f = {"name": "unlisted_%06x" % v}
            m = mods.get("%x" % v, {})
            module = m.get("module", "?") if isinstance(m, dict) else m
            if module in ("?", "") and v not in funcs and not r:
                # an entry Ghidra never split off inherits a library module from the function it follows, e.g.
                # unlisted_5c0ba0 in the D3DX vtable 0x646bc0 right after FUN_005c0b45 (lib:d3dx) (2026-09-28)
                i = bisect.bisect_right(function_starts, v) - 1
                if i >= 0:
                    pm = mods.get("%x" % function_starts[i], {})
                    pmodule = pm.get("module", "?") if isinstance(pm, dict) else pm
                    if isinstance(pmodule, str) and pmodule.startswith("lib"):
                        module = pmodule
            if f and (f.get("lib") or f.get("fid")):
                module = "lib:crt" if module in ("?", "") else module
            # the retail name (the rewrite's name only for an entry Ghidra never listed); the C symbol is attached at
            # build time from src/, so renaming or adding C never needs the retail image
            pointer_slots.append({"slot": va, "target": v, "name": (f or r)["name"], "module": module})

    rg.write_frozen("layout.json", layout)
    rg.write_frozen("imports.json", slots)
    rg.write_frozen("code_pointer_slots.json", pointer_slots)
    rg.write_frozen("game_crt.json", {x["name"].lstrip("_"): int(x["addr"], 16) for x in funcs.values()
                                      if x.get("lib") or x.get("fid")})


def code_address_ret_bytes():
    """code_address_ret.json: for every code_address_<fn> the C references, the bytes the original function at its
    address pops on return (the immediate of its first ret)"""
    import gen_link as gl
    addr, _ = gl.extern_map()
    frozen = {}
    for name, counts in sorted(addr.items()):
        if not name.startswith("code_address_") or not counts:
            continue
        a = counts.most_common(1)[0][0]
        r = subprocess.run(["objdump", "-d", "-M", "intel", "--start-address=0x%x" % a,
                            "--stop-address=0x%x" % (a + 0x4000), EXE], capture_output=True, text=True, errors="replace")
        for line in r.stdout.split("\n"):
            m = re.search(r"\tret\s*(0x[0-9a-f]+)?\s*$", line)
            if m:
                frozen["0x%06x" % a] = int(m.group(1), 16) if m.group(1) else 0
                break
    rg.write_frozen("code_address_ret.json", frozen)


def main():
    os.makedirs(OUT, exist_ok=True)
    extract_retail()
    code_address_ret_bytes()
    print("refreshed", rg.FROZEN, "and", os.path.join(OUT, "halo_image.bin"))


if __name__ == "__main__":
    main()
