"""Generate standalone/data/layout_check.cpp from standalone/data/eq_bss.cpp and eq_data.cpp.

The engine globals reached through several names sit in clusters: gap-free runs that must keep the original image's
relative addresses (eq_*.cpp explain). MSVC orders them with "$"-sorted sections; other toolchains (clang / wasm-ld
for the browser) have no such sorting and keep definition order instead. The generated check compares every
object's address with its cluster start against the original offsets, so a toolchain that lays them out differently
is caught at startup.

    python tools/gen_layout_check.py
"""
import re

FILES = ['standalone/data/eq_bss.cpp', 'standalone/data/eq_data.cpp']
OUT = 'standalone/data/layout_check.cpp'
DEFINITION = re.compile(r'__declspec\(allocate\("\.geq\$([0-9a-f]{8})(v?)"\)\)\s+__declspec\(align\(\d+\)\)\s+[\w ]+?\s+(\w+)\s*\[')


def clusters():
    result = []
    for path in FILES:
        current = None
        for line in open(path, encoding='utf-8'):
            if line.startswith('/** 0x'):
                current = []
                result.append(current)
                continue
            m = DEFINITION.search(line)
            if m and current is not None and m.group(2) == 'v':  # the pads in front ("$<start>" without v) only align
                current.append((int(m.group(1), 16), m.group(3)))
    return [c for c in result if len(c) > 1]


def main():
    found = clusters()
    names = sorted({name for cluster in found for _, name in cluster})
    lines = [
        '/**',
        ' * standalone/data/layout_check.cpp -- generated by tools/gen_layout_check.py from eq_bss.cpp and eq_data.cpp; do not edit.',
        ' * standalone_data_layout_check() reports every clustered global whose offset from its cluster start differs from',
        ' * the original image (a toolchain that does not keep the eq_*.cpp order).',
        ' */',
        '#include <stdint.h>',
        '',
        'extern "C" {',
        'void __cdecl standalone_log(const char *format, ...);',
    ]
    lines += ['extern uint8_t %s[];' % name for name in names]
    lines += ['}', '', 'namespace {', '', 'struct layout_entry {', '    const uint8_t *object;', '    uint32_t original_address;',
              '    const char *name;', '};', '']
    for index, cluster in enumerate(found):
        lines.append('const layout_entry k_cluster_%d[] = {' % index)
        lines += ['    {%s, 0x%08xu, "%s"},' % (name, address, name) for address, name in cluster]
        lines.append('};')
    lines += ['', 'struct cluster {', '    const layout_entry *entries;', '    uint32_t count;', '};', '', 'const cluster k_clusters[] = {']
    lines += ['    {k_cluster_%d, %d},' % (index, len(cluster)) for index, cluster in enumerate(found)]
    lines += ['};', '', '}  // namespace', '',
              '/** Logs each misplaced global; returns how many there are (0 when the layout is the original one). */',
              'extern "C" int standalone_data_layout_check(void)',
              '{',
              '    int misplaced = 0;',
              '',
              '    for (const cluster &c : k_clusters) {',
              '        // the pad in front of a cluster keeps its start congruent with the original address modulo 16',
              '        if ((reinterpret_cast<uintptr_t>(c.entries[0].object) & 15) != (c.entries[0].original_address & 15)) {',
              '            standalone_log("data layout: %s is not 16-byte congruent with 0x%08x", c.entries[0].name, c.entries[0].original_address);',
              '            misplaced++;',
              '        }',
              '        for (uint32_t i = 1; i < c.count; i++) {',
              '            intptr_t actual = c.entries[i].object - c.entries[0].object;',
              '            intptr_t expected = static_cast<intptr_t>(c.entries[i].original_address - c.entries[0].original_address);',
              '',
              '            if (actual != expected) {',
              '                standalone_log("data layout: %s at +0x%lx from %s, the original has +0x%lx", c.entries[i].name,',
              '                    static_cast<long>(actual), c.entries[0].name, static_cast<long>(expected));',
              '                misplaced++;',
              '            }',
              '        }',
              '    }',
              '    return misplaced;',
              '}',
              '']
    open(OUT, 'w', newline='\n').write('\n'.join(lines))
    print('%s: %d clusters, %d globals' % (OUT, len(found), sum(len(c) for c in found)))


if __name__ == '__main__':
    main()
