"""Merge per-source symbol files into symbols/functions.txt (what ApplySymbols applies) and
symbols/hints.txt (never applied; fed to agents as evidence).
Precedence per address: user > agent > chimera > opensauce.
OpenSauce addresses are for Custom Edition (haloce.exe); this repo targets retail halo.exe. Same
source, same build day, but irregular layout drift, so OpenSauce is only trusted where its address
is exactly a function entry in the fresh retail analysis (and then only at 0.7)."""
import glob
PRI = {"user": 0, "agent": 1, "chimera": 2, "opensauce": 3}
fresh = set(int(l, 16) for l in open("symbols/ghidra_entries_fresh.txt") if not l.startswith("#"))
best, hints = {}, []
def load(path, src):
    for line in open(path, encoding="utf-8", errors="replace"):
        if not line.strip() or line.startswith("#"): continue
        t = line.split(); addr, name, kind, conf, rest = int(t[0], 16), t[1], t[2], float(t[3]), " ".join(t[4:])
        if src == "opensauce":
            if kind == "func" and addr in fresh: conf = min(conf, 0.7); rest = "opensauce-ce-exact-entry"
            elif kind == "data": hints.append((addr, name, "data", 0.5, "opensauce-ce-unverified")); continue
            else: continue   # hook/call sites inside CE functions: meaningless offsets in retail
        if src == "chimera": name = "sig__" + name
        key = (addr, kind if kind != "code" else "code:" + name)
        cand = (PRI[src], -conf, name, kind, conf, rest)
        if key not in best or cand < best[key]: best[key] = cand
for p in glob.glob("symbols/user*.txt"): load(p, "user")
for p in glob.glob("symbols/agent_*.txt"): load(p, "agent")
load("symbols/chimera.txt", "chimera")
load("symbols/opensauce.txt", "opensauce")
rows = sorted((a, n, k, c, r) for (a, _), (_, _, n, k, c, r) in best.items())
with open("symbols/functions.txt", "w", encoding="ascii", errors="replace") as fh:
    fh.write("# generated by tools/merge_symbols.py; edit the per-source files, not this one\n# addr name kind confidence source\n")
    for r in rows: fh.write("0x%06x %s %s %.2f %s\n" % r)
with open("symbols/hints.txt", "w", encoding="ascii", errors="replace") as fh:
    fh.write("# unapplied hints for agents\n# addr name kind confidence source\n")
    for r in sorted(hints): fh.write("0x%06x %s %s %.2f %s\n" % r)
from collections import Counter
print("functions.txt:", Counter(r[2] for r in rows), " hints:", len(hints))
