/**
 * @file include/halo/game/api.hpp
 * Functions of the game module that other modules and the data tables call (namespace halo::game). The record types are
 * forward-declared, so the header is light enough for every caller and for the data tables.
 */
#pragma once

#include <stdint.h>

#include "tags.h"
#include "memory.h"
#include "math.h"

struct render_lighting;
struct render_animation;
#include "cache.h"
#include "game.h"
struct data_array;
struct game_engine_definition;
struct game_time_globals;
struct player_control_globals;
struct player_globals;

struct Point2D;
struct ScenarioPlayerStartingLocation;
struct TagDependency;
struct camera_basis_out;
struct circular_queue;
struct client_update_carry;
struct game_variant;
struct hud_world_text_params;
struct object;
struct object_placement_data;
struct observer_target_candidate;
struct observer_target_cone;
struct player;
struct player_action;
struct player_control_input;
struct player_update_queue;
struct player_update_record;
struct real_point3d;
struct real_vector3d;
struct scoreboard_entry;
struct team;
struct ticker_text_buffer;
struct vehicle_update_record;
struct win32_find_dataa;
typedef float real;
typedef uint32_t datum_index;

namespace halo::game {

/**
 * The engine globals the game module owns (their storage is defined by standalone/data under the original link names);
 * other modules reach them through globals().
 */
struct Globals {
    game_engine_definition *&current_engine;
    game_variant &variant;
    game_engine_state &state;
    uint8_t &teams_enabled;
    game_variant &pending_variant;
    int32_t &variant_history_current;
    game_variant &variant_saved_default;
    uint8_t &variant_saved_default_valid;
    int32_t &profile_cache_count;
    data_array *&player_data;
    player_globals *&local_player_globals;
    player_control_globals *&player_control;
    data_array *&update_client_queues;
    data_array *&update_server_queues;
    int16_t &local_player_count;
    game_time_globals *&game_time;
    int32_t &time_force_single_tick;
};

Globals &globals();

uint32_t XCreateSaveGame(const uint16_t *save_game_name, const char *root_path, int32_t mode, char *out_path, uint32_t out_path_size);
uint32_t XDeleteSaveGame(const uint16_t *save_game_name, const char *root_path);
float angle_delta_wrapped(float from, float to);
uint8_t any_local_player_within_10_units(const real_point3d *query_point);
void apply_remote_player_position_update(player *plr, object *unit_obj);
void apply_remote_player_vehicle_position_update(player *plr, object *unit_obj);
void cache_file_switch_map_by_path(char *path, uint8_t apply_state);
char camera_observer_find_best_target(real_point3d *observer_position, observer_target_cone *cone, real_vector3d *facing, datum_index exclude_object, int16_t team, observer_target_candidate *out);
uint32_t camera_observer_get_target_angles(real *out_weight_primary, real *out_weight_secondary, real *out_yaw_pitch, real *out_yaw_pitch_rate, int16_t local_player_slot);
uint32_t camera_observer_get_target_id(datum_index *out_id, int16_t local_player_slot);
int32_t camera_observer_target_compare(const observer_target_candidate *a, const observer_target_candidate *b);
uint32_t camera_observer_target_direction(real_point3d *candidate_point, real_vector3d *facing, real_point3d *reference_position, datum_index object, datum_index exclude_object, real_vector3d *out_direction, real *out_distance, real *out_angle);
uint32_t camera_observer_update(datum_index player_index, real_point3d *observer_position, real_vector3d *fallback_facing);
void cheat_all_weapons(void);
void cheat_make_player_invincible(int16_t local_player_slot);
void cheat_make_selected_object_invincible(void);
void cheat_spawn_objects_near_camera(TagDependency *tag_array, int16_t count);
void cheat_spawn_warthog(void);
void cheat_teleport_to_camera(void);
void chimera__kill_feed(datum_index recipient, int32_t hash_key, uint32_t message_type, datum_index subject, char broadcast);
void chimera__spectate_fp_camera_position(camera_basis_out *out, int16_t local_player_index);
int32_t circular_queue_count(circular_queue *queue);
uint8_t circular_queue_push(circular_queue *queue, void *source);
real control_axis_sign(real value);
void ctf_engine_flag_tick(uint32_t flag_handle, object *flag_obj);
void ctf_flag_object_clear_carrier(datum_index flag_object_index, real_point3d *position);
void custom_waypoint_get_position(real_point3d *out, int16_t slot);
uint8_t custom_waypoint_matches_filter(int32_t candidate, player *reference_player, int32_t slot_index);
void custom_waypoint_register(datum_index owner, int16_t slot, real_point3d *position, const char *icon_name, float height_offset, datum_index player_filter, int16_t team_filter);
real distance_falloff_fraction(real value, real max_range);
void game_dispose(void);
void game_effects_update(real delta_time);
int32_t game_engine_accumulate_simulation_ticks(float elapsed_seconds, char keep_remainder);
void game_engine_advance_simulation_ticks(float delta_time);
void game_engine_allocate_tick_record(void);
void game_engine_animate_hill_pulse_icons(datum_index fading_player, datum_index growing_player);
int32_t game_engine_announce_time_remaining(void);
void game_engine_apply_catchup_speed_boost(void);
void game_engine_apply_current_custom_variant(void);
uint8_t game_engine_apply_kill_streak_message(int32_t **envelope);
void game_engine_apply_partial_round_reset_message(void *event);
void game_engine_apply_player_grenade_counts(uint32_t player_index);
uint8_t game_engine_apply_player_interaction_message(void **envelope);
void game_engine_apply_player_join_message(void **envelope);
void game_engine_apply_player_profile_entry(void *event);
void game_engine_apply_player_spawn_loadout_message(void **envelope);
void game_engine_apply_variant(const game_variant *variant);
uint8_t game_engine_attach_players_to_new_bsp(void);
void game_engine_attribute_player_death(datum_index victim_unit, datum_index killer, datum_index death_object, int32_t killer_team, char credit_kills);
void game_engine_begin_end_game_sequence(void);
void game_engine_broadcast_kill_feed_by_relationship(uint32_t source_player, int32_t no_source_message, int32_t message_a, int32_t message_b, uint32_t subject, uint8_t broadcast);
void game_engine_broadcast_kill_feed_gated(int32_t broadcast_enabled, int32_t exclude_index, int32_t alternate_recipient, datum_index subject, char broadcast);
void game_engine_broadcast_kill_feed_or_direct(datum_index recipient_or_all, int32_t broadcast_enabled, char broadcast, int32_t hash_key, datum_index subject);
void game_engine_broadcast_kill_feed_to_team(int32_t message_type, int32_t team, uint8_t broadcast);
void game_engine_build_end_game_result_text(datum_index player_handle, wchar_t *out);
uint8_t game_engine_build_kill_feed_message_text(datum_index recipient, wchar_t *out, uint32_t message_type, datum_index subject, size_t buffer_size);
void game_engine_build_local_player_control_input(int16_t local_player_index, real delta_time, player_control_input *out);
uint8_t game_engine_build_message_text(wchar_t *out, uint32_t buffer_size, datum_index subject, uint32_t param_1, uint32_t message_type);
uint32_t game_engine_build_scoreboard_sort_key(uint32_t player_index, int32_t score);
int32_t game_engine_build_sorted_player_list(uint8_t invert_low_stat, scoreboard_entry out_entries[16], int32_t mode);
void game_engine_build_visible_cluster_bitmask(uint32_t *out_bitmask, uint8_t local_players_only);
void game_engine_capture_player_profile(int32_t slot, int32_t commit);
void game_engine_check_bucket_scores_and_end_round(void);
void game_engine_cleanup_dropped_objects(void);
void game_engine_cleanup_stray_items(void);
void game_engine_cleanup_stray_projectiles(void);
void game_engine_clear_unit_shields_when_disabled(datum_index player_handle);
void game_engine_client_apply_team_assignment(void **envelope);
int16_t game_engine_collect_matching_waypoints(int32_t candidate, float *out_positions, uint8_t *out_slots, int16_t max_count);
uint32_t game_engine_compare_score_to_others(uint32_t subject, int32_t team_mode);
void game_engine_compute_local_player_look_vector(real_vector3d *out_forward, int16_t local_player_index);
void game_engine_compute_look_angles_from_vector(real_vector3d *facing, int16_t local_player_index);
float game_engine_compute_time_scale(int32_t param_a, int32_t param_b);
void game_engine_ctf_assign_flag_ids(void);
void game_engine_ctf_broadcast_state(void *request_fields, int32_t machine_index);
uint8_t game_engine_ctf_build_message_text(datum_index recipient, int32_t message_type, datum_index subject, wchar_t *text, uint32_t count);
wchar_t * game_engine_ctf_build_player_text(datum_index player, wchar_t *buffer);
wchar_t * game_engine_ctf_build_score_header_text(wchar_t *buffer);
wchar_t * game_engine_ctf_build_team_score_text(int32_t team, wchar_t *buffer);
datum_index game_engine_ctf_create_flag_object(real_point3d *position, uint16_t name_index);
int32_t game_engine_ctf_get_score(datum_index player, int32_t team_mode);
int32_t game_engine_ctf_get_team_score(int32_t team);
int32_t game_engine_ctf_initialize_flags(void);
uint8_t game_engine_ctf_initialize_for_new_game(void);
uint8_t game_engine_ctf_is_flag_eligible_for_capture(uint32_t team, int32_t flag_id);
void game_engine_ctf_notify_both_teams(int32_t team);
void game_engine_ctf_notify_flag_carried_throttled(int32_t target_player);
void game_engine_ctf_object_expired(datum_index object_index);
void game_engine_ctf_on_flag_captured(uint32_t flag_index);
int32_t game_engine_ctf_pick_random_flag(int32_t exclude_flag_index);
void game_engine_ctf_player_drop_flag(uint32_t player_index, datum_index flag_object_index);
uint8_t game_engine_ctf_player_flag_tick(uint32_t flag_handle, uint32_t player_index);
void game_engine_ctf_player_round_reset(datum_index player_index);
void game_engine_ctf_player_touch_flag(uint32_t player_index, int32_t team);
uint8_t game_engine_ctf_point_within_team_flag_radius(float radius, int32_t team, real_point3d *point);
void game_engine_ctf_profile_post_update(void **context);
void game_engine_ctf_profiles_updated(int32_t mode, int32_t machine_index);
uint8_t game_engine_ctf_query_player_score(int32_t key, int32_t index, void *buffer);
uint8_t game_engine_ctf_query_team_score(int32_t key, int32_t team, void *buffer);
void game_engine_ctf_reset_objects(void);
void game_engine_ctf_reset_round(void);
void game_engine_ctf_reset_team_return_credit(uint32_t object_index);
void game_engine_ctf_respawn_team_flag(int32_t team, real_point3d *forwarded_position, uint16_t forwarded_name_index);
void game_engine_ctf_return_all_flags(void);
void game_engine_ctf_score_flag(uint32_t team, int32_t scenario_flag_index);
uint8_t game_engine_ctf_unit_is_flag_holder(player *p);
uint8_t game_engine_ctf_unit_weapon_must_be_readied(datum_index unit_handle);
void game_engine_ctf_unknown_48(void);
uint8_t game_engine_ctf_unknown_60(datum_index unit_index, datum_index item_index);
float game_engine_ctf_unknown_70(datum_index player_index, real_point3d *position);
uint8_t game_engine_ctf_unknown_84(int32_t kind);
void game_engine_ctf_update(datum_index player_index);
void game_engine_digitize_control_input(player_control_input *input);
void game_engine_dispatch_end_game_notification(void *event);
void game_engine_dispatch_item_pickup_event(int32_t machine_id, int32_t picked_tag, int32_t param_2);
void game_engine_end_game_sequence_stage1(void);
void game_engine_end_game_sequence_stage2(void);
void game_engine_end_game_sequence_stage3(void);
uint32_t game_engine_ensure_variant_history_has_entry(void);
uint8_t game_engine_find_first_eligible_player_on_team(int32_t team);
int32_t game_engine_find_nearest_unused_type4_location(int32_t *excluded_indices, int32_t excluded_count, real_point3d *reference_point);
int32_t game_engine_find_one_valid_starting_location(int16_t type, int16_t team, real_point3d *origin, float max_horizontal_dist, float max_height_delta);
void game_engine_find_player_by_name(char *source_name);
datum_index game_engine_find_player_holding_object(datum_index target_object);
int game_engine_find_valid_starting_locations(real_point3d *origin, float max_horizontal_dist, float max_height_delta, int16_t team, int16_t type, int32_t max_results, int32_t *results);
void game_engine_flag_local_player_units(void);
void game_engine_free_custom_variant_cache(void);
void game_engine_gather_team_score_totals(uint32_t out_count[2], uint32_t out_score[2], int32_t filter_value);
int32_t game_engine_get_current_tick(void);
wchar_t * game_engine_get_default_multiplayer_string(const scoreboard_entry *entry);
real game_engine_get_max_look_pitch(int16_t local_player_index);
int32_t game_engine_get_multiplayer_sound_duration_ticks(int32_t sound_index);
wchar_t * game_engine_get_multiplayer_text_list(uint32_t rank);
real * game_engine_get_player_color(uint32_t player_index, real *out_rgb);
void game_engine_get_player_scoreboard_entry(datum_index player, scoreboard_entry *out);
int32_t game_engine_get_scoreboard_place(datum_index player, int32_t mode, uint8_t invert_low_stat);
uint8_t game_engine_get_teams_enabled(void);
int32_t game_engine_get_time_remaining(void);
float game_engine_get_time_scale(void);
uint8_t game_engine_get_variant_by_name(const char *name, game_variant *out);
void game_engine_handle_kill_feed_network_event(int32_t **message);
void game_engine_handle_sound_status_event(void *event);
void game_engine_init_player_look_state_from_object(datum_index unit, int16_t local_player_index);
void game_engine_init_tick_record_for_mode(void);
void game_engine_initialize_for_new_game(void);
void game_engine_invoke_profile_post_update_callback(uint32_t arg_ecx, uint32_t arg_edx);
uint8_t game_engine_is_inactive(void);
uint32_t game_engine_is_map_and_variant_valid(const char *map_path, const char *variant_name);
uint32_t game_engine_is_object_winning(uint32_t handle);
uint32_t game_engine_is_tracked_object_winner(int32_t team);
uint8_t game_engine_is_valid_team_player(uint32_t identifier);
uint8_t game_engine_king_build_message_text(datum_index recipient, int32_t message_type, datum_index subject, wchar_t *text, uint32_t count);
wchar_t * game_engine_king_build_player_text(datum_index player, wchar_t *buffer);
wchar_t * game_engine_king_build_score_header_text(wchar_t *buffer);
wchar_t * game_engine_king_build_team_score_text(int32_t team, wchar_t *buffer);
int32_t game_engine_king_get_score(datum_index player, int32_t team_mode);
int32_t game_engine_king_get_team_score(int32_t team);
uint8_t game_engine_king_initialize_for_new_game(void);
void game_engine_king_player_new_life(datum_index player_index);
void game_engine_king_player_round_reset(datum_index player_index);
void game_engine_king_profile_post_update(void **context);
uint8_t game_engine_king_query_player_score(int32_t key, int32_t index, void *buffer);
uint8_t game_engine_king_query_team_score(int32_t key, int32_t team, void *buffer);
void game_engine_king_reset_objects(void);
void game_engine_king_reset_round(void);
void game_engine_king_unknown_48(void);
uint8_t game_engine_king_waypoint_filter(datum_index player);
void game_engine_koth_alt_scorer_tick(uint32_t player_index);
void game_engine_koth_ball_idle_tick(uint32_t object_handle, object *obj);
void game_engine_koth_broadcast_hill_times(int32_t mode, int32_t machine_index);
void game_engine_koth_broadcast_team_scores(int32_t mode, int32_t machine_index);
void game_engine_koth_build_hill_boundary(void);
void game_engine_koth_build_hill_boundary_fence(void);
uint32_t game_engine_koth_dispatch_player_scoring(uint32_t player_index);
void game_engine_koth_find_marker_position(real_point3d *out_position, int16_t type_filter);
uint8_t game_engine_koth_player_eligible_to_score(uint32_t object_handle, uint32_t player_index);
uint8_t game_engine_koth_player_in_hill_bounds(uint32_t player_index);
void game_engine_koth_player_tick(uint32_t player_index);
void game_engine_koth_relocate_hill_marker(int32_t ball_index);
void game_engine_koth_relocate_object_hill(uint32_t object_index);
void game_engine_koth_reset_hill_marker_history(void);
void game_engine_koth_submit_hill_marker_geometry(uint32_t tag_handle_as_uint, const render_lighting *lighting_override, const render_animation *animation_override, uint32_t param_4, uint32_t param_5, float *vertex_source);
void game_engine_koth_update_hill_occupancy_state(void);
void game_engine_koth_update_occupant_table(uint32_t index);
void game_engine_load_from_variant(const game_variant *variant);
uint8_t game_engine_local_player_score_is_nonpositive(datum_index player_handle);
uint8_t game_engine_location_blocked_by_vehicle(real_point3d *point);
void game_engine_maybe_render_post_game(void);
void game_engine_multiplayer_sound_queue_tick(void);
int32_t game_engine_multiplayer_ui_state_id(void);
void game_engine_notify_item_expired(datum_index object_index);
void game_engine_notify_kill_event(uint32_t player_index, int32_t hash_key, int32_t message_type, datum_index subject);
void game_engine_notify_object_value_event(uint8_t value_byte, int32_t hash_key, int32_t machine_index, void *subject);
void game_engine_notify_player_interaction(uint32_t primary_key, uint32_t edi_key, uint32_t mode, int32_t interaction_type, int32_t interaction_seat, int32_t secondary_key);
uint8_t game_engine_notify_weapon_ready_state_change(datum_index unit_index, datum_index weapon_index);
uint8_t game_engine_object_flag_bit3_clear(int32_t handle);
uint8_t game_engine_oddball_build_message_text(datum_index recipient, int32_t message_type, datum_index subject, wchar_t *text, uint32_t count);
wchar_t * game_engine_oddball_build_player_text(datum_index player, wchar_t *buffer);
wchar_t * game_engine_oddball_build_score_header_text(wchar_t *buffer);
wchar_t * game_engine_oddball_build_team_score_text(int32_t team, wchar_t *buffer);
int32_t game_engine_oddball_get_score(datum_index player, int32_t team_mode);
int32_t game_engine_oddball_get_team_score(int32_t team);
uint8_t game_engine_oddball_initialize_for_new_game(void);
void game_engine_oddball_player_killed(datum_index killer, datum_index death_object, datum_index victim, uint8_t is_suicide);
void game_engine_oddball_player_new_life(datum_index player_index);
void game_engine_oddball_player_round_reset(datum_index player_index);
void game_engine_oddball_profile_post_update(void **context);
uint8_t game_engine_oddball_query_player_score(int32_t key, int32_t index, void *buffer);
uint8_t game_engine_oddball_query_team_score(int32_t key, int32_t team, void *buffer);
void game_engine_oddball_reset_objects(void);
uint8_t game_engine_oddball_time_scale_override(uint32_t player, int32_t value);
void game_engine_oddball_unknown_48(void);
uint8_t game_engine_oddball_unknown_84(int32_t kind);
void game_engine_on_player_death(datum_index killer, datum_index death_object, datum_index victim, char is_suicide);
uint32_t game_engine_pack_object_flags_or_passthrough(uint32_t input);
uint8_t game_engine_pick_hud_hint(datum_index player_index, int32_t maximum_length, uint16_t *out_text);
int32_t game_engine_pick_random_recent_location(int32_t exclude_value, int32_t fallback);
void game_engine_play_multiplayer_sound(int32_t sound_index, datum_index recipient_player, uint8_t broadcast);
void game_engine_player_changed_object(uint32_t param);
uint8_t game_engine_player_has_respawn_priority(uint32_t player_index);
uint8_t game_engine_player_is_eliminated(uint32_t player_index);
void game_engine_player_new_life(uint32_t player_handle);
void game_engine_player_profile_cache_add(datum_index player_handle);
int32_t game_engine_player_profile_cache_find(datum_index player_handle);
void game_engine_player_profile_cache_sync_all(int32_t commit, void *callback_extra_arg);
uint8_t game_engine_player_ready_to_respawn(uint32_t player_index);
uint8_t game_engine_player_respawn_priority_gate(uint32_t player_index);
void game_engine_player_round_reset(int32_t player_handle, int32_t callback_argument);
void game_engine_player_select_random_target(datum_index player_or_all);
uint8_t game_engine_players_ready_for_bsp_switch(void);
uint8_t game_engine_players_ready_for_bsp_switch_strict(void);
void game_engine_players_update_client(void);
void game_engine_players_update_server(void);
void game_engine_post_rasterize_post_game(void);
void game_engine_queue_multiplayer_sound(int32_t sound_index, datum_index player, uint8_t broadcast);
void game_engine_queue_status_sound_message(int32_t sound_index, datum_index recipient_player);
uint8_t game_engine_race_allow_grenade_counts(datum_index player_index);
uint8_t game_engine_race_build_message_text(datum_index recipient, int32_t message_type, datum_index subject, wchar_t *text, uint32_t count);
wchar_t * game_engine_race_build_player_text(datum_index player, wchar_t *buffer);
wchar_t * game_engine_race_build_score_header_text(wchar_t *buffer);
wchar_t * game_engine_race_build_team_score_text(int32_t team, wchar_t *buffer);
int32_t game_engine_race_get_score(datum_index player, int32_t team_mode);
int32_t game_engine_race_get_team_score(int32_t team);
uint32_t game_engine_race_is_winner(datum_index player);
void game_engine_race_player_changed_object(datum_index player_index);
void game_engine_race_player_new_life(datum_index player);
void game_engine_race_player_round_reset(datum_index player_index, uint8_t team_flag);
void game_engine_race_profile_post_update(void **context);
uint8_t game_engine_race_query_player_score(int32_t key, int32_t index, void *buffer);
uint8_t game_engine_race_query_team_score(int32_t key, int32_t team, void *buffer);
void game_engine_race_unknown_48(void);
void game_engine_race_update(datum_index player_index);
uint8_t game_engine_race_waypoint_filter(datum_index player, int32_t team);
void game_engine_rasterize_in_game_score(datum_index subject_player, float opacity);
float game_engine_rate_location_ally_bonus(uint32_t self_index, real_point3d *point);
float game_engine_rate_location_crowding(uint32_t self_index, real_point3d *point);
real game_engine_rate_player_starting_location(ScenarioPlayerStartingLocation *location, datum_index player_handle);
void game_engine_reattach_player_unit_unused(uint32_t player_index, uint32_t target_object, void *local_offset);
uint32_t game_engine_remap_placement_by_type(uint32_t handle);
void game_engine_reset_all_players(void);
void game_engine_reset_all_unit_grenade_counts(void);
void game_engine_reset_player_look_state(void);
void game_engine_reset_player_profile_stats(void);
void game_engine_reset_respawns_and_cleanup_bipeds(void);
void game_engine_reset_round_objects(void);
void game_engine_reset_vehicles_or_race_cleanup(void);
uint32_t game_engine_resolve_multiplayer_placement(uint32_t handle);
int32_t game_engine_resolve_netgame_flag_role(uint32_t handle);
void game_engine_resolve_player_team(uint32_t player_index);
void game_engine_scan_netgame_flags_noop(int16_t needle);
uint8_t game_engine_scores_tracked_individually(void);
void game_engine_send_end_game_notification(uint32_t reason);
void game_engine_send_player_profile_update(const int32_t *machine_hash, const void *cached_profile, int32_t commit, const void *current_profile, int32_t target);
void game_engine_send_round_reset_message(void);
void game_engine_send_team_allegiance_message(char broadcast);
void game_engine_send_unit_weapon_loadout(uint32_t unit_index, datum_index player_handle, int32_t value, int32_t machine_index);
void game_engine_server_update_player_positions(void);
void game_engine_set_variant_by_name(const char *name);
uint8_t game_engine_slayer_build_message_text(datum_index recipient, int32_t message_type, datum_index subject, wchar_t *text, uint32_t count);
wchar_t * game_engine_slayer_build_player_text(datum_index player, wchar_t *buffer);
wchar_t * game_engine_slayer_build_team_score_text(int32_t team, wchar_t *buffer);
int32_t game_engine_slayer_get_score(datum_index player, int32_t team_mode);
int32_t game_engine_slayer_get_team_score(int32_t team);
uint8_t game_engine_slayer_initialize_for_new_game(void);
void game_engine_slayer_player_killed(datum_index killer, datum_index death_object, datum_index victim, uint8_t is_suicide);
void game_engine_slayer_player_new_life(datum_index player_index);
void game_engine_slayer_player_round_reset(datum_index player_index);
void game_engine_slayer_profile_post_update(void **context);
void game_engine_slayer_profiles_updated(int32_t mode, int32_t machine_index);
uint8_t game_engine_slayer_query_player_score(int32_t key, int32_t index, void *buffer);
uint8_t game_engine_slayer_query_team_score(int32_t key, int32_t team, void *buffer);
void game_engine_slayer_reset_objects(void);
void game_engine_slayer_reset_round(void);
uint8_t game_engine_slayer_unknown_84(int32_t kind);
void game_engine_slayer_update(datum_index player_index);
void game_engine_spawn_or_replay_netgame_equipment(int32_t *message);
void game_engine_spawn_player_starting_loadout(uint32_t starting_equipment_index, int32_t *frag_count, int32_t *plasma_count);
void game_engine_sync_variant_defaults(void);
uint8_t game_engine_team_close_game_check(int32_t side, int32_t filter_value);
uint8_t game_engine_team_has_scoring_capacity(int32_t team);
uint8_t game_engine_team_is_leading(int32_t filter_value);
void game_engine_tick(void);
void game_engine_touch_multiplayer_predicted_resources(void);
void __cdecl game_engine_unload(void);
void game_engine_update_custom_waypoint_navpoints(int16_t local_player_slot);
void game_engine_update_end_game_sequence(float delta_time);
void game_engine_update_item_scale_and_pickup(void);
void game_engine_update_lead_change_state(void **envelope, uint8_t *message);
void game_engine_update_local_player_control(int16_t local_player_index, real delta_time, int32_t ticks_this_frame);
void game_engine_update_local_player_look(int16_t local_player_index, real yaw_delta, real pitch_delta);
void game_engine_update_netgame_equipment(char force_respawn);
void game_engine_update_teleporter(uint32_t player_index);
void game_engine_validate_scenario_placements_noop(void);
uint32_t game_engine_variant_add_to_history(char *name, game_variant *options, char *path);
game_variant * game_engine_variant_defaults_assault(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_accumulation(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_crazy_king(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_ctf(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_ctf_pro(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_elimination(game_variant *out);
game_variant * game_engine_variant_defaults_classic_endurance(game_variant *out);
game_variant * game_engine_variant_defaults_classic_invasion(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_iron_ctf(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_juggernaut(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_king(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_king_pro(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_oddball(game_variant *out);
game_variant * game_engine_variant_defaults_classic_phantoms(game_variant *out);
game_variant * game_engine_variant_defaults_classic_race(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_rally(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_reverse_tag(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_rockets(game_variant *out);
game_variant * game_engine_variant_defaults_classic_slayer(game_variant *out);
game_variant * game_engine_variant_defaults_classic_slayer_pro(game_variant *out);
game_variant * game_engine_variant_defaults_classic_snipers(game_variant *out);
game_variant * game_engine_variant_defaults_classic_stalker(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_team_king(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_team_oddball(game_variant *out);
game_variant * game_engine_variant_defaults_classic_team_race(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_team_rally(game_variant *variant_options);
game_variant * game_engine_variant_defaults_classic_team_slayer(game_variant *out);
game_variant * game_engine_variant_defaults_crazy_king(game_variant *variant_options);
game_variant * game_engine_variant_defaults_juggernaut(game_variant *variant_options);
game_variant * game_engine_variant_defaults_king(game_variant *variant_options);
game_variant * game_engine_variant_defaults_oddball(game_variant *variant_options);
game_variant * game_engine_variant_defaults_race(game_variant *variant_options);
game_variant * game_engine_variant_defaults_slayer(game_variant *variant_options);
game_variant * game_engine_variant_defaults_stalker(game_variant *variant_options);
game_variant * game_engine_variant_defaults_team_king(game_variant *variant_options);
game_variant * game_engine_variant_defaults_team_oddball(game_variant *variant_options);
game_variant * game_engine_variant_defaults_team_race(game_variant *variant_options);
game_variant * game_engine_variant_defaults_team_slayer(game_variant *variant_options);
ScenarioPlayerStartingLocation * game_get_player_starting_location(int16_t index);
void game_initialize(void);
uint32_t game_no_player_is_dead(void);
uint32_t game_safe_to_pause(void);
uint8_t game_safe_to_save(void);
void game_set_local_player(datum_index player_handle, int16_t local_player_index);
void game_simulate_tick(uint32_t predict_pass);
void game_start_new_map(void);
void game_stop_current_map(void);
void game_time_format_minutes_seconds(uint32_t ticks, uint32_t count, wchar_t *dest);
void game_time_format_minutes_seconds_ascii(uint32_t ticks, uint32_t count, char *dest);
void game_unload_map(void);
uint32_t game_variant_option_default_by_index(uint32_t selector);
void game_variant_sanitize_options(game_variant *variant);
void hs_vehicle_gunner_evaluate(int16_t function_index, uint32_t thread_index, char first);
void hs_vehicle_test_seat_evaluate(int16_t function_index, uint32_t thread_index, char first);
void hud_draw_scoreboard_row_text(int16_t row, wchar_t *text, int16_t column);
int32_t hud_draw_world_relative_text(hud_world_text_params *params, int16_t row, wchar_t *text, uint8_t highlighted);
uint8_t hud_nameplate_candidate_filter(uint32_t object_index, void *context);
void hud_update_teammate_nameplate_fade(void);
int32_t local_player_find_free_slot_index(void);
int32_t local_player_get_zoom_level(int16_t local_player_index);
void local_player_set_controlled_unit(datum_index new_unit, int16_t local_player_index);
datum_index local_player_to_player_index(int16_t local_player_index);
void main_switch_structure_bsp(void);
void multiplayer_game_variant_description_generate(char *variant_name, ticker_text_buffer *ticker, int32_t fraglimit, wchar_t *game_flags_wide, wchar_t *player_flags_wide);
uint8_t netgame_equipment_game_type_matches(int16_t *types, int32_t count, int32_t current_engine_index);
void network_queue_destroy(circular_queue *queue);
void network_server_broadcast_object_type_changes(void);
void object_placement_data_set_change_colors(real *color, object_placement_data *placement);
uint8_t player_add_kill_streak(int32_t slot, int16_t amount, uint32_t player_handle);
void player_advance_multikill_medal(uint32_t player_handle);
void player_apply_first_position_update(uint32_t field0, player *plr);
void player_apply_pickup_effect(uint32_t player_index, uint32_t pickup_object);
uint8_t player_attach_unit_to_parent(uint32_t player_index, uint32_t target_object, void *local_offset);
void player_compute_view_forward_vector(datum_index player_handle, real *yaw_pitch, real_vector3d *out_forward);
uint8_t player_customization_slot_set(uint8_t *base, uint8_t new_value, uint32_t key);
uint8_t player_execute_pending_interaction(uint32_t player_index);
uint8_t player_execute_weapon_drop_interaction(uint32_t player_index);
uint8_t player_find_placement_position(uint32_t player_index, datum_index target_object, real_point3d *point);
datum_index player_index_from_unit_index(datum_index unit_index);
void player_kill_and_release_unit(uint32_t player_index, int32_t respawn_timer_override);
void player_kill_streak_begin(int16_t slot, uint32_t player_handle);
void player_kill_streak_continue(int16_t slot, uint32_t player_handle);
void player_kill_streak_set_max(int16_t slot, uint32_t player_index, int16_t value);
void player_kill_streak_tick(uint32_t player_index);
datum_index player_new_local(datum_index requested_handle, uint32_t machine_index, int16_t local_player_index, uint16_t *identifier_record);
datum_index player_new_network(datum_index requested_index, uint32_t machine_index, int16_t local_player_index, uint16_t *identifier_record);
void player_profile_cache_initialize(void);
void player_remove(datum_index player_handle);
void player_reset_after_unit_change(uint32_t player_index);
void player_respawn(uint32_t player_index);
void player_set_action_result(int16_t function_index, uint32_t thread_index, char first);
void player_set_team_by_color(uint8_t new_team, int8_t target_team_index_desired);
datum_index player_spawn_starting_profile_weapon(TagDependency *weapon_dependency, int16_t rounds_loaded, int16_t rounds_reserved, uint32_t role);
uint8_t player_swap_to_weapon(uint32_t player_index, datum_index target_weapon);
void player_trigger_full_health_effect(uint32_t player_index);
void player_trigger_kill_streak_effect(uint32_t player_index);
void player_trigger_shield_recharge_effect(uint32_t player_index);
uint8_t player_unit_has_parent(datum_index player_handle);
void player_update_nearby_interactions_primary(uint32_t player_index);
void player_update_nearby_interactions_secondary(uint32_t player_index);
void player_update_queue_create(player_update_queue *queue);
uint8_t player_update_queue_pop_current(player_update_record *out, player_update_queue *queue);
int32_t players_active_count(void);
uint8_t players_any_pending_seat_or_respawn(void);
uint8_t players_any_without_unit(void);
void players_client_catchup_on_server_updates(void);
void players_dispose(void);
datum_index players_find_local_owned_unclear(void);
uint32_t players_get_active_by_index(int32_t index);
void players_handle_deleted_unit(uint32_t object_index);
void players_initialize(void);
void players_rebind_local_player_after_load(void);
void players_server_catchup_on_client_updates(void);
void players_structure_bsp_switch_regroup(void);
void point3d_array_project_to_xy_plane(real_point3d *source, Point2D *destination, int32_t count);
void position_update_queue_create(circular_queue *queue);
uint8_t position_update_queue_find_and_remove(circular_queue *queue, int32_t target_tick, real_point3d *out);
uint8_t position_update_queue_push(circular_queue *queue, real x, real y, real z, int32_t tick, int32_t sequence);
void random_get_table_point(real_point3d *out);
real response_curve_evaluate(int16_t table_count, real x, real *table);
int32_t savegame_find_first(char *root_path, win32_find_dataa *find_data);
uint32_t savegame_find_next(win32_find_dataa *find_data, uint32_t handle);
uint8_t savegame_index_append_slot(const void *entry, uint32_t *out_slot_count);
uint8_t savegame_index_file_exists(void);
uint32_t savegame_index_get_slot_count(void);
uint8_t savegame_index_read_slot(uint16_t slot, void *out_entry);
uint8_t savegame_index_remove_slot(uint16_t slot);
uint8_t savegame_index_write_slot(uint16_t slot, const void *entry);
uint32_t savegame_slot_handle_pack(uint32_t slot_index, uint32_t type_nibble, uint8_t flag_bit_30, uint8_t flag_bit_31);
int32_t scoreboard_entry_compare(const scoreboard_entry *a, const scoreboard_entry *b);
uint32_t scoreboard_entry_compare_by_unknown_04(const scoreboard_entry *a, const scoreboard_entry *b);
int32_t select_players_to_display(int32_t mode, int32_t max_count, scoreboard_entry *out);
int32_t tag_reflexive_pick_weighted_random_index(datum_index tag_id);
uint8_t team_pair_flag_test(int16_t team_a, int16_t team_b);
void team_pair_override_add(int16_t index_a, uint8_t unknown_08, int16_t index_b, uint8_t unknown_09, int16_t threshold, int16_t timer_reset, uint8_t unknown_0c);
uint32_t team_pair_override_adjust_counter(int16_t index_a, int16_t index_b, int16_t delta_selector, uint8_t *out_flag);
void team_pair_override_clear_flag(int16_t index_b, int16_t index_a);
uint8_t team_pair_override_get_flag(int16_t index_a, int16_t index_b);
void team_pair_override_refresh(int16_t index_b, int16_t index_a);
uint32_t team_pair_override_remove(int16_t index_a, int16_t index_b);
void team_pair_overrides_tick(void);
void team_pair_table_allocate(void);
void team_pair_table_init_defaults(void);
uint8_t teams_are_enemies(int16_t team_a, int16_t team_b);
wchar_t * unicode_string_list_get_string(char *path, int16_t index);
void unit_apply_starting_profile(int16_t starting_profile_index, datum_index unit_handle, uint8_t reset_stats);
uint8_t unit_get_current_weapon_autoaim_cone(datum_index unit_index, int16_t require_zoomed, real *out);
int32_t unit_get_local_player_weapon_index(datum_index unit);
uint8_t unit_has_must_be_readied_weapon(uint32_t player_index);
void unit_invalidate_local_player_zoom_level(datum_index unit);
void unit_reset_gauge_if_flagged(uint32_t player_index);
void unit_set_local_player_weapon_index(datum_index unit, int16_t weapon_index);
void unit_snap_position_if_far(real_point3d *new_position, object *obj, datum_index object_index);
void unit_update_active_camouflage_depower(datum_index player_handle);
void update_client_advance_read_cursor(int32_t target_tick, const uint32_t *record);
void update_client_dispose(void);
uint32_t update_client_distribute_staged_entry(uint8_t *out);
uint32_t update_client_queue_apply_tick(player_action *out_actions, client_update_carry *out_carry);
void update_client_stage_entry(uint32_t *source);
void update_queues_dispose(void);
void update_queues_revert(void);
void update_run_catchup_ticks(int16_t tick_count);
void update_server_dispose(void);
uint8_t update_server_new(void);
void update_server_push_player_tick_history(void);
void update_server_queue_create_entry(datum_index requested_handle);
void update_server_queue_push_history(int16_t machine_index, int32_t tick_count, uint32_t *source, uint32_t extra);
uint32_t user_profile_signin_state_is_valid(void);
uint8_t user_save_path_remove(uint32_t user_id);
void value_step_toward_target(float *value, float target, float max_step);
void vector3d_clamp_length(real_vector3d *v, real max_length);
void vector3d_closest_point_on_segment(datum_index unit_index, real_vector3d *aux_vector, real_point3d *reference_point, real_point3d *out_closest);
void vehicle_update_queue_create(circular_queue *queue);
uint8_t vehicle_update_queue_find_and_remove(circular_queue *queue, int32_t target_tick, vehicle_update_record *out);
real weapon_get_zoom_fov(int16_t zoom_table_index, int16_t magnification);
real weapon_get_zoom_fov_resolved(int16_t zoom_table_index, int16_t substitution_check_index);

}
