"""move the retail extraction out of the build: tools/gen_standalone.py keeps only the frozen-input path; the
extraction (pe_layout, reader, imports, extract_retail) becomes the maintenance tool tools/freeze_retail_inputs.py"""
R = "C:\\Users\\Liam-\\halo-re\\tools\\"
p = R + "gen_standalone.py"
t = open(p, encoding="utf-8").read()

i_pe = t.index("def pe_layout(exe):")
i_rw = t.index("def rewritten_functions():")
i_ex = t.index("def extract_retail():")
i_main = t.index("def main():")
pe_block = t[i_pe:i_rw]          # pe_layout, reader, imports
extract_block = t[i_ex:i_main]   # extract_retail

# ---- the build tool
head = '''"""Standalone build generator, stage 1: the build-time tables for a halo.exe built from src/.

The standalone exe is linked away from 0x400000 (it runs no original code), and at start-up its loader copies the data
image linked into it (standalone/image/*.asm) back to the original addresses, so every global our C references by
absolute address (gen_link's EQU symbols) stays valid. This stage reads only committed files -- standalone/frozen/
and the src/ headers; it never reads the retail binary (retail_guard.forbid_retail) -- and writes:
  build/standalone/layout.json         where each piece goes (virtual address, raw size, virtual size)
  build/standalone/code_pointers.json  every dword in .rdata/.data equal to a function start, with the C symbol that
                                       replaces it (or why there is none)
  build/standalone/code_entries.json   every rewritten function by its original address
  build/standalone/imports.json        IAT slots (normal and delay-load) the loader fills: slot, dll, name/ordinal
  build/standalone/report.txt          what still ties a standalone build to the original code
The frozen inputs are regenerated from the retail binary only by the maintenance tool tools/freeze_retail_inputs.py.
Usage: python tools/gen_standalone.py"""
import os, re, sys, json, glob, collections

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import retail_guard as rg   # the build reads standalone/frozen/, never the retail binary

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "build", "standalone")


'''
main_block = t[i_main:]
old = '''def main():
    os.makedirs(OUT, exist_ok=True)
    if not rg.NO_RETAIL:
        extract_retail()
    # from here on only committed files: standalone/frozen/ and src/
'''
assert old in main_block
main_block = main_block.replace(old, '''def main():
    rg.forbid_retail()
    os.makedirs(OUT, exist_ok=True)
''')
open(p, "w", encoding="utf-8", newline="\n").write(head + t[i_rw:i_ex] + main_block)

# ---- the maintenance tool
tool = '''"""Maintenance tool (never part of a build): regenerates the committed build inputs under standalone/frozen/ from the
retail binary bin/halo.exe and the Ghidra export out/functions.json.

The standalone build reads only those committed files (see tools/retail_guard.py); run this only when a change to
src/ needs something new from the retail image:
  - a new C function that retail DATA tables point at (code_pointer_slots.json only lists slots whose target was known
    when it was last frozen),
  - a new code_address_<fn> thunk (its ret byte count, code_address_ret.json),
or to rebuild build/standalone/halo_image.bin, the retail image tools/verify_image_source.py compares the linked data
image with. The data image itself (standalone/image/*.asm) is regenerated by tools/gen_image_source.py.
Usage: python tools/freeze_retail_inputs.py"""
import bisect, glob, json, os, re, struct, subprocess, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "harness"))
import retail_guard as rg
from gen_standalone import rewritten_functions

ROOT = rg.ROOT
OUT = os.path.join(ROOT, "build", "standalone")
EXE = os.path.join(ROOT, "bin", "halo.exe")


''' + pe_block + extract_block + '''def code_address_ret_bytes():
    """code_address_ret.json: for every code_address_<fn> the C references, the bytes the original function at its
    address pops on return (the immediate of its first ret)"""
    import gen_link as gl
    addr, _ = gl.extern_map()
    frozen = {}
    for name, counts in sorted(addr.items()):
        if not name.startswith("code_address_") or not counts:
            continue
        a = counts.most_common(1)[0][0]
        r = subprocess.run(["objdump", "-d", "-M", "intel", "--start-address=0x%x" % a,
                            "--stop-address=0x%x" % (a + 0x4000), EXE], capture_output=True, text=True, errors="replace")
        for line in r.stdout.split("\\n"):
            m = re.search(r"\\tret\\s*(0x[0-9a-f]+)?\\s*$", line)
            if m:
                frozen["0x%06x" % a] = int(m.group(1), 16) if m.group(1) else 0
                break
    rg.write_frozen("code_address_ret.json", frozen)


def main():
    os.makedirs(OUT, exist_ok=True)
    extract_retail()
    code_address_ret_bytes()
    print("refreshed", rg.FROZEN, "and", os.path.join(OUT, "halo_image.bin"))


if __name__ == "__main__":
    main()
'''
open(R + "freeze_retail_inputs.py", "w", encoding="utf-8", newline="\n").write(tool)
print("ok")
